apiVersion: v1
kind: Secret
metadata:
    name: hindsight-db-secrets
    namespace: ai
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:J4OepGA1plWO,iv:qzRusIuLRKQ2yDmhgfpBX/tbNDBS1iZVRGvBi8ka8YU=,tag:22B0t0syix89pxdElL50fA==,type:str]
    password: ENC[AES256_GCM,data:a/p4CGSpa9W0VA/8xvA+H0BiRbhAzuvGPzEXsGOKIcHHYI75QsJg07Tc/Fk/HTPUIAKBTwrE574WfzQ+9NA/5Q==,iv:40hGVJT8MoZpoAFOSTZwIFyDHvcotsrGpZUh16iGV4M=,tag:uHpBvb6v/oz8Gh5hp19QXQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:2G3ZZz7/ergRwVz4MNDTJA3TFuhlDQKtQbPvIgHbH16+ifhhuCrmhXG4vYKX8bWwFNeAr/XwYWB51RytWLri+kdrklRgeeKT82sgq+AKcCtkXPrz9ZTldOsMm2RrtvUx8wF9YzQmUcgl/q6aVcg/011+oANGwg==,iv:fwKJewar+JEM061OQ2l5Dj/p1c8lBMCvTm/zQT6VM88=,tag:1PrdIv2rPw0SQzP6QiGWpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OGtHdW5wcXNpK3lLWm5F
            bHdvaDlQTTlSYzFFWUdqajB6M0NKQW5zMlgwCmVVaFhSUmdTSGZ2c2tCZmZjMDFR
            Z2F4SHgxRU4vZkZqRW5LaVpjZGo4dm8KLS0tIDhMZlFlbEsrbFA0OEFnY0kzdzdE
            cUxxM09hTWJyQUxFY3EvZ0prM3V2c2cKh+EYwM19He8wt4sTsqa4tkUO792oanLv
            M4LEUOM5Uodsg7VWaJndphMCgrcIMf4hBEAgSAXoS/EhAtMfNMQ39w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T21:29:09Z"
    mac: ENC[AES256_GCM,data:7RvE8K42V9ciI9aMKTBMcUqe7YHfuOUvZiS0UNmkpVyfYQ1Ja1WeeC1/EMLHSXEdB6HseZ/xsOkzmcsHoX7IHQ+3V5Ca9CzDn3HuJnUvZ/cr+Rj478P044csj5IzbXfNYyIUXk/mcYohRCIeOhqOeCnT38pT89BkyURviRZas4I=,iv:jLfvacnmICYQkw/4pCXUT+c5L4Ebrh4nNrH3raLpFGc=,tag:Lwa5WmnfDyTiN82BD96mXA==,type:str]
    version: 3.13.3
