apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: ai
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:A293Z/REFN2tDuw0o9XCJ5FnxVxaaRMi+OmhITHWIw==,iv:cp1BVKZRI2VKCVI7oL6hwKuwj+27WcdLGqBTNRigSi0=,tag:vUH/sloIiZ3bm66+kf8MOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbzBDTGlyUWJlNVl4bW8v
            dWF0M29ESkV0SklnY3U0cUVvVWpabjRVRDJnCkNwU2tSNFZoaXhWblEzQXhCdkFO
            d25yRjlEc0tMNEdwQ0Z0OHdjNEFrVG8KLS0tIFpSaDdCdWpxcHNpMTlQMG5SY3BU
            TFNnbFZWNDJEaWpSWWhwNmw0OHRTNmMKd+ExQ3EUdnSkUNPbejCpRYJiLWfv3OXl
            FqqawgTd5+y2B7rNiXT0iym6cs7pUbrZ2hubYJu2hEwov5cvQb3qow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T21:58:45Z"
    mac: ENC[AES256_GCM,data:uCYLVjWmwK1meU8RwgZLAEpXoaQzvdXxp4Vp7arWAiUIRIbdKXiQE13YLa3Yl6xAVno7qdr2EN4k92B+0zjVfHwuzOO6MQK0pA1jUzmYvC859Cvu5JaI1FtQQlaySaZYc/yJJFFKfgp4TKdxEcu9EYCK9DpFSpw5p1T8ANOxdgA=,iv:Myly3Ku5+W+JGgIORNyOnuAqfmVJVLRcHbClxvxC0Ok=,tag:PjprfK0eV2my7DB/LCe4/w==,type:str]
    version: 3.13.3
