apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: ai
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:lmPovKVkk6qEjIbL1UYY2jIVxAuFrFaliQ==,iv:AEExbxZlJNLzMjZSmbO2pHlcoEh69hCu4nghPutpct8=,tag:tQR6ERsvorUQAtbbGBEZQg==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:kTwF1DvH9rT+asMqcUtIj2P3cmEUvNC0r8VVDVu2Xq63PgE=,iv:IT/2sGoJuvkFE4KY51R4uBa8xgBkN/7pS+Ti8HNjC50=,tag:q2bJ3yEegyHgOqVbmPYirw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aEhmRXJzditWOW43bzY2
            Zng3aDNnR0oxM1krVzBDWFROV25RRVZXTWdRCkg1RFVzemxRazBLVGRPR0tSdDVR
            OEh4bERzdHBZYmFnSlNMemFKQXVTQW8KLS0tIEZ5OTVjTmtiTjYxR2NnWUkxN3d5
            VzVvMzlKT09kaHYvOVVyNlVwZkdDeWsKa7C3uc8NIs4ighFdPPB/VhxrJGgUiwP8
            xz4DE5wmP0kCzCmiUekZnDkocCS79sa/79Y56bcQURxrj4UFmXYwmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T22:21:29Z"
    mac: ENC[AES256_GCM,data:/k6z5Z5gIMoDtqwefwGLEvcwheiDlhsjR3vhSzf45WnTy6nLCQ3PZLJAatmmcfQtaHWNPyoKKYAePHB5ZMIR5LYhO7EZS7h3HLpiD4HibS3N+vh2hwgsKtTvH8Ku1wku9bcU7+nNPTFbSA+4oH3s8NlTEI12jB6euFjbcgZJvzg=,iv:mFUUUp31fgzmCD8dhyauR/giFgdFQb8kdeY1oIa8Eew=,tag:IU78iNLD5YMDwbTRf6Gs4Q==,type:str]
    version: 3.13.3
