apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: ai
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:lmPovKVkk6qEjIbL1UYY2jIVxAuFrFaliQ==,iv:AEExbxZlJNLzMjZSmbO2pHlcoEh69hCu4nghPutpct8=,tag:tQR6ERsvorUQAtbbGBEZQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aEhmRXJzditWOW43bzY2
            Zng3aDNnR0oxM1krVzBDWFROV25RRVZXTWdRCkg1RFVzemxRazBLVGRPR0tSdDVR
            OEh4bERzdHBZYmFnSlNMemFKQXVTQW8KLS0tIEZ5OTVjTmtiTjYxR2NnWUkxN3d5
            VzVvMzlKT09kaHYvOVVyNlVwZkdDeWsKa7C3uc8NIs4ighFdPPB/VhxrJGgUiwP8
            xz4DE5wmP0kCzCmiUekZnDkocCS79sa/79Y56bcQURxrj4UFmXYwmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T22:02:48Z"
    mac: ENC[AES256_GCM,data:ydq4pSgAyrpkysRbY7mNu8kWbho+lxrQHOLVWXy6z3p705IkOx7NMMg3QYYouua/wdTwjb1qbbWIOHq/4bkQmAMOjEwH4WMQ3yD5KY/zBDWiiunqvSPeaX3zSl1L/WUbkwu9DYbBrmM6bna6vuJZl2AfegxoQvZy3qIWkrBMd7o=,iv:mOkqaaUg9K0w6IojitZekx9o+ORwEb8r+xDHRoQfnsU=,tag:rE0eDIFaP340tiqYPhBunA==,type:str]
    version: 3.13.3
