apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/bjw-s-defaults
resources:
  - cnpg-cluster.yaml
  - hindsight-db-secrets.sops.yaml
  - hindsight-secrets.sops.yaml
  - helmrelease.yaml
