apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-wireguard
    namespace: media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:R4ESHacMbBtItJHK5rMBYtGLGumKWiNfvNXHPM651onwYf2H7mXbdpkq46fgpePiEkJ0BfCV/4eoDdNPzPO+DL5TpHg3yi318aIeDmsCptTjuC7t2Yg8Ip6OcXdVtTT0O3/Jo2MYUn21cZ4X1EcgUI9h64Lh4n7qoq0/ECdV+dvzThRgDYO+CtfoZ5KNpJGyhyMTpQerj3/5H2zRVvADLqN/ImkQYJIeTaFO3et88WKGGbMdXeA3UVNUxJDYapkls9HTWNJy2XPcZCoE2DFq1mbZSZP9DT7OCIARBQiaKqP31kAiZzooNga36bO+LfYHW+VvV+VYL8wRWvW3tBYvuiF+xBCqYrV4AYJelnS5fG16HnqimP7f16E8,iv:sCzhaN5mZAEdmJWbHEU0wixQzYB9uuyv30IoWxqH/aM=,tag:v2dQzBexMPDsLpn+U32UVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WmIyQlZ4Z01GZlZPM0FZ
            aEF2QlppUTBwVkVFVnRoOS9LQmZsTGVSRkQwCmlwNDRPZzBYRHd3UlZDKy9PZU5S
            aVVZR012UFRBbjBnNHFHd2JWT2tnbFkKLS0tIGI4OWU2TXVKK1BVWXhBOVplQ1pQ
            VXZiL2Zrbm5xdXltci9QdVMxSm54ZWcK5IoFlkSqBhy0g3IblBP16msqV4TW1Gix
            1QQ65dL6DIXP1ocrtaFWS8yw7nHDhoQPj9KVBWtpFsgI0NPJAWtVvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T23:59:07Z"
    mac: ENC[AES256_GCM,data:sScGEj5JACEb9FF/S/0wOgobF5zCcvXYvLpsJdjdbSHfKRHtqgN7x8B7nqOC7FWvi4Ow7f4TCi3Ex2tFhlmf1SqXVlNsX7OxynxSOg3WPP7OQ/RiantyAAtNZPeyEkhABQPaX0kbP4woO/+yWzyF8EGOWXs/ufM+QtqUED3cqhQ=,iv:Y55VVcIzgbTfXgwpJbPHs3K5b4inVbnazHkdImNugBM=,tag:4pA56k5+4Df2m5PnaAg/8w==,type:str]
    version: 3.13.1
