apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secrets
    namespace: media
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:2p7cKwSjtcIxLPEXGDDYPmmrxeWUO0D7Xw3Cqhp1x+w=,iv:C9o++e9gLM3p6mUcTyfJHhSXLknxVazwwddeBnfHQHc=,tag:Lo4GjgV3ji6UpFIlFAk23Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa0ZJTXJDamFOR3lnN21Q
            ZHdud0hYVUFBMXlWbnp0WnRnQXk5dysyZUJJCjk4R1QrcmdiQ0dNSHB1WlNrNUVW
            bzB1S2dOWko1SVF3VHhiSTZiV1VwSjAKLS0tIEFCUXI5OGdLWHZTVDZXRE5wM0M1
            VEdxdkYvVitBTk5JYzU5RFRvNVJoN3MKVGqsCz+lUAfD0aMq+NtlQAY54YvMw2cc
            gZf52b1f4DeSyPCui3WQzDSCWFC0ZEjoWLHQ35evR40k6t0wPdu9BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T19:08:26Z"
    mac: ENC[AES256_GCM,data:98TIihX45GQu2oJYsrn5C9e7ObwLV9NtcJL7tZ/1ZoikesvJ8n9cF+PcJMbKIX1bKlcAu3iczaP0c0LfwIHIFIBi8VgldslPrfZEC9RrA0WEvXHFQmvmmSHimMfblFMYy4Mfepy6d2lDGZfjMDC1NWhML+GL6M9lXzUxYTmh+4Y=,iv:VndR7rFACLirP69Nx2FfCl9CEkZNZyn/ZwSRR3j+kWQ=,tag:W1wAJyb7IWR+8nfOmH4/Gw==,type:str]
    version: 3.13.3
