apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-runtime
spec:
  conditions:
    - namespaces:
        - renovate
  provider:
    onepasswordSDK:
      vault: ila32wb6c5nmide43fi3w6zc2i
      auth:
        serviceAccountSecretRef:
          name: onepassword-eso-token
          namespace: external-secrets
          key: token
