apiVersion: v1
kind: Secret
metadata:
    name: onepassword-eso-token
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:FyLmtpZBYmByz255Oxotr8TL3AYkhpJsGM/bKzct6EonHj1hu1IgxpJXBhMPrtwXN1xHyS9vuSHKJNucxZNHrOP6UpLBVk1GvrPW3pr5txJG0WjwNgSZ/9Ml1g2IuLHG0TAiWiJB+2dTbV0duPq+cFWdSkhXtnKBEJNiSScoW3+GZk0xDDQpGUxckcXaG7u+X6QkMAbMm1Ipk/9wF9U3tFzy/113vE5PGiIxdLxW9Wmgyq2zBhhPDxvJQm75bwSolLcmSPEHcxLiXavQIYde6/EQY9Fm2LAKukbaYLLuk45s+4Kg/9RTOCczkey1mvkFaDLjMMpfCraqsRg8NM6NJGEQXK24B9U+x/ziAEICWcQbwKampjdLYXNquAY06SvNhhAvE9Jq/tlt5AdxI7A4BgGZ9gz0EMOBl2ZRNaTWeQkfcUgufLuJaR4natcBOgGqwhnha8fOSJs3tlJ5KI2C10gq4dZv1ElGcxkINbnTtyziSUC9sUzAdEf+jklwQVamPYTagmEETJwZgxjEitQScKOUOKY5lHGSnu8shtxollbYoJcUj0wE88emuWy7UMzv3+hhVvrhWjDhWn1icj9X5lr1o89du5riAUyl5aq1mxbRdoWptRkf6t3gmgLmEcWTt+wWre7ILFqgUt6xU0CEHEjm/kNEclzVYoYQ/O8ZYPefKyl7UYPmX49/CZYL8aEUyHXE/Dubm6vK+sAhZV1s8Qfr6zk+8WADlTkUbyRGRmKAjlPtyppf+X85aqRLmufaj7/7Z+O3VVH01SY5v07GZfdoNAVE4Bs0O5z2H9NlB4xAt+/75xyb42q/XiRYNTOoqU2F8zQhoV9fQaMt5EoMYcGyKJk+yXf+GDrz5unu51+wMHmwDSioMU19tU1Ezzdmzibus1ArDULSi+fUM3xssWHn2Kja95Ur96LftwLzz3QSxlREK4+mDgv5be8lwaJmQdn3803eqz7OlIVzkPgzhpb9pY5iHIdwK8S4kLSK7fcA+VKeEll+MKFIfDHAaNUMjJARX9McOUAklm5bKRUevUiEWRjXRaNoa6QkPWd5iAXEeNrqDbUF6XM0o/Uo9F9t7oB8hW1dl6+9jvbEAwxOQeRnDl7ncAKSGRomCH2vWl6OWg==,iv:kKgQPHiE9dEWJEPUV1GLSHkJRLmL4R2BMuHwzecNlRU=,tag:5wI6j1r02vIQZuxFSPpXiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMS9EVVJmSkcwUk5JYkwy
            WXJJSHJhYkc4OHF5MnQ5Zyt6V0FQYlQyVFI0CmdSUmU4RFJEVWQyQitlUHN0b1ZM
            Sit5YzA4b1V5UEFxam1EYVNXajJSdG8KLS0tIGJyc0RuWXM4cnozSVhaQzZoT2lo
            SEpGYnB0LzEzNGZyUnRsMytjV01HSW8KgYt6Lo0J5P5OIgf/zhO12NNGjxrXTVQI
            wa3wEE7SfOSqSc1VwbhSYM30FjKz6BNtuLlr2P+T5SmZgD+wfVm9zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T23:56:31Z"
    mac: ENC[AES256_GCM,data:tx/IE5pmU6a/POoblXsJcYz/4KNnH/3huAaiVz+7y2/9hN5GnDUkkbSruY1WnrbF4wZ/q1Flio6VNGAgFTLYV1Gav+UwapgUxmmbRGYqFGIBLL2r3YrDGaZCcD0xdEdRFYAVSBUznUcv3hflAcEBJd4LLMKj4zxtDZjKK14/ra4=,iv:hEranhpT/4WScTKO50VYkeQmdLu4GyQRIeTqA7BGy3c=,tag:BH9tim5rmfGjh4f7MfEN+g==,type:str]
    version: 3.13.3
