resource "local_file" "ansible_inventory" {
  filename = abspath("${path.module}/../../../../ansible/inventories/openclaw.yml")

  content = join("", [
    "---\n",
    "# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.\n",
    "# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.\n\n",
    yamlencode({
      all = {
        children = {
          openclaw_vms = {
            hosts = {
              (module.proxmox_vms.vms[0].name) = {
                ansible_host = module.proxmox_vms.vms[0].ip_address
                ansible_user = module.proxmox_vms.vms[0].ansible_user
                ansible_port = 22
                node_os      = module.proxmox_vms.vms[0].ci_user
              }
            }
          }
        }
      }
    })
  ])
}
