---
- name: Restart systemd-logind
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted
  when: not ansible_check_mode

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true
  when: not ansible_check_mode
