apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:xbVjWJcXeECMiHMsB3pvTe5oEZsPpPUN+7Ft7Ov2iUSa+MjMxS+/7xYR4qHrfDFEULVRVIwbigJNzsBu9EEXYbiqefmcuk9AeFd3StmCTKsop6URPcoDyQ==,iv:n+UkPTtXrDuj+ka2zTrR3WR9O9gKYXJOCQ4jxZ5vz5Q=,tag:tf1gsZMuJVTqunwS1TEnYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN0JXK2Q2YkJwTDlYb0VH
            QXVoeGkxckI0SHRXa1JXQ0FNRHhhZFdJT1FFCnpWNDlsSlNUOHlBNEovRmFjcXI3
            YUpsUko5ZmE5Z3MyVjZ3RWl1NXV0cHMKLS0tIHRWQWpjN21RYlZvSlJnMWxIVjZV
            NW0rZTBab3RNUE8wVVJSUXp6ajYycWsKc23NJPGlbtNRp10R9j2e4TKT7o3TBDr5
            V+FBBR5qtdEKSEk6MGti6s/bLHtDuhC7ta7Fq/OPMP+fSLPBSgwXKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-21T02:01:21Z"
    mac: ENC[AES256_GCM,data:4KroMyHSEBpAJN/cr60ZSuuGaUNMJuI5NZWFH3b6F8K/LC4tiR5pCmWe9TOsF7rw9jsSE6Ix1hCCPMGDAl4HIkfRT/Ki4Bt4vNPYIHed2YbtaWRk586m1rp5pkKZIhJuqXtWC+N5RHdFaBonjymTJKjFR/ZNbVFL5I28C6UhyPM=,iv:c0c7b8iGqURxR3Ktuk9Uh58syyxXP2ql6Ple0t9ku/g=,tag:Jp9HvWvssIFd/0Ej9ElNqA==,type:str]
    version: 3.12.0
