apiVersion: v1
kind: Secret
metadata:
    name: paperless-gpt-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:nRbrAQkhiwL2a/pXz4aXN2CExriF9oxaYZI3EhwfEfqp6PxmKx1R/w==,iv:F7CgB0vfzbnTMJX8O/hxnBc++/66dzguMrUQFFiUjdY=,tag:S5Lk2MSYn4aH9IpBzxAS/g==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:8YuaYThHMFH34Z/9S03AFEhw7OC/sQIQAw==,iv:chEYiQExCKVi1fKW0qYQHm90bKAYT8qhcs7AoBzSlkc=,tag:f4T3nRWpvMfRL1PvqUQSxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cGcwSnFtNkJCeUZTTGwv
            V3hMU2w4RFB2V0hRenlRODM2Ni9IamlyTG5ZCjZLM1V6WGRsUngrOE81b2Evbmpw
            dkYzRWtHWHVhUXdTUGd1alZHRUtXdlkKLS0tIHJXMnpPRWI3cDd0WDhHbTNwbjhj
            SDlKRzAwL2NyNC9DOG5HbGwzVmxxSE0Ka37rii9LSyx6dBmLgIlvGWGhlHg37uvF
            pB4LNbR9gfUWbgLCDVzXW0eCEzsNZu3NLhaLMez6wPHnkP69P984Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T23:01:13Z"
    mac: ENC[AES256_GCM,data:J6NTVzigmOB+g8pvRBJwJNdDahHpRtEKpkXSOj0BJi+0qyhAEcPqRgao8khE/IjihCffHUJFLLCbiya8/rSAfIBkIfz/3tkjP93yqS+jCVfDUezuKKS2PImmhIWDscLkmO//rqpa5WCbTJhEola2SV8vHJrMcX4OU2c2iuvO7i8=,iv:Ub8bLs0wETJUG5egYW2xcDhEATJ8Inw6vkhnidBnuY4=,tag:8aJreQiKtxU2IsUhhUdZHQ==,type:str]
    version: 3.13.1
