apiVersion: v1
kind: Secret
metadata:
    name: paperless-gpt-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:/fVTvU9fKrx+OWrPZbQTTuM5PYtT1XgytfXPa4lC+Z+Dl2XlreRw6g==,iv:bxFkWKFLpNr2d7LO+HAuvoDL9c2C0jDrr9cNzQRD038=,tag:FHbYGLWCWWnycwS777ByRg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:g6evpmqyxobumki7Nf9eACjmvmt02WSZqw==,iv:3Ec0ZlWrK3wPQTIu9Ho0iBCITFmTkVbjRT1g9yKCBhA=,tag:GGep6goiUPEWVrq6gX28Zg==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:ZlJAw13Qnc6TEP69WX8KkexLiOUMW8FSpLVg/XAIxD5aGI4=,iv:zY/0CqgQB8P5N+qILi9/AQryBijv1ca2jhZIj+4vtsM=,tag:gal9mCOjBtT/RXQrpY4QzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVy90aWRxdjZjQmxla01K
            clVUVkRZVTUvQVZLUDN1ODdsZ0liY2lOdTBJCjhTN0FaOWdDdnFnWXNGcFEwNUs3
            a0dVWHBNN3R0T0lBaFZ1L0NXSFhVcG8KLS0tIFRiSlB0ZncraWJtNWlESGJwREVZ
            MTBoLyt6bWQzVlFDb1lkOWdXYlE4RFkKXXUeAv9HDP55AxDmL7ZPFrmuo8mYcULs
            FCOni/XWzYBnFeXFmY6GwV36ailg5hZ4KfNLAAAYmqViPG/cpw21gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:19:21Z"
    mac: ENC[AES256_GCM,data:6bFkE0s7yWMA8SOwYCLasm0Xxk1w+P0mOqRlCvvTdagzOKPh8sL5AnyAOJLjlZNfzGRr9LsKJQ2wz9VpLFPndDE/p2k5OZ1RXnLCFe+u1gNRxKrR2E2V6YNzI2px9lqOmHAlCbAuSzWNUpCLoPJKQ14lNAt7avSE2I+F974fOpQ=,iv:VWF1DmVTRshBn+9VCc2dpqkGzlUG/HkRx3zk214tHPE=,tag:q/0RtStivNDQS7HzOYsOrQ==,type:str]
    version: 3.13.3
