apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db-secrets
    namespace: ai
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5M8vkynDTK5Kbw==,iv:/vz1ztbBY7OC5lXGNAjYYymArghthoEzTi3v8PdbrkQ=,tag:1h7RdvU3V8Hf1cDL5CGUXg==,type:str]
    password: ENC[AES256_GCM,data:OQrQelMHgO4bFwU5uB4qj0Ok8c6SvkaDWMKNsstseWg5Jk6w0JjqXobP0Q==,iv:03QfVPqTcMpjlXnZeNEaoioClNsQKo4AjRQZfLnB2nQ=,tag:XJM9vi+GnwDsVjV5M0/7AQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Kfr3jWCkPMOMLsZ06XymDr592152D/q7mLlxAZuqwzVjwobtpPS9vrwX+eDNa9cA2TPZvpzBMFC9YftUpTz/R5FO2MbW1oEu18ekh/Zlo/xDpuj61dC4CR/y6XKlI7aTgbR9EODeYjkm/rFPTApBZRlso5jSGibxag==,iv:uhW6NRMhSrRfuqfJ6GO75pqayGFYw0Vb59PevqPpfmc=,tag:I4ENCgc1nuBmZ+68G21ABg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUDU3d29Sa1NydDhORzU2
            YzBvd1Q4bVhqRWNLN05IN0xRWnBqN05aUENVCmVBYUxyeVY0R1FKZWhLMGIxMFVl
            RlJNZlY0bUoxVEZ3U3gwbWxDajE0NVkKLS0tIGhhNXBuMEEvd3psbExBNTBzYUZv
            Z0ZoUmpNOXVZbEY5SFQ5MEp0YUxLblUKrVKXxbQZUppH7Gt7tQtiH3tZ1bJxgxjt
            z0fSaQZsLsiS0iUaIX8qGgKRtGwFNNWg6w3UsmHoHq9AOT2JmMx8kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T21:26:55Z"
    mac: ENC[AES256_GCM,data:t7aJ4Y5GDpgqSyokzA7ghiI7xH29CTxV1woHEw+5VPAoGTAoHXmZ/poMm3KIfwcqFZLUNm7+5AG6CynGYrzyyo9fl6+VCjoQHvJCLwbU20GEkLkg/rdY1S/y0ghjtQ7Rf1iLj6iYwvvfL7+ffhQ32kiJfw2aLsxyT75MukIPd/0=,iv:hrfRISnsFIB6G9dOpzeFtpm3D3SAkoNYu1VIzH6Fze0=,tag:aOQh8BcgoxiNf8rK+pyKVA==,type:str]
    version: 3.13.3
