apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: ai
type: Opaque
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:834HQLWkUMyeHdjvR0LA9jfZbWoyedLnvwLsDJyKfwvjIfRAjl3mDBbvCioZ52nPzzJCdABk9XhCjeoAFgzQoQ==,iv:+fCGWozIXT8x4XmnxGxR6DegmiI7tHl1X8HKsXzTPhI=,tag:YUoToUIPYcheJ/0C2/RSfA==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:Mto4L3jzg0Fsd+398q5I/I8Hmz3oIlB8yA==,iv:qboAVt1WJUAnwD4dek0Us50Raq6yWWq3cjY6ivjL/d0=,tag:4QjgPCR805sOvJjyefYVfg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:J+JIedZDsXPocif4UYPeXdV8l21h5WWRn7QSmtfWorzi39/Ps6QWfFqWWFQrbP8CwJT68wKGZKKV4lp3ydbO9Op038uv7OLo/A==,iv:/OsaeZEKjR0ACCF8YYVIsl5zMWNZkXdYZgrtnN2rXAI=,tag:1yvOBcCtknUpYuscCKMcjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcnBJQXU5R05RMHp0S2ND
            UkVEY2JmdzNSd1k2ZndNcm5FZFZReGNuRHlBCkJmOERvQWlzbHU4RFNPc2Jta2Vm
            Y3hFT01ERGRYdU9zRkdSVE1WSjBnaFkKLS0tIGtPL1pwd24wZkI0bGZaRHdqLzlI
            SDZid2RtRWtRVUUrbGtqTkxsSVVRbGMKoqOF5XwBcg+yCXa/B8zboHomNR41c6kq
            cy8tkXS/jcUyU7HdCC7HUxKCDz9JRTBhO88dPqBjL1S1eZYCBQMMsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T21:51:08Z"
    mac: ENC[AES256_GCM,data:8YRu5fl+/GjiYZsSj9t5+maDsuYnemy0NFq3tkwGFXuCRTNUxRFongeo+pawF9/fQYchkH3Nt+ONICxSPBAjiKqkv1GXZ70dvX6S8tdxOc4fv42w3V0AW0fHVEk4YSQ4c5nIiMvl/Eq/NL+cAGdT6bjXoFlUv1jrzJF2NaI7UAQ=,iv:nVMqs5wWXApp5dL7YPqNmys5PLJLzD3qmOje0hu4L1s=,tag:IkXBwUEg4b/FkKUcQYOTIA==,type:str]
    version: 3.13.3
