apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: ai
type: Opaque
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:vuHcep236j9/gAqtdJqupjmCMS14dg5HS5YefCZ02Aok81MysmKPyWuExMTtLijh0O1cOjkZCsrMyxa0i40WCA==,iv:8BrkSs5E6NWz+YDrR731h8IPhEvJRShbVHIbcQCYaAM=,tag:p8y7VR/PDnv101ADCbEoCQ==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:ndpj/Bl4Z3eZrbfC+b8B3Ue3ClIONiMBTQ==,iv:rUTHX3hc+/FW13IRD92k2J8m4Hz+QDQEvdF1G7arZU8=,tag:2f9GUrsRLmzb8KJAJsUm8g==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:qb6fR9DlvLsV1wmoIDheWS4B/mSEpjJSnUh/N7aC1mqKN2/Et7Pq0VMenbCn7dMme9/7+TIDwjgcsZidh8r+XB7B0Cw11Hma0g==,iv:etNKeR2YOgxHxxxO515dm742asPJd1taapiAuxhvK2Q=,tag:bCW8NulcMjDtScSMiw1sJA==,type:str]
    OMNIROUTE_CHAT_API_KEY: ENC[AES256_GCM,data:CJMnxYDa0zC+vLTiNUBV9Q96bWECaK1MFvYxtlp0oulcFOg=,iv:M0oclHh2r8AUjDV19DBbf8CjZhc35nJ0hOQNdo8RWPI=,tag:UcGU3f4q/hGobRSH6LYkGw==,type:str]
    OMNIROUTE_EMBEDDING_API_KEY: ENC[AES256_GCM,data:c1TYuXngBi1orYJr6iGwxBd1xHkreYzL95sfeKkeqgj0uRw=,iv:82GcVufo++qtXuMwKn8UveytzW4+wm95zKBsZKWc4Uk=,tag:nDQmpNFxk9pYNH+QToY9/g==,type:str]
    OMNIROUTE_AUDIO_API_KEY: ENC[AES256_GCM,data:G00m0oZjNA3hIOkYCl86FVTgNNjmlC0FC+fArEd1aAA0x9c=,iv:PC3JKk4C3ZtnolCWTds6y62E2AVM1mCnVoD0vuUFk1w=,tag:8wIdGb3TI6c9gbdxakCfGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXemQ3Y3ZseGRmRFNMQkJt
            ZUNoaFZNSUZydTJ4ZHdUMXpWcTNlSUNYU3hjCmg3RjZReStRSUoydGdSNkVNc1po
            OENDVS9PR3VsQ3NGTzl3dG5zUGZnT3cKLS0tIGRiMnB3SHp2NHR5MGZqNW5qdHR6
            MkdITzl3Z1FBNWUrYkQ1enhPaDhxY2MKMUHnieAtpF4/qRRekkAQcs3oT856BFK5
            Trrf77St2uHgfvW6l7jcrqKHi2bTGmp5WhKu6xtnq+V0zEeNeVHTew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:19:21Z"
    mac: ENC[AES256_GCM,data:zR7wrp1IoCoha2xJJxWQp9E/+1974eW1cmXJivjjpBt+g+7Jw/Ti0N7L4sFa+DgayhkjuimJk7SzPP6Lp3/woQ3QX+1L42vw4hO233PgB5MUNjc7KNZUmIV5DdNYOyvxcYFJ51rini4YJApyDUpEdugnBMFASsfsC7mbpHYoPi8=,iv:xOGtXxFwdb6wTV9n6orpk3PcMmMR1Jer/+g2s/MGOvc=,tag:7lDZ61MT/JzG/a8vgxIe+Q==,type:str]
    version: 3.13.3
