netbird_fqdn: ENC[AES256_GCM,data:gGDAGF9CIgkZrqWffTEmxCwRRHpKv+VkvOXnEl74VFc=,iv:avKz2tm4gAOSxLXzi18pZSmNjooPAb5tsrj33kw4UKc=,tag:v3dS5vtaYXhhbG7SZBDibA==,type:str]
netbird_acme_email: ENC[AES256_GCM,data:Ery7e9VVFRTtntLRNAnKOFXQOyftEa3JTnu9HZI=,iv:uKF8VSIwK8q6oXrPJfnxbvLvgEfVxTTpSF7fizqoPYw=,tag:E3tEbTASPZLi/amMtatTAQ==,type:str]
netbird_owner_email: ENC[AES256_GCM,data:pePObg/jZnTRj46sn8jwYUX/2yhYKuFO1EUNEKQ=,iv:x8PGu1K7L9nokUiE+dZdXXnoGXntyIoOYZj8ON24IBc=,tag:hjvKJG7qGeqSkQPJ42C9zw==,type:str]
netbird_owner_name: ENC[AES256_GCM,data:DY24B52xEkog98vYFjtzVg==,iv:FOrIxePAiSmsHlEx3g0bb4TAtigRoTAmTJ09ccc9HAs=,tag:jXwsgwhhQcyqVN0vhWl0Tw==,type:str]
netbird_owner_password: ENC[AES256_GCM,data:Xv036TPOmjWqxO3scHR8DFnHYCpKzW55r01tTiwSLHZVLfahyYvfjmBboSU=,iv:Wqz5J3cav/YB2rdh5FWRUIL/DjAejRw8+AAtGgSTWeU=,tag:ejzBdBVSuoV1NmgtgQdXlw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMkgrVFFTalMxaFJOYW0z
        blQzZmtheHhJZHZTOTM2UHFsZHl5ZEhTQW5rCjQ3QlYrTjNNM0oyR3BqVVE0VlBx
        R1lIQzE5bW4wYXVYNTFwQzR5aFRqMFkKLS0tIElNTi9aek9zUzBHSTZsQ3UvQTVX
        RVhnZk5PRUJoSGw4cTNrV29FOGtIZlkK+NQ834pPOjT+2Fiv3+N2TmP3KLQWf+v9
        IMclWAYjByfg42dbABvXddCMds7Naf/+NVRTdWttWHMkqSbrvqbsHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
  encrypted_regex: .*
  lastmodified: "2026-07-15T19:41:08Z"
  mac: ENC[AES256_GCM,data:GHG83XDWk1ak1ZqW0vex6WvswnWv/5h3XiNpIpLUQa4p92dNF4WGd4+ps7O9HyL2dgjWncxgtSyk8Sw4q/eQKwyybGl145YuNC7oTfF2dV9W9j0abqtDYLZkc3ShhG7P/uvbDd6wQPCrX+4BwTtKQUOOe3kASqxyVg9y1s5N0fc=,iv:kKth6/4BeJIYkI8nGY6b/KDEOox63keb9z+etSNWIxA=,tag:zx1c4GWP/Yg1Z350ATfhlA==,type:str]
  version: 3.13.2
