omniroute_initial_password: ENC[AES256_GCM,data:75YaPIFsSgZ/FwG5g1PzwSgBxBU+0K4hiKHm3r6xYZs=,iv:Br3fZV2EXT0yaHadM3u713NUHOqxcWbtJ8dWxL0CtEc=,tag:nEUbE/ZemBvVdl0ZasVMNg==,type:str]
omniroute_jwt_secret: ENC[AES256_GCM,data:ONriPyM8aA7Wq06fMMmU3dbcNby7AecAfqdqcSCY+FtjuxzA4/ux3xyIeEZmLIP9L1x4CcACFujOdUT+BB2nRg==,iv:eQet2kVPp61iioJSBRKBT/vWPMVe8prTXYSRoBDRyLM=,tag:GOqtHlVPqo3Ahy03zTOWiA==,type:str]
omniroute_api_key_secret: ENC[AES256_GCM,data:IWlxW6lLasGtp7paGQ3NprwWeu3MxnR7Es3YVtWwu4kKf3wJupt9s1p3YmPzhofykL6CM6HRJKjxIJJzGy+LaQ==,iv:C5ucpicD+5qST889MQIlKrtwUpaQAIHEs+/RtKDTbwc=,tag:4I5Cvq7uOVFwnGjRrWaNIg==,type:str]
omniroute_storage_encryption_key: ENC[AES256_GCM,data:OCkDeFuYuZNle1620H8L8LPtc95yjd91MrhYq7+v+cELsypOo9osMoNABVNNdUaS6MDmdhRLlzMddcCFzPV9GQ==,iv:7X3sh4E1D1B36Q8jfIQt/e2OiFHATNXs2jTiAVC7Z6c=,tag:dSP+ki4nudrs+jFe+qLj+w==,type:str]
omniroute_ws_bridge_secret: ENC[AES256_GCM,data:S2RiL6gcufO5pl4Fys+V4nbP0pIwuXLa8q+ljcnHT9eiY/+pvFjmPvccD7E=,iv:KysI+521bC9VrTcSPcdHk+nQ5MI61pgT9HiQMBfetMQ=,tag:aamuik4p7v8LbhznFCjWmg==,type:str]
omniroute_openrouter_api_key: ENC[AES256_GCM,data:4SqK2NkniVOQbQiDrwJ6Fil85hXi04z0uS8LUPv15X9QsqVDQN/JYCiJYn8OIYKfkCSq6LdmTZSw9TMJVXFnSrxOIcdsx+wTGw==,iv:gQaLZULn1gP6powvQWAuVTdzm+EZlC76/dVP2D5vdQI=,tag:B9klJ6rLk4Q9y4V/FujUgQ==,type:str]
omniroute_glm_api_key: ENC[AES256_GCM,data:mgQvWMJXkNSQQVSqD4jEceqvM6446tmRIqyh8GYp5e0iIPuS0a2GyRJER0dgacgW6Q==,iv:ep/nee+fvs3u5mfGuHvbnY3qXadgs8oHBo7y10Vsp7Q=,tag:GFc6fz4xxhek7cpFjbrPhg==,type:str]
omniroute_llama_swap_api_key: ENC[AES256_GCM,data:SFFgr0W7odyl6Pztgxw4gX72dPC//CvApwAsDq5qzUzFMA31XLhl8iPRZekQcFpvM+OPxPfhI6FmDyAH7GJfzA==,iv:pHIpM9R3Xj2lEuL2TCyCNiySj5vwWAL2Qpl/OawRTrg=,tag:eG0JSSpfn9dfsHC7JOe40Q==,type:str]
omniroute_oidc_allowed_subjects:
    - ENC[AES256_GCM,data:U3tF3Bl36T5YkcEvzPNWt2KrPRTB,iv:8m0itc1ROFmGLJSbEtHl8HnTvAbueL2b00g79QYgFcQ=,tag:UbHphgRf29gTEmbDV0ty7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNGJDa3JSZTNsbTVURm5q
            cUU4Z2ZMeGZEdDYxa1ZmOGFneDU5ak9mUDEwClR5SDZkTFZIRG5qcHpPLzg1dHNS
            WTRYeEtZbmNZM2lsSlZrVXU3b3I5U0kKLS0tIDZFSU03ZzRJVklha1pVakhLMElk
            YmdNTW1ndHBrMmxaYm5DcnI1clg1Q1UKRJA7PQtqs3Ta2+Tbry8FJDKaFHyDj4sI
            Wu7Ylf3hXIZjSe4kXGJZ+6NHrIMeL3Cw6jziPHIlIRhB8iHq9wPDjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: .*
    lastmodified: "2026-09-17T20:52:40Z"
    mac: ENC[AES256_GCM,data:OMqW+JqT1OITPpYTrjn0G8UXpiGu13qn2gdSUZRKXE2uDT00uRghSbxwO7mnzjcG2jyN8ti6aDSIQsjsIR4EFDTVr2sGpy74neOSpG0AGGKtEfP8LvMuA55Q1XBfSizFojDqKxgnj0gUuPAIguH3cu+sDf23fM71HZuu3Exc3hA=,iv:wK1zmeX5IHin3e1bB6uBUBkicEMNJI9pqw2k4sBd4mQ=,tag:Mhhr2g4dzBgDMVDsW/S60Q==,type:str]
    version: 3.13.3
