---
garage_version: "v2.2.0"
garage_auto_minor_updates: true
garage_release_index_url: "https://garagehq.deuxfleurs.fr/_releases.html"
garage_download_base_url: "https://garagehq.deuxfleurs.fr/_releases"

garage_user: garage
garage_group: garage
garage_uid: 980
garage_gid: 980

garage_install_dir: /usr/local/lib/garage
garage_bin_path: /usr/local/bin/garage
garage_config_path: /etc/garage.toml
garage_data_dir: /var/lib/garage
garage_metadata_dir: "{{ garage_data_dir }}/meta"
garage_object_data_dir: "{{ garage_data_dir }}/data"

garage_require_config: true
garage_service_enabled: true
garage_service_state: started

garage_arch_targets:
  x86_64: x86_64-unknown-linux-musl
  aarch64: aarch64-unknown-linux-musl
  armv7l: armv6l-unknown-linux-musleabihf
  armv6l: armv6l-unknown-linux-musleabihf
  i386: i686-unknown-linux-musl
  i686: i686-unknown-linux-musl
