apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZQ24U97lTBwifNgj4Dt3R7WsQ69lMSE/yPERjrkuqf+yhQOKmzRc4zUNAejoHEUXojl2+yr01j5XjgrC/mgu87Bkv5ncI2XKAVlbFbqw/rM4GaIk86piJw==,iv:oPAekO+AjcSK3KieOMkdiJl733ooTlvTKOMEBWHkFUs=,tag:52fb8+jxjANvp9PKlWR2mA==,type:str]
    username: ENC[AES256_GCM,data:qbFaTUTak7GDa6ZZ,iv:rDp/c0ls07Ynx/zPpBpDZcg+HC8ojbNPFPQ8v9988cs=,tag:oe8JuIBRDUTcuh4q5M1W3w==,type:str]
kind: Secret
metadata:
    name: dawarich-db-secrets
    namespace: utils
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV0JmMFovSTVCbm1TYkp3
            N3pYeW1MYWlNTlhnOEx4MlpCMnJxeXg3SFZZCjBUVkgzOEliOXdNdkJkaWMwZ3RZ
            dGJVYjR3ZnJ5Z211QzZyTlJZNDdNdXcKLS0tIEF0NUhZVVlkSXNGYkpyb3V2OWVL
            RGJuVEdQcHFsazFwMk0yVnF4QlplSTAKNAzqeh2vHDV+njOqB+q9rAodyEI6ScRt
            FnHOs+sUX4o3t8UuJiwYUysPMBpeu074tr2Uu5z1/EofdUlMOOAkQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:37:59Z"
    mac: ENC[AES256_GCM,data:JQu4Jjlt4vRnJJ8ZmFnF3Qdogh9H4J0KOmougLydCxGyOx9TFdQLNHS6GqGPLdSwGaecgQAFEdnsd4OxCIEEcv+hXVebhK+g0D55hnEfoFTfoCuA25EJ2ThDRoySY9V6D/KaN5cooJyi24dikIsFqcLkvdCYRtIdPq1/cGxmX/A=,iv:yet0/w6sLq9FfZ5iWw5BBQOsg5Ins3X7AqYTuXa/Afk=,tag:YVFFrRGvgL6WIXNMJILywA==,type:str]
    version: 3.13.1
