apiVersion: v1
data:
    AUTH_JWT_SECRET_KEY: ENC[AES256_GCM,data:2c7oq3Ua7wbpdaNKP8NOcKmYiXpNI4Ev19MxQLbAp8c8FofD7EU583GO8isotPSfPK9o0pt96sNRRBrq35Vx6CMbItVn7LGvmUUPECfpn+H/eEv1cqCdoC3zOCLTtfsSBXTX/7IVPovbnpynrF2pK+lxN/e/h4BGtaWJYv+rcmJtfLyYpdbY1FyUr30wKbnUHvhNvDURjQ927Jfwl5ld1zaqOG2CRvism9Wg1g==,iv:8TB4GpmvE6Nqm8Ld3wFuLyTvf75Drs1whHV9uLe9Tqk=,tag:/poVhP60n0vSAPzDgM0Evw==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:/ghJ3aDE270lwp/14pfxU4Edtir4iTWAcqzvABrEVMieQBNyaTlDRkJN3yxW2oMRC+Ha5S6BQx24jo7C7L5PxgfepMWk5frkGwEW0s1P9QRP3dUDZuAyJrrQXKAB4q8r2l0vRePwY3sYBp4Pt4zwPSnuky8cUM6fp8W7mz9DQI9E5PcvWtc5Ex6sEAqaLibT7oWQ7QCE4tECIkOBjjTarioIvdFX4IzqBD4q3Q==,iv:cazT6J1eXjV7Qyy4vtn63tbbsl/0TuK9qQWcsIqS0W0=,tag:lkM2i20JKgTDDGMlWUGG6Q==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:GasyMXDsn3jmzORHVqUi02AxFZ0NU/tRMsMdAD+Q/Tc3Ptzg4iAkvtfOODzeTGLnC7gvELZ9Q3q6Up95,iv:2V4tOZdZ5VS4WIhOT/32juXWrxvQ0K8xHaFQfUiB0u8=,tag:g/P5uFcjSRp516QihxgeLg==,type:str]
    METRICS_USERNAME: ENC[AES256_GCM,data:PwIp/V0V01CetUC0haCXTA==,iv:otYOJdxhDeF0dgU3nICz+WawgkvZT9PUUfOS8tGrCOk=,tag:pV4eWXAeblGMCsPyouPbGA==,type:str]
    OTP_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:oqInn1hLju5g87oGlbJ1ohhYn/+a7L7JYGtHnmuu6G+wwdf4xbOm4fl8L4CD0eH2u1YGsYbPhSbipFyZsSNnctDp4PsifBpe7bkugsRSxw7V90/OVSM3Qg==,iv:LBXprsSpPRfQsF15rfriHBawR+E9QvvWm+bILMa61qc=,tag:bY0k+Dc6jysUDMgTmJqS0Q==,type:str]
    OTP_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:5em/sgkrICYd/bA6yG/apCnTaApREdZrInFjTe/5vrnzq/ZKMNXiS7+Jk+owUMlvFCx9Z/fE/Zxw1jhF3DARGJFu3nV0qI3V9/8lmYsB15IfkAJ09AgAeg==,iv:+gSgSMnid+UoiEMppb3aXLr8XH287C1TDoc7Ii1rPLk=,tag:pJEjIB20pgWUSiMQFb525g==,type:str]
    OTP_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:z/Ya7dfUNszgISfT5feeGXIo0Rb8PgGxKl/Lg4UkthpVAILMm1HRdr3cn8t6auemPQVhWTiqsosyHkueQFNHSXJDrJGQgNeU9AoE8HcYjbkDSBhfHamtzw==,iv:ta7A3Fjr+IsLZ+LwcGGDQSKfZixxUyFGoCCyEEkk8kE=,tag:ju1HZL9JHkIqAKQx+LlEKQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:kdWWKoJ3FbSKSmcvLAUXu1mNbzfkI3MdmitUaxLjgRdCNzV5M4BVPLDCg0dQT7g/FfEjwvb2nLyYCDnQduNqLlg/Hzprb6ntnvgq4tVORPPRT1/0ZYv1km75T37f3PcAYjnjPLLxxKYUtnNO/pWuWqkNY7jo2GF9Hy4cvI6H1c32sdCSK49WDUdwm1KBQX6nDU7wGWb+UAnvCbp8fvT4rcKuUqIwHYufj0sbdQ==,iv:H2xstGNBu2dpzre2Ds6pk4uQwmH6MJQm5xd1hALXEgg=,tag:zXSbcW2NSIgn6K5Yxm6Jhw==,type:str]
kind: Secret
metadata:
    name: dawarich-secrets
    namespace: utils
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWmRGbnh1dTN2dEc4Tmx0
            bDZocXovYlkyRlBVL0M3bk1PY1Q0Z0hYT0c0CmZWZENodTBiU1I5S05kTFhDb0V6
            UTFSOHM0QnoxeUNLTlFEckRuU3Q3QncKLS0tIGhLTmllOUZydlJ4eHd2Wkxud0wx
            cEs3cEFNSXltR0s4SS9FQ3J1NEkzamcKDu1ZkfQsEMvgfdLXiSgT56Cj+KqodzLd
            ugjr21ceqOuWRKu40H9JiJwaYCQNdbiqskxsl+9jSBvnagCnyNagqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:37:59Z"
    mac: ENC[AES256_GCM,data:OsAAvEeTEKNJEFk4w/dzVOMjD2evRsKw4fZRBra9KrxGfR5Y2iJAKBt6nX4N3bGTGmuM4AbRjo+Al/rmf7/OJoLdyvMJb9czxip0TR9FkU5qmBKgol1sX6tV/QmSOT62jt1I0EjQPfk1IbQ4a+rhjqx4rHJn6LawLAP4DCnTVHE=,iv:NDEhG4NLN2COTE1emUV8KA/WEfJb0fvWsK780/+XgOY=,tag:4e3FHV9JWJLf6Vi34X9qNg==,type:str]
    version: 3.13.1
