apiVersion: v1
data:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:4jIR/ZVHCLBE7amdCGUFYhyn6fV30+8kMtZnSZAAocjuutNi06MgxgWXLv+Fb5q8a25n5LNBpPo3mkUfdY8AJHlnYY819C1kCEBMpLMq9eh4XVwIxPytZg==,iv:ToQqUvgZ6sTJ/v4hTXluYBDECdlcWaNe9mUL+ZZMWpY=,tag:saPz/8MMmW41RZsoh6P1Kw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5WaRjCTrV3IrxpaXJiyBFk1yJXiLmQeKHTEmtqs6koEDeqlL/53DZbtYHFXiD7x2LDQU6yLUoB34AWqp37zHf611W8ygI0Cnolo8PIZy0lYuuGxyd3ZB4cVYFazYDssbY5z8OsfKw8WnohYJVz15+5BJSyR9n6kIBgwATvI2N5U=,iv:SriIHd/UvrLAnZ82P2xnXxmRVr1z4g2vx++WMFI/zHQ=,tag:KsqJmby0J4cKVqOxcAdTzA==,type:str]
kind: Secret
metadata:
    name: dawarich-oidc-secrets
    namespace: utils
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVNPU2pkdW1yS2lCaVpv
            YWRTS2N0d1VQcEtnaXE3WlV3RDU2dFNkcVdBCm9JVlEzbkhuYndrL1VGN216ZS9s
            Rm80VkVJaGJGRVg4NEp3YVljOWNGZzAKLS0tIGdCRkZBZXY3THhkYkpMNE9PZ3o2
            YXpKM0VTSWJtcUtnaHJWczZrY1Z0Y2cKBmrvY5Rq5nocrFKbnMeEO0L2qV2ZRf2j
            zjzr4mkUW16zvvIX+wiPI5SqGjglUcUowIzgB8K9ybFb2w/suiNDQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:38:00Z"
    mac: ENC[AES256_GCM,data:yxVTk/9Hd4+kAsGPNCEVLm5Q2eFSAJwewxl/9INDSFwDdiP1Vezj2RbRRFARTUhovvhOiqWj9vAauKAKWiZC7msSWIlpViY9GO76zy5iooWbLRKL8xcouBzLiBY5ffGxK9F4r2zc4Td6QQGDjZhMfNC2NR9JMkLnidcSP5QePcc=,iv:7Mg/0CORyq+EVBonLIw+Vd2uFrcGkJd8rpHw+XSGZAU=,tag:/JUO5XAoQFznCHryX2IC3g==,type:str]
    version: 3.13.1
