apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/bjw-s-defaults
  - ../../../../components/ingress/traefik-base

resources:
  - dawarich-db-secrets.sops.yaml
  - dawarich-secrets.sops.yaml
  - dawarich-oidc-secrets.sops.yaml
  - cnpg-cluster.yaml
  - helmrelease.yaml
  - scrapeconfig.yaml
