apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dawarich
  namespace: utils
  labels:
    release: observability-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: dawarich
      app.kubernetes.io/name: dawarich
      app.kubernetes.io/service: dawarich-main
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      basicAuth:
        username:
          name: dawarich-secrets
          key: METRICS_USERNAME
        password:
          name: dawarich-secrets
          key: METRICS_PASSWORD
