---
- name: Install oh-my-zsh
  import_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: spaceship
    oh_my_zsh_install: yes
    oh_my_zsh_plugins:
      - git
    users:
      - username: "{{ ozh_username }}"

- name: Install spaceship prompt
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
    depth: 1

- name: Enable spaceship theme
  file:
    src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link