apiVersion: v1
kind: Secret
metadata:
    name: discord-presence-secrets
    namespace: comms
type: Opaque
stringData:
    VNC_PW: ENC[AES256_GCM,data:C+uNVNjlypPk4azMkuiSPCsJ4rYgwJW8v1NFfuUEhHrINtyrBsI=,iv:OS8eRTeDBW5XgjEcLnPrINo3zmDFNWFxOAnF9kuHAkA=,tag:KR+wQhvyA+XyFhDCY5wFbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDck1LNmF5aEo2ME8wTER5
            dDc2alZxVHNEOUw5RUNLdDdqMW8zb2dEQkZvCkhRb0R2WG1LREFFcTNiMUtCWW9X
            MkhxWis3MGd2eE1OVUZUUXBGcFZnbjAKLS0tIGRVdDZ0bXJOK3hvR2FlQXhzRmYx
            emYrVHdqK01KdXBVTXhQQkxtSXA5aTgK9f46jYLVyCqop9OKLdqkMWE2/+tNYSZd
            /7AwMAoS5fyMUf9WrFct3J03MU1UzCbFXW7AOQhGcNOedWce62+/Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T23:58:45Z"
    mac: ENC[AES256_GCM,data:JXa+yC49hva2HLnUGTwLSNFhgHgoJK7e8kKccgTnn1VoRmr7wbmPHlXaSOsPGz0mJakheGZ3HPvDHlHT5TLAjOwDBdC3Hda3EKwGGJVngColUkjPo9K5zAp0ASL2CCPKwtwe7xsbFkvVtGgCSB750pVth5XaIukfQHHsro45X94=,iv:HjspUA+bzhY8fX8Zskkj9h72FdeHGid4rE8jtbvwCpA=,tag:PYe/PRxBVaWf/igOf3cz2g==,type:str]
    version: 3.11.0
