apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secrets
    namespace: media
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:5kGi56Omgb8bRyxfbrs0jVmrULCJX+6uYgi9g7tPRR0=,iv:1hgEus+jZFKPbVlcmSUue/Jq8bQ/ddxHytYVJM3v0wQ=,tag:QsSl1iCCVCfvvxe0+Fi3Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVm9iZDI0OEN3YWRsdEZB
            MzNXcHpsS21jTkYvLytyVmgyNXNOM1VUL3lBCnJHWU15c1dscFhaNXIyWVluNnV3
            eHR0eTlCbEppRU1OZDNnVG15bUZUdGMKLS0tIEcrcnpDaE1Yb2pTcnVOaWRvRU52
            UUdXdzJpTGRzZlFScnl1bmZiQnN2MDAKOXA8i0CfHI9Xi8Pm5Lwa9X7yqDCxZdzg
            MU/6EKDEnc9a6Oyfc7pNfgcbIqfNM2tnFGAxYQpX2IRCz7nym+TXAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T16:39:08Z"
    mac: ENC[AES256_GCM,data:rsqlL2o6osE7WhxCS5haSfhYP3VyCosD8avRyVlsNv5GLI0O4TCQ1To/uRxItDBi0hTaTipxP9+O0P0W+2ZJmJDlOCtG34fTIqLIYITyVyeeQk+s5GzErBDdPBAusN25SQzknuqQjcgqq0saN2lmcGXT33r1+wSm7sf1Nk7cDDo=,iv:lCscQ8pRd38i2X1Zo2D/Ol5tRHbVlNfBst3clLeHucs=,tag:rdBIjsvRodjB1TgIUqbAZw==,type:str]
    version: 3.13.3
