---
- name: Reload host power systemd units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply host powertop auto-tune
  ansible.builtin.systemd:
    name: host-power-powertop.service
    state: restarted
    daemon_reload: true
  when: host_power_powertop_auto_tune
