apiVersion: v1
kind: Secret
metadata:
    name: apollo-backend-db-secrets
    namespace: reddit
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Bjj0/oVh,iv:JsChgix9z0sR6b5jTLjjYaqDegotAgxIuPd79+OnjFQ=,tag:Rsbg5OpzFD9M7i1ZrwxJDQ==,type:str]
    password: ENC[AES256_GCM,data:+NQFvUh43ryl6o9fd254AVoXAwsd/p5cLEN4GrNIxSuFb4CKdJQTdmRzNyeTMdKBlUVme1o/AwLMyzo9N2u/sQ==,iv:l6H2Ob133o5bjUZaQIMsNiJwf0h+XaMQ0HvTbpiNSf4=,tag:48dblFiBWRhBq/hrb/RyDA==,type:str]
    DATABASE_CONNECTION_POOL_URL: ENC[AES256_GCM,data:OnW2RDTy8CpxW02g0ubwdp4iGyHDi8WRh+SQXZl3+a//0GKIp68IiVhZrk+Nb14biGuSpuE+T8U2y2hOt/M4Uw8m7xqPTf/5ePFSnFT/3st/x1/yMnoR1BROhzl6yLp4lj/eRNGz+BemNZPzBCEF79Ws,iv:2SadxnjgcqS/W7/Oht+djM+VP6Xisjab45pqQJ24ZJ0=,tag:X0QE65CeHrmXyN5rcjf6xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMkt5UVI5QVhrdmQ0cktD
            TGxKRVpzalRCa3BMUXR5eVRNbjlJZC9EZ2xZCnV3UWtjY3J1TU5hRkdJTGRwbmhH
            aWZyOW5mZEhVUFpSMkZ2Ryt2d1dhUGsKLS0tIFErZGhSLzhNaFFLdi9xT3NIdnRv
            TEU4Q3FxTGR3MmZ5SGVoVG4zU0hUSWMKqSOxnnnmf9Q1PiKsflHjHwRTCgglOn8A
            0X8dYYpRxGD8oCNUMS9k8QGCYcmDVXIlsTL6MALTjmsNQcl1BllJ9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T20:07:40Z"
    mac: ENC[AES256_GCM,data:IeWfJw+VFxrJZxBVxhwbo7fD9ulE6CUIYHG0omp2H+poGbFhpdphLpnSXdHz2njhelNjfJhaL9L1qASjd8LapDRTtTwbLLJEpv2QjTdiEWrmFRZ0SJhCUiK0SlgxFkyOckcKpC/xJYABUOIg3MA2Knb7/VxxB1IptOQMV4AkK8U=,iv:rkuRvS24+RJbfJEqf+U6mjKUBCGf6+fkcAB27URMAt0=,tag:14uHYOgBJHZTUzhPgF0WJw==,type:str]
    version: 3.13.3
