apiVersion: v1
kind: Secret
metadata:
    name: apollo-backend-secrets
    namespace: reddit
type: Opaque
stringData:
    REGISTRATION_SECRET: ENC[AES256_GCM,data:bZqPDc5eK+oJLc3fmd+qX54cM0SV8zgioEti7uG9/BmiMwtGpTGsfGXiMTZWYDQDJYECc8HD+3qISknTAUcDOA==,iv:++baDSa0Mle2TxWBcZRijP3vrd/oYeNh6lx0hrFwH1E=,tag:JRAzaj43mdR0vqaQevllOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5azFIS2t3eEFWbWM3dUht
            Rk92OWFNbnNIcFgrVTJVa1RxZERISjRucFFBCkJ2L01hSERZRmJDZWE2bFlxeVpC
            dC9KTzR0TEFNVzZ6VzdjRS9Mb1RVbW8KLS0tIGFxbmwxL0tQSnpYaExLL0Q3K3hG
            NStzWGNhMFFldldZMm9rOVZPbVJuN2MKjVrLnEUN5mvHNW6GxqqIxq34HmIs5WaW
            bQky6VrBXgYROkfEonPFP0cur+z4HjJ4vtH0ZGbZREKJx6Ko8LcvUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T20:07:40Z"
    mac: ENC[AES256_GCM,data:koZBtJJxPIuyo3pYmoo+/KpA9+gGPtnQcyifSXjAXNejb2EsNVAQrceHIP17z4FhX8zJCjfJSdZ3wWF+kwRBkZoXRwKWmo5aK8Eim9dzsBFBYuK3btXvN5Qs3gBZnRu9L3cbyd5Kk8wcHkgOMw6TkfwLT6CSgshqASMrwqB9OFw=,iv:IHhS5e0hZpg+UYKFw2LUWACqmCdIdmfei6x9cWxWIG4=,tag:/OOARWCmHdH49RmVs07Izw==,type:str]
    version: 3.13.3
