---
# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.
# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.
#
# This file defines the Hetzner public VPS hosts and assigns them to the public_vps group.

all:
  children:
    public_vps:
      hosts:
%{ for node in nodes ~}
        ${node.name}:
          ansible_host: ${node.ip}
          ansible_user: "${node.ansible_user}"
          ansible_port: ${node.ansible_port}
%{ endfor ~}
