apiVersion: v1
kind: Secret
metadata:
    name: discord-presence-secrets
    namespace: utils
type: Opaque
stringData:
    VNC_PW: ENC[AES256_GCM,data:C+uNVNjlypPk4azMkuiSPCsJ4rYgwJW8v1NFfuUEhHrINtyrBsI=,iv:OS8eRTeDBW5XgjEcLnPrINo3zmDFNWFxOAnF9kuHAkA=,tag:KR+wQhvyA+XyFhDCY5wFbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDck1LNmF5aEo2ME8wTER5
            dDc2alZxVHNEOUw5RUNLdDdqMW8zb2dEQkZvCkhRb0R2WG1LREFFcTNiMUtCWW9X
            MkhxWis3MGd2eE1OVUZUUXBGcFZnbjAKLS0tIGRVdDZ0bXJOK3hvR2FlQXhzRmYx
            emYrVHdqK01KdXBVTXhQQkxtSXA5aTgK9f46jYLVyCqop9OKLdqkMWE2/+tNYSZd
            /7AwMAoS5fyMUf9WrFct3J03MU1UzCbFXW7AOQhGcNOedWce62+/Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-14T22:30:33Z"
    mac: ENC[AES256_GCM,data:9DOz7UL3RUX/goQs34qxaXi8uMaCrlgQGo62HVeHuqzmT6dWDwsW1i+Bcw2pgCZstP5BA7Huuxtk7bBknLntTaPOv8yRY9aJVAWd6qt5v2xXanf9BxMLh+SS9dw+6l510ugY6jJBVQFTW/G1NFB5j26cPWVy2IRPxIztwOZ3Nlk=,iv:WWEjLlU+YCDRIBQiKDCEtUuSMZrQmzDikMuCsvtefnE=,tag:9OYuuUX9XHJnbieVJTsStw==,type:str]
    version: 3.11.0
