# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-exporter-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: plex-exporter-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PLEX_SERVER
      remoteRef:
        key: ttz3ot4kdb6ohr5dtilaz4cvha/INCLUSTER_ADDRESS
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: ttz3ot4kdb6ohr5dtilaz4cvha/password
