# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-automation-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: jellyfin-automation-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: dqcuyxfpwztrpuw75ydrpnrvpu/TOKEN
    - secretKey: watchstate-global-webhook-url
      remoteRef:
        key: dqcuyxfpwztrpuw75ydrpnrvpu/watchstate-global-webhook-url
    - secretKey: scrob-webhook-url
      remoteRef:
        key: dqcuyxfpwztrpuw75ydrpnrvpu/scrob-webhook-url
