apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-automation-secret
    namespace: media
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:vyTW5daaDLz+yA1rF3ybzcjyCQ4JJQQOEMUSquexFdQ=,iv:997u1cHa/6BiHWERGBybwkp61LEvhXLwaDFrkvUvsQw=,tag:zC0SYBJTeYNtF/H8Bdwi2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMXg0Qzd0YVo3V0xkcUVz
            RjFMYlo4bFc1c2g3cGhpM3hlSEhQcENxRG44CnVPdSszRy81Q3RwUmo2ellXQWxK
            UW8wMmczRmw0S0Q5Zm1XREZhZ3V1TEEKLS0tIGN0ZmxONVZWSUhFMCtOTVd3aFNL
            RktFZzhrdDlzcGxTRGsvOFB6dStsTGcKNjfG/JZXhrHku2MzYVmku3iSztDm/5fo
            c9jP0dy2tK/j2rWTP3D/t0TtmyDQUoKfrBvaDLJb6e7j8QH7ZtsWYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T22:52:03Z"
    mac: ENC[AES256_GCM,data:fvfmZkftof/+lSRALHm5vOlvWtRw3lmXjNna7OXTz56+rnEV4DAvN5+DoRYn/liJlXme56br80lRRIlvwlG3fPttwKYkMl+gNoS8vOlhqDD9lnRlpccTibxGYWs+Pa1Zn4yCQuCqL0FKRqGm9zDqm2El7pED/Bx4e0skCsnglps=,iv:cGHrOtbP9EthBIb/MpgcbNqtQLn0wjp2IDM084JaRQY=,tag:dRLyosAqNyFNZS2n+iURzg==,type:str]
    version: 3.13.2
