apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-automation-secret
    namespace: media
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:Qy8wKH34G9Q4dgzzMXxFq46rqbXpuV+HsaiMG5nx04Y=,iv:2OZm1igMAbSrQxA8VGCOrn9cdfd4Vq0qQ5IyII7LGqM=,tag:1cvBodPpnqX06zoomGDb6g==,type:str]
    watchstate-global-webhook-url: ENC[AES256_GCM,data:2jLvzDj9A4g+JISBb9EhsLzDV2JCxIEnfjv9SXF4+/nNcsWOeWfIOKdAjBwwHzyRyZBbnYMPVSf+tS0wH1p96oyfzpNgDobsVl8UzD2Plpe8WUeeOkt2+qKCnepmvyLSsJSnv1bJVxa7iGRLcYKB0HzqbriF/zT52t171JebaS22X2z5pg==,iv:R+yGYtkiv3YqYnoPV23Qw4/V4D/jHR6B21K0tWLU+vs=,tag:+d7lZCDdHb1r6+d51udGfA==,type:str]
    scrob-webhook-url: ENC[AES256_GCM,data:aKGOMlnW9PGgRsKAEAHL8cDsTJfwjNDNPZ2Mzb8Nnln8bE6i0kE6cY7xwS+vf++s7jyow6eI8ANEzX7fe4g+v5rbiB/NHaNZhHaUm3XCJky0jVJxgZXfEuVshqJeOrampWZjRNzTi335DYORSkzqil4fT3bOsa1P8NHH,iv:V6WeBNwOCDNj+rYMqBZgsVt/Eu+3rCbtAvsxOtVMEjc=,tag:w35CX+C89rlO5F5gfjldgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTUI2bXUvRnZYV2Vtdmxo
            dCtYSHArOUpNMmg4bGtxbVdGWVpNdUZLL2xFCnlqZ3ZQM2xzUm56UkNqTVViazNW
            Q3F4SWpPRmw2VFo0aDVZcjczckhNRFkKLS0tIDJKbGRzbWhnYXFXVWVuUFFoMnlp
            WU1qT3dIL04weS96RWhjc0FwRktlblkK8Ioe7lWDQyCUT/NOIJJFKrElqKOnO6I9
            xcJSkPZG5IF33GKyHNT9iPkyB76smm7gW6HNLsB70fKr3szZsx2Z8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T13:43:57Z"
    mac: ENC[AES256_GCM,data:3g7PAcOOOHX66HBbpUY/jXMsaiP8e9vnpCERippRIbvRlknjET725PBaTtFrjkhqMSoRnooH3M98SyhQ5r/DWzI9IBm9ia340fZWbVXHbMRmi3v19HK3J0iPbzNzxJovZtktAtphPa/rfMz2Kwg99H1AZHew0Po6Eqy7ALTWPHs=,iv:/22FpY0RwkrBHtIxrYOJ7d8/3DhZGKecMT7e1pE0yw4=,tag:b/J74gSNb6KDJ96ZrMV/EA==,type:str]
    version: 3.13.3
