apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter-secret
    namespace: media
type: Opaque
stringData:
    JELLYFIN_ADDRESS: ENC[AES256_GCM,data:EPTjEssvjpOthYqYEdjzUbnpFqKj,iv:18zHTtqgzN5R4jkGe2mmpQvr2iuLlXaqem49BahhCaY=,tag:RnxSs5q4O6JJYFeUlWrjww==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:cVlIHVLr/hDUDbypfh9AKVDmuqdAtVJR5coRoNlnORw=,iv:k8mom3Mx+hidLpgkQPaZ2tpaVUCZl2YxY5l4ApeSczw=,tag:pECWyZROGsvn7gSP5r9npw==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc3BaYm5KQlQ0TGNQQkVY
            aEE0bXNOTEJiSStrTk1uOXlkT3YzeW5XUlRvClU3dFAwM0ZkZzZ6Z3FWREsybktr
            MG9SN3BRd3NFZUxVdTdnTEt0VmN1Vm8KLS0tIFhvVVVVVFZ0WHhXLzhYV1JIQlpJ
            WHJXWlJyZ3Z3WVd4aWE0Zyt2cFowN1EK1Nj1RHT3W7c19nznRZsgKwVByvhmRHrA
            NHh5LEr4p1v/7McrO+stwAGon2a0D69qlfSWRVNtX66E/BgTYaAv4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T23:36:16Z"
    mac: ENC[AES256_GCM,data:PcKkTRq9BYVE1RuO8Cro03NjVvG+CTi89ow9mBtSEza4wJZm8D6vukb5IqUiA+Yd8V6GiTzLgAc1oQ2KqZbDODpM8D6gwSefdSTgDEwjkgeT/hGTK51DL2F/vEYq2tsv2IuFdreCaiWUQF6LfgVq0bUlHhLkamGU50ljbZ18p3o=,iv:MmATtzMQh692QyKUvQgwZJBVih7Ozpkxd5kb0O9/oqU=,tag:4QNEaYbmT5TYvqUDZDKhMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
