apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/bjw-s-defaults
  - ../../../../components/ingress/traefik-base
resources:
  - helmrelease.yaml
  - automation-config.yaml
  - automation-cronjob.yaml
  - jellyfin-automation-secret.sops.yaml
