apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.sops.yaml
  - dashboard.yaml
  - helmrelease.yaml
  - ingress-grpc.yaml
  - ingress-http.yaml
  - middleware-allowlist.yaml
