resource "local_file" "ansible_inventory" {
  filename        = abspath("${path.module}/../../../../ansible/inventories/photon.yml")
  file_permission = "0644"

  content = join("", [
    "---\n",
    "# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.\n",
    "# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.\n\n",
    yamlencode({
      all = {
        children = {
          photon_lxc = {
            hosts = {
              for container in module.proxmox_lxc.containers : container.name => {
                ansible_host = container.ip_address
                ansible_user = container.ansible_user
                ansible_port = 22
                guest_os     = "fedora"
              }
            }
          }
        }
      }
    })
  ])
}
