apiVersion: v1
kind: Secret
metadata:
    name: mailflow-db-secrets
    namespace: utils
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RH/82Z6Nq6M=,iv:jhf//MkFMsc5doF3ItzKR9+81VlEveqqk0kiz1wbeq0=,tag:j909+HnEaP/yVZArjZ7YCQ==,type:str]
    password: ENC[AES256_GCM,data:QChntOx1US5hVhGB6b2Mx9NhtDhWus/+66KtRruG0BnEGlU/h1n0TuqRNUAJ4x9A,iv:cOAucqEBgjB3i/cjJ2Byz6zNkmpTcMJhJAQba4sV+GU=,tag:XG3O0yANlUXdzoA2t1PWag==,type:str]
sops:
    age:
        - recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY1JKVUtJTWhiZzNXL25H
            ejRReTkxVVhCWENOdXM0OS9Jc2ZpRkh0cDBRCjUvN3k3ZkFLQWFQRnhET25TN1JZ
            QkVJS0ZydnIxamFCbldsY0xndWpGNnMKLS0tIGUvYmlDcndnQTZ2bVppM2NwdE1m
            MGlyQ3ZVVEpCUGh6MWxrbnpGLy9IaU0Ka2m+JIHdkFjWzPNXtzYSMXKGRwMqEO2V
            w5GhlHWx8IdwuE2u//8LsiLMzDaUwiURfWWhzFLCwdm8iF45BYyM1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T22:23:05Z"
    mac: ENC[AES256_GCM,data:a6a6RLZ/JauqTk0QZCDTSvy5avwCJ/PKy3+8CFD7/LTd5a34Xhk4JHIvEBgHbCfzrWgPq5CSOj0ZQg4uTPu5SKS+LabuJRTk6OJaZ0Ckysjtocmi+JH+HNV+DTVGHS7USvFoKaIAS5mP6jz62baMG7Luz75aGR7ZK6BBXXd2P8k=,iv:kZgMIHe/YySPifpnQtTtOjzUpRd9T+Db6Yk1nM2HWjo=,tag:h9owWcoVNZoPpnKxUeyLjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
