apiVersion: v1
kind: Secret
metadata:
    name: mailflow-secrets
    namespace: utils
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:MaOMf62fujBA2CXNiWqGa5JIz/qb6HAFa90qsoo0BzqgMuA+0vQXK+HpzqQyeGgNgxdfyqNzwlCudx0nsvHUkg==,iv:wPfC2mW4pLLCGT+mBCxe8cX0nM4zfb+C9DpWjaovvHU=,tag:pzfUNXi5e2A4XotDxbmb0g==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Whm0kEiZ4Kric9SEZkhJlTzFZmuP4OmZaIVDl9rMN68Gl+6EHO48nxAJvoepL9Xm40efx/9r0mJFYkhM0y52ig==,iv:omgdxa27NzKvJn7FxlBCIcPsGwhBoTMYAql4t2/AmAg=,tag:ZvG3fG1R97axEd8cInf/ZA==,type:str]
sops:
    age:
        - recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QjJHcjY5K21iN3lLSUFl
            QXVNRFBJSGduQWZNYmloaVIrNUZCL0JBZVVNCjhrSEVEMWxyQmQ2UXRuTGNLS3Rw
            RFdBb1JnRTB6TkdXcUF5NDcxSXdtSzAKLS0tIE9CYkdidlNPUHMvc01qUTJqVWFm
            Q1ZSbVlwTWpxQVNteXhhdnBVdGhPUXMK+kixYpe2tm63TTbbCzdGnep+eLe7K5nf
            uznSRWIulPlWNSLvZVoRzu1iMNglStWqGSLCXKG+SgD5EE8sZZJTzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T22:23:05Z"
    mac: ENC[AES256_GCM,data:uXbtkemctq7kkyKKFuGNAm/Of2SLE9fmPElGcy8xiI5ao6rv9TXVctRzJPJ1vSp9dPRfttFyr3tooi156yE456AOhIoPDiKuw1V+FcMYHvlBS3O3Qznc8Y9CH+BFSEc83/VP3agRM1gLyoBLOKuvomo7t5EEXHC3M9mgbPFX7Iw=,iv:JKy7hD4igmHqZaJM02aaNSulGZj7ffIGJpmoAJuj4x0=,tag:R1S0CQyIBV67ep1as37Kyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
