apiVersion: v1
kind: Secret
metadata:
    name: gitea-mailer-secret
    namespace: development
type: Opaque
stringData:
    GITEA__mailer__PASSWD: ENC[AES256_GCM,data:1nG7sbelWLxoN2bfmA6i7vRMaA==,iv:ezNvQ9KgXVbBjI9qDQ+J06ZxBLvZJB66gkFOvG9/+HQ=,tag:XaEgDDlXCg3eEKmlQb1KMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmtYZW9pQzFTdENVRE9I
            VlhseWFuejZXUDlSNjRPYitCZHhRT3d6OEdBClpENWVaSzFOMzljSThPMXhtTUlS
            UGRFSkhzQjh2VHZSbGp3SDh2YXpNR2MKLS0tIGpwaVhWZU85b1pPTUxsUnlBakYy
            YXVrczBrUnkwcEQwbHdiQ01SeGVSd00KaWwG5cHDMEhpO4rvR91V4dB0p500wq/H
            TZPJWaCOnyoEk2NLw/xPI/g/DM2fWEki2N5ZdDf1cqfbCBPK4TSv7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T22:20:16Z"
    mac: ENC[AES256_GCM,data:Jrh3QUbND76catx+322Kq8Jpv7sh6w9FyBmXRFEMlvc5cWxqS4IwipPa97xmlhfA6pZrOt5McfG9m5hWHeWsdtm98BPHAG0to8rm7xiC3ZsYQCo4Hu3N1ufmLC33S/x+CYNoQtdwWjmAtyD8GPwGDI+NIdtkNEYJdzJgiKIo3Dk=,iv:embF37EQgajNTGdk4lWqBro7tWccEL7XtYHk7aBDQHE=,tag:nSjPjcX2rWOZajil2ZKrGQ==,type:str]
    version: 3.13.3
