apiVersion: v1
kind: Secret
metadata:
    name: gitea-mailer-secret
    namespace: development
type: Opaque
stringData:
    GITEA__mailer__PASSWD: ENC[AES256_GCM,data:udAXdzCYNRLfmA6t1SDTmgCqZAo=,iv:lR7ayuO9bh247/mHaEVFkll4+Lpsy4NA5NsdtqPyRMY=,tag:iZ0b0B7Gh5BmMFQ7pl6Zlw==,type:str]
    GITEA__mailer__USER: ENC[AES256_GCM,data:DQX/q4cUMjRWcOp2+7vFdkDPUiL71FK+Cg==,iv:TiW/Iid4Ikor87oJf0ANewhGPdHTAZVSUUlNbyIZfXg=,tag:/eDiNz2P2p62vJ6sJ0K6IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmtYZW9pQzFTdENVRE9I
            VlhseWFuejZXUDlSNjRPYitCZHhRT3d6OEdBClpENWVaSzFOMzljSThPMXhtTUlS
            UGRFSkhzQjh2VHZSbGp3SDh2YXpNR2MKLS0tIGpwaVhWZU85b1pPTUxsUnlBakYy
            YXVrczBrUnkwcEQwbHdiQ01SeGVSd00KaWwG5cHDMEhpO4rvR91V4dB0p500wq/H
            TZPJWaCOnyoEk2NLw/xPI/g/DM2fWEki2N5ZdDf1cqfbCBPK4TSv7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T19:34:13Z"
    mac: ENC[AES256_GCM,data:uxU8wRVVfU87qy06PLjf8jeL8srO/2tCzD/r36vkFSVmoJ0B5mNTXlicJJH3iPMdMjOFigFSTCSwIh0heWK7hcOp5YmX0Dq9K2gvjwI3de+nWfyslrfG08wjnc+G7TCv/jo7IIYFOvhPMqQsynZPQgIS3iwzcwPcKGSruYWj/uc=,iv:0ocCcxw1Ox+K+TCr3cQnw6L70pc8JBPvwoGwUk4HbiQ=,tag:XZJbr2l0U+yH7whAo4CtuQ==,type:str]
    version: 3.13.3
