apiVersion: v1
kind: Secret
metadata:
    name: gitea-mailer-secret
    namespace: development
type: Opaque
stringData:
    GITEA__mailer__PASSWD: ENC[AES256_GCM,data:iBZeoPZNLOkh1zXhwEpcCQ==,iv:Md3hIsN/QA9FeP3/nJ8NR5PQierx4PCJQbDe7eavAgc=,tag:c1bWwYGsW7+NYrzl+LuXsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmtYZW9pQzFTdENVRE9I
            VlhseWFuejZXUDlSNjRPYitCZHhRT3d6OEdBClpENWVaSzFOMzljSThPMXhtTUlS
            UGRFSkhzQjh2VHZSbGp3SDh2YXpNR2MKLS0tIGpwaVhWZU85b1pPTUxsUnlBakYy
            YXVrczBrUnkwcEQwbHdiQ01SeGVSd00KaWwG5cHDMEhpO4rvR91V4dB0p500wq/H
            TZPJWaCOnyoEk2NLw/xPI/g/DM2fWEki2N5ZdDf1cqfbCBPK4TSv7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-05T20:51:12Z"
    mac: ENC[AES256_GCM,data:w/8grwgn89gZqEdmh/OSfLxihEdcjLquKKfy8zUiERLq1nCsrby9+KeyRgP43ThjAxE6KDnodM/KY5vHD5TPYl9ErP9QH2/+w2dpj3V8BUCCZiLGv0SVnCqlvywXj7Wjo84BdIvV/d4OkCprx8Z1XnIfQI08GxK4oaLayg7e+ls=,iv:POFbwHxaiTV4VZhGSrF7390AZ+P2Dlt8sO3/RqVTN2E=,tag:ZjAz8eHi/MnYNP/t2HMcdg==,type:str]
    version: 3.11.0
