# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
  namespace: storage
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: garage-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: API_ADMIN_KEY
      remoteRef:
        key: 25gs7wib2fr2agq4qg56nwjqf4/API_ADMIN_KEY
