apiVersion: v1
kind: Secret
metadata:
    name: garage-secret
    namespace: storage
type: Opaque
stringData:
    API_ADMIN_KEY: ENC[AES256_GCM,data:2hTM/Aloicsz/FCS6QvbuiT38Tmh4h7wWTFAaEglwF+x20iCTeWVY/mZ,iv:c/pc06evLNEe1pgzgGmipYwOKLQBa8MxqrGfkoIn5U0=,tag:AtmOciuKIcKHJ+Vb4tyUbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVFBmQTVHaG1qaUJrL3FL
            OS9zdDhHODYwamdOU0s1RkdqdEtXYXVMVkhrCk1ldXVrRGpVdFZhemsxMSsxbmo4
            Zm9EMHFUVVg4ZWtKc1VueExqYldsSUkKLS0tIFQ2NktQREhGMkhWTmd5VGYwTlVB
            VVZnc2xxYlN4dVl6bDg3d01KbXJsVW8Ke3tcMzYgAC8WfGVf+RgTzN4CDdR1Tlsl
            Q09mYUyIK8LxXg/GqGJgbHVMg5v4vaOv+2rvlpNB/Yat32ofFH3Mtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-22T01:07:33Z"
    mac: ENC[AES256_GCM,data:2NqE1Ce2vJCLMqhSfG0+qMx4SAhMnOqcRqucONMqw0zVToNg0mHk9nJ4WhIwYwO8jZivjEO+sIOMheoVw1cBYfQEJrUQEaQdS+lGYZ2ksba9TB0KHSER5v0BNJM3XhuMwHqEYPecrgYYu0RHOfwsepOqSgl8ui1/iBeqrSVzPCA=,iv:JGMEtVJXNoPWDGvfGt9Z39v3tW4DjYhL5Nm0Wq1cw7k=,tag:Qv62zIKyNSzg986Xov9o9w==,type:str]
    version: 3.11.0
