---
# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.
# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.
#
# This file defines LLM LXC hosts and assigns them to the llm_lxc group.

all:
  children:
    llm_lxc:
      hosts:
%{ for container in containers ~}
        ${container.name}:
          ansible_host: ${container.ip_address}
          ansible_user: "${container.ansible_user}"
          ansible_port: 22
          guest_os: "fedora"
%{ endfor ~}
