---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check cloud-init config directory
  ansible.builtin.stat:
    path: /etc/cloud/cloud.cfg.d
  register: common_cloud_cfg_dir
  changed_when: false

- name: Check current timezone
  ansible.builtin.command: timedatectl show -p Timezone --value
  register: common_timezone_status
  changed_when: false
  failed_when: false
