# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bark-allowlist
  namespace: reddit
spec:
  ipAllowList:
    sourceRange:
      - 192.168.0.0/16
      - 10.1.20.0/27
      - 10.42.0.0/16
