---
# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.
# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.
#
# This file defines the K3s nodes and assigns them to the k3s_nodes group.

all:
  children:
    k3s_nodes:
      hosts:
%{ for node in nodes ~}
        ${node.name}:
          ansible_host: ${node.ip}
          ansible_user: "${node.ansible_user}"
          ansible_port: 22
          node_os: "${node.node_os}"
%{ if length(node.labels) > 0 ~}
          k3s_node_labels:
%{ for k, v in node.labels ~}
            ${k}: "${v}"
%{ endfor ~}
%{ endif ~}
%{ endfor ~}
