apiVersion: v1
kind: Service
metadata:
  name: metallb-controller-metrics
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: controller
  ports:
    - name: metricshttps
      port: 9120
      targetPort: metricshttps
      protocol: TCP
