apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-identity
    namespace: flux-system
data:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:9TCWm9ElBvZJrlyJ1RonCSh2EyQmDOTZ,iv:ZhjPzjqk+fN8zr+mbdQmQ3khGoPd79Dv5OHLucx1nmM=,tag:GFtZkiUeqnAAfLunLzkNAg==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:6OYa5mGzz99WYh8nJ20qHec+ao+kr3WuHC39oQ==,iv:ltMPacT+/tBjQKMow1CLdlH3QaEpv6/O9y0WTbNGel8=,tag:VQtUJXa4GH6Ny6PwgbOGzA==,type:str]
    METALLB_L2_POOL: ENC[AES256_GCM,data:rWxUmBhy0nuIrGPy11PwJPuQnMcenjcf2rSnInk=,iv:1ddQ1r0scXzNva58axzpoYMRSt8VuvwCsXlTedZ6RDA=,tag:oiJgeSABt0YVbHQYgoWGDw==,type:str]
    TRAEFIK_LB_IP: ENC[AES256_GCM,data:oIlylaFV9XU55KwDNII=,iv:p2HthDL3a85u9roTP+Uk2AENxHmWco2jzJLfEOK2W+k=,tag:XY9dRbF6JwtUl6Pq1GwnPQ==,type:str]
    FRIGATE_LB_IP: ENC[AES256_GCM,data:S6Nac5oJ4ijKnRePS38=,iv:0IYBewwTesRYflAnUSl6/aX06h0sa0+AoZLNOA1gxp8=,tag:j5FdsqzZMHMU/mQILdHNag==,type:str]
    ALLOY_SYSLOG_LB_IP: ENC[AES256_GCM,data:vcjjZ+5+P8DFOhyXqgU=,iv:gjLmXf39Kwx6bJSXsFL4EeTtakSENcGXPgRjjx7DASg=,tag:1GqlCjQCytsH1/bHE2LPRA==,type:str]
    PIHOLE_IP: ENC[AES256_GCM,data:P+dW2h0gw+2J16Up,iv:pfqAYVnuuJekcHpsq37Avqy3S3aY/B3EKhvRUokLC64=,tag:u79z2TQSZvVPlYLDlVc40w==,type:str]
    PIHOLE_URL: ENC[AES256_GCM,data:m7dy+DYMjC5A3z2Ng1ehwlrtfSU=,iv:hBkXsBqh5Kc8g13O+cWbzQTdW5pTrZP/bSR22oxmWlI=,tag:I/YKJCcZUcsAMlr4FkB/OA==,type:str]
    UNRAID_IP: ENC[AES256_GCM,data:EF8flwBYJEl3K/dh,iv:MLC7aaOh/h7fsO5JqRmjNRIYkpaKsAsuVAdn8FeLiFg=,tag:dYS54yOjfSne2FiHwVEfUQ==,type:str]
    KVM_IP: ENC[AES256_GCM,data:gwfEaeVmoSuu9ooG,iv:iFarWBFvmiUD8VZPSeXRbJVGV3Ufksu3g+zx2KiZE9o=,tag:PZW23O+RvVpLCjH4PrmgDQ==,type:str]
    RPI4_IP: ENC[AES256_GCM,data:XFi7QUMON2U7KVIG,iv:jdICv57i0/LRGboSDcS5cTOEAGAS8uasmHwadGYITW0=,tag:jbDujuZegMDYmxal952V2g==,type:str]
    OPENCLAW_IP: ENC[AES256_GCM,data:bC5dlUTX32bjVzMdTQ==,iv:CaP61pVpuToE3BOBOnyJL6Ueq1yUlls8FI4lX53ydyQ=,tag:Xebw1J1n4P4CmLUp8T1WzA==,type:str]
    OPNSENSE_IP: ENC[AES256_GCM,data:r2CHxSpW625zDpUQ,iv:5Kmt65J6mwCMqhMR0H0ztxLv77KLilBXOD9aHJWFaRc=,tag:hZPWyyHEqWxT/k8XHRYUTA==,type:str]
    LLAMA_SWAP_IP: ENC[AES256_GCM,data:Jb7MGRHKjjoovnXFeQ==,iv:y88LKTwIDV5C9GxZQLE/BBGGZrjvkrGTzlrJVhaprJE=,tag:IKsAoF1ZZEqNFfw+GjrPXw==,type:str]
    OMADA_IP: ENC[AES256_GCM,data:Hl7JKhkTORU5KNk=,iv:mdu+yo7ZAA1vQkwbnUJ7EvgAtA9QikXbLhltwgNGHhU=,tag:cHi/M8hKC8Cw+rMVOokxog==,type:str]
    PROXMOX_BACKUP_IP: ENC[AES256_GCM,data:vqLV4yxs5NO2AYc=,iv:7a6yObZGxMRNj8ZSwSaKFmAIi5E2mU6zuYuCXe6tnjQ=,tag:Oepi/GaPsXuHZ7itL8XNhA==,type:str]
    PROXMOX_IP: ENC[AES256_GCM,data:MIwKmfAR+tnPzyQ=,iv:Q+E9nLizBasLRw8wEtpy777klg6bJblk+vApKFTCJ6E=,tag:FyAHi8040EPFZHquOQ+oIQ==,type:str]
    EMQX_IP: ENC[AES256_GCM,data:HpPLaeP1PPvqtarQ,iv:SzLTPGuzbEAjt96snHx0c6NMLCrXBzreQoz4eG2tr2s=,tag:gnI218zzL9OQYEoI/NpPmA==,type:str]
    ZIGBEE2MQTT_IP: ENC[AES256_GCM,data:EbizHO57eetURhqN,iv:UXMky0tQb6Ipd4nc3RDz1NDceYxjn2agzbMkOc9dALM=,tag:4sydioI2DhCs+J2HJs/+Vg==,type:str]
    HOME_ASSISTANT_IP: ENC[AES256_GCM,data:dKrgZQio2LxZcQqy6Q==,iv:h8msajAe60vfD6neP5dxLLzeK15f64264yNYCoj9B1k=,tag:dFQ0c31ZSkrV8Xj9iXC7cg==,type:str]
    BAMBUDDY_IP: ENC[AES256_GCM,data:bGqQpE3Y9qbaGVJN5w==,iv:pboIZuPLRXA00gCS/aWtGJT+PflbeY5M2Puisel9VcU=,tag:+gb6vp60/DpPHXLnOikSFA==,type:str]
    GARAGE_S3_IP: ENC[AES256_GCM,data:psmY+/9AHlHt+aCsxA==,iv:peJtgJKyeQbO6/TJPL9T+V9NNMhaUrogECxbrA0hw+c=,tag:2af3G+70Q3CHRk0zWq67zw==,type:str]
    PHOTON_IP: ENC[AES256_GCM,data:T5Qbo90Ps/43Ir3WQg==,iv:8hCFwBDc+m+hhuj31s2SpGaLtvBm2e1/2D61OXSuNo4=,tag:ZKKOgxdIafjQNzhZuAK4tw==,type:str]
    LDAP_LB_IP: ENC[AES256_GCM,data:QCrL/n9WTe3E2MoIi5k=,iv:0yIF0siavwXfTDYLyEpNkXyz+ERfeUwwsJWclz0Cm6o=,tag:qMyV+iCbkQGQEh8xI6ZqXg==,type:str]
    HERMES_IP: ENC[AES256_GCM,data:NdiUY+b+u7mXdDp8U0E=,iv:mmLgU5/CoHMaCoCDnpHjrrAMYAkQbcfDYO8uGGFIxjs=,tag:3He6dlzN+EWpkOVGpX75mg==,type:str]
    ESPHOME_BUILDER_LB_IP: ENC[AES256_GCM,data:MydLieHVrWajkWZ1w2M=,iv:upMp6Lg7WMKXSLQ84s+Bn20oAZM+ZWXMQhVCSdAhqBY=,tag:1iLvA+bZK4IOVLHUXViYGw==,type:str]
    DEV_VM_IP: ENC[AES256_GCM,data:zi/fPuR0d/zK94f0p0g=,iv:JQ/clpEdpviyuzUTGvF+7HTuYrk7NlIL+cMvzGxZ034=,tag:v6BbU+4WewLN3pE9I+C8UA==,type:str]
    OMNIROUTE_IP: ENC[AES256_GCM,data:fEOkeFn8JbteNoclikE=,iv:zdXhtJ5NkPFvUIZZbmLVsUfapp/X1w1y8VMp8rr7Y7o=,tag:PnTbt7LZAvy9aUCukfrqWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRko4MEEvZGh2anJNblNa
            YjBMdjFyNzQ3bHJXaDN1YUdRdWs5NkNIZ2lnCkNESnVpaGVTcEhsZTlPcWtXdjNp
            NGpyeE1JMmRuelN6WFdGb1g1blN0elUKLS0tIG1OanFYdlpKWFBEVlFpaCtHL3pN
            VWtSbWZWc1R5b2YwYWtibkxpdVBBSDQK1Ddf6vS9e1bhF4Bc5ZQ1GW6yVdetV0wD
            cLqSH3vIhWmCz+E1UtGGLoDIN68ubPBcS8Ge/hv1XZzJOrhjhXXkKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T22:38:01Z"
    mac: ENC[AES256_GCM,data:Pa/V5E8NskA6Xc1Upah/MH+IiDQw2iGTTgPq5Mq3y3/EyGXNtjq3Ing3YSRc7lSADLgy8Ek3NAKkSMaFK6UEXOfXHYJ1EaF9WOEt6rYybH+PUWtYvelPZN72s8qGICqDOZ3cp92xl1MhG2eKu1xDoWLc8mRAWwAAIUY0gJvoFZQ=,iv:mD5J/FZg9SIGhifTIUssxBWQjX7ybV6t+M1RLrTDhZo=,tag:wy3Bz7WgKLNofg1+5jNZXg==,type:str]
    version: 3.13.3
