# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyplex-watched-secrets
  namespace: media
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: jellyplex-watched-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: USER_MAPPING
      remoteRef:
        key: zdprlbybz3w7wsnrjjazodwgcu/USER_MAPPING
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: ttz3ot4kdb6ohr5dtilaz4cvha/password
    - secretKey: JELLYFIN_TOKEN
      remoteRef:
        key: dqcuyxfpwztrpuw75ydrpnrvpu/TOKEN
