apiVersion: v1
kind: Secret
metadata:
    name: jellyplex-watched-secrets
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:pxs8+us2TxrYOuJaE6QP743zlRE=,iv:go1M+lz1tFnkYM4HR+2zabw+hAcwKgJMSkdKr8BOVKI=,tag:+Uj8D6f0wHaYX9LktVnvKA==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:JByxNosMpxC81Bco+GIc/KOexf0fQFNriP7sveEKD3M=,iv:rO0lzV2RJEtbObBrwGsWJg/t6UhhbcrN6hOsS5dSHBo=,tag:DbA5YR56wuWSA+VGYYujWQ==,type:str]
    #ENC[AES256_GCM,data:uSVvaUwQY5jpUqTmxoM=,iv:g7mqSuQLkmI1F6mnmp+v5AHH+BmTUdcNbYzyqWZBkss=,tag:XoFKhc2C5gtZwxWGjyXmMQ==,type:comment]
    USER_MAPPING: ENC[AES256_GCM,data:Y6/Av3ZWo2WMCX0TOOrdCtEHRuPZPw==,iv:wy2qpJb+mDn7ja34eF4ADH8VPHY7hYlAIeiyItAbN0Y=,tag:/VocTKBf0rLIquk31efU6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZEtUYkc2SEZJYlFvQlNv
            K2VjS096bGhSS0w1SkRHQ01GNFB3QXM3cmlvCnlmaEJyQnJRMzRTZDl0QjlzTjVx
            T1RLaFZYcW9RVDROMFQ1YkZhR0VobzQKLS0tIG1YWE1XanNZZkRYUEsxM0hIWW5I
            SVpiR0lubkdyZFMzQ0FZMU9Ya3B1RGMKbx+DzyOc2voDB48Z9zGeaSvkRMSo0J44
            3NmE08ez1BCEA9sQgQ/uw83G/FZ0eGIYBnDnYTWwX8orcAHC6fqzdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-03-06T18:16:46Z"
    mac: ENC[AES256_GCM,data:yb1JPqEjdZHaSP23xW8oI1RZz4E/ktkITHBziYloQY+3tuiYuvnF7AYhccdUnKWRfz6KTuSgQIiRt7ThrdfZubXNR8a1E5hgrcsn5G9LtWongn7X6sTy6y4k16JYeGdtegGL+PjpkDAPYy9wv6oeAiBRYrDvf4zEiOtzx8b5Xms=,iv:JggSuqj7HQ1RLKic+kvZUxOFLY+jEY1ClhdZKwHrcaE=,tag:2EUOW8sI+ruZYSfJKnEOZA==,type:str]
    version: 3.12.1
