apiVersion: v1
kind: Secret
metadata:
    name: jellyplex-watched-secrets
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:pxs8+us2TxrYOuJaE6QP743zlRE=,iv:go1M+lz1tFnkYM4HR+2zabw+hAcwKgJMSkdKr8BOVKI=,tag:+Uj8D6f0wHaYX9LktVnvKA==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:JByxNosMpxC81Bco+GIc/KOexf0fQFNriP7sveEKD3M=,iv:rO0lzV2RJEtbObBrwGsWJg/t6UhhbcrN6hOsS5dSHBo=,tag:DbA5YR56wuWSA+VGYYujWQ==,type:str]
    #ENC[AES256_GCM,data:uSVvaUwQY5jpUqTmxoM=,iv:g7mqSuQLkmI1F6mnmp+v5AHH+BmTUdcNbYzyqWZBkss=,tag:XoFKhc2C5gtZwxWGjyXmMQ==,type:comment]
    USER_MAPPING: ENC[AES256_GCM,data:Y6/Av3ZWo2WMCX0TOOrdCtEHRuPZPw==,iv:wy2qpJb+mDn7ja34eF4ADH8VPHY7hYlAIeiyItAbN0Y=,tag:/VocTKBf0rLIquk31efU6w==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cC9maUJNVmdoYTluV29a
            KzYyMGNYb0lOTVhYK1Q0L2YvY0o3K3JVc1R3Cm9MTUEwdmdzUjRKZVpPSGJmYlZh
            dVlzeldhVjFVcEE0VUU3ekEwWE4vWmMKLS0tICtKbHNRdzhCVkIvTmVjU0FXNm1h
            bHRDeVBBUVV5emZxN2FtQnNIU3hPOU0KNSDZzeiaMk3gcwg/fHWQ9J0DYa411mqn
            DUhbwTyaeZTXrbu0c7rdVz5PbHCiZsqDFVaPGC/ackhSTlkDZAsStA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T18:16:46Z"
    mac: ENC[AES256_GCM,data:yb1JPqEjdZHaSP23xW8oI1RZz4E/ktkITHBziYloQY+3tuiYuvnF7AYhccdUnKWRfz6KTuSgQIiRt7ThrdfZubXNR8a1E5hgrcsn5G9LtWongn7X6sTy6y4k16JYeGdtegGL+PjpkDAPYy9wv6oeAiBRYrDvf4zEiOtzx8b5Xms=,iv:JggSuqj7HQ1RLKic+kvZUxOFLY+jEY1ClhdZKwHrcaE=,tag:2EUOW8sI+ruZYSfJKnEOZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
