---
emqx_version: "5.8.9"
emqx_package: emqx

emqx_gpg_key_url: https://packages.emqx.com/emqx/emqx/gpgkey
emqx_keyring_path: /etc/apt/keyrings/emqx_emqx-archive-keyring.gpg
emqx_repo_source_path: /etc/apt/sources.list.d/emqx_emqx.list
emqx_repo_url: https://packages.emqx.com/emqx/emqx/debian
emqx_repo_suite: trixie
emqx_repo_component: main

emqx_prerequisite_packages:
  - ca-certificates
  - curl
  - debian-archive-keyring
  - gnupg

emqx_service_enabled: true
emqx_service_state: started
