apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog-lb
  namespace: observability
spec:
  loadBalancerIP: ${ALLOY_SYSLOG_LB_IP}
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    - 192.168.0.0/16
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy-syslog
  ports:
    - name: syslog-tcp
      port: 514
      targetPort: 1514
      protocol: TCP
    - name: syslog-udp
      port: 514
      targetPort: 1514
      protocol: UDP
    - name: syslog-rfc5424-tcp
      port: 2514
      targetPort: 2514
      protocol: TCP
    - name: syslog-rfc5424-udp
      port: 2514
      targetPort: 2514
      protocol: UDP
