apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tidarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
  values:
    controllers:
      main:
        strategy: Recreate
        initContainers:
          prepare-custom-script:
            image:
              repository: docker.io/library/busybox
              tag: 1.36.1
            command:
              - sh
              - -c
              - cp /tmp/custom-script.sh /shared/custom-script.sh && chmod 755 /shared/custom-script.sh
        containers:
          main:
            image:
              # renovate: datasource=docker depName=cstaelen/tidarr registryUrl=https://docker.io
              repository: cstaelen/tidarr
              tag: 1.2.6
            env:
              TZ: Europe/Berlin
              PUID: "99"
              PGID: "100"
              ENABLE_BEETS: "true"
            ports:
              - name: http
                containerPort: 8484
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8484
    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: tidarr.lan.${CLUSTER_DOMAIN}
        hosts:
          - host: tidarr.lan.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        enabled: true
        type: configMap
        name: tidarr-config
        globalMounts:
          - path: /tidarr/docker/settings/config.toml
            subPath: config.toml
            readOnly: true
          - path: /shared/.tiddl/config.toml
            subPath: config.toml
            readOnly: true
          - path: /tidarr/docker/settings/beets-config.yml
            subPath: beets-config.yml
            readOnly: true
          - path: /shared/beets-config.yml
            subPath: beets-config.yml
            readOnly: true
          - path: /tmp/custom-script.sh
            subPath: custom-script.sh
            readOnly: true
      data:
        enabled: true
        type: custom
        volumeSpec:
          persistentVolumeClaim:
            claimName: tidarr
        globalMounts:
          - path: /shared
      media:
        type: nfs
        server: ${UNRAID_IP}
        path: /mnt/user/media
        globalMounts:
          - path: /music
            subPath: usenet/music
      nzb-downloads:
        type: nfs
        server: ${UNRAID_IP}
        path: /mnt/user/media/direct/tidarr
        globalMounts:
          - path: /shared/nzb_downloads
