apiVersion: v1
kind: Secret
metadata:
    name: netbird-operator-api-key
    namespace: netbird
type: Opaque
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:kIVcnmJ5sFpFpRB5u/N+WWOa0yWJIgj7o+g27Q7ccIPCbVCz5ZMuIQ==,iv:qjIeE5z2Q+zD+iLYwm1r2/iEqOo2FOsJB8e2LFEtq8s=,tag:VnmD3lZpCMfvp9C/jIp2Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjBqSHd1VUxOdC9IVDFv
            YkoxUWhIcDJ5YWZVVlFzNWRxVTAyRGRHT0ZJCjg3Zis2Y0hKc0JKY2xXV1RWTU9o
            S3dDWWtITmcyRkVGVytDUkQ4WUxZTjAKLS0tIGwwbjhGUGRvbEtBWXJ6TkJYczE4
            S2g5d2tFbGtGU2hJRVd6bmlZWW1ib3cKVoaz6YuYGDXdCJU33z8uL78+SXBAKl6Z
            VWPFVL2ZfrncR1qBico623dUJBbra2emuKSqf8dozy2KyWAoR/hm6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T22:50:34Z"
    mac: ENC[AES256_GCM,data:cRqLeEINuUav1rsV72/OmgS0Ff3iF+eeWj5ojUYenfF49ZKPNjiyLXSd5Cm3BWD2PBZzpnVoZ2ADyQf43CrzT1G2+5G59sJEqJDvcJVJmSpkwhg8zWEh/Hozk3ihuPRjsFxbx6+pQEDCpU2ui8RjX8vksld5snouctLtQ8NWhHw=,iv:qlNh5c8r8uy1hVgI2fHabRPJrlJN189MOHKIHRtA1C0=,tag:zEahecOmsCWLndmPGFCVgQ==,type:str]
    version: 3.13.2
