# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secrets
  namespace: utils
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: searxng-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SEARXNG_SECRET
      remoteRef:
        key: f7mvqrbzscnt2s7gzalzkpx7mi/SECRET
