apiVersion: v1
kind: Secret
metadata:
    name: searxng-secrets
    namespace: utils
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:anXMFNxvb7atyifO50YITFUSEFtgMLGYcqngxpnJ8MzW17Ux6x7o1A==,iv:Hyi+uEBrJ6mkn2nw1ZJxeDF+uVix9OO4M+VJeZs/OPA=,tag:Te1E8Uq8zsOhp5pMoUkl4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRWozUEgrdXBqd0Nhd0tI
            OHVMYXkzb1E3Lzc0M1RrU1NxSXZ2U0JiaTBVCm0wRGZpc2YvQlN1VnZTRisyeXE5
            U0JwMmNobExlRitSajBYeUY2Y09HejgKLS0tIGZIOTNSQ3lYUEVOazJVZlY2Wkpz
            ZW1EQjQzcjRRbnlkNWdEajRSOVJpa1kKMi6ImNbx4V5PpC0VcV7898Uv3k7QLExW
            Yz5LVkrpcselYK3rD+RFo/Q6DWPz0VrH4U9bA8HzqrpgFpooUzr5jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-22T22:47:30Z"
    mac: ENC[AES256_GCM,data:LAPRpzAs/RlKwXtbeQzg60+88Ej5tDVohJqWkwMKf3fnedbDH+RumT2bXPTGD73WXb06MumzbIphLQzjAeW+SD4LTwRNNuteCSGsh2jenkL9h/nguc/XZ3RH5HOhPzeg7vQJjjs/d5dMFWOYE9O/6/MXr+i4cbfByZdEHlZlbf0=,iv:YjUT7/7jYxwPXVGUTgh/Q6/lN9U+Z1PiOe4m51aYpdk=,tag:/uxL5BKGNVY8lzU9GNg2BA==,type:str]
    version: 3.12.1
