apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XV5PdxovrtSujg52hUPk+NhSEdloZ3nrZv0=,iv:/km7UlAXWVPWrPVlzIbQ7ORB3gGj43gpbK62BUOMr+Y=,tag:2BXVZzgeszmFkPOHS3ls6Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xqBG5RtwS5zfcbkjvVARHecAyJ7DjfE3JMrzRR4VLMws1KoLoQvrI7zoWUix/fyAa9FlqcVXAdwPgqHz9UuaTg==,iv:MxKepfHDh78EBTXosZmuAA1pQLPsM/VVV3cCdQWqcqU=,tag:QgQrbtsNjnJneHd+oMgqzA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:HsoYgwHikueSE/HLu8z7sIBqXJ3NkLUXjZ8FTsEyg5Na7U0G,iv:dQalO59Egfa7nrvnytAfMNI1TEVF5kbQ1BEZJ1V6L3c=,tag:eIwoXyVta4KwjBqitzVEgw==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:6NG0JBg=,iv:kC+XmO4nthsql5vYmX8SHq1v9nS1kUxKbO2I8/yxFAU=,tag:5Va4nrhqbQt9O3YKEELy0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdU1HZkEvd3VRQlJZQUZz
            alNCWjVBVjVPaHdJVCtzTkcwaGNaN0VIUlZBCngzQmY4T3QzMWU2Qi9VY2JvYXIx
            cEpnNmpnNmtvalpzWDczMEFYcWlUL2cKLS0tIGFla1pyQk1YdzBMZ0J5aFRKRVYr
            eVZkcGs1NkYzaCs2OVAycGdYSEgwdjgKHVdSXYH36IhYMg7ohzbHaLdZPNB/SUbC
            tJfkNB6wWTx/TDWKxeTQnY4tYMn/ElhKZxNi9JgZf5uvPvWjCd7uPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-23T22:15:38Z"
    mac: ENC[AES256_GCM,data:n6r+6bH5qW/9lKXEUjrP41gsnpT0opCf0Db+11zo4ouwDGCn/YAPPA3zg04Rlsa8rihyOzOgbYhoSQqzvkpEDPocsVYkxkigZbXZDedADpfxAtCYo7d7ME+W+6IhpbMYNwhPoUbrM5BdtjlF48BfPMJiMUJFcBryry5YEfUVLGU=,iv:8IGK6XwOclBJuBcRBCwmNvItIEVPgUbqAtqM4EnjXis=,tag:qHOIVpbU/D8YoNJt401yPw==,type:str]
    version: 3.11.0
