apiVersion: v1
kind: Secret
metadata:
    name: opnsense-exporter-secret
    namespace: external-observability
type: Opaque
stringData:
    OPNSENSE_EXPORTER_OPS_API_KEY: ENC[AES256_GCM,data:0cC3yrJLmV/LMQH6KVbyqqidbB/+5DEt8srs1zi15pKfIMf3kGNTsykzK7sCwwHevJoexAnJqI68gr+bYW0idLAgDvnbBssKXbRfeVsCKfM=,iv:1gaymfIJuYSTJHsEAnZrkTcQ5J566ooO7mzQMH2hpFc=,tag:1OCttpZl+Wq7qr/WCYmgVg==,type:str]
    OPNSENSE_EXPORTER_OPS_API_SECRET: ENC[AES256_GCM,data:y/meIIdPUpxcV0K/OsJ2iziMfMbVVcdgfU5eDi26zT28X+0EqcOgn14oXrPBN+1U1ZvixzoVyB5F5wjnm8ua8Do2IOML6OzhP5jyknI5zcQ=,iv:+y0Ha6D1smYVZYVmUCKbsZ2xWHU4ZnbU2Iv3gGT1xFs=,tag:MrYBNNIQrSuTuX+Rhm6Sdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOWk1V2krWjQ2VVpCTDFX
            dVdEVE9VdE9NS0MwUmZibUlDRVh3MlBod0VvCmJWaEx5eTc3RU02VTlKM1paNUZW
            azJiSW5ON2xyVVY1TnJZcDBQa29DSjgKLS0tIGV6Y1hVSUxXdEZqWUNUb1BTYUZM
            MHczSjkzNW5xbnoxckFFbUprVk5vZEkKYl6yFb8S3C1qRtEJsgjJDQmk7fv0uN80
            raHzUA50dSBj7vaCRJ9PPPJe3iCTpibLHZEZ5HHqlZUPj6bx5hXQxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-05T01:16:47Z"
    mac: ENC[AES256_GCM,data:D8JtKbvba4ar9YpJWjReKN3ykS6xcaWnpL6nthG2XH1BBPH5eU2Y+K0m2VFlE+hnZ5Z4h36BG7Tl1mRslW+nGKYsAm6gKslL7ge/TcRAaLcxbvXa7AG+YgHPGuRCv2+OuQoN7cwnvyUEZ7PujvDZCeNfsOGPhuDt75ZJ6fWOisU=,iv:obIxO+GVmKiPJ+UZmMmo0544j21TpDu+/x6lt5z9a+4=,tag:h5/hdx/GFFrXEJOJkcq4FQ==,type:str]
    version: 3.12.2
