apiVersion: v1
kind: Secret
metadata:
    name: opnsense-exporter-secret
    namespace: external-observability
type: Opaque
stringData:
    OPNSENSE_EXPORTER_OPS_API_KEY: ENC[AES256_GCM,data:0cC3yrJLmV/LMQH6KVbyqqidbB/+5DEt8srs1zi15pKfIMf3kGNTsykzK7sCwwHevJoexAnJqI68gr+bYW0idLAgDvnbBssKXbRfeVsCKfM=,iv:1gaymfIJuYSTJHsEAnZrkTcQ5J566ooO7mzQMH2hpFc=,tag:1OCttpZl+Wq7qr/WCYmgVg==,type:str]
    OPNSENSE_EXPORTER_OPS_API_SECRET: ENC[AES256_GCM,data:y/meIIdPUpxcV0K/OsJ2iziMfMbVVcdgfU5eDi26zT28X+0EqcOgn14oXrPBN+1U1ZvixzoVyB5F5wjnm8ua8Do2IOML6OzhP5jyknI5zcQ=,iv:+y0Ha6D1smYVZYVmUCKbsZ2xWHU4ZnbU2Iv3gGT1xFs=,tag:MrYBNNIQrSuTuX+Rhm6Sdw==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eTQxZ1NjUDlFSU1ubTlS
            YVhoK0pHQnduYklQaVZTRjczMWFkR2lOVGgwCkJhOCtteW9jWW4veE5GK0Via2FU
            RVcxK2tkTExkY1BNalRQYXZOdXRCV1UKLS0tIGZzZTJlaFVXb25uTzBGK2FzUEwr
            NWlpaHdZaElITER6Q05HVGZPejZzem8K1H/dD4nDfGNfd7vzRv+DWwzVvIvy1KAZ
            2IP/5+dcntx+03lIw/4Vsx9KNuTB4Gi7JC9c26P++tjfS97z/3joPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T01:16:47Z"
    mac: ENC[AES256_GCM,data:D8JtKbvba4ar9YpJWjReKN3ykS6xcaWnpL6nthG2XH1BBPH5eU2Y+K0m2VFlE+hnZ5Z4h36BG7Tl1mRslW+nGKYsAm6gKslL7ge/TcRAaLcxbvXa7AG+YgHPGuRCv2+OuQoN7cwnvyUEZ7PujvDZCeNfsOGPhuDt75ZJ6fWOisU=,iv:obIxO+GVmKiPJ+UZmMmo0544j21TpDu+/x6lt5z9a+4=,tag:h5/hdx/GFFrXEJOJkcq4FQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
