apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: opnsense-builtin-metrics
  namespace: external-observability
  labels:
    release: observability-kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: opnsense-builtin-metrics
      targets:
        - 192.168.10.1:9100
