apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:BUvobpxoaWwILBq9h8iapnwyu/cviKZiNau0kKTtzhnLG8FTAvtdtEq+7hV/9PXRBBIseKuQ7SpDvSW1Zfhhdy1d3FPzo1GjkL67qQBi2uYSZvyfiZdDb/LDwpr7RAOyVEmsOcw8CYVKZiXQlcDiZQ+QAZZCbUENtrgFn6Nrs3jmar/zffuihQ+fNM3UzoJvJOGye8KLG3tnGrPk3aWOhKfzo3u9C7SZPt+uQEeKPyVfaQliS3dwWGi/QhySDcBbhula+kMMU8EHkBfNfM+laAm6uax9f/MHqcr+eZy++4XuLiDxeXeL5NwAtZyRGW+NIIQRTKS7wyw=,iv:dX1PNCyGH8iapd5FLvgRe2/boKJOTb7qkoLyLp8qem0=,tag:PreHrVq0hjB2DMtP1fVW0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWTZwT3JKODRHaUYzTFVs
            cDJoL3FWVXVRSm81R2Jybk9MUmRYSEx3b1VZCll5bHFEWkRaUDNlbkxIZVJyTU9L
            N2hwdkNCbG0zSW1SZk9RWWViT0FRQmcKLS0tIGNqMVVrVzhXd211YTBuNG16YWl0
            OGhqK0lmK1hWalZTa3l4RjdDcHZzZWsKR3j4gglsdo64oR6oGgomsWRWmFFw7wOj
            Zud6VgCdLiYL6rE0ORkeiKJuScl852YGDXg8wOb9kCrENZjmvLCVAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T22:12:40Z"
    mac: ENC[AES256_GCM,data:c6IQS8wxheN2BRYj0PLSxjNyCYVzpNsMrlTvAhd2OSRf7BbwKFyuggrVXiGO2McQL0QRK9XwdjxG9YUEpie1a/1qQxTnw0WrY4c7edjMJqcGf895nSHpM8F1xxkW2bBbamItTQblIcUvYLH+7qljRQwHxbGsFMRFLUNCAAR4IVY=,iv:otOYyxWG9qz3DpEJoMBBAfrjnPaUVHX95Dkweyxa3Mo=,tag:dkHay9sXYp+nNNvqWF8cQw==,type:str]
    version: 3.13.3
