apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:gYPjcPLfNCUrerqcqaqgAKq/8JVTntEelQVJy+BrQIYIsPowgX5lpo5pZmRwye/xFIebnHx1Lt1b9oMwWcmQbH8yjWMENulJjcKuYChvym1qsOmSn3tR04uQJsJUzlsRzx/82aPPvh6svNJ+E0q6awCN2ggFagv98vBDNc6KgIdU1g3dDRQiZbH1FDNQCTlQFEA/UkLhHLPfhts8vGVbx3aerTbrgQqNPixGOLoUkLCmHDThWXP0vA==,iv:NYp4XkEEk2IfJEpWRRX6bfWA7Zcw3BuKeP/iSJNbp4c=,tag:DdsoP+k7N1C9YsDaKCupPg==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaFdnZzVMK0dFd1ZhT3hh
            RFB4M3VKbTFEZnJBWWkxTmVzdUFDVXRoT3lrCkxiTWFvMlJkMXg1OWg3MSt3Z3V3
            Ukhpd1ZvaSt4RldnMzRjZzFNODAzdGcKLS0tIDBYd21SUnIvTUMxQUZ4RW0waUln
            aWEvNVZUanBNMkpQV2UwalhHby9MWFEKyk0xVlo5FQ46w5ltkzUZhP5zlab+x7Bf
            XrzxC7x9sOW4DGhsbX/uM1fpVVqQAR3N2CWuAXljPtg456v8rWIZTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T03:59:07Z"
    mac: ENC[AES256_GCM,data:Talxzh3uHeKTa/NGs0KELGGSLHjFbs3NyyQB86/kl/orQezZybqarl1ryc0mq7TZf9bVRhtOtGBlNRBsd/wSXaCaBzVijKk03SIdVMzSCk33tmLJsrVyAXIfj3lLLzantN5MSKgV3igNvgTezumBY3kOuxuLqb9sNmdaa2f4Pog=,iv:uQD6wuc/VFx3bCQhIIpYrkk4jss7GIFt5+qON6yfxO0=,tag:vYJWph29Ej30R8YXJt1BbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
