apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:gYPjcPLfNCUrerqcqaqgAKq/8JVTntEelQVJy+BrQIYIsPowgX5lpo5pZmRwye/xFIebnHx1Lt1b9oMwWcmQbH8yjWMENulJjcKuYChvym1qsOmSn3tR04uQJsJUzlsRzx/82aPPvh6svNJ+E0q6awCN2ggFagv98vBDNc6KgIdU1g3dDRQiZbH1FDNQCTlQFEA/UkLhHLPfhts8vGVbx3aerTbrgQqNPixGOLoUkLCmHDThWXP0vA==,iv:NYp4XkEEk2IfJEpWRRX6bfWA7Zcw3BuKeP/iSJNbp4c=,tag:DdsoP+k7N1C9YsDaKCupPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWTZwT3JKODRHaUYzTFVs
            cDJoL3FWVXVRSm81R2Jybk9MUmRYSEx3b1VZCll5bHFEWkRaUDNlbkxIZVJyTU9L
            N2hwdkNCbG0zSW1SZk9RWWViT0FRQmcKLS0tIGNqMVVrVzhXd211YTBuNG16YWl0
            OGhqK0lmK1hWalZTa3l4RjdDcHZzZWsKR3j4gglsdo64oR6oGgomsWRWmFFw7wOj
            Zud6VgCdLiYL6rE0ORkeiKJuScl852YGDXg8wOb9kCrENZjmvLCVAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-03-08T03:59:07Z"
    mac: ENC[AES256_GCM,data:Talxzh3uHeKTa/NGs0KELGGSLHjFbs3NyyQB86/kl/orQezZybqarl1ryc0mq7TZf9bVRhtOtGBlNRBsd/wSXaCaBzVijKk03SIdVMzSCk33tmLJsrVyAXIfj3lLLzantN5MSKgV3igNvgTezumBY3kOuxuLqb9sNmdaa2f4Pog=,iv:uQD6wuc/VFx3bCQhIIpYrkk4jss7GIFt5+qON6yfxO0=,tag:vYJWph29Ej30R8YXJt1BbQ==,type:str]
    version: 3.12.1
