# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watchstate-secrets
  namespace: media
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: watchstate-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WS_SYSTEM_USER
      remoteRef:
        key: vzzm7blvx4lwj3mqgzptnmnsy4/WS_SYSTEM_USER
    - secretKey: WS_SYSTEM_PASSWORD
      remoteRef:
        key: vzzm7blvx4lwj3mqgzptnmnsy4/WS_SYSTEM_PASSWORD
    - secretKey: WS_SYSTEM_SECRET
      remoteRef:
        key: vzzm7blvx4lwj3mqgzptnmnsy4/WS_SYSTEM_SECRET
    - secretKey: WS_API_KEY
      remoteRef:
        key: vzzm7blvx4lwj3mqgzptnmnsy4/WS_API_KEY
