apiVersion: v1
kind: Secret
metadata:
    name: watchstate-secrets
    namespace: media
type: Opaque
stringData:
    WS_SYSTEM_USER: ENC[AES256_GCM,data:sxpAX9I=,iv:nwX60O/l3bHbKgShFsY44UvkeSK6S2v3Dt3E8rHXtt4=,tag:dRA+eNKK3U5muQ6JdZKuqA==,type:str]
    WS_SYSTEM_PASSWORD: ENC[AES256_GCM,data:wI0ZDJfG9/52ZvZEmtB+K1nlASFqYwXaCsRAAVLojXCzVKcau5/SAA9DU5vkQzWk+McPlJajpJLxkO/pbPV2jsnPI/RY,iv:0QByq2BgX7jTz6j+8uhmNmpt1QhPjdw1KUquPFvTDl4=,tag:2knB/jWJANcm2BHNMgwRiQ==,type:str]
    WS_SYSTEM_SECRET: ENC[AES256_GCM,data:Q4ZNN6cHb+C69xbtM9TK5qL6d725F6gy33nwH3BFoA73kpbJz5mMUoLLMkIjY2D0Z8BNDsEKcHvQ6YKijRHYF+7X20gAW582bv6KuC43Jogxxsqewg3wRLnpV0Ou+YDN,iv:y34iyR/57qCEgBg84RTNx/Vk4oASFfKOPCIUtR1L2UY=,tag:ir6s01xDuXg5nHj8nceQ5g==,type:str]
    WS_API_KEY: ENC[AES256_GCM,data:kaUUQqWu1QcANvqhiuiqEJK3O0qeVdOnMnwyGaIqtLZPA0wjwjfe62chwmubk0b4tvUa4o+NOp7yLFcHmMHMjw==,iv:/bxYQ4SwCSKFFnR+T4dRx4VR3xme0EPmLMASAcd5gLQ=,tag:T414zdTc+cdOXgEn9rkGRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNUxkVmJnRTdKQXVRTlhq
            TlNtUStwVXF6NjdEYWMzUkMzUEZiOVBOb1dRCmxvdUs4Tk8rZFVNR3FXTUo4ZFM1
            QXhzbks0N1NtcjFxY2hqT2wxRC9pU0UKLS0tIFB1Um1nL2pTeHpZTWZpQ3RZbmVo
            UTYyemxKUkxtTlRCT0JPNzBoVDRjQzAKHSbFtoZd707WDe7rwUoWzu6fKyO07Xtg
            Gg2gWyOeNP7GzmuYdEkNDnT26yxGVqcf2SUcfVB56Mo6qh9uNfK3AA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T18:42:06Z"
    mac: ENC[AES256_GCM,data:U6Zj3NNybZQQMu7v8Lai7qHyz4ndN5aE9LYjYUhYpavCohOLy+6toC8jrNDgEJg6GOQK0OGkYAAEUWwq3LKmY1y/G/q4WYVyM7UTL+wpwLc1zCXMW3ylp2d8bajl4tF7355qJsb80KDs6o+kuGk9iCv2uo8JnQlzb/aA/FrlMSk=,iv:6/ubsHmI0uRpae58WuevMJPu47XoWiVParipnyMRGFU=,tag:lfw6mcB/uekNocaTzayTxw==,type:str]
    version: 3.13.2
