apiVersion: v1
kind: Secret
metadata:
    name: plextraktsync-servers
    namespace: media
type: Opaque
stringData:
    servers.yml: ENC[AES256_GCM,data:0Bb7FgeWMZNKcGMcHw4NTmfO07uRSkTNAa0dbpVIOo2w8KTOdd9RSvIIUVWF4kRJzzasRVWKxnI+55mslUHbqRM5bJyKFBYy2gvZxzY1CkMlwZy72hyjBgqKuRFo56jBhU3CrTtICOTrqOqaZt52+5M03PeOLDhNbhdCmugqVTLjrM3QWh2yARk97XeESXc0hPNWNb2AceWC00gpLb02dbXlhDANCWWQOCkixJOLzvVkoEsjT2Qb7b6YSwIWuUYGxNFFM0OJJDyj0HpOyVuvl2mfzJovqo/H+7AmONARHLpEUz3SxQqz5E9n9C9QOgFplUg5Ro3MW1P5Q0uaRqGCNK/n0QJrmxVXMuVyxZM+TFYGbpj7SAQfGIRKr3H03lgwrHasRWKmxlFmPHqWJermSTyjtzmGqmjKec1kbmuMrnqrrxwUxRKfr5T2+pZxC5aM/t9fIMk7HRh0nCWVovq+4B3ItE2jwRvNdI1VmtQsF026szFAfmfK5GzVxVxSWQ+7cypoBcFFmJ487bKf8RSr4a7yMFumlZ4edhiS5Io/iUfceIlMs3sFW9rrnW30BoCFewv8Fr9Bs4ycwLCbRbqg+YQJmhQ6zna1DUdhXeJ8C6IbXGLBKBrljd7xgfYvx3PaVQHLzKzH2hdQGN0Xg7F2TFqsLxQLvx9xL0pTei/TCjeuCEgOUZFgZ/tg7w+leOsP8xA4HR3xSQVxQW8lz0a/bgab8gk89vUTLh1rOtUYYAM5E9C4v/Zcg/1giJWaSb5Qkjf46QSFsoMegvII3zHeQhGsczLBvZEkraqSHuWGuSMg9IqNThSD1WpF1NMnG8C1UL4BJ6aVzefhIeuY99mSAmKJ3A4TSZ6u54/bK5QEqFjpggpW4wKnkgzvcxzN5x+NW55AjdU5ZzBO5OzBZCnFvFSY1CJCrvnoCPjsjtDnve+Vn0wfC+lsH0hqhPct5sIT/wiBYemwq5AV5FqcojtDXUywRLKUCRmGFio3dCrLYvhyUJOahLy1MQ9G23LJxJYmWxm5KBGzWybQr2pB81oRfk+q8bSO,iv:SM/kzQCE018XRDu0as7SjEkzQOGvolQKYbmfr0HdsOI=,tag:A21dGPRGKzbRRE8Q5+zW1w==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaVJMNUZUSVAyaXVZZE1B
            MmdXUW1YRjR2czNsSTUwdUZ3MmRBSGtVRXdjCjg4aWNhYkRra3BvTTFESWtkQ0U5
            TE5hN3A2cWEwZkpOL1ppQi9KVGxoT0UKLS0tIDJGaGtwUHUyNThBTEJKTWROSGJB
            WmhMbllFWU1PZkVoNmtSeUFTWW4rdEkKA6swzuYueDTVaSlanRMHnoSKBJ+j+LlJ
            SESGogkN6KrS9KjQCvjDcW6WVNvTrqVxmPvh1DfgrYO5rI1hQU43XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T14:31:54Z"
    mac: ENC[AES256_GCM,data:dNtZjO3buH0PlFJ/nkyuR4LO2k4ufTX4Ez5ti6wth/5Kgz3aaxZj2V/kVI0GpXvKvx9pQE7a4WUUrYb7iWPcRyJ6G9dDydBHn55eH3MwK11PmvXbMhYjbvE3s5BkVApDTfo5Y6WovF6GTkB4nd0eGRNEka6E9ve7LNretL0FfZU=,iv:ku2cquHVWbMt6bWhFNzhiGYUbv9BFexut/85rLhDbrA=,tag:CXE0AuHptYTECAG24N7mZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
