apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
    namespace: cnpg-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: authentik,security,automation,immich,paperless,nextcloud,ai,media,utils
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:+h4VmIAIl9LBtEC5QDPmIVhj3M9xXCfudmQ=,iv:BWQxrKtKy1KWmv4XpdOPnhdYlpykZQAXaPURg2MpqSo=,tag:qJztYNSaQ0XsM7eeSyB2lQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:st+aqJ8gQ4AAybtfPf+3PVzpDhLTG6cRU6D4LVH78BbUSoFaQkx006xIfMImlTlydWBkX4HsBXrgQei1w1/i9A==,iv:GYesTSMSvmGi2R0o5+5Y/sSpxnQKRpwssze0XsMFGIQ=,tag:z8sVjlOnofmi0ZOmyHaZ9w==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:CZuaDp/R,iv:Gij05qNc0VedMHwgHnT42tO4yuq1a3UwcAuaiV4FrGQ=,tag:0vFhbbHrZ4mu4VcUGzsdpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV1ZlOEd4cm91eVZJZURI
            cGtxa3l0bVU4VnlZZ0xjV3BsWlhGVGJBNUVJClJwRjhIUkZlcGhsa0ZOWDZnZFNV
            TlVGVjNudG1TWHdic1pkRjdWNEdHeU0KLS0tIEZUcWpkbENUUEJIYjZTeXhkUThl
            V2hudElzeDNyVFFuQnR6QThSWEFlZ1kK19LsT07dK4ycJ4+8lH5mKz/COTODwPUY
            3zQ/DbXZHo3dyFp0UbG7N0hS8ZU4UHH87+0ZIeIE92ZHZt4/mo8a6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T20:55:46Z"
    mac: ENC[AES256_GCM,data:oJTz0N6aHRxi3HVjC0WmW+zeXSBxOpOOdUukVi3Qbp3B1WxMHOJkoMrCTLyhvCW1jPi4Lz5+8J6WBj76rOxnnL2w2MVHT5PxM2V6LFo2qdhSL8BoYfPy5wmZdfttPDsbh/flnzgvKZAsoYhd4PHpN9t5ks365MyEP6JZ9305P1g=,iv:pO7vDOW6n5xvPBwPIjqQn04JoLJrq5Zg9lNMePXI7AQ=,tag:8kUotttw9LMrwzY8nj1CMw==,type:str]
    version: 3.13.3
