apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
    namespace: cnpg-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: authentik,security,automation,immich,paperless,nextcloud,ai
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:06b8YomIByy36xm57/FQNwpaG9s+JQnK350=,iv:FSznzdC8KItFVWlWMNifn49ucK594y0f7ZGoYBlXrVU=,tag:469qtNa4tru+BynIgjwJxQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:hIPGENvjuKEv1Z22DwJFO2GywPs4vUvLzV9m2Ie/py+uDYDjgPVqojWYQ1PU4S/YNaZc9EccWnIFLIg8yThStw==,iv:VYInYa7UUdztpJrX+6rsei3pe77W9OD9ZjCM+FE6oRQ=,tag:Ce2n3GQrPPCSyttXzyhWJg==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:QJ7r376m,iv:utOKwfpSSD2MantA6Io/8VtCsCeJk5KHYr3d9VpfW90=,tag:/8hgLEVBzmNYhNR61ZX86g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYW1va01XOGhxNk1jQ0s5
            WktMYStiMXFobHNuR1YwNXg4OXQ5UDVXckRFCmpYVVRzYTdHWlprcmRsTTNjd0J5
            elZtOWlEU3U2Y2dYMG1ZU0svSm5mNVkKLS0tIE15VGliWnlhaTd2N200T09mYnhC
            Q1pwNDAyYXpTREd5MlI2QS9hN3R2akUK9OUPNQx2a8WjLUB6u7k+QNaU87FXaMZw
            nevZrEPZ1C3MxHcy+f9kq3iLzVxooqeXP1amBa+vg+xf/WnVU/RCHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T21:25:23Z"
    mac: ENC[AES256_GCM,data:WYVjtkEff+r99eNTeRpXIatg8EMiYrkL4Fjh2Hu43g3lryE3kzyNK4nJ/gFIHCWggEDYcBdPQ1rK/AMAT3XlRriPepQcfuz7/vmFd2OM/FQHeyYfwHzo6LVVHh5V5WDCBBJiiYF/vUAc23fwmVOVREUZO5EvMOy8CEuB9t4vUsQ=,iv:rjHHlMZGk9z62WqwPmMgM3x9lHq27IlLIPwDDcrr9jQ=,tag:oJTH9WelNoBwy1WDX3f+nw==,type:str]
    version: 3.11.0
