apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: ai
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:qr3tyTMZysTH3LbBdcJ5ae6FUMxCKYrw2WSJLMD0ZsUrF8uDwuJmZpSNCRg0BEjkDZHKVZ1IvIdZHH4drfbdXN+/eQ==,iv:dab/Uftd0nI7lzpH0s1xoTxHCdBoc98yA3Xxcqg4XGo=,tag:ikciD5NP067g04MdRaKc6w==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:Ngd3z1Rum8bNmraN6xnjLtyCkYoSejsWWnxTC2UY6XfRn1P2XUckKdEvi4v9+8rIKozowUXdpGbzHNZgEl3t6w3niw==,iv:AJebeFsHPxSpEuFudpiLkNoQwwgB1vZ6dQUbV1U0xro=,tag:swg+VOobH+zADVyVFVTZcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZm1UaXg2Y0Y4Ums4enFZ
            RndSTnZnZEt6WCtLbi9LOE10WW9Cak9TTUVVCjZCRnFJdW8xN1oxZHJNQnhLNkFm
            c242b1k1RloraWVPb1BESkRlN1ZKTDgKLS0tIG9WcE5qY3B2dnVHTnZNdjNtSHlV
            UERvWUxnaHJkVFVIK3BxM2p5bS80K1UKQ7b+7XfOPIED6oiqFlRZbHffCztAnYL9
            IrK9oln7wK9uuxr/NWkqfPZf9iTDH7uye/+GPBmmpMFLb1EDcPd+UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T20:58:02Z"
    mac: ENC[AES256_GCM,data:vSOCooItG3Ob7hHlsCsEediL6n/iVrwRYl8UCvqJmlVlTl+KOR3PLqthbPIqprNv1BC2Yb1mENU/AMlvufnfeM3Vn9TxVWu0n5eY3KckB1b95jmJE+2tOi0QjFbdUcx4J0n8ya4irgvn3tNeWTYf3sW7xJG6D6JqX5ORaCmwYhI=,iv:TcX9Y35HG14KqJppGPRoeujZW29k8YjnvYUZXmP4Dqw=,tag:fRnljZyNL8jT0ImVseQN/w==,type:str]
    version: 3.13.1
