apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: ai
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:qr3tyTMZysTH3LbBdcJ5ae6FUMxCKYrw2WSJLMD0ZsUrF8uDwuJmZpSNCRg0BEjkDZHKVZ1IvIdZHH4drfbdXN+/eQ==,iv:dab/Uftd0nI7lzpH0s1xoTxHCdBoc98yA3Xxcqg4XGo=,tag:ikciD5NP067g04MdRaKc6w==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:Ngd3z1Rum8bNmraN6xnjLtyCkYoSejsWWnxTC2UY6XfRn1P2XUckKdEvi4v9+8rIKozowUXdpGbzHNZgEl3t6w3niw==,iv:AJebeFsHPxSpEuFudpiLkNoQwwgB1vZ6dQUbV1U0xro=,tag:swg+VOobH+zADVyVFVTZcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MUNQcFFLcU9xNVN6RTZa
            bFFhb0s4bldQVHRoMGp2bkQyTmtSM2syNWdVCmRMYzVObk85T3RTR2ozOWgweWN6
            cGxoQ0RmeEk1UVg1V1dsYzJnZ0tFcXMKLS0tIFNoTGVGTnJ5K0NySjhHOVMrNTJh
            ZHNOS29ZY3M5ZlVPL21sM25CL1lrMEkKGBcG03pPOCywpU0c/HfmwlJRcXQc0VJ3
            1IPDoHy9gF249DLoS6l5sZFR251S0PcN8evxTlycpukSokJEN/HymA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T20:58:02Z"
    mac: ENC[AES256_GCM,data:vSOCooItG3Ob7hHlsCsEediL6n/iVrwRYl8UCvqJmlVlTl+KOR3PLqthbPIqprNv1BC2Yb1mENU/AMlvufnfeM3Vn9TxVWu0n5eY3KckB1b95jmJE+2tOi0QjFbdUcx4J0n8ya4irgvn3tNeWTYf3sW7xJG6D6JqX5ORaCmwYhI=,iv:TcX9Y35HG14KqJppGPRoeujZW29k8YjnvYUZXmP4Dqw=,tag:fRnljZyNL8jT0ImVseQN/w==,type:str]
    version: 3.13.1
