apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-secrets
    namespace: ai
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ixp51ICibQ==,iv:ZZxib3Sh+SxDNZ5jtLQ/ccmlDOilpFiChpKdztKwlgg=,tag:+BsHH9/ZkQxuUxtUZmxZlw==,type:str]
    password: ENC[AES256_GCM,data:alIDhCWpCfkBL7ipWsDhR0tgOFqhPHuCSmzLKbkx6eL1aEq8eVm7h1/i/Yn9wrPPH7A9g5RP5UgU+4CPf00oMw==,iv:Tw2trzpj/sVRCKQV99z+5esmCIWwCHkKiGaG+bfP4ew=,tag:iYjdn4jE6+UBzmF0Wd4Uxg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:XFuNWNZsoyzmnPpcGcmw42LFnT6FpNsMzqIx6guGr9batoTseKpA9hmJ3zQDkduDwIjufjUSUxCV0FQjVPjugV+h/OPnlv/iUwnsRvttxvII6vVgP/Q24BEUNHGRxT0eSUGClm3R2VVzwm3E2cjPGQ==,iv:6CfpTybD8hXYzlURvMOh5W2P7P8T3PJ92aPJGVPHmDk=,tag:Oe0ig84iMux6nYpYUlz//A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bnA1eUJjRklJRVV2Uzd6
            b0lsNS9FVWJETmtmK0FPejlKWlFPVnRzTjNRCnh5TUNZRUNyNklRLzRrNEVPbm15
            bEl1MjlOa2p1RHlWV3gxdmVSQVpsY3MKLS0tIHNkZE5RK0JPckNvOG9ydkc2emRC
            LzBOcSttSVpzK1R6Z1I5RUlXUVRVYjgKLQ+HXHaGDpaeXg+B9Ut/wtLgSqZNoM3X
            /j4/9ywyZN6ynflZw31qNU5XHLe7IJ39YbCnNbcgI5eqEbmJdPT9nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T20:58:02Z"
    mac: ENC[AES256_GCM,data:voqoIiuyo4/Q7tRPyGX/r22GYKp9ZQzmZysQRE8P/TMRLO65pwQNwsEHe2phBuvuLdz08/A9X3PJqDyOEVnZMQRo55dRM7WM9CdTyZ3AGivAHUfTA+5g1GviXsjK1Ly4h6Bhn/QIA0H3Q7SSA8llg6JdW+trjYK/Z3+x9ZboYMw=,iv:LiNdY+YHtTcVAm3njNEd+OubmjwRGq9FDDRoW8fW2XU=,tag:7ToZdMTfg94w2GTtIW4BBQ==,type:str]
    version: 3.13.1
