apiVersion: v1
kind: Secret
metadata:
    name: litellm-credentials
    namespace: ai
type: Opaque
stringData:
    LITELLM_CREDENTIAL_LLAMA_SWAP_API_BASE: ENC[AES256_GCM,data:tfy5Hs6Yvf71r5JkNxRF46YeL8txVrlOc/IMUw==,iv:TTo8BkH0XNGWCWfbyjC1R9vX44Ot5jWjnpqO9VSvgUA=,tag:6T8xuwVAwqaQ36aeBoubcQ==,type:str]
    LITELLM_CREDENTIAL_LLAMA_SWAP_API_KEY: ENC[AES256_GCM,data:XLkZ0eA2ajnUhGNOE822FalxGSOfF0nKC2NG32nS1naEp60GjBiD6CuMa1Xc/5B1fkGPYe9WGXhV7hJ2XM4aNA==,iv:wSeQPMJafYE2OjTnve6qkGWDxKfoXuFij9jAbRPPDfw=,tag:JH/jQlUX1UsWMQh3iRXweA==,type:str]
    LITELLM_CREDENTIAL_OPENROUTER_API_KEY: ENC[AES256_GCM,data:kbDsQjWmtLRxwAevQ9py9HbqFFTW75zkHgD78HBi+QTiS1V3H3YwFGrfRC1O8yfX2wyZtbyE7FR1EzYsXbDRf0pveFnnAWw4jg==,iv:bj30Ci/4ImafVMXCNsmxIgbw+npOglBrR5CnUQMvz/c=,tag:aKotPHVufaml+HG7oeSMGA==,type:str]
    LITELLM_CREDENTIAL_ZAI_CODING_API_BASE: ENC[AES256_GCM,data:2cc5I04DRm230NWh2utUE8kT8rf0+VFRQNeTigw4bsc1Tm4=,iv:uJjIUbqXAk67hPeIoA4LD2ojsK+85T3ZugXpGCn2gKs=,tag:72E6uNkenWLfJwPKz5gHIw==,type:str]
    LITELLM_CREDENTIAL_ZAI_CODING_API_KEY: ENC[AES256_GCM,data:SObipN6WuY9Lulh0d85eFit48hsf57hjsb2p0uvX3PHAKXuIEqAj15EZmnoDWZe9lQ==,iv:XDYx0Ulepo7BoXsjSOBfcRnmW7Zjdr9UnMbU/NI8RbU=,tag:B3W7+0vVZ5txx6EkYkIuOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eExBOCtBNWR1ZlIyenpM
            ZmY4blFYblFna2NqSmtmL0RlMjlSNVpFKzFBCnJVV0F6OGh2dU5paVcyRDJhK1NI
            Z0dZOE40UnVWVklQSTJiRnpXTHNORjgKLS0tIGI4SXdpUDhuRWR3RFpxMGJHZHVI
            bnB3UlByanRsUlBxVkQ1aUxJMnBSSmMK7nKrlYfxaTmjyRmPhLXtQLe91YYbM6+O
            sTrR0bojoH1UrCuWTBbzqoO4fcjjg88PxG9nBl1B8P5BVeAi4BXu5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T20:03:46Z"
    mac: ENC[AES256_GCM,data:qGipGPYbbbLAlIh+9or4a37BCch17RBHPtygmWIBkRkkyRlfKcCd6Gxv1FY/n9LX5VBmxrZXta9wy5pBNNoLwtJc/BUQpktO72r6ZrzrDRjORnfFnBW3B0IONZWB3le3uo0NbokbouYN9c2T7IVoDFs4iWqgkjwlzRwr4n1CqAQ=,iv:EoVdARlxJrz4sg+eJCjWhwR45IgBgMhBWZ9PA+2NfqE=,tag:sN33OSk4OOhicIrNfbDs8g==,type:str]
    version: 3.13.1
