apiVersion: v1
kind: Secret
metadata:
    name: litellm-credentials
    namespace: ai
type: Opaque
stringData:
    LITELLM_CREDENTIAL_LLAMA_SWAP_API_BASE: ENC[AES256_GCM,data:VthU/z02FJjUUMWDo/sGZVf5SXkLM5k1wQKEKg==,iv:hiLzZ5K6LcYcH9QhmjCnhBVlRUZ0H4iX9KjzIUSHmoM=,tag:KnfYx+r8qm35vwGpei4W1A==,type:str]
    LITELLM_CREDENTIAL_LLAMA_SWAP_API_KEY: ENC[AES256_GCM,data:Xy0AqV9tcvE+i0Is8WY17slmGyXdtW01sPA+8Wwla5101CvD4QbAuLI7K4iwwTF0B6MiHicCaHksNFNbUr/T+Q==,iv:4FqSzejgw76OhJ5s8kXsUZnQwS1xCgDlgxp8ODaJV/Q=,tag:AVUo3vZXZY2gpqML91IxhQ==,type:str]
    LITELLM_CREDENTIAL_OPENROUTER_API_KEY: ENC[AES256_GCM,data:1w4scyFbApKpwOwmEenPOxWSvlxQe/CiJC6VYwkPlGZIK3ngOvpNbx/vmMyabavAlURhXrOAMIh/EjHvoZ3h44avS2TAFKeXkg==,iv:Ll9M2utNc6OdSdtjFvV/DJiZbIFDUDFXIR5VAex7afg=,tag:l310F3mBge6xQZBdIJvW3g==,type:str]
    LITELLM_CREDENTIAL_ZAI_API_KEY: ENC[AES256_GCM,data:YxHRFNd5TbNHAJlmWso1Cz9mEMJhXe4GsG8YJr+Dcqd8fWS/iYiV3M1u/rw8r7UsPg==,iv:8mnwqlig9OPWr+VviPkd/vbrRznToEn5Nagq2iPLZtc=,tag:2XsKfO1o/iIM6YsTzX6g/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR1h6aVNQcGtKNlFIc3pG
            K05hdThBV0dvQUhrY2Jwb1gwd0l5a0VoWndrClg5R2ptUkFMYkhTTGVZcFJFU1Qr
            V0dodnZ3ZkxsbDlBSkFwc2dVVUF3N1kKLS0tIHozdGZDUHJmcVdRZXJvM0tGNENI
            SmFDUHpoRzgvZWxQR3ZKZHNXWEczRVUKbqtw3ePnOvlX9+nDSrxlEQXjPBckhyPW
            Tmu1MMtvaXjtSh1riBA9Cc0YWWC5Oxm9Oywhvrzx43VmB6wnR3rpvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T22:57:15Z"
    mac: ENC[AES256_GCM,data:dB5BbCe/MrQEWiI9xUuaKUWzlRueWhdFcu2GXBTODcXccZa+otTG+dlhRAL9R8r2278GFU0osFXCsSbOK9caQBcVFYxnkuBot/LGjWT7E2o+kqWNlpa7a3I0Jw7t2nu9NAWi9pXkWP8w7jQwla05wkO0tC0rCKXpagLV1sRsTYU=,iv:pBMtzSTKYNG63QXL5VpPcU7dZUNLjYh1o+NnlAnvFaw=,tag:Jygg/OmCj0VIgtTwApjpPg==,type:str]
    version: 3.13.1
