apiVersion: v1
kind: Secret
metadata:
    name: litellm-credentials
    namespace: ai
type: Opaque
stringData:
    LITELLM_CREDENTIAL_LLAMA_SWAP_API_BASE: ENC[AES256_GCM,data:AWtd0LPlq5rfrLGcIMzvMMjyPZ20nxfXaOpkRw==,iv:iKaYuZ698WqbQ/TTtjxVy8ni5RqRA3Q1h+6saUcpwTc=,tag:fv5wqdUHkBa0t4+iagNp9A==,type:str]
    LITELLM_CREDENTIAL_LLAMA_SWAP_API_KEY: ENC[AES256_GCM,data:jjtyk3fcxXE5PovkCLh+ShGjw3XTOyAWI6VjCTWHnVbfzKdN5N4Lsg7sU0YmBzXonuwzf6xg30LETjgUmlLN7g==,iv:fQwpny3beNolx0gBa/FP20HszSGgacuPPdKwU7ov19g=,tag:D3k8GVnxYjINC4ZHYHcQiA==,type:str]
    LITELLM_CREDENTIAL_OPENROUTER_API_KEY: ENC[AES256_GCM,data:7sHOFt3T6ZotFDyTVvcpfWFGz0ISlXHOMUxWPqTq8qeRzi7yUdygqwlM/ZQ6cyyIL3xzzDI8O8Pcl3irbSvv8HACDcTSIyevZQ==,iv:W0YVgMz0ExiM3o4+zH8IhB5N2gX+ZM2B9/4EfbsgZtA=,tag:oMxKA+i1m0jqRFxkz101Tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNTBPbW51WGF0dURZNUF2
            SGwwM1A2UzJjTU95eUZtSUZFUlFvSC9jZEVVCkNQUW1xUTBvZk9KZ2Fxc0kzdnpo
            RGhwMldTbXg1eXJtSFErNCsxVkxJTDgKLS0tIDdUeDZINE9sTVd4UUtuSUVLcUdD
            WkZWb0JqVHk5ZGFMciszTHN2N2dvclUKrQ6qCE2NTER4y33wGQWLOv1pzNkAzP4R
            +nGaaJSZwUMdw728mPrba/rPO4ZAhMvryILJkAJz6InOUjWOD0CTAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T00:01:49Z"
    mac: ENC[AES256_GCM,data:DaTJ77K+KQaPnao3XvvJQ7eUuzpAhIHlnTbtHifVVMTnhDCXmXtdSOD6QMUNjSOXqhW6p3rcI1Rfbgf2bGqnQN98Slfzuo8SKWBucoT9gxu3pDX0ohowlEU0dceozQTnYLIdL4GJsk9piYlPtIlqydsR99peH6xtcSj20ergsng=,iv:BjsTzp2kIA3D0yeKo3GDoC1QsuVd6IC0RhM1YJ2fjds=,tag:b937NrCvcP33hVnhv4mscQ==,type:str]
    version: 3.13.1
