apiVersion: v1
kind: Secret
metadata:
    name: mailflow-db-secrets
    namespace: comms
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RH/82Z6Nq6M=,iv:jhf//MkFMsc5doF3ItzKR9+81VlEveqqk0kiz1wbeq0=,tag:j909+HnEaP/yVZArjZ7YCQ==,type:str]
    password: ENC[AES256_GCM,data:QChntOx1US5hVhGB6b2Mx9NhtDhWus/+66KtRruG0BnEGlU/h1n0TuqRNUAJ4x9A,iv:cOAucqEBgjB3i/cjJ2Byz6zNkmpTcMJhJAQba4sV+GU=,tag:XG3O0yANlUXdzoA2t1PWag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY1JKVUtJTWhiZzNXL25H
            ejRReTkxVVhCWENOdXM0OS9Jc2ZpRkh0cDBRCjUvN3k3ZkFLQWFQRnhET25TN1JZ
            QkVJS0ZydnIxamFCbldsY0xndWpGNnMKLS0tIGUvYmlDcndnQTZ2bVppM2NwdE1m
            MGlyQ3ZVVEpCUGh6MWxrbnpGLy9IaU0Ka2m+JIHdkFjWzPNXtzYSMXKGRwMqEO2V
            w5GhlHWx8IdwuE2u//8LsiLMzDaUwiURfWWhzFLCwdm8iF45BYyM1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T02:01:11Z"
    mac: ENC[AES256_GCM,data:XijYYWzj+bMO3iJ7QD3wM3kaOq02Ao7LuuJk+aMh6FNVSLgXM2CL+fw3mLIYOz78sjDgFACGYzhEtZlbBDidjdg/MvUlVAoo6KBCww4cfq0aiNXBMZjbVfXZgT+MHqywDz0zgbWJULc8TkHUuGApFYjoQRbJsML638NkePNly+k=,iv:jnH84+RTHe8mUIaS6RZHzgZR1iqPohPC+0QvUmaeztE=,tag:EjA/as3aG4oDTy5cxXWXXA==,type:str]
    version: 3.10.2
