apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:puTQ0/609XrYqJyM36NYLGBrX0wxiWEKK3l53acmUKk8uK88bNEs9uk=,iv:pTyFEbsgN2gG+vnQFmz8WU5tI+xjLRdZ0S10i/u8WhQ=,tag:TjkhzNcegjibxDjw70kRqw==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzVFaU8yYzVVYlZGVnc5
            aUg2ZU1LZ0ZrMDUwdTVva1d2Rk51QkU3cWpvCkFYVmdTK1lLaDl2MEFPQkZHb1p4
            YUNFSFdabEZCSWhJNjRnTW9wUXNEQmsKLS0tIDB4Y3RNenF1K2ZRSGc0ZUZxSm9B
            T0VMSU10d3BYd1p6Tm0zTGFNL1NKa2cKf9Zfq3mEkg04pqmsC+eoIu53EnnT8HBT
            ok70OucVWlinl9mTzQRv6OtDE84oDpi9AxPK1jWYbqR17dHJ+XvNdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T00:03:29Z"
    mac: ENC[AES256_GCM,data:AzLcbpPB5Eoh2vZW5lF+xYqaHWGJ8gN+AFw2o3cPMFD3SOpgkLLjRYCv/UyFb0Ons5PhO9tFuxI/9yFJHsZxvqyN2Tepa52EXgwDnixGwS8A60j2HzdG7FVufPftGDLdzmPeXmf8mUotjWrAj8g2Htcm7wJKF6/6BQirxKc1nXk=,iv:J43AKQ2bLr33UYusmYf1O3iXXm93su80bDMbJCugfPg=,tag:I+pfKhQMW2VXYv5KRjcpPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
