apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:puTQ0/609XrYqJyM36NYLGBrX0wxiWEKK3l53acmUKk8uK88bNEs9uk=,iv:pTyFEbsgN2gG+vnQFmz8WU5tI+xjLRdZ0S10i/u8WhQ=,tag:TjkhzNcegjibxDjw70kRqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaVBsa3RrYmQ3aStFY0ZI
            bjhGQi9pRmF2WWs2b2ZGTW5qWGZKNGtGT1VvClBKL3FNNFRtU2p2c2M3djI0VCtP
            Nyt5ZE11N3N5SHgra043aklLdC85SE0KLS0tIHlVVi9ZRjA2bW5HMVI1OU5XZURC
            amxNazNvaVEvRUYrMzF3MkhxbUNWZmMK00KB67dBtT+dVakP5Bdez/y6iCPeeFC+
            rjdhl+ycDNEqrKU7KvKjh64Y05+9T5DT+A+NEl8atX2UZzuTJvvHhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-08T00:03:29Z"
    mac: ENC[AES256_GCM,data:AzLcbpPB5Eoh2vZW5lF+xYqaHWGJ8gN+AFw2o3cPMFD3SOpgkLLjRYCv/UyFb0Ons5PhO9tFuxI/9yFJHsZxvqyN2Tepa52EXgwDnixGwS8A60j2HzdG7FVufPftGDLdzmPeXmf8mUotjWrAj8g2Htcm7wJKF6/6BQirxKc1nXk=,iv:J43AKQ2bLr33UYusmYf1O3iXXm93su80bDMbJCugfPg=,tag:I+pfKhQMW2VXYv5KRjcpPA==,type:str]
    version: 3.12.2
