apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:4zHWJztdF9Ed9j1p4UpinIpdBGlN1pUXJYK5VK857kgfU+Gd5s624k8=,iv:MDj0xtqo568IGEhYnpYSCo3sOYc0hhDgpzRjfukA6SI=,tag:mKFOrIFIXE4kQy2XG4DwxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaVBsa3RrYmQ3aStFY0ZI
            bjhGQi9pRmF2WWs2b2ZGTW5qWGZKNGtGT1VvClBKL3FNNFRtU2p2c2M3djI0VCtP
            Nyt5ZE11N3N5SHgra043aklLdC85SE0KLS0tIHlVVi9ZRjA2bW5HMVI1OU5XZURC
            amxNazNvaVEvRUYrMzF3MkhxbUNWZmMK00KB67dBtT+dVakP5Bdez/y6iCPeeFC+
            rjdhl+ycDNEqrKU7KvKjh64Y05+9T5DT+A+NEl8atX2UZzuTJvvHhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T01:33:01Z"
    mac: ENC[AES256_GCM,data:3d06/2YXE1z5CfjK0M6bSzg73NtYLKswQzBQPVf2zz43H7nxSgk710Uleunfql1/Oqaj+07+Oxwj95a8e52p4XDGd4RUlQCfdtE8QLUQrkrcZ3oJV0ocA0IQjBilefT7lnU4y1kh5kS/KaxdUeX1H9mibUfYAbybhocuApemoc4=,iv:MCLkwjWo1JHepk9T+uSdSK4EpdogkF7AtDG5P2rV7po=,tag:k6AXzRpwFhO72XE3kNei3Q==,type:str]
    version: 3.13.3
