apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: external-observability
spec:
  chart:
    spec:
      chart: app-template
  values:
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=docker depName=tzockt/speedtest-exporter registryUrl=https://ghcr.io
              repository: ghcr.io/tzockt/speedtest-exporter
              tag: 2.1.2
            env:
              SPEEDTEST_CACHE_DURATION: "3600"
              SPEEDTEST_TIMEOUT: "90"
            ports:
              - name: metrics
                containerPort: 9798
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 9798
                  initialDelaySeconds: 10
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 9798
                  initialDelaySeconds: 5
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 9798
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 12
            resources:
              requests:
                cpu: 250m
                memory: 64Mi
              limits:
                cpu: 1000m
                memory: 128Mi
    service:
      main:
        controller: main
        ports:
          metrics:
            port: 9798
