apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: external-observability
spec:
  chart:
    spec:
      chart: app-template
  values:
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=docker depName=heathcliff26/speedtest-exporter registryUrl=https://ghcr.io
              repository: ghcr.io/heathcliff26/speedtest-exporter
              tag: v1.6.2
            args:
              - -config
              - /config/config.yaml
            ports:
              - name: metrics
                containerPort: 8080
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 12
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
    persistence:
      config:
        enabled: true
        type: configMap
        name: speedtest-exporter-config
        globalMounts:
          - path: /config
            readOnly: true
    service:
      main:
        controller: main
        ports:
          metrics:
            port: 8080
