apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-exporter-config
  namespace: external-observability
data:
  config.yaml: |
    logLevel: info
    port: 8080
    instance: home-wan
    cache: 60m
    persistCache: false
