apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-db-secrets
    namespace: media
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6tO6k+keLNRk,iv:M80e9EiOQriHE4YHhaFuWAAMabiWwMJa0nnbLokA5Yk=,tag:qVyWSVxj2FmgEZqkogVeLQ==,type:str]
    password: ENC[AES256_GCM,data:34ka/iBL7t8o7dhaxo/nbY5eM1bF8Nw/XGsJd88NEV+t7+GdRFFn3akBAxrVSgvcgtpH2nHpXoH2aijNU9OLvw==,iv:hOtWxCN6gO9fmVX3N/GdHPq1Dd0xGeL5QPq5ZyZbncw=,tag:wEt9C5XWo7vnbwoE13ieOw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0jzVazG7pn3DT7C/F4NQytOMZg5NrNJbtso51ns32VYC9URuElgmMYHgeKtQDipkhBgeKnlitqz9q6gtxsIBWum7AajET2HdZjkCrzcbiRrj6WL9ZokWg0M7iwfUgPvFwZrt+ntfFX95eeMtI+MspEgSMypURRm7GepT3JhxfO5ObV6Aymar2Lck6uc=,iv:OU/EcOb5+VLlwfPb0s6/BJcGOlmRG2ruqDAASE0sslA=,tag:PUILCgtWGHDvXnRFerBgkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRGhsUDVPbFRjMkRPNk9Z
            SVVYVXVjTzJiQ2JsVHJGcVBJdzJ3cWwyVW1FClllTGYvV3lsb2wzZ0xNUm5rc0hx
            NzFoeWUrNDhJbkdmc3NoVFNxZzJMZUkKLS0tIEtrM3BWRVhCcjhOZEl2SWVlTGd1
            ampsVVJTWEVNb25OUlJuNmFqUGp5OWsKYLLYsB3JRp5jQgi8hP6A8AGrTW2ghJit
            N5uGRZHobQUzg+p12KupZt73ohVnCkLuxMWToVHavNHzBivAex8XNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:43:30Z"
    mac: ENC[AES256_GCM,data:SQYJEwwR9cnBhtixeY6Xm0aWTGLkAZ2cnzuIjgp7qu1DHgvesHD9/fgQtXhSRE5B/+UVjOq7HfZ4P2ODkYecQ0t0/UzflF2+cKPCnUXcgLts30I+B5WZw7jpQEivQ/A79XQGPVsBNnSHv7NPIzUZ+K4+fjO9SxSiaf2iTgZ/D6g=,iv:JTQpiAlg4F66dCNC5an8uaupjrqWmzJOLsCaI+4lHco=,tag:e5crRaXil8vwfGajX31Wow==,type:str]
    version: 3.13.3
