apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secrets
    namespace: media
type: Opaque
stringData:
    BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:aMgTHQUU+UPj,iv:I1YikQiPCPcaVeTdc4IQ7wQn+VqcTrE9jYoFw4O6AaM=,tag:JvD5hibgBffeTZFO+a6s7A==,type:str]
    BOOTSTRAP_NAME: ENC[AES256_GCM,data:wK0T1comCiu8QiFlZLVFLw==,iv:eoednZowwof0Ayr2HW0HsW4ny97yGPrG3HixE72M4BQ=,tag:0fo6SHzkvcpffnynP5lMgg==,type:str]
    BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:P+yYY3FE1Oi0UzbpuMZdMslsDDvU,iv:V3suw5qId3Acm/iTNtDQzKQJS3oij7/kBUsKuNzJpLY=,tag:NvXwNhEA52zVC0y8GoZwwg==,type:str]
    BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:dvKxaUVzLx3QQPq1u4hov1WsjGc83DV3WJkFUxLvyrBcgOyiMn2w+57aFiFBPZN/vtDe,iv:G53La2mOcT/99cSLHOlvrb0ZmSt0VAI+08OBldrx5Is=,tag:5IVSTdNpZiwTxA/Ez9EJSA==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:+EdrmoEpyocWZJpDS1AtIXp0e5C0dn9z5vdMVQcnQAXxOQ04Icut9sgmQhmMsL0eAYiUDjZcm+W5xuXxpOtQnA==,iv:Tg5xckIFwPwxmso8kAwb0z5PEel91/AHxPBBBLO52ZU=,tag:W6/IZHocPuBlUoIgWepIpw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:YfII3q3Gp9WRBGC28B0IxIp2y71uQE5bwlZPlL+fCVfIHuGne033YAetp3kIsyHbMOvHLAeZTh0oplt6MrclcQ==,iv:g00odP9AjI1HlZcbI397H0BS7BwhVlu5PgO9LpnGrr0=,tag:T8lPjEEnz/3Bac44Qry8Bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd09WY3RCaDA5SHZRYS9K
            bGRUQnpRSzVpRGlVMEhXWlZmeWhLcWFQQW1RCkNDSzMyS2JsMHN6dlViSnZJU3Ny
            Z1lXbCtvWC9XQUJ5RExqNHkvTWV6MU0KLS0tIEJneHdHVkhUSEpoZE5SN0ZKZmlH
            Wlk2bVI4UFl6Q1B4VnMzNGw4TmVqZFUKnxKAG/MgZiKkPETAqasTqCsANp4LZv8J
            R/UPCLB/70ITNCoD4MiISiW1cigkaFIAKqpnfKZhk2EsS+KWNOhGVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:43:30Z"
    mac: ENC[AES256_GCM,data:2L8lOgr/o7TGdS4GtGtXpLIJXDcXA8KTKi0SgIxoILipsw1F6kglkNUR0tP7GV+5sJQu5onP3jB8GVmTzNJg7VaHKkutICT4LjDpl5BEpINtc4kD2+FnLq+7dQjOeI8/NXOfRQrb7bUWWf9pSocwKkz2t63TkB2eDsycdHLjaUo=,iv:1qUdeIvJ/Al+NggrEkJvAnmIMld5/nRkYSCoMEw+Moc=,tag:wHfek2VfSrtZ47Dfp9+Ztg==,type:str]
    version: 3.13.3
