# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidatube-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: lidatube-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: lidarr_api_key
      remoteRef:
        key: v42ajh2hijezgp5ov4nwaw3gpu/API_KEY
