apiVersion: v1
kind: Secret
metadata:
    name: lidatube-secrets
    namespace: media
type: Opaque
stringData:
    lidarr_api_key: ENC[AES256_GCM,data:WDZX6W/utkruXq6VLencKuzzrGLzy680EauF9ASRCIA=,iv:/nSJTV22NrVAkRYIVTbbldAefZh2WAzjM/JaayYJ9Oc=,tag:f/7EK0cpbPkkwLE4VZEY3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMUUvaXlTNjVHVzVzMTNp
            c25HZVIwK2tuQVFleHJrcE5MdGlWUjRJTEU0CnRFTC9GNnN4RU9FamU2dmN5OUly
            ekVDdTRvT0RHR0pCZDVrNVlnY1NzaE0KLS0tIEZMcTl6b3FtUXJwUThFK1lMYkFY
            dHBHQU9ScU96V21RMDVERmhpdWRHQnMK1Cs1ayNmc+txgK2TAX0RJ15m+dZ9Enfy
            RbqhhlOF8yMWGj+ZWZWKjDa1OMwQgIOAq2x0EMP/Ywj02InfYMrVRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-11T23:59:06Z"
    mac: ENC[AES256_GCM,data:d6qokd2dNuu6ldwASVRRFb/HYUuG4CFw/yy8I5bQYTm3YuJHageJnN4h0z70M9V9rUt1ic4D/cRxl3BT4JNajlh47mqd1TGkmJK+28v70Cu1HwM5TtLb6qmGXy5yT1uvMuSby7TnwtZ+4pDdYmka5IowwaFxHjktzlwNWm6KUqA=,iv:Y9BGtZIngjXr4hsLGXYv9DhY5ijoc0vLFoG8zt9klMU=,tag:ad9gc5oN7miGc7Js1paj1g==,type:str]
    version: 3.11.0
