apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: security
type: Opaque
stringData:
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:z2MjVrUvu96pLqwjPRJFHtqAs78h++xObkA3uSK7fgM2W1ob7Xz2kRYuNa1ZQnnrWvEKlgJU,iv:KO/2kGZuTwb5vmEQxQ4Y/zZittd2Drft2ZZRUg8Jeyo=,tag:dr0M98IH1FL420bjY9QgGw==,type:str]
    FRIGATE_CAMERA_USERNAME: ENC[AES256_GCM,data:l7d+oeJz0w==,iv:R8SZSh/8SeNiNb5C0OLxt+uiSMUPZGgtnM11WamwcNk=,tag:8usjQwMiVa38lLEVpV4tLg==,type:str]
    FRIGATE_CAMERA_PASSWORD: ENC[AES256_GCM,data:QPHZHbFu04ErNbSR2KM=,iv:g/0sbpMG9oGFj6bY3GKp/spmMo4eI822g57CtQq4ucY=,tag:aG82E2b/wDdW/hdQmLXPeQ==,type:str]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:Gippn10leg==,iv:qz5NemPTfIFBgsQXX/ZIJGWSuo6psb5cXtd3rS9a+m4=,tag:4ykD4NrE8EgDsVY4XXiSeg==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:LwMVXV/NwkZlRBDlru8M0cXLBxkPq5DoBst71UgGQBuAAMfY20clBKyrQ4MTWceYREpI134=,iv:QBvoj3iXc2Lo03jZvkyIooO5Z/mcozGFdMGx9wMqD3g=,tag:5MWI/YV7XYZBtbuCPKnv8w==,type:str]
    FRIGATE_AUTH_SECRET: ENC[AES256_GCM,data:LDB1u7mXuUD0dY8jvmApdovLT9mlk686TwR6YV8hgslBoB8fVY02673RgNKgcnOaLXSl90Uh5ZC1A8eMb0cpC8HKjif/v+0z1Kmf/bx1kz5W0iSvpuV5CzI4MUlDxSQ97J+vStJKRgbfautnXDTz3zRU5kdepEcNf26EcjaUxYw=,iv:3soSWoWv6FnxodiLmVbkzNyiT7/EhfkpBPmMlaB8oLM=,tag:sEcXqRwSzU4LvadZuF1zww==,type:str]
    FRIGATE_LITELLM_API_KEY: ENC[AES256_GCM,data:2UPCtqLY3HcKKBq2zvZy04XTiUYj+tuwIw==,iv:qaHwT+j29xsI94by+ToWEe70Y+Fx+N/sEy+Zv4sFrFs=,tag:3HElwugQQEx0K46HWnl2EA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlB6N1NYNzBaMkFITWpM
            cW5JTDBTSk9IcU1zRXlyT3hDbFJBSEhqeEI0CkhrbEZlMVJLa3A3OFJjQ1lrWU84
            d3lVeUJaTDZ2ekZGNTRFR0RINU9JNkUKLS0tIG4vUk11UjlDNTNFVGU1YTE1Z0k3
            VDZDdGl2SW9ReGJrWEErd3VtbmMzeUUKmU6I6mHklrpeYxbM6QzwQj8rgbt8jwKv
            L9x5pgrdhDgm5dHR2PerAZIDYy3WPpyNhtMgiQRr9aCn5x/a0c0vDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T00:17:19Z"
    mac: ENC[AES256_GCM,data:g0mLmYa5h3UpEio2F0rS/HRlgj5N6KXG+q3axrAoxO5P+78HV0qzikNc8EkXTjr7ek+BE9iK4oGdWum5tJaYXuaEGqflu9j7J7vdOOaAPBB1l9u7hEZKGueSv+FV5/UZ67krG41sb1afyGNS2aUQhClgQLGA1a3jcSBARij7mTE=,iv:tZyLYtrbftotw0mb3dnKTHKEUVnMeItgkh5uatUoTQ8=,tag:+3XYs5tVjdYRmN6sxMcI1w==,type:str]
    version: 3.13.1
