---
- name: Download K3s binary
  ansible.builtin.import_tasks: download_binary.yml

- name: Restart K3s service after upgrade
  ansible.builtin.systemd_service:
    name: k3s
    state: restarted
    daemon_reload: true
  become: true
