apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: utils
type: Opaque
stringData:
    HOMEPAGE_VAR_WEATHER_LATITUDE: ENC[AES256_GCM,data:dr9oS97AMlUztiG4vYXVpgU=,iv:yu1zc4068OAhqpgwcxqDv/TMl/KATzdLlppD/C6dexo=,tag:cevhn7LGJ7hmn8gjYO6o9g==,type:str]
    HOMEPAGE_VAR_WEATHER_LONGITUDE: ENC[AES256_GCM,data:lajmOASyW3a56s54lA4BJytg,iv:dPcWKvZsATxLBrpvlvX0Hm2drCACF76dwuAWHb6XqfQ=,tag:aGqG3ngKMSrowvSmJFTHSA==,type:str]
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:KMJJvvm5yNJsMTFqiX6dIt0XEAx/2k7K4VPpNu9TuaDKWmZWKqKJweMUHp5O7LAPjJ/026QdEqnu5y+hf2B40g==,iv:AfVGLw0KXKUdAHjkCqLjFYr1ruI6oZiF3oNdTcfiyuk=,tag:Gq0869lMtbTFp45wlAI5bA==,type:str]
    HOMEPAGE_OIDC_CLIENT_ID: ENC[AES256_GCM,data:SdLgZMpLrKqno5nxf5nkhHI0+SnnYwvUFiwX0ErLwxEz/4fuVCiAp/UA9kcDxW2z,iv:tuWYiJZer87j2oa1YJuF95ZWQdxXdsUNH+UfFof8vkc=,tag:VdoetTQDg5gY/46bfU2UDw==,type:str]
    HOMEPAGE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:h5oy+ZyUuoh2N5wPA0pJj78N4GHBfQZzmMrMK/VhHY2kh6MnYCTZcwIWnxNmOzSHsuEuo7za/8dJIRfnkTROcA==,iv:sNR2k8zcgQGccvgrOBBvBdjK9SNjH1h9G+pWJJ3eI1g=,tag:aMYKC9TshDMKjBOTf2YPug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZHRRbnBkNjM1VjNYcEZn
            SmVhU2NyRWFaYUxRQytWV3A0WTdZRGd4dTMwCkNEalY2Q25jVnlOUVJrZk0zQVJP
            RkhpeEV1OTQyVVRQdkozY1dGSXRrVmMKLS0tIFZVNHVkQVZEYytDWTM3ZTNlS3lo
            QWMrSHR1UzJIUUtFbFovWS9uWkxKNzQKuClJqk/UtCuanL7dI800lzGYxLXalXgA
            OlhEIyykUwWZI+n/77TqvbmbjLTuaat96h+Rrro1IC0xMqeqjGi3tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T13:31:37Z"
    mac: ENC[AES256_GCM,data:S+CLhtx0fShbyVhv5mALtdDh/G3WGVDHdOhQmtsB3kDRd+u395A55hquAm3TVcF3aVbdFW2eZzvszqbesCc6PfEk44Y+4xXGxdNBNWOxSGDzEIePJyjXLbx5SQN4KD9YVqFpGSXlwD6+rsmEU/uJWEr9os65BRC0hzkPxcXfs0A=,iv:iBNNREe7OszqSuVRuBNSz26AaM/U7oSxnP7KoInJTkI=,tag:+ZFZhEDWBSaM+o7o1thcPA==,type:str]
    version: 3.13.3
