apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: utils
type: Opaque
stringData:
    HOMEPAGE_VAR_WEATHER_LATITUDE: ENC[AES256_GCM,data:DjfCY9dG3mckfnoBvKDot80=,iv:S3B9B2qAUKXv5NX6k2t3xAAEGaYmft7gXoWrGsRzWVI=,tag:AJA8oColg6fRXF/r2PkqrA==,type:str]
    HOMEPAGE_VAR_WEATHER_LONGITUDE: ENC[AES256_GCM,data:22LGcEJyI7u7trxqzjpzEPc2,iv:YXS9/tfidb+iMfjF+wPD+7EpgrQJ+5QDKn5F2lViTfE=,tag:Gv9mlRpzno2NSMGjf4L/uw==,type:str]
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:hNeCNKyCWspznz/X/PaN1Umfpu5eXK3xe6otxniQOTGmXN8mglRmU8sQ+ePXduux66MhuYuLuw6xg98tje43Zg==,iv:5CobJrdpLdrNCMuE8Jxkl+pE2eoHZkJxfYPfvfy1txg=,tag:ZoN/mooY7bG9+MAXjDgVjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSGFkbU5EdWJvYkQ4bkJx
            aGRPSEl2b2JqeVZWMVlPZkx4UWFCZjFYZmhvCjNrYi95NXBLU3JCa3oxd1ZRSVlu
            N3E0S1o4d05rU2x0bEsrVDFadnFOYVEKLS0tIC9sR2FmL0RONXcrQnk3dGNIemVP
            aHgrOWFqaHJta25abE1HZEVmWWsyb3MKaRQek0suuiXL4wgXVQYQ6k0AFqCPa8wn
            Ae+UdyjvKiJMpOnHd5zulpziziizjEuy9nTR3nCDuDLm+uIR16BNhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T13:42:54Z"
    mac: ENC[AES256_GCM,data:T7eJzhIz1wMA2YMZImgkvjZXlArUBzvtKmNIr2Jj3aOz9Ue2B9uSc/J8mk4S3LPS1o60+uMOBh+vN9orvpFFYVs2RhNbRWoqdArc4rsuevoihGWWTJq8QbCnvbG6OTHPd/ajsCjRCxI6N6eljbkq8CgVg93hst1rSZn+tC4lt/w=,iv:pgdMH05DhnOP5Ximn613ZMdbzmFesU9dfugjenmUO4A=,tag:3gQPXK466xKbND4GkYWf3w==,type:str]
    version: 3.13.3
