apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: utils
type: Opaque
stringData:
    HOMEPAGE_VAR_WEATHER_LATITUDE: ENC[AES256_GCM,data:X+me4v5Q4HEwKYCA+Ln7Zhc=,iv:ws7qTXiv4feJMWWg3QjGrc1M7NnUNS0BgBA8VlZUUdg=,tag:5w4jn10KCOSiiaenPN52zg==,type:str]
    HOMEPAGE_VAR_WEATHER_LONGITUDE: ENC[AES256_GCM,data:0VdFJ9X0umfJRW9C48rVUHfS,iv:9d9FI9vaFtI31x0WW6KLyJ/YzqPxtQgJWm+5RkNLd3I=,tag:Wjk3RP0i4XBWcoFd+H6cQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNW9QUEUwL1BDWUROWWVW
            S1dHR3pkN0VhWU9relI0TWFYOVhnSVhmbGxBCmNPQzNHaC85ZnNrdm9iWHRTQkF0
            NkJnSk1RaFVuck5kZ1FXaTU4aWhiRjAKLS0tIENTVFVZVmlTWmgxenBvMEVnTlFT
            aFFHZzdNTjV5d3ZsUlM0ZDh5ZGlPbHMKHSIfwkjH0/LB9pDrDm58pqCwft1zQJGE
            +YtIjRbOkMh8FCGnsm2xb3utkcZKr6HOr8Ah7LApkgPoW0KaAoYaZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T12:22:18Z"
    mac: ENC[AES256_GCM,data:Ip/JEx80HS7jCoDlh0kVEnsDItQApqOyQyyBq1F9xllF4UX61BDIG00kRNrHFapV1i52zbYRxmmcXi3VZ4RvN4AeVz5hyVWH67nAgwEfuzQsogk0yFVovI7+WvneTTH0mfEcLP7W3V0i6PHYg5QXqu4yHrGrEzsFPi8F1cuzQa4=,iv:cP6VanOknXKfFcxKy+7qJhzPMz0Ey3e7G0LRH+f97LU=,tag:tpeIE7yE/vNsHRl38693Dw==,type:str]
    version: 3.13.3
