apiVersion: v1
kind: Secret
metadata:
    name: sure-secrets
    namespace: utils
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:xQ81f2ly7Vx1GFLASoHN6iqQAXhOr4O5NpHmXcrkMx39lCfu9a6kCmTwXJI2u0POgC42T9lQ9qkElNs3ucx//GpMJWy2LlAQxrQLG/9oRsujHLEHxsvtSdYBTdBQKW4h8QtcDWmAbTeb+cv/EjWWgQxfvPR9AQyEm9cKTD/FNTA=,iv:zPmT54tH6i2hAdIWFXSVzCp83I0uqV7fALx42bDsM0c=,tag:mqjbKu0YUBWsMD5jdnZ2VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWGNuZlAxZC90WVNyYSts
            WE1iRzVrcjIwUklabG9vSExtbTl6b0FQVXdnCmRtY0lCa0FzUENROWlyM2h6NmVF
            MjZvMlZMNTNEemczMjh4VkpKeE5aemsKLS0tIFdzdCs5QVV2RTg4Z3A0K0xYQTQ0
            Mzd1YjdneGgyRFFYWkdqbzJTQ1duYjgK7g9iE05cZMBCemkT5nVzzGOeifMW4Fm1
            uLIG+Knb2mt0OKXRYqOd9zsm2V1nQbjy2V5JJ6QURHTFxBoyKzBHFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T11:13:42Z"
    mac: ENC[AES256_GCM,data:JbYiaRsUvGKvv6/tBbN4ZYkk6F9E8PgHWo8f5nHyqPZ90FxIw6dTcIsuXvAuqpsJ3cluXSF5HsjQwRsFie+BOm6osxFVooZyD+27Gry8uQrOw3kimDLlV9Y+0vd12geLKqpZ2SUKAaL2pALOOHO5iXeZ5PQCT2LN3J2R/yAsz+A=,iv:cOR8FA3s6y0VFTdKIJuMt7KNOgby5x5hJDQCu7E10zc=,tag:VHQvKHeUgPw6LQT74DAkiw==,type:str]
    version: 3.13.3
