apiVersion: v1
kind: Secret
metadata:
    name: sure-secrets
    namespace: utils
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:xQ81f2ly7Vx1GFLASoHN6iqQAXhOr4O5NpHmXcrkMx39lCfu9a6kCmTwXJI2u0POgC42T9lQ9qkElNs3ucx//GpMJWy2LlAQxrQLG/9oRsujHLEHxsvtSdYBTdBQKW4h8QtcDWmAbTeb+cv/EjWWgQxfvPR9AQyEm9cKTD/FNTA=,iv:zPmT54tH6i2hAdIWFXSVzCp83I0uqV7fALx42bDsM0c=,tag:mqjbKu0YUBWsMD5jdnZ2VA==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:sHT8l4cQRsyH6u1dwDS9AMV230J3Q55s+nbfwKhXv8v2brk=,iv:IP1PLCxKR3CIL3LGOXDkfMWwjOVl0CC0W/ABKzDf6ZA=,tag:LPQefAGeFcqdjeDrz8hnGw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:DZt6/7OsX4Cl+Ic9ufBwb+KukcexNb2hj/6GUKOsc+g=,iv:PJzyIVFQ3Z+YOHrJW+/2Pjp+Z0JQV5qduJFOaiElQ8Y=,tag:R+C3Xj15Msq9OxDglLggdA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:9FzoTxn/7lTWJoiQxlUz8mr6kvU=,iv:JS6r9APAoxYFv3k+AAm8L9v3ocgxGnLV3e0tcJcvWUA=,tag:ckYbocJjJwj8nL/0fnFcSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWGNuZlAxZC90WVNyYSts
            WE1iRzVrcjIwUklabG9vSExtbTl6b0FQVXdnCmRtY0lCa0FzUENROWlyM2h6NmVF
            MjZvMlZMNTNEemczMjh4VkpKeE5aemsKLS0tIFdzdCs5QVV2RTg4Z3A0K0xYQTQ0
            Mzd1YjdneGgyRFFYWkdqbzJTQ1duYjgK7g9iE05cZMBCemkT5nVzzGOeifMW4Fm1
            uLIG+Knb2mt0OKXRYqOd9zsm2V1nQbjy2V5JJ6QURHTFxBoyKzBHFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T22:09:11Z"
    mac: ENC[AES256_GCM,data:Yw4Rvr6LceGnUvgG8qcyc/DrozVOjENO36OI5BdjzT7VAxXlrpyqbFyU2sbWsII+Wad9CppTv9gpEUohuk6xpJ/yvqGez9KA8cq5nJ0ePLNTSaDQLjR7+m+8YQDw6vREju7fsFA+diWTAjRmtPat2glFk7S1tZmcfymjhoQcoHI=,iv:+pzg/wJEWwuba7EPlp8vZ6D6f7v1GIceZCaztyZY1RA=,tag:ECcPD2FYmUEJIPtRm9Nbug==,type:str]
    version: 3.13.3
