apiVersion: v1
kind: Secret
metadata:
    name: sure-db-secrets
    namespace: utils
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Qez9Eg==,iv:3AQMRUOV5+r8u/VTmRefcZoNSZtE79PYPu7jr1OM7Jw=,tag:mlJxudDF1a3Gd9jjG1GxUQ==,type:str]
    password: ENC[AES256_GCM,data:g2ZZFlE+OjPy0ZaC8woRBljmmBthk5RSDS0BGufcE/s9XNtPehDmWyL4uvpxUuh7,iv:ycVH4uOkTYYPuux00iyzmMyXQq5NLhW6rI8Yb6rdvjI=,tag:q0F8oas5xFWg0BVYyEFfNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbnlmanhrdUhIZEE1T3I3
            RWxlQSsxKzhZN0huVXNCSVNCOHRYQWtJaGhrCjhPTUZHZXNsT2p2MEE0S2J4RzVL
            SllJRUFwL2svcVBxZ1NwOWFmWkR5cXcKLS0tIGZQQjdPV1B6N0duVHJ5ald3NE1i
            akR5anA0Q0c0RVNBZGp6WWovSlhZUW8KTjSSkVdtYM1IN9LOt7fj53oSlJ5V1B6w
            +jE5ah28/bUjVHIDDI36ikIdkUhPGZI4LcY22WxfF27gy11f1QkB6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T11:13:43Z"
    mac: ENC[AES256_GCM,data:75paGG91kW8UUqsbckt5u1OlVaUe9iptN7bbIPtNRBiSZGtA5LZiJzrRo9DBFV4RE153JSwC9BBXDJ6y00hVCAlW8iDC+CJB7ux1LuBGBygUR98RHK3fWRNpDQFP9ZEg539r/BOz5QPu8URVFWZqGSjQEYJS06ePoqr04Bjjosc=,iv:noEshTLdXD/dYwGjCH1wcdlA8nP8GIKeyveKumBsV8k=,tag:k+fn+QDa8B2eLehoujfUkA==,type:str]
    version: 3.13.3
