apiVersion: v1
kind: Secret
metadata:
    name: sure-secrets
    namespace: utils
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:uh2sfHaEgrnD6L46NySeZ5KLEaI/ChocQX8338s1wUclkyDk15/5sm0bc1vdscR3JduUGM9GQwzoSjE3FUyhtt9mB6oPZ35AVWeXD4/ci+0b/WOUhIuCvtK6rik7CrAvld+pWFrOYs89NY0Ov+u/JqZcbhFVT3X0IPWJYjdLqHo=,iv:IgZ0Ivc41uyOeYVR6+ftAeOpQVV/jxMBcX4wtw4mTXo=,tag:v+7twWeA7MadGjW9dv7hPQ==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:VlaQWjbcA3A3A5HLqXUL68k1pH61swfwlA==,iv:D1joPAvvJIcBCfN4Q0NukX4O1pdLljVbSc+rV1E5el0=,tag:CanspK/7b/AwWTI6KDILrw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:hjA+uZ+oc2MmhjlkSXGW3pdWKFroyKJuYBe0dDEWJTE=,iv:hyTZU52EayCI1VAibcfTOsXpFziZjC9rYhQdGOPlvk8=,tag:c6QGhVdVDps5d2UiRPEawQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:Ix39NtSrM0uPCukGwxuZ3frAqi8=,iv:tAUupnlgO9UdBtmJHMbhxsbFYOso538X9RbCDkkQ3C4=,tag:t9HqGO+ZPV+hxhnRuVIx+Q==,type:str]
    ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:Ba3dTE6Be60ryJk2CUAu2GDyeCqVuADsuSdO6poXqgU=,iv:ulSX00Z+WSc9yX0p1dHa1fHZ8qAlpFi88JsJIhZFWJ4=,tag:Iouo8Sa6vBQYegn5gp3o6Q==,type:str]
    ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:wunhorWDUsiGWohzNoQoPBTfACVl0IxYCEHQDuUe1DI=,iv:qgDU1g2wFF207CM+r75VgUKX+gYZcoWNTYDILPcTw5E=,tag:HxT8fjtDchY0CYzNlkcQZA==,type:str]
    ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:CxkgFT6duXLd2LgRdXYMq8SwKo6CvPr4dPOgi9cG/ro=,iv:EI8yu5a7gAvHcvF3lfTUVezjFxZiWa7WCSi7YvsjRDc=,tag:h9QZdztb9InCHO3p0lDpsw==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:qsfI5FCuqP9kpR9Z0Igb9K4tKGJqi8zYCX+/03N5ZUOK4CI=,iv:wLsOBhsEgbyCMaSZBi3XLOYotXox3353GTKiDmFmdP0=,tag:kn2HfJJ3ZA6TrqWnUDe6XQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb2lVSG5yNEdkY1BQQUdZ
            TW51K3NNOWRPeUZTMUdyVFI1MWE3Z29ZQmp3Ci9oeGJKSXA0VVM1aUV5aGxnZmMw
            Nno0TWMzZS9vd0pqcmljajlIY0hCSGcKLS0tIDk0ZnJoUlR6dnhhZkNQNk5vU0hW
            NXJaNUZqbytGQk9nUTRQUTh2ZG5CZzQKRSyoReWazxJljHpaefG/5CIjyaenROQZ
            rjA8J1GSnLCGYSC4WQR5n9P8QtJJn4y6ivEKbC5GKvBqxoN/zJID+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:19:21Z"
    mac: ENC[AES256_GCM,data:rVFHwo7ALNx6MiosAQKMMnwFlxO/3EoDuIYprwzlPnDDkp6HF4rqdY4FsoEEOzZhAbgS4BbGDBCgxDV9d1zTl6YGjhHoMNvtDbepM/cp3Ey/tU7zP1VPzvM+sbEPwVm6sjUdq72bgru2F6sOR+q/4U/Q92gD5DG34mZY5GBCnrU=,iv:VHg2EBC61FzSR8TY/6jpCkbCCZvMCWgmKc7N2ntwxig=,tag:swiRf5AEFcjplg174jMEfA==,type:str]
    version: 3.13.3
