---
- name: Upgrade selected K3s servers sequentially
  hosts: k3s_server
  become: true
  gather_facts: true
  serial: 1
  any_errors_fatal: true
  vars:
    k3s_operation: upgrade
  roles:
    - k3s
