apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-dashboard-opencode-observability.yaml
  - grafana-dashboard-k8s-views-global.yaml
  - grafana-dashboard-k8s-views-pods.yaml
  - grafana-dashboard-network-edge-lan-trial.yaml
  - grafana-dashboard-longhorn.yaml
