apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: posterizarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "0 0,5,10,15,20 * * *"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 3
          failedJobsHistory: 1
        initContainers:
          init-permissions:
            image:
              repository: docker.io/library/busybox
              tag: 1.36.1
            command:
              - sh
              - -c
              - |
                chown -R 1000:1000 /assets /assetsbackup /manualassets
                find /assets /assetsbackup /manualassets -type d -exec chmod 2775 {} +
                find /assets /assetsbackup /manualassets -type f -exec chmod 0664 {} +
            securityContext:
              runAsUser: 0
              runAsGroup: 0
        containers:
          main:
            image:
              # renovate: datasource=docker depName=fscorrupt/posterizarr registryUrl=https://ghcr.io
              repository: ghcr.io/fscorrupt/posterizarr
              tag: 2.2.32
            env:
              TZ: Europe/Berlin
            command:
              - /bin/sh
              - -c
              - |
                rm -f /config/temp/Posterizarr.Running
                pwsh /app/Posterizarr.ps1
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: "1"
                memory: 1Gi
    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          persistentVolumeClaim:
            claimName: plex-media-enrichment
        advancedMounts:
          main:
            init-permissions:
              - path: /assets
                subPath: kometa/assets
              - path: /assetsbackup
                subPath: posterizarr/assetsbackup
              - path: /manualassets
                subPath: posterizarr/manualassets
            main:
              - path: /config
                subPath: posterizarr/config
              - path: /assets
                subPath: kometa/assets
              - path: /assetsbackup
                subPath: posterizarr/assetsbackup
              - path: /manualassets
                subPath: posterizarr/manualassets
