---
host_power_backend: sysfs
host_power_cpu_governor: powersave
host_power_cpu_epp: balance_performance
host_power_cpu_boost: true
host_power_cpu_max_freq_khz: 4200000
host_power_powertop_auto_tune: true

host_hardware_extra_packages:
  - intel-gpu-tools
  - ffmpeg

k3s_iface: enp86s0
k3s_storage_mode: manual
k3s_storage_expected_uuid: bf176804-6285-4d34-842c-c6483255b503
k3s_allow_workloads: true
k3s_node_labels:
  homelab.lan/cpu-vendor: intel
  homelab.lan/gpu: intel
  homelab.lan/role: general
  homelab.lan/runtime: baremetal
  topology.kubernetes.io/zone: daring
swapfile_enabled: false
