---
proxmox_kernel_params_add:
  - "intel_iommu=on"
  - "iommu=pt"
  - "video=efifb:off"
  - "video=vesafb:off"
  - "hpet=disable"
  - "acpi_enforce_resources=lax"
proxmox_kernel_params_remove:
  - "i915.enable_gvt=1"
  - "intel_iommu=on,igfx_off"

proxmox_power_tuning_enabled: true
proxmox_power_tuning_start_now: true
proxmox_power_cpu_governor: powersave
proxmox_power_cpu_epp: balance_power
proxmox_power_cpu_boost: false
proxmox_power_powertop_auto_tune: false
proxmox_power_tuning_units_to_remove:
  - disable-turbo.service
  - powertop.service

# GPU Passthrough - Intel UHD Graphics 630 (Comet Lake)
proxmox_gpu_passthrough:
  pci_ids:
    - "8086:9bc8"
  blacklist_drivers:
    - i915
    - kvmgt
  disable_vga: true
