---
proxmox_install_ai_amd_packages: true

proxmox_extra_host_directories:
  - path: /mnt/ai-files
    owner: "100000"
    group: "100000"
    mode: "0755"
  - path: /mnt/garage-s3
    owner: "100980"
    group: "100980"
    mode: "0750"

proxmox_kernel_params_add:
  - "ttm.pages_limit=28311552"
  - "ttm.page_pool_size=28311552"

proxmox_power_tuning_enabled: true
proxmox_power_cpu_governor: powersave
proxmox_power_cpu_epp: balance_power
proxmox_power_powertop_auto_tune: true
proxmox_power_tuning_cron_entries_to_remove:
  - "@reboot /usr/bin/cpupower frequency-set -g powersave"
  - "@reboot /usr/sbin/powertop --auto-tune"
