apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-install
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/infrastructure/security/authentik/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-identity
    - name: observability-kube-prometheus-stack-install
  wait: true
  timeout: 35m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-identity
