apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-cluster-identity.yaml
  - 00-infrastructure.yaml
  - 05-automation-renovate.yaml
  - 10-metallb-install.yaml
  - 11-metallb-config.yaml
  - 20-traefik-install.yaml
  - 21-traefik-config.yaml
  - 25-external-dns-install.yaml
  - 26-cloudflared-install.yaml
  - 27-netbird-operator-install.yaml
  - 28-netbird-config.yaml
  - 30-kube-replicator-install.yaml
  - 31-reloader-install.yaml
  - 42-authentik-install.yaml
  - 43-authentik-config.yaml
  - 44-crowdsec-install.yaml
  - 45-crowdsec-config.yaml
  - 50-cert-manager-install.yaml
  - 51-cert-manager-config.yaml
  - 60-longhorn-install.yaml
  - 61-longhorn-config.yaml
  - 62-cnpg-install.yaml
  - 63-harbor-install.yaml
  - 64-harbor-config.yaml
  - 70-observability-kube-prometheus-stack-install.yaml
  - 71-observability-metrics-server-install.yaml
  - 72-observability-loki-install.yaml
  - 73-observability-alloy-syslog-install.yaml
  - 74-observability-alloy-install.yaml
  - 75-observability-tempo-install.yaml
  - 76-observability-opentelemetry-collector-install.yaml
  - 80-nfd-install.yaml
  - 81-nfd-config.yaml
  - 82-intel-device-plugins-operator-install.yaml
  - 83-gpu-plugin-install.yaml
  - 90-storage.yaml
  - 91-apps.yaml
