apiVersion: v1
kind: Secret
metadata:
    name: karakeep-ai-secrets
    namespace: utils
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:oJbl63SJxxZFDbRmBQhhgNT4+RyDwOO1hQ==,iv:BTrKiy8SwBCCbAhGAQtf0z3JwEw0lsMCm0qN356opd8=,tag:iQIONoRpwizkJoKnY1/UeA==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:nYSOVXuLL7eDdrZnTonbIbadYxnLCwZ3wbxSTDy5SE+1Yeo=,iv:MHSHDW9dyTYihwLblSbbKIK9T8TFwNGqiMNddcpMshc=,tag:nWs1hH9W8QT1pXMzO8o6fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ejRLV2Rob0FTSTYwVnZ6
            RGpqWVpSK2Nzd08xV0xHQmk2UUo1WUNIVGxjCll2NVNaVG13dStJRXlKQWt3OTg2
            VGdwSzEveERodEZ6VGdKaUU2ZVZmVVEKLS0tIFlpd2I1MmEySTlhclV2Ry8xcjZj
            V0xhSklxYlMvUWljYmh5WmFhSmNZWHMKAA/0/g9bPTgVYP51oyqmKLU3DRb8CRQc
            /4KV/YhF8JVyyNDEKrJmwxAqo8KpSDPnSwY2n2Bl7iVMIx4A4DtPOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:19:21Z"
    mac: ENC[AES256_GCM,data:oAEKEhZ2qZth92HPIeCLTTRhGc6up4tAhs+SoyEaBa/VleSpU8rzSlAmrWFauCz46cp+hKbRDn1DGWCLaJQD1ag85HgC1Ktp6G0p5YDkfK4+S3xLl9jjtcQZvWN/EoKYyDTH2Ix0/NWmm5uVJjYbEufOHeF9in4Tw0zSDVwgbcI=,iv:9N0VFplKwjeIdTV4rs5ZATWiYfJIizMaKUeNA5ZQ6Zs=,tag:E7vPEpPBXyAerS0277k3jA==,type:str]
    version: 3.13.3
