apiVersion: v1
kind: Secret
metadata:
    name: karakeep-oidc-secrets
    namespace: utils
type: Opaque
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lhyXsbaJ2hxjuoKDvIgTL8zXZIn4NHBQVV205ad0Q+DKLdaNuJumXgfR/EdIZc8x,iv:Bz/6a9fpoaPOtiGreMsCg5dQWjzPRjp0h6iBMNSA75E=,tag:jSFBN2peiE5D9qktDK88+Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:YfeCrZ95P/VabCBUBA6zM4z4yjOmdrjv8/MNrlYZOaN062Lvgyr05hziR6g3oXJ/,iv:dRV9hb+IeH/7f32T60GvySL/2Ci5aG5cGnxegUiBbtw=,tag:tToUPmYXZQtOgll5R/3GLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOXFsMnF6NldhZXFsbUVy
            VDBObmFuTnp2a0xhZXA2Znh2OWtVNENCdzFJCllUSzFESlVHZU1SOFlsU2VlaXdV
            U1ZaRmQ4bnlBTzQ5bjZDUHdWSFBrbUUKLS0tIGRWTGJJV3hUY0dhNERxSDVNNjcz
            LzJHQzA0M2JyQnVrOHI3Q3l1bU9xRUEKF2aayC9vatBwe5X4UfTx4asqfLUxIJo/
            FIrW2NcKBeCxrso0UeVcxVO4qMJIseKnB3htZG/BFCaTXGuYXCmN/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:40:29Z"
    mac: ENC[AES256_GCM,data:38dxpUAVJA7Zuf7JvS24wVvVW4kfk4+myBj6V/xFSVQoD9hWljwCBXkX/RkAlY61I5WJHHqzS2s+sEmfGsNDIJzYbbX6nWZBbM/m3yjeT/dwKkDcBacT/fM8lqF07xrMzW2Vhms9dqkI9GKaH6aMESYQY5F6bCChKIMC3GikScA=,iv:oapHoLpK41gd0E2DqMoqaI1XFZbq0brCJRSM5ALZN98=,tag:Nsc7qGJeY312D0Gt3uZumg==,type:str]
    version: 3.13.2
