apiVersion: v1
kind: Secret
metadata:
    name: karakeep-ai-secrets
    namespace: utils
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:G7c2I/zHtZ98EigMtuRH9StxrXdVWM7X4Q==,iv:2+w6Ij8oT+IcgdnsZRYuNVHkPSng0zEzmd9Nhgr1W30=,tag:7wDj3EYMu46KYuEZsP2qyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbk1FV2c2cFA0NTd4d3BY
            VjNYSVA4MnJ0OEdTNGg3RXgzeE5HWG02MkQ0CkxsMlJSYmgrcFRpRVljY1BjQzBz
            a3F6Q0xTckwvVjRsbWxlWExvbUN5Z0kKLS0tIGhsckJZMCszZ2ZMZG9aa2svYXJE
            Z25WZWNrZzVKQndKbDl0THdGdXl6WlUKyq9ODDvYEpkYCrU8cYiFG41PYK6zWW0+
            +uRA1zcBZwYkQBm0QhwsWxqJeCOAdVl1YuOcHtDCYKy0dxY9K+2WZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T23:13:23Z"
    mac: ENC[AES256_GCM,data:tRt9C34bMjGHuG9h+JFxzhFP4kDaNsGQ8Sx6msyoHKV65dIiPnuXV7+S/jEI/6fsFqp9GH7X8r9zt6jkAyFTgetbQxVIG9qToXYZ1iq2WbtSeVFwVzOl0BwrGsXuoAMu6H7CZJSsMmOHBs5G85+7xBCwBcYnnutA0A9+VuNvxgM=,iv:6bJfJUuBQAoMGGQHX2gt83t/pmcdjEobbo5jjalPqf8=,tag:cScu+h2BEfRgKi+ghgNzOQ==,type:str]
    version: 3.13.2
