apiVersion: v1
kind: Secret
metadata:
    name: karakeep-oidc-secrets
    namespace: utils
type: Opaque
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lhyXsbaJ2hxjuoKDvIgTL8zXZIn4NHBQVV205ad0Q+DKLdaNuJumXgfR/EdIZc8x,iv:Bz/6a9fpoaPOtiGreMsCg5dQWjzPRjp0h6iBMNSA75E=,tag:jSFBN2peiE5D9qktDK88+Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:YfeCrZ95P/VabCBUBA6zM4z4yjOmdrjv8/MNrlYZOaN062Lvgyr05hziR6g3oXJ/,iv:dRV9hb+IeH/7f32T60GvySL/2Ci5aG5cGnxegUiBbtw=,tag:tToUPmYXZQtOgll5R/3GLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSHlxQzhvK2c5MDlSbER3
            MWhtQ1VpVVhQTFBKbTdXZVBIU0NVdnpKalVVCkFudE9TZWRDTjhrdDkva3RGZEJP
            RlhvWmd3cFAvUXFxOEt5R3FOay91TDgKLS0tIGlXdjErcUlMeE43bkprWDRkNUVx
            N2R4T1ZpbEc0RTM3VzRwMlkwZHV2dU0KBwpiaWjzunep7fLXwtvAFOouPsvFmDyT
            b9HcWnpI9cj5C2Jm4tsgGa0Mdzf91xQAz5eZcVgNHY5JKKWcNk1hdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:40:29Z"
    mac: ENC[AES256_GCM,data:38dxpUAVJA7Zuf7JvS24wVvVW4kfk4+myBj6V/xFSVQoD9hWljwCBXkX/RkAlY61I5WJHHqzS2s+sEmfGsNDIJzYbbX6nWZBbM/m3yjeT/dwKkDcBacT/fM8lqF07xrMzW2Vhms9dqkI9GKaH6aMESYQY5F6bCChKIMC3GikScA=,iv:oapHoLpK41gd0E2DqMoqaI1XFZbq0brCJRSM5ALZN98=,tag:Nsc7qGJeY312D0Gt3uZumg==,type:str]
    version: 3.13.2
