apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: utils
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:3BVUpVw6I4YkjCMrbp5Jvyya+rdW5GY+yF1LhsiKpWbspoOyA2zL70BwrRsM26M+,iv:TBLzWR2FIr3PoTN1vn6i5ncb7DrqMEVa5FZtIzmY8mQ=,tag:pcvZXN6VD7hY1B6vLW6kzA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:bOC1OCnH6QcVv9Jxvd+Ik6ZKjWqmE0uvWmeUI4vEu8sgtebyZDjhJPB4nSV+NSh2,iv:/aHWsBUEoZSVi6ZfsNbOIaicXXIOcz2RMZ6uYKlc16Q=,tag:LSR6yS5py+eLix/rKKWKwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUoxaDA0RDh6Ry94ek9j
            ZTV4NFlrSkxTaXlZakQxZ1pKN2I0VzBwY0JnCkpNemZnaEFGMnhmcDM1aEVyV09z
            SEd4Q2tIWjMvd0p5M3k3d05EZUdrRHcKLS0tIFNyWDVOKy9qTjhnSnhkRXFnYTFr
            Nk1mcjFzdUowMWltanA0ZXM2NkpTeVEK12WscfYQmo9rw1OZt5cIUgtjsr5e2DxF
            8RuFbpfA2PqlA7z/paoS9icSWxV2t7D5ig5XHO9/VLXbYpoRrEmwCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:40:29Z"
    mac: ENC[AES256_GCM,data:Gnojm/01Zo+hk8KLJ36Ba7ILhqqtlwzFSSOqGpXZWYMG5ODeMbvF+hGU5dOTdExIVpTh/6mjtyDBOeaYMtioS2MqKzLR7k7WJ29BkdnLkbmha1wvMwiK6JpdT/nJiUQby90qlMjVUvR+sGufwLC9BwvBA1Gu8gTgGpl8FJob2jg=,iv:u/9NgMq3RmYDF3jzY/Amkm+HP+hcdFfJyPYUzLqWiyo=,tag:ykmhDEmHVNIlDTaF7x3JzA==,type:str]
    version: 3.13.2
