apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: utils
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:3BVUpVw6I4YkjCMrbp5Jvyya+rdW5GY+yF1LhsiKpWbspoOyA2zL70BwrRsM26M+,iv:TBLzWR2FIr3PoTN1vn6i5ncb7DrqMEVa5FZtIzmY8mQ=,tag:pcvZXN6VD7hY1B6vLW6kzA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:bOC1OCnH6QcVv9Jxvd+Ik6ZKjWqmE0uvWmeUI4vEu8sgtebyZDjhJPB4nSV+NSh2,iv:/aHWsBUEoZSVi6ZfsNbOIaicXXIOcz2RMZ6uYKlc16Q=,tag:LSR6yS5py+eLix/rKKWKwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTNGWEdmdjZEYlhPaDRK
            Uk1XZlFiMHZBclNyd0J5MitpZnhyVjhpcTB3CllxWWNPR25LR0h0TEhEcDhHb3ND
            ZmlCQy9scnYxdTVLd3ZDTFN1VldTc1kKLS0tIEVSWmpMdVJBbjg0ZmxMd2R3YXlW
            R1VxblRFMmY0QmRRNWd0UVk5c1p6ZXMKUwNqKNi16452x/vVNNq0rHVHi+PN6Ga9
            G4/8ur5RelvfMf/7A//KES3xSmmTjhNPVX26/hxMZIbBrzfTymwRpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:40:29Z"
    mac: ENC[AES256_GCM,data:Gnojm/01Zo+hk8KLJ36Ba7ILhqqtlwzFSSOqGpXZWYMG5ODeMbvF+hGU5dOTdExIVpTh/6mjtyDBOeaYMtioS2MqKzLR7k7WJ29BkdnLkbmha1wvMwiK6JpdT/nJiUQby90qlMjVUvR+sGufwLC9BwvBA1Gu8gTgGpl8FJob2jg=,iv:u/9NgMq3RmYDF3jzY/Amkm+HP+hcdFfJyPYUzLqWiyo=,tag:ykmhDEmHVNIlDTaF7x3JzA==,type:str]
    version: 3.13.2
