apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pniFiueaRPA3DKD3wJprSPvgwQ9NNzK7zYHAzch2EAmUjpSnaZBuKQ==,iv:hpk9NTfjYd0aQaurWwy6H34oYUQp7RnujkbRAdIxAC8=,tag:Wbd/EaZqw49axsk+BaLzRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcXBXWjgrd1lRYmZUeUJU
            cEMrVGtOeVN1SkVLbHBBTDUxbHF1VEtuQTNVCk1HNThBakY4R0NFV2tWc3V6T2Jk
            Z1NnT0h3WVRGaE9GdnpPb0YwbmNIZkkKLS0tIGNNTG82TG5vbVhJbHJGMnlFMDVJ
            enFOYnJDZGVJdzlLd0pjTXZndjJIUU0KtTK+Uz5Dtl+jt5PdzpcfL/GVsHVocOwt
            tQEfNVvgWpLYmebQlqj0sqR7AL6dhBhbtHbIkuvdDn7Hprmi4gU0QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-23T21:38:04Z"
    mac: ENC[AES256_GCM,data:GJa2C9OfHCAUYymhsCaUnHokKBitXNTKIJe7vPakD8HZZX08u++iEbQtF7jd7zmEK/OMW16xk7Tvg0EYe1f1QmELVP1oV8iZaRzwcGs1CVtOeK3Y8Ure5qFq6u9l9BwXd/NKsO767EOLudkTODXqvNaVFj+G5/ucnF11xMg7slo=,iv:2J8U/F0o0Iol8hSYq04tn2Vn6/PjT1DNTvySS+5BM98=,tag:q6sPlE9o6Tu6YUIfNCI0JQ==,type:str]
    version: 3.11.0
