apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:tWo6YRyaf5ArIeW1fzs3DU5o7a3YI7LGLUen4tGbMGpRw6UAOpe5T3TURPF215viCdIrLtc=,iv:SY1MDhVdTASOdNOFwJZHIwEKmqFQEiMj8rOvM8TL3/4=,tag:vdHKUhiR64tWuNjGdpp7cQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcXBXWjgrd1lRYmZUeUJU
            cEMrVGtOeVN1SkVLbHBBTDUxbHF1VEtuQTNVCk1HNThBakY4R0NFV2tWc3V6T2Jk
            Z1NnT0h3WVRGaE9GdnpPb0YwbmNIZkkKLS0tIGNNTG82TG5vbVhJbHJGMnlFMDVJ
            enFOYnJDZGVJdzlLd0pjTXZndjJIUU0KtTK+Uz5Dtl+jt5PdzpcfL/GVsHVocOwt
            tQEfNVvgWpLYmebQlqj0sqR7AL6dhBhbtHbIkuvdDn7Hprmi4gU0QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T01:42:02Z"
    mac: ENC[AES256_GCM,data:WvGUwTzVTTjae9BcOCczd/HaZ+ZnroB4X1CeCZnTNMOsAjDRwdOHzhnKbzM79p1AJy/KgF7axi/nnKmvbqU2yhKp9JwsXYdpAKnfiv/7gJfqjjzNBKWUlhA34MTY2Jm/MV6lRKhwTxEqEHyi7EjDatR4H91egjkLEtns5tnQ0o8=,iv:OraEcE+LaPQaibVgasZ6b+hVa9cZoIwIzcrSOyaqwOs=,tag:nE+ZrWpvnbe+XLQ2MFBzmA==,type:str]
    version: 3.13.3
