# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-exporter-secret
  namespace: external-observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: omada-exporter-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OMADA_USER
      remoteRef:
        key: niug5iu3ousuqyffxi5muv5miq/username
    - secretKey: OMADA_PASS
      remoteRef:
        key: niug5iu3ousuqyffxi5muv5miq/password
