apiVersion: v1
kind: Secret
metadata:
    name: omada-exporter-secret
    namespace: external-observability
type: Opaque
stringData:
    OMADA_USER: ENC[AES256_GCM,data:8mW9pqkVF+bX8M8DbVsK6pj1hDxfK1fIDED1PNL0FWYtJxL2BhRwqWo=,iv:enUQoP8tnWCh83EAbSvkQNP1b7dA3ODPcF50TvGNhaI=,tag:tGN39/oNNdJA++bH3kiEJA==,type:str]
    OMADA_PASS: ENC[AES256_GCM,data:KBHYTEJWK8M1yA58WyEJnS86wqI=,iv:0lhACznmkXxUOOSOwOrBPB9pn8MT1xFql4UqACSNoqA=,tag:AM7at9nj6Q4NHjRwMO+Peg==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVzc4anVRckdDdUVRNnBh
            UmtOVzhKYS9NcS9tMytKRWk2d3dlSXBSWERvCnpWT3AvemJrWXFDRC9mTS9FZmtw
            Q3NsM2taN040T2hOVklwbHhwdUhITjAKLS0tIDlucUdiUnNwRnVWYUVYTEU1b3Zu
            YUYvdGNWSVVBRkJRTzl5YjhKL1hwNzgK2GVELheUcRgGENIGBP4WA8ODXHEBxwCn
            IM5SGNJhZk0BZDt/RYg8GePx7LrzV+D7GCZhoi2H6Tj80gJVcfAnhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:42:06Z"
    mac: ENC[AES256_GCM,data:T9jz2I1dGbI0kJpNiGFXYmSgd012cn3Y0PKGW8/ItB3HeHRXsdUu/lCPfz8S9t43bXK7YmMazSQuh1WmR9kwN2EBqnVjdRyLQ0RYy5/3wUBSxVdblxmoauSjX7i1p6EgfXgTHxFb/6f4w/A1gCr8w9ZMtcRjueqjBS8jZMrSoX0=,iv:XCLLhtaPPzuoqFX37ukLlajHvx0RAOMM1fvEw8sijkw=,tag:jY11zZGZCmO7wNTozHezWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
