apiVersion: v1
kind: Secret
metadata:
    name: omada-exporter-secret
    namespace: external-observability
type: Opaque
stringData:
    OMADA_USER: ENC[AES256_GCM,data:cYkrU+puqlY=,iv:V0tTYPYJHP3VOlk7XTnqYwzZDdbdn4a45WSCoCVyn/4=,tag:wItXEY9tLUl3jCGyE41l1Q==,type:str]
    OMADA_PASS: ENC[AES256_GCM,data:EeR4/RfqmYlNi2irPzB6TmMOcmKe+RHI1uJEyDdvnburM1f3RQ==,iv:paUyVnRSvxQjNt8kWPqT2foxWWDZsuU8pg6kKHtDI5U=,tag:UjJ9unm6mjp4c0I3GNmT7A==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbnNBOTdCb2h0TG5Gd2Ft
            VWM0UC85VTkvbFIvdENWTmx6dnpONUREaGo0CmVBOThKaTJpWjBXbU53OWtwOHlM
            MTRHYUUzZXRxR3JVMjhmTlIzSXBXSmMKLS0tIGcyUnNmVVNReDJaUUZ3aCtFaDdB
            TW9JckdZTmhTY0gycEEyWTNyVGVTMUUKmzOOFH0g4KlMMvnzkA24quqabcenACAr
            Guktey4R9ydyLFsHtgylU+ccpZTh4A6Hz3Rs+K2OB754Vbo9BOBiKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T01:19:57Z"
    mac: ENC[AES256_GCM,data:9JkNaeDIloeVh26OFIa6ywTY2c1w86OIzV3yTvs0LAcyfTcfruV6mHDMJzqCz1yR59UEzXZlstMhvUK1FezM5QAvVYG+rtSiZlXeIUoQqyT0Ie40NGMHyQzuFpTFoxaHuer77CTz8D/epDy61ZDNMSCFFPMC6ZgZxo8Ycv7QMG4=,iv:xInRk9RF3ehkJJUWB0jqmF9pigmtHEWYJVJEJIzyOdQ=,tag:jzsOUqOrfqk+Ab0/7P4N1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
