apiVersion: v1
kind: Secret
metadata:
    name: omada-exporter-secret
    namespace: external-observability
type: Opaque
stringData:
    OMADA_USER: ENC[AES256_GCM,data:cYkrU+puqlY=,iv:V0tTYPYJHP3VOlk7XTnqYwzZDdbdn4a45WSCoCVyn/4=,tag:wItXEY9tLUl3jCGyE41l1Q==,type:str]
    OMADA_PASS: ENC[AES256_GCM,data:EeR4/RfqmYlNi2irPzB6TmMOcmKe+RHI1uJEyDdvnburM1f3RQ==,iv:paUyVnRSvxQjNt8kWPqT2foxWWDZsuU8pg6kKHtDI5U=,tag:UjJ9unm6mjp4c0I3GNmT7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMUE0SkZHZzNqMGhqOFJX
            aXhnbXB6OGFtN3J0d2twdDJnMkwxQlZpalN3Cm85TkRiYW94UkNkZFU1ZnRFSmZW
            K293OGk5VGYyV1ByZ3BQWE5DT0FCeTgKLS0tIENEcnRwTVY1TmJ3cDVWbmtEREdY
            UURWS29xQ0lnT0orZTJqcEIwamxnVFEKFWHQKbRHRRXmTEaazhM+HeYwEFSZ+V3M
            /Xo01F/EsQYQZeFj6hx4K398m52mm706YBMymKeroCtfTujU578ReQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-06T01:19:57Z"
    mac: ENC[AES256_GCM,data:9JkNaeDIloeVh26OFIa6ywTY2c1w86OIzV3yTvs0LAcyfTcfruV6mHDMJzqCz1yR59UEzXZlstMhvUK1FezM5QAvVYG+rtSiZlXeIUoQqyT0Ie40NGMHyQzuFpTFoxaHuer77CTz8D/epDy61ZDNMSCFFPMC6ZgZxo8Ycv7QMG4=,iv:xInRk9RF3ehkJJUWB0jqmF9pigmtHEWYJVJEJIzyOdQ=,tag:jzsOUqOrfqk+Ab0/7P4N1Q==,type:str]
    version: 3.12.2
