apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: production-ingress
  namespace: netbird
spec:
  dnsZoneRef:
    name: k3s.netbird.internal
  # renovate: datasource=docker depName=netbirdio/netbird registryUrl=https://ghcr.io
  image: ghcr.io/netbirdio/netbird:0.75.0
  workloadOverride:
    replicas: 0
    podTemplate:
      spec:
        containers:
          - name: netbird
            command:
              - /bin/sh
              - -ec
              - exec env NB_LAZY_CONN=off /usr/local/bin/netbird-entrypoint.sh
            env:
              - name: NB_DISABLE_UPDATE_SETTINGS
                value: "false"
