apiVersion: v1
kind: Secret
metadata:
    name: airtrail-db-secrets
    namespace: utils
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Up16a18qk/c=,iv:lbd0im56i23151YtrRqXxOyXiswBoLIPeCECK3HRgZY=,tag:8LiJ6CIQqcjuqmCdT89MLg==,type:str]
    password: ENC[AES256_GCM,data:l8AC8Oi0E9R3xUZLKFvauTsrMXp3zY2ChJNXpJo0/+StcI45VzzAYQuOZTF6F1NNVjuaQErmdG7nOu7exO1q6w==,iv:X7RZ7KJ583VEMPYl2xOH/dhj3aDzjOwh+D1iM1uUDcs=,tag:gUFSiFMEWz3enk1JKueLxw==,type:str]
    DB_URL: ENC[AES256_GCM,data:pzf6rydOj23KjzMdUMXsODAApgLgW4DyFDA0rfAi82AcA7ghPPm6W7S5q3R/DaAHjsUyC9B0oGq7O9S3ZvGSSdKZbjEzoU2UTh+wa6UGqmHTOOe5QFMuOq7kPKy9hIHOGyDEey6NVhQPHzjahGPACd0=,iv:QpKXl7/mbFpS8ILzgiDILW5VPQnGZfQsUbg+KLf9c9o=,tag:11i7MLwMhMSsalZJrMgb7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOE94b1NUc1dXVWw2OTQr
            SXM0L2JyMEEzVmdiMGQ5RGdodENzVzJhVzJRCmY1ZGh3Y1VsaXhPM1BWUFZpbmpY
            UDIycFM2YytpQjF1ajloeFFCQXlMcTgKLS0tIHIxR3ZxUW5EVTBmbTRsT2ZrL3Ax
            QWZDS2JmUTJiMTNiVGJXMDlHMnpVZ2cKMlTyhltY/LXYJWlgfNwOZMBrVFTprtvg
            SjtgnYADIqiIdEyBx7HjLpxyrSrLd38+0pyJC8ODA71giXv6fHtjmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T00:46:53Z"
    mac: ENC[AES256_GCM,data:iAgzjqhy+NWcpxuSjs+CGBVfeSjWJJJFVDXDfaEFca5XnaO78eRYkJoPw+rIm0/gLrb5s546OdkkmQclR37RXeq3VpRKmEZsXo5SOGDwaFcdMjqmdBX4moTkDaeywnc/x+kGuvz5VGI4dbvoibnCBEsun1XQX5NFNf219gEOLt4=,iv:psW3qWtA24M4LVy6PTCiJ2uvp0XQ7jjkLuJJO6HaTeg=,tag:PJ596sM3uQyjpIk3KdqsOA==,type:str]
    version: 3.13.2
