apiVersion: v1
kind: Secret
metadata:
    name: airtrail-oidc-secrets
    namespace: utils
type: Opaque
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:95AP2jX/wpePa4Gd3IPcWOSmGkO1a4RG8q2Ex7EyoWZKrMIG/BcKKio9Yz9Libd1vFkgS/nXhBVJYRmYT2dyrA==,iv:gCvRXVUN1A4vTxVYwsNFBXKkEKkeg3MvhyqY5cNdQfM=,tag:trzB4VSta8W+r2ssfwMV+A==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ap7S646raoeWNT2MTf/ON8xxV9yQXJa0t5duiO610ZPGPyjW/p/H1Tnu4mIRC0V64Y6aNK1T/V2/UZqjCnepKDejEFHJoBRSRkE29bzhYX+IFmPM1uP9/51Nk+ojXn4pW5vnYfSTiru2vkxhMuOGGD+PLnO1ONTq62HIYHinuAk=,iv:fYnU2SRdsPkVQVaAzoTflJzra5DhEVrOx+YgkpizQ/M=,tag:s2LO4te8KUmhWqUroh3AuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTJESy8wSHVVMVpHcDkv
            dHZQUXBmdkwrU0kwVDVnaHptUldzVlJWSUZVCjRnNjd3Y0w2Ty82MlJIdklsRHFW
            NWc2a3RpWXVhek5mbGFWNDZRVGFiMHcKLS0tIGJ2QVhPVVRBUHJ2Nll3NFQyWGdw
            RGdyTm5wSlk2dEhWYyt0Q1dnd0pITXMKztrOYQugYIfgwGzQX2HxyeqPDaya8nwp
            pVEvlmZH2ReS+eNV0yov/E8lwrArKX2C3WTVWTyHbvbabMZm0Slupg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T00:46:53Z"
    mac: ENC[AES256_GCM,data:alBm47CAPznM/Pg0be3j+mXD5xYs7QCNCcTyxxC0CQ5kCID2o2j/Pfc/MhA6zhI2UhV6jYo8WutCJzPqWTNBhSEreuzfQPx8mx9mhoDjc6q2z5XktGpRU/DX85LMf9J3j4cgDbwq/3svQ15CwXK+hDdBvbnAGMXB1ZzqNw/e33k=,iv:0c/780DuoYT7AJo13SqgrolErPAsOM1IQQqgwfSHQhY=,tag:uNUCWzbOLzRLbCgM/XEDvw==,type:str]
    version: 3.13.2
