apiVersion: v1
kind: Secret
metadata:
    name: airtrail-integration-secrets
    namespace: utils
type: Opaque
stringData:
    INTEGRATIONS_AERO_DATA_BOX_KEY: ENC[AES256_GCM,data:CFqaxBH+4if7DSoen0/zJHBXaPI8BUPotydeS3hODkh4CmHKYpP9Rkx0ldaaBfRdL7E=,iv:yRkuIsKxQs7eZQEFJgIlWk+BKmodFF9l9QOgU79tAWY=,tag:MGBgNo42bx2U4XmY7IhRmw==,type:str]
    INTEGRATIONS_OPEN_AIP_KEY: ENC[AES256_GCM,data:45bzkYAcf69tQUDxtWK67Wj0GBG5vn1UcuGCA95zOvY=,iv:pHy29Q4X+1wcvs9qtTcNE9AfP6MCpdDHevBM2sIKw2U=,tag:xomaVcHBwYh3w8SY+TyQgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVEgvUnNmbGlSdi9RTGcz
            V3Q3dE10Q1J0ODhFeTNlelR0T3BHbmdYMWpRCmlmT0ZrMysrblB2K3VKSzVYd1Vz
            OHNYQTF6U0F1ZEh3MWNXNEhaSkNVNncKLS0tIEJ6bzFhcklJcDkwMzkvSVp3RXNt
            dlByMUUvNGZtRUh1dHVzQitBdlBNY2MK7GhVqkOu5jpIdJGR9pzZ6RPzlum3RflN
            XGrV43ZXkdN+hZPm/7jd1Y73NMIDoBhhVoRlOkFQtqPuJ74zIHtPHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T22:25:24Z"
    mac: ENC[AES256_GCM,data:6sgDd/JZP4NUW9Fj2UR18GAkrNjaNbyTgtyRou9ZLdxd3gxddlgmF7IFBR5eTckv9lL1Ao7x5Oo+gQ5G5KxrGeyMQNKQUfem9pe1ZnyvNDvrEmySpVtXyU6ek1fX0M/FV7R+xbnT6XrFWRQib8Oz4ga88t3RD3MxPYWS29jlmmA=,iv:9W70wIZ7EWoW5ehRvLWfO4BCSj6uTO91GDsLlsZpfVo=,tag:Ybk5ZmhbWdO5ocvOjtRLMA==,type:str]
    version: 3.13.3
