apiVersion: v1
kind: Secret
metadata:
    name: airtrail-integration-secrets
    namespace: utils
type: Opaque
stringData:
    INTEGRATIONS_AERO_DATA_BOX_KEY: ENC[AES256_GCM,data:6JfXxSAi0GaziUK4Tf4rMWoV/eBynbC2fC12VepHzSkcLNNOls6M2kgSgfQjZSB5BAk=,iv:UIg6EZmXuEvuDOGogZRNuVlMlXZ3+rlATDAneVCGj/Y=,tag:3syRSuJgZPFs7InvQm8TgA==,type:str]
    INTEGRATIONS_OPEN_AIP_KEY: ENC[AES256_GCM,data:fhkH9x6EohZe1jISmmC/TLWfJdm6yRcb4fcZCKCjzl0=,iv:NepxQgBHHY1eQAAjpqTKWDhS30AZ4vDtY1awyDyQ3ZQ=,tag:Oo1KmM7kuQAUxZgL3CmqsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VWVnODlJcXBBUHlDb2dK
            Qkl5YVNlSHVVNEk0aHc5RmwyYzB1WGhsSUVBClVFUENYZ0RDTjhFeVBUTlN1NEFw
            TjdBWXZQNStydENYbVh6WlBscFBqWk0KLS0tIE9RL3pNcFk0QmNpRGtMMVFtZUFU
            VzVEUHVBK1l2SjEzc29odmJtWkpGY1kKG+KX1BSM7tM6+jOewNOikeHfT0rpXqV3
            VxbBD7fRldUGboRDkVsAvrp5rKN5lEOX1EbBZeM4M4q/7ntYN2TDvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T01:40:51Z"
    mac: ENC[AES256_GCM,data:99XIwzO9ZEq0K3fg0Cp8muSXLAl+LG5DFvCVgLjijQi5fO24BtyfpJ7FGwdjYyLyOX17icxwgLXl9+TUjvd0087QSX33piELWm2MSYgHtPK38d5FOWapKcHS8f10X4J6QEdRnlFwCY/1jS+/D4ILxBrs5qg6lplBd4EFX0UvfIk=,iv:UN3XNiKy6/D1xL78C47W4DNtPEpRrJbFeyavL3tP74s=,tag:n9yKT6eQ2msEMdHuLiQtlw==,type:str]
    version: 3.13.2
