# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airtrail-db-secrets
  namespace: utils
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: airtrail-db-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: srrqbnw3upbvmyjihprcreilmy/DB_USERNAME
    - secretKey: password
      remoteRef:
        key: srrqbnw3upbvmyjihprcreilmy/DB_PASSWORD
    - secretKey: DB_URL
      remoteRef:
        key: srrqbnw3upbvmyjihprcreilmy/DB_URL
