apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secrets
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pHLUHwwZQOlX,iv:mxif/e0cY1ukrtbK+6aLgH4ZHoJQVc1Pk1STrNNrB2c=,tag:CAe9A4r6hZPYoiuhd17R6g==,type:str]
    password: ENC[AES256_GCM,data:yb1Q6aoTsaV1PeU3DjaPyHqy9ThMQ1uAHh4v8i12RB+GuLTlvGYv2voqAmc=,iv:GcBbRbfXlkLq/O2B6TzDob51jUYYrJhaaYC7O5ypbsI=,tag:de9te2hXzebCCvqqhbvwXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNlpGSFZSMFU2bGtKNVpR
            b3J2UTJnSEVFdWpQV1M3d21hd1l6cXQrdDFNCk1xQ01ITzR0WncwSDlaUGtJb1lW
            dWwzTzVSNW5WdEVUb2lEZi9ZRjdoRWMKLS0tIGR4d1FYeXJYZ1ljbnlIbnByRGxL
            R1pjdm9McVh1TUg4YUowMlNiSGtaQ2cKctT9gjNwnaCavFD2VgDUS5lJSES4+GuX
            c6vi/qL86MKHXTfjj2kypgCX8xoeq12hJdsh3AQPCeoJqCuHq2QdZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-03-07T11:40:19Z"
    mac: ENC[AES256_GCM,data:8SCuPvRnQPuNJ23Vlpe/EYcSToaBl0yTvNCGy5vZTJsSpdxrfD/A7FyUO/7FZ3ehCJQZYzsXYZpmBAEUiScQeY9Q4B3LtnQUVnC7F+n1rwHF791EztCXtjM/J8GHRWzdqWWuhr+8jvfadBojqCNUFbgflZY38PZYB1s4N8Ji6Kk=,iv:n+JGZ+I2n+EDlpRR2FGlJ91t+onylA0sdngTMn4zLnU=,tag:gGGzIMsgM7mFBiUkzlK+Sw==,type:str]
    version: 3.12.1
