apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin-secrets
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:d8BguDPmN4v6,iv:fKPlEZSXn/XIHT9aeFuAKObaARYIsisF4rE+E1j+46A=,tag:z5+WISkaWlZLni63+xTdKQ==,type:str]
    password: ENC[AES256_GCM,data:gQSCz0IbG9VxvO/qM2mQnfEWF6ivlE8W3zZEMT6RkKQEJiPQUQU=,iv:k2pZwau880iaxIjBhtRAaf30+VeYIP82+1q7LXfwNAs=,tag:kAmtmhFzowQE6Qrxh12Wbw==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUjY5VmVWWHZDamFmOVp6
            MDRYczlvdDBUMnFwMWRScS9NTnQwa3pzMjFrCjdoSExhaXVPeFE4VW9MUHlhNXcz
            d0dUM2NObW5yc0ltelB1OUl3M3QwQUUKLS0tIDhvTG5VbytuSnE3azBvb2NaTHpl
            ZW9HVTNseEVGdlBDM3JEeUQzNGd5TlEKXiDQpCYcgfQpN0IUoXBXjeoGNkhbyrap
            Aj6DZmVLjzHisk6f9uPVmuTivVxgPEKbHSNWTTuuBjo3FaCNAmo0Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T11:52:37Z"
    mac: ENC[AES256_GCM,data:IlaoMEdZOA3R91mm/8hEMJh6HPs7fNYS5zonKsE9x+RGct8bo9M4DOy2uaamYgek0qeuxtDPyXGrDrQraFjbUnZCLg+ZMVM2a5bHl9A67umbl0/mM+xcTBcopJGSeXOQ3ZDKD2U+c/9dAcXxdfIIK5KXb6eYOI2qmUOGJmZmtUo=,iv:z8fdvF8LvVL+0r1v5qpCUkRckoVRerfU6uBVqJivP9Q=,tag:Iuyt19Iind5jYV0tB4onwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
