apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-mail-secrets
    namespace: nextcloud
type: Opaque
stringData:
    SMTP_NAME: ENC[AES256_GCM,data:2h7SIOewJSQqvDEBXMOQHqzsafflIy9DKwyNIRgnS6rOEA==,iv:2fCjt1Pu7oJJmCAhb4KpuKeJL2yP5sruWCTqu4r7cBM=,tag:AVPq2jgJ8mz+vvIuPzenog==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZoGhEWtVzxrIREITzPjTVQ==,iv:E78zSuPy79QgtP1tWlY7dcvF7Q14yrSYYbIZ4DsDSQw=,tag:SSWz8bi5R7TEeOOpyuIWHA==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYjIxUzdHV2RhUmhNMkwz
            VkhWQkQ1elgrZWZYcUJ0K1JZbFNyRFlVZ1dvCmMzMENIZVlieE5jd3pHOUNnVjYv
            cnl1b29lLzRtcXRteUl5R2cwUEtQQUkKLS0tIERXM1BsaytmaFQ4TGlFeDFxSGhS
            aHRlUGUyWHQxQWxMT2UrU3FTMkc4WUUKk/16WNKURamruh5kHLmBigtqTlm7fIxc
            XLfQN8PbZRfO8cF+duSjG9cYL/SQicJBlad4SIlUyS3T1pgKdpDxPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T12:11:28Z"
    mac: ENC[AES256_GCM,data:kHmnI91LfdNpGBtICW3GRNSuKMgUkHJhYKd8KdrIaeUuAfPjem+oUyKMDQpmfOG178/uX4aVr1083QKkdOz0T5ITuFmrqWTbYy3luvIPtP9UEePQ1a41lo6zUAIXv/lsDGfJpoQVlDBjAx44gQKs2Kg6xO+8Bp8IxHIC+X+o9Ow=,iv:E7F2CM/9U6wAu/1sKTWA4+TgX1Af5gfMAkCii/7ZHVA=,tag:Dk3+mFq2OQxBl3kbQMeRxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
