apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secrets
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pHLUHwwZQOlX,iv:mxif/e0cY1ukrtbK+6aLgH4ZHoJQVc1Pk1STrNNrB2c=,tag:CAe9A4r6hZPYoiuhd17R6g==,type:str]
    password: ENC[AES256_GCM,data:yb1Q6aoTsaV1PeU3DjaPyHqy9ThMQ1uAHh4v8i12RB+GuLTlvGYv2voqAmc=,iv:GcBbRbfXlkLq/O2B6TzDob51jUYYrJhaaYC7O5ypbsI=,tag:de9te2hXzebCCvqqhbvwXA==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a3drb1dPTTJqZnNMTWlJ
            ZVVHM0x3VXJEeFZZR1FxNVZDQVN0aWVBUG0wCjdVOUgwZ0hackVzbUNJcTVFTE5P
            QWpwTmZZTGhyWHNQcGNmUDBBSmgwMUUKLS0tIG9IUXJ6WUxqOTk1L3o3bUxnUjFJ
            cmFTdWVIdFFBMWxOdmJ6eWYzblVKQm8KUM55b15+E+NIdwYem6EtLrnx4IPZwmb/
            MwvBAjyG+DEj0QvyP99CnUaUDKFI7TLBFYb84u4UhOjD7cU1Sh+kjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T11:40:19Z"
    mac: ENC[AES256_GCM,data:8SCuPvRnQPuNJ23Vlpe/EYcSToaBl0yTvNCGy5vZTJsSpdxrfD/A7FyUO/7FZ3ehCJQZYzsXYZpmBAEUiScQeY9Q4B3LtnQUVnC7F+n1rwHF791EztCXtjM/J8GHRWzdqWWuhr+8jvfadBojqCNUFbgflZY38PZYB1s4N8Ji6Kk=,iv:n+JGZ+I2n+EDlpRR2FGlJ91t+onylA0sdngTMn4zLnU=,tag:gGGzIMsgM7mFBiUkzlK+Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
