---
lxc_hardening_user: "{{ ansible_user | default('root') }}"

lxc_hardening_sshd_settings:
  PermitRootLogin: "prohibit-password"
  PasswordAuthentication: "no"
  KbdInteractiveAuthentication: "no"
  ChallengeResponseAuthentication: "no"
  X11Forwarding: "no"

docker_install_enabled: true
docker_users: []

comfyui_model_download_profile_names:
  - qwen_image_lightning_bf16
  - qwen_image_edit_lightning_bf16
