apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  namespace: ai
data:
  librechat.yaml: |
    version: 1.3.11
    cache: true

    interface:
      endpointsMenu: true
      modelSelect: true
      parameters: true

    endpoints:
      custom:
        - name: LiteLLM
          apiKey: "$${LITELLM_API_KEY}"
          baseURL: "http://litellm-main:4000/v1"
          models:
            default:
              - chatgpt/gpt-5.5
              - chatgpt/gpt-5.4
              - chatgpt/gpt-5.4-mini
            fetch: true
          modelDisplayLabel: LiteLLM
