apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/bjw-s-defaults
  - ../../../../components/ingress/traefik-base

resources:
  - configmap.yaml
  - middleware-admin-oauth-sanitize.yaml
  - librechat-secrets.sops.yaml
  - librechat-vectordb-secrets.sops.yaml
  - helmrelease.yaml
