apiVersion: v1
kind: Secret
metadata:
    name: librechat-vectordb-secrets
    namespace: ai
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:09+vKU6ih/trI1rUgkkMz02DJTsh1nXLRznNE/KnlvgrRDCp73QCWnfrh/SiYxomNhconKfAcNIh82j3FHmMdw==,iv:OwC+an1WwJsHpla06USLrEKPtHDeUpuDcQ47uZE2Bqs=,tag:snH+MGgRgmdG5Xnu8z2wtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaGQ5U25HM21FbHNUdmFn
            Y2tSL0xBaGFrRWxzKzlVa1R1eVFRV0xxa1NZClR6SmUxT0VlV0Y5Z0tHME1Od3BE
            d0J6NENZUmx4TGRVM2J5V3lhN0tML3MKLS0tIEhmMlVLckR4ZlE2TzdySUVJV0d5
            K1NRSkp1U2tMUGRFZS9ldXFZbHAyN2cKrGYXRoGMOUIExj3cXmcOl+3Btdd8hOZA
            EEns+McwXpsgZN/d2+tj1vCsaNHveAdOhFN4/54nM9NbQVvW1qjvMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T01:48:09Z"
    mac: ENC[AES256_GCM,data:RxZJw5395tfviFuwi/NOQaAPZp6f08VYpUixM+rLqTnAPWyTwsku8qXOvMtASrly3QoTw2SSU0k2E3oBgsawJ6tLQ0CkbEy33U3KxQN+lt25jQR/OoooA7PsvmiToVFNWElsZ9EYTdE6dXdE16uy+k8b4I+r2NeXR5FXO7KodDE=,iv:9mp1fVC3vfZej2ub3BzRjZ20qJ1iQJZe3wcttUxM4i0=,tag:fBQu+5GmoFrpc15pk5EW/A==,type:str]
    version: 3.13.1
