apiVersion: v1
kind: Secret
metadata:
    name: librechat-secrets
    namespace: ai
type: Opaque
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:u1pMLOLUiCg2zRwgv7BhN+jXWAPwrFZWISrxL2adIzvAkZMBcRN/vwa5q8HNrWrNFO/xPdajkpZXlNRgtPX97Q==,iv:mzoWQSU3Tp80WNXyfjpP5cSy34trmetf09KsbC5rri4=,tag:mCA8Xibw2Li2TzuHtaZQYw==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:wCxwxTdBIFnoICPWPaUv+hRxb76eMK0BaEDhHOZrs7Y=,iv:/LUfQSXBN5/3sufyjtysIbMPCL9LQeiulzc3K5RIOTw=,tag:4EDXKdsTLpywGBSMdzPB0w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:CrDD/1FQ3KIThFpTQ4hSlVoYtzzjL47TDuFIdErVtdLp8NHkN51Y9CKcZdhPLDK/fFgKbLatKXf9kUWLrbKCeQ==,iv:wEQhBOhcStCFaLcJW/WeMsnzuoJ2RS1DXsj6JPQours=,tag:3TNThHfje9iBo1P/Wgsmdw==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:nPMPrhEBIJkvunCCKXXhGDDgYYC09dy0nleY0nHOUSwS7O9/lbrnHWxgw67x2PkSLf0gNX30xcHzL02wAnN6Wg==,iv:UV2CBaXdEnnpESkZGSSbhDgXd078IyK+JJTGE5aZXhw=,tag:GzMH5iy1MkcRIrqRJRuirw==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:n0c5g30Gqbh0Ln9wjfJPvwgC8fDEeHq5sITJ5VpeyFIqkSNuTgm0jq+HstLnnjlnO781Blk/UXPtSxef7n9lrw==,iv:tgYBttxd01k+u26psFK9N9s5VdUdeK8q+2HDM90s2wE=,tag:Z4+jLpZTlv3A6jbkO2/PXw==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:DwcbWsoyADveHtS3KvADbev5w0gPumEOJqVuUiUjw5Hj/s5mSBF00Cvc7HuHi+h9uw/tt1aaY69E5C/CxYtcOA==,iv:QyMMskBAVJ+KrfNQSibURdr0rr1/dWdDGYaXcOtRXkA=,tag:KqMr2tPaf43HNJZ9b+TWIA==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:vi7koqI9liRphK7He3RpT32W7P0ulBbl6Q==,iv:tjq0IZvijTGssJsjN5K+y9qM4b74W7vLYqZ1vrPafnI=,tag:2Kngbf3s5BOTixEP2Eal5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcFl4dW5UOVowWWppcGF3
            bXF2cVNGSit3Q1NiNnNBakpuOTNvMHlKVkNvCkl2MEkxQ0pKZ1BuWnVUa0FwNVFH
            SGJrQ04zdG1wUkUxT3BiM2FwVUxlZk0KLS0tIFVsMmVzV2R1WXZJend4TFFEUHA2
            ek14aFgrOTU0eHV0L2xrYjF2U3hPRHcKeLO9iXbSkrlN1fdz4UqRzyPnswCWGfg7
            rAuheo7JsQnjSGU7ZFiipcqMeDT8W6usbqVHTHBOV8tXmtAJ8ImVJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T02:07:01Z"
    mac: ENC[AES256_GCM,data:prBsjomUp5EmD6xI31Key0EBocXIilKHKCT34Be90TdBUxRZQRc+ZaALjTLCQ+X5vyr5sN4CuOMDvlOiVHjycirmRv1ykgTAlp/WIXf+4IEhzsCggl1hwwAnXyYt9lMUSSOn8zx88ppAi55i0VDJduspBVk/pG6Oex4SI5yDEtU=,iv:+FfKMIsI7K78V3A690l+dMqk0qw1F07rMTZzGR43JEg=,tag:/AwNbmrylWtz8dSzf7xlIw==,type:str]
    version: 3.13.1
