apiVersion: v1
kind: Secret
metadata:
    name: librechat-vectordb-secrets
    namespace: ai
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:09+vKU6ih/trI1rUgkkMz02DJTsh1nXLRznNE/KnlvgrRDCp73QCWnfrh/SiYxomNhconKfAcNIh82j3FHmMdw==,iv:OwC+an1WwJsHpla06USLrEKPtHDeUpuDcQ47uZE2Bqs=,tag:snH+MGgRgmdG5Xnu8z2wtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3VTUnQ4dVMzU0JIc01F
            NUEwR0RaM2ZHMW9vaDE0M09xSTV3TEtnbUI0ClBMUDJpSHZzaHFoMEFnY0Q1RGhs
            T1JKaXE5cmVTalNmcnVyTk1nYXVjK1EKLS0tIHRLM29TZEt6aWR0cG11ZlM5OGpa
            SjBzNTBxVlZhWGhHc21aRVdDL2lPblEKK2rv9jBy8r4PettYHL6imo4d4/pdAjyy
            FD8PBlXv4PrJPKK+GNypb/TQYYtMtVMHT9ceeLfO0UjY6fW+iT/ULg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T01:48:09Z"
    mac: ENC[AES256_GCM,data:RxZJw5395tfviFuwi/NOQaAPZp6f08VYpUixM+rLqTnAPWyTwsku8qXOvMtASrly3QoTw2SSU0k2E3oBgsawJ6tLQ0CkbEy33U3KxQN+lt25jQR/OoooA7PsvmiToVFNWElsZ9EYTdE6dXdE16uy+k8b4I+r2NeXR5FXO7KodDE=,iv:9mp1fVC3vfZej2ub3BzRjZ20qJ1iQJZe3wcttUxM4i0=,tag:fBQu+5GmoFrpc15pk5EW/A==,type:str]
    version: 3.13.1
