apiVersion: v1
kind: Secret
metadata:
    name: scrob-db-secrets
    namespace: media
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:T7vJfhM=,iv:Y7CPGOfq5qVCJ1EB+v4QBWg0sbD7/zqDLrgBjARrCf8=,tag:AZQ2/wtqE8CeAKdjQjaAjg==,type:str]
    password: ENC[AES256_GCM,data:i78jeb7Y9tqTQSPQ4N4uOp75UXfyuBQhJgXzp+tUOs1PSXYffvT+pAALKXN0tshZGM+yUtDVQTe0ddrIfY38dQ==,iv:4CvOyne4SZhC5tupoKLnyTRLFT+mcl2dEF3xZq30wx8=,tag:p2zZ6uOI2GBaG3lgmbcyOQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:qByxuAZf6ak3fVX3T4WupkgOfAwTjnayZNUKjuySmWNrSXppQz5CmAPAVqzC+E1h2L+X3IbzfsvKM6RbfTYg4AO50zmfkcd8F1zEgu0r3uTlA7GD0VdDaFujUVnEIlNdngBTyaoGZTkBchC0fhcqlYp7QYPZpu7Ka+bDUETweGpGI8t60V6oZYoK,iv:6CjTzmeDc/vYn23ZW+5xM6PBO1lHAWUsygk5ljxcUzU=,tag:hyqB8CZoOFrbgJa+BZwSDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeEVRR0JoM3ZabFBlajM0
            VkZzeTRYajREL3Q1UVppMnNJYlY3UzBiTVdRCmV1TjAxWVZWV2pyVnQ5N1QyRndI
            eWYrdHpDWnQzRzJEMlFrWE5Qb1A5M2sKLS0tIDEyckZrd01jTkpvMlp2K0t1bERW
            K0pHeWxJcjZLMUF4RHNXYlB4Y0Y4TFkK45rXAUqhzvTaxgiCIF/diPR8pQVs7bm3
            y5LmaQYgzjrbTpeQ0mzdXht/7/UG5WI9MB+I3Om7ivaeCPsiHf8c+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T10:56:48Z"
    mac: ENC[AES256_GCM,data:cfkI5/2uqniWjQyqObwQ40UYAH3PUJGwjckdqZfA7HU4EJOrRsvtBiMyroFB0XiAC0UhO47w0m9Y5FghxK2W4+aKHzhlYylZYE7DJ9CUpFFKD9h9ppio50n8R54pL06c34CkAF03WIFH/DJprGn9Ygggo0h87yHTnBmgpG4sVDE=,iv:0SUr3NJC8E+bQw9Rh3SbgiTcxOExOV4L99st5GAuOFc=,tag:XpL9CCSHHeAw3ZQXsz/MiQ==,type:str]
    version: 3.13.3
