apiVersion: v1
kind: Secret
metadata:
    name: scrob-secrets
    namespace: media
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ul8fUAq0AxwOaZBFp/GH6AuACBv284XsbHrYHO6wfOV0Fpe32PakbRt36iMyhpnJ6bz9fHWwuV/pjVooktz3vPtp+PNpc3DzvHBKDlpYwkyev+FDf+RJZSKmEi7V6S3J/dhe2RcNMFsJnhnEF33/l3T1C88L4pRLWTPnJU+F1gU=,iv:1bLdE6U2ZUhI84cFrfNJNriUPowAjlfHbV9RD0KSee4=,tag:1ffUtcB730jEjWGFq2ThCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDVEY3NEbkhlNjFMczlZ
            YVdrYW43dUlTQ0ZzTzhxODAyaCs1Z3VCYkJNCnBiSEtDcmRmUkNpQ1hCNVNxNUFM
            WFM5WnFvWnFhcERkRFBtYXphcmF1WGcKLS0tIFRMUFdOQm96R2F1Tit6eUxIU1Fz
            Q2VDSFYvdXJCcmg1WHE3bEpkODBxSFUK5RNm/AMI4f+FoZfbBDfb+RcJr4H8wP1M
            AXSkqsiGOtEBZ2nO8b+UXqE3536r9e3fE5lex033LmxkSvWwoWDprQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T15:51:47Z"
    mac: ENC[AES256_GCM,data:Yb5wWWurK6PhczDgRTVLKLQACnmPEoznN3xoTzhp7N4j+d4E8LBk++TyQwxGV6i0xhsjXpBdRCZ8BwEl28WfFlDPa+ZwzyncxPVHritOjG3CC9HI/HXLdu0BAX8diHmge7WG6zEVG+a+ioJhEm3wbGwSgCKzuXqkz7sdlxplQPM=,iv:+5FUlkd9PegWDsBw7wdtgk+yQbpbWaTYJ9jSfWF077U=,tag:PhMwEQJKJwEmphDufiSgpg==,type:str]
    version: 3.13.3
