apiVersion: v1
kind: Secret
metadata:
    name: scrob-db-secrets
    namespace: media
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:S2+KnQU=,iv:K17vJZexm1SK8F2Fbj8BC9eDU+hDngxnwIebt0rTi0I=,tag:efKZq+9r7bDgKxrexaiXbg==,type:str]
    password: ENC[AES256_GCM,data:Ewq6eI3gZvRX2F0gwJOyGP8b9WZRUmCQVnTiSYK+CYS128TsaZu/3dOEaDnfxBbUVHTEzFhauoKMkwpFrUTo+Q==,iv:cGEu9B52TU/mHhB4SBr4Nt09oYbWvoniS8PVydIuh6Y=,tag:7yTWQ/6LAzhlA27ExC52mg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Z79SxdkMfDRRo9kQzKUVbF4qqwF1HyESCxvVbmKYqqUx19TQo2MCRxuiaKTcUR/iFs3nLz3rAcP/PffC1j+srS84Imm4GGlWE/oIaIwg3AVuYeMEGnzcFIe0HKNp319x1owkgYttPMsS4nOQd/V7BGWQzL7yhpyzRye7mF5dPCxyPA==,iv:pqmgsWk18xYTcsEkuLKUcVc2ONs8RJ1ZgCU5lcSFhT8=,tag:ZIFIDyYE5MFaIqYINwgyLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMmJ5T3dIeG5HNnAyaUEr
            WTYyc3dHU3dYcjJhbmFCeGtPanpJK2VJeEJvCmZDeHRNZFV4TEh5RFlBdS9Vd0dV
            T1J6dGNya0VYL2QvOU5TNXlxaVRpUjAKLS0tIG5qU0Fjb1c0ekYzS2hIUmhxWDh1
            ajU2dEtkMWsrczJkQlJPTmxCR2N6UjgK/9Y2iU03KD5zGfghCJSqE/Op30y7S1XP
            29prwzt1G/k//xBVQUGOXVnGGCWCx1QG02GOodApxt12hYo22BG7Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T15:51:47Z"
    mac: ENC[AES256_GCM,data:IRcUB02Alae5dQhfwCi3THLNDkJ2Ms0zHcSrfMlKEexZd0Xrf66sWCBkwZywUihqg9qnDXPjJZ0txWROW6qZIXKwugeaArzD+IRc7QQCQ4t/VqAxaRC+1YZQyhlkWmFkoMLCTMPFoBxkXSysJRiOSFP+p8dAZeQjffrX44gEB7s=,iv:4elwWVKrY2UVUVwz+UT9SxZ7pdPL4D5hATJbfQ8jp1w=,tag:CE0gV8sXH/OYssgv2bNs9Q==,type:str]
    version: 3.13.3
