---
# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.
# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.
#
# This file defines the K3s nodes and assigns them to the k3s_nodes group.

all:
  children:
    k3s_nodes:
      hosts:
%{ for node in nodes ~}
        ${node.name}:
          ansible_host: ${node.ip}
          ansible_user: "ubuntu"
          ansible_port: 22
%{ endfor ~}
