apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter-secret
    namespace: media
type: Opaque
stringData:
    JELLYFIN_ADDRESS: ENC[AES256_GCM,data:mwkJR6UKGY8+JVejc2tfjak3KPY7k0dqdHiaaDPIoYZoYPkJh7w/RELBJnE=,iv:FQdOceqIdFnWbj6IiwjaQz8NQmrvniIcg9QKl0Ls4aA=,tag:azUGwqLplg2LMghy0ymswA==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:qyjzC/Hv5uvvV9v/euYmJ7Mea2FzlOAzCOGWwpPkGdk=,iv:tYHT+1BHrAcsn9B48hkRBrzi/UTbX0wH501mOyJTdUw=,tag:fCgYrZrRTPcPwyRsQESqGg==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZngvMGNPcFpodS9ZbjQy
            TDlkdnJjVVlzaDhESitEd3FDOEQ4bVhGaXpFCnJHTUlhdFJzdjhad0FhRVozYU90
            elNObG8rUUFKeitZZFVUUDlFRGUybW8KLS0tIG9oWFB2eHZ6UVFVWklhM1h4YzZI
            cEE1UHl3KzRpMU1kZDNUQkpVTzd1NEkK3ZVGqShacoNYMZBqq3NFpRGOECEV0Xac
            LqDa/ZH5HS5o/+zOny2m/XdUUjyQ4OYxuAvAhxDbweMoNwp+PNeKhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:42:24Z"
    mac: ENC[AES256_GCM,data:BWFYzAaRXlRRtltwFohCKPkPQmBTv5B4+OH58qkYV77EDQ37o/WQ348T4jUWY4pfdACx1DcSZrbWFtZ1E2VdW5D/9UNG4NWDXmFMOjdHrGmx4nrvHfp4WwEyVHLwmDMHpsnZ8WkqdV8RyTUwcqpsaz2zAa26hJDtREYiFoKVZ6w=,iv:/YeZ1uwHFvm+9pRO/krlkiLVxzOzZfLW3ihOKengBV4=,tag:rHSR/rGSMBeVFM3x/FC7RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
