apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter-secret
    namespace: media
type: Opaque
stringData:
    JELLYFIN_ADDRESS: ENC[AES256_GCM,data:mwkJR6UKGY8+JVejc2tfjak3KPY7k0dqdHiaaDPIoYZoYPkJh7w/RELBJnE=,iv:FQdOceqIdFnWbj6IiwjaQz8NQmrvniIcg9QKl0Ls4aA=,tag:azUGwqLplg2LMghy0ymswA==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:qyjzC/Hv5uvvV9v/euYmJ7Mea2FzlOAzCOGWwpPkGdk=,iv:tYHT+1BHrAcsn9B48hkRBrzi/UTbX0wH501mOyJTdUw=,tag:fCgYrZrRTPcPwyRsQESqGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckhPbEpVWUFnRmR1S05B
            NTNkWDU5TGJHbnhOL204RXE3VHJML0JlRm5VCkdyQVhjVE5FU0hsb1cvR2gwUXdz
            UzVWaU5Zb1VKY3ZjSnBaRURLa0owd1UKLS0tIGJ5NW5vSC9reWFrWHJqRVFLR0s0
            OUk0OXRGRS9ReHA1eUd3ZmtOS2I5akkKvY6hIGgbJdT6Ek6L2gE0t5/0esja7ERW
            G8u1Vi0EDQR5OvwTli6ECbnmz0YqYGiYOR15SE586VPR1RjsML8JHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-04T12:42:24Z"
    mac: ENC[AES256_GCM,data:BWFYzAaRXlRRtltwFohCKPkPQmBTv5B4+OH58qkYV77EDQ37o/WQ348T4jUWY4pfdACx1DcSZrbWFtZ1E2VdW5D/9UNG4NWDXmFMOjdHrGmx4nrvHfp4WwEyVHLwmDMHpsnZ8WkqdV8RyTUwcqpsaz2zAa26hJDtREYiFoKVZ6w=,iv:/YeZ1uwHFvm+9pRO/krlkiLVxzOzZfLW3ihOKengBV4=,tag:rHSR/rGSMBeVFM3x/FC7RA==,type:str]
    version: 3.12.2
