apiVersion: v1
kind: Secret
metadata:
    name: tautulli-secrets
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:EcZWak2+pLDp9swQm1nOhoeNq8Y=,iv:EIdajiD+J0WHe5WLwo3MBTvXAh9/DUjGxI6oIuYZpUA=,tag:niwGCTJ9013A6n8nJXn2Uw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:ChfFDBDiGzePHiHgpQbewghNR1P6/sUrei69JyyZI1g=,iv:SMZpsrK5nQ8UdSqNYn+VjfvpmWFI97kqxyS6PK/GaRw=,tag:fw+VqARiTDhpV640zI7nlQ==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVWZiYmhKN3dlSXhCRDBh
            ZmRPTHNNbW5vWjVCU0YrQ3FrdGg3b0RUVEhrCjhIeis5SlBuRjJpY0Z1MHVqM05j
            MFdMM2d5NE1RZ0F4Q0pLMnAwZktpdGcKLS0tIFl0d1NIdVVXeFpYTWlId3piekZO
            Z0NqU3BOWmIvNUhLRVNXRFhsTy9FaG8KVPjfi7hLNfJmwSZqqg8ANjeZlv5+/OPa
            pgFJXCL2PMS3imRq3cm/N07jniAmtmm75EWS8h0JjyGv6+h1FomHWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T13:20:33Z"
    mac: ENC[AES256_GCM,data:kizowD8MfVnBcyTsUwzrsXzYXMoRTDOhMBHtUkmz1mRhvkW8O8TmbvOfgKTUzPo5F5McTUQADF2RZ98prVKY044nCtE61VlrURFqpsEc1G4cMH11f0nly9xWbfMCYgXjEf0OdgIE2MuMb0LeRPExMMf96lkok5iKphVAx1BaEN4=,iv:+qVEX6cHIN6Waw5hyl9BmSPXAVWoBnStWfJ53Q4U0Mk=,tag:lLuwNE0kS4+Ck8ap1ltxmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
