apiVersion: v1
kind: Secret
metadata:
    name: tautulli-secrets
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:EcZWak2+pLDp9swQm1nOhoeNq8Y=,iv:EIdajiD+J0WHe5WLwo3MBTvXAh9/DUjGxI6oIuYZpUA=,tag:niwGCTJ9013A6n8nJXn2Uw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:ChfFDBDiGzePHiHgpQbewghNR1P6/sUrei69JyyZI1g=,iv:SMZpsrK5nQ8UdSqNYn+VjfvpmWFI97kqxyS6PK/GaRw=,tag:fw+VqARiTDhpV640zI7nlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRWx5b0ZKT20vNFh6WTAx
            QUV2OWRlTm9zUHBoUnpya2FsNjhSQ2hjNFhvCkpkeXMxZGEySnhsRVNRWmwxaXAw
            L3ZlaWM2UGg2aXFLREpBZ2tRTGtvUmcKLS0tIHF1YTJDWGUyTGNIWFRoVU10a00z
            bUE1NmxGMG45dzFHUThDYzErZkxJL3cKF/6Dl6mEtDoxqKFRDoJDQtTM3VT9f0n8
            FGDVVSTFdU4FApcIC//paaFpRxA1Z+5GPH9Y8Uoy/zCvLjrrHxoEjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-11T13:20:33Z"
    mac: ENC[AES256_GCM,data:kizowD8MfVnBcyTsUwzrsXzYXMoRTDOhMBHtUkmz1mRhvkW8O8TmbvOfgKTUzPo5F5McTUQADF2RZ98prVKY044nCtE61VlrURFqpsEc1G4cMH11f0nly9xWbfMCYgXjEf0OdgIE2MuMb0LeRPExMMf96lkok5iKphVAx1BaEN4=,iv:+qVEX6cHIN6Waw5hyl9BmSPXAVWoBnStWfJ53Q4U0Mk=,tag:lLuwNE0kS4+Ck8ap1ltxmQ==,type:str]
    version: 3.12.2
