apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:8BpHkb9lCpJg,iv:zR6MhqDwcckJLhDjW6Zqwho49mEsS0K98CqLfEBFf6U=,tag:k9jzkUbRLLeo3aKiHxkPZw==,type:str]
    admin-password: ENC[AES256_GCM,data:eYCcCSJDyyrtckzls5BJrALv0bCwzWtAUr5EjREorQwDowHxd1H+90ydz0MaWXcW6s1V,iv:wYL0AmhlNwWxHboswHoBnJ2wTw5f8LzhDwIKrui4AvI=,tag:JfI5OhCCoy4O8xKzRu8eaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQXdjakVybUREUTdqLzBr
            eVdPSnl0WVNjVXN0M2ZYTHEzRlFwZDEzRkJNCmZoWWxIUUNhb3VrVzdJRHJzbE10
            enVaVkMvOFFsc25KNEUzVVhZVWpMNVUKLS0tIDdjWmxqazE0aldNNlV0Sk55WFMz
            Q0ZjeTFYb1FZYi9hUEpRdVhnMFIrRkEKZlU5b5GSkJ1d5+7pHG9GTLAryuIdK5G8
            JQW/yDx9t5me7SbYC32it44BVABO1YJbbuPVPxV4PwOzXQuxX7I7aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-23T21:06:56Z"
    mac: ENC[AES256_GCM,data:rC+9GjdVseSpHnukqKxCKWnq2bRL0rIzhOH7230gysPkGGn3OFZKIS/JzRmCNE0masl2Mw4AM4LjJ6nDttI6RmIRMH1d+H/BHG9MsxQpU4RM+K2ew+SUCW95VqMwOPm/fFmNWR0G7WoWcRL6ywA1JHthWQS4h9YUzmXodljJHfE=,iv:qH9YtkbIooIuIi92uM5keLwnSwq/xkUrR6nPb8Dq/2I=,tag:fbN3bbqChmZFz1wvT4taBA==,type:str]
    version: 3.11.0
