apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: authentik-rate-limit
      - name: default-headers
      - name: crowdsec-bouncer
        namespace: crowdsec
