apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: automation
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:Wd/ArwM4g8iBAbZ6urFjHwq1ZKanS6P9deuDuMg5ICwbBsOv0x9D0k+zq9+ucQBbucOJx9N3nhw=,iv:hfCA5Ktre7KSbbrFHeptY7Vg6GbR/tpB5v0q7+v0J6I=,tag:4RmJNw/opD81RY8ijgcfMw==,type:str]
    HERMES_WEBHOOK_SECRET: ENC[AES256_GCM,data:0x3H1JUFzzhbF+A1Rxxjz9VrYf6dQj6htT7UBboy0ow=,iv:8V/9jv2D+8VSxcnyA3KfXq6v6pUjBC2b0fpDwbU9b0Y=,tag:Q7E67rjH54ryT9e/tJpsMA==,type:str]
    N8N_INSTANCE_AI_MODEL_API_KEY: ENC[AES256_GCM,data:YQ62IhUpZ+YdDx0XjlWBS27+AZYkM+61ew==,iv:qp7oHt4l80OBz3ommq+gfCR89kOBCEAMHLzPscL9eBU=,tag:78TZzXROaPlWHhplxhFoFQ==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:ROpZJ2YldyjRqX1Ej/0TX83AjIzsASy/Ntv1m3u2cwBcbbQ=,iv:vngl5BAThpJqWns1Cow3YAJ/IZb5qxaKlVxksA8/fD8=,tag:2waWdMlv3GbaxKib+aHDjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0l4VUdNYnQxZFlzeTRG
            eGFLSmFnZmUxNnpLWjh5R1ZpMk9rNmZZelNRCnlXMnhQTFd0S24rQ2tNWE9nR0J4
            cHhRWGdydVJKbUxsNkZzL1pwZy8vU2sKLS0tIHF6a0dzbWdVZ0o1VVV2dzBvMDM4
            TUJYeDZmbEJFZlpmOFlhbi96WWlvWnMKY9KbC45hGLM0yJETbC0frpK11xaqz7BF
            nwRMsoJhU5i743GF8dASbAleIY7Ju9ToG40ftnziJKdLpnECX/XouA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:19:21Z"
    mac: ENC[AES256_GCM,data:DABIuE8rHRfZdhtekbEbTrbFJCx/jcbGNXnTVZ20XlmjcErkwK8qxYPUMsGGNBfII5GRHymyb17LYgsgUNDRXY+O3eP3E2CtOmShqSXv+Hj3RWLwjYtyfVZc74RXLTG0bf9eEcbKpapIxcUirsfEzxMkNyqawB0/hrvvAMFj9Vs=,iv:8sG+czhiPF6o5B7BY00NUGN8+P2GBmhmJ+MwyKXDjXA=,tag:0TbfgYtA+ElCl4th1XBNSA==,type:str]
    version: 3.13.3
