apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: automation
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gV+x,iv:Fp9ltzCbjRcmeAh47DqQ0ReYHeVufuKFUf4FgbDQ0g0=,tag:0JdjOhEbdQdPvn7ttiWx6g==,type:str]
    password: ENC[AES256_GCM,data:IGAGCc3hkWvYDTtXNgTBpxT22RMRAnr6y3QhKgRCZSRh7Fbe1JidD2P4a61pTcs=,iv:2mR7PBQgB+dQ6uXhFQlZLDYidTLrtVelkpE6Rp5ZTW0=,tag:DJltbidPwA7RWU3nfH4Hjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWk1KT09kYzEzeHVuVXVT
            YThJSFlaWTNRbW5ocWlaN3Q3VGRyUUkyZFhnCkJJWWJnRHhLcnBMZTFOeW5MakZn
            dVUyWkhZWVBzY1Z3NzU2QVVYZ1AvK1UKLS0tIHZrelV2elhZWjJnKzdzN1AyUDEw
            NU11azE1ZXdYZzFmNlpITXhIMEQwT0kK8+6SFqoX9oRi/v9vKqEsrZKxe/pD51bg
            K2hPg3AoxGQNChPI7VzAV2K8PiV+9lOtyd0BO+RUG6OEk3898i1C5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-22T01:25:19Z"
    mac: ENC[AES256_GCM,data:lHmEDy5+vjaaonpVYGu8nrlTaP95Myz6KtGBpGnrJU/ol3+84jesXz66igWgcP6VxSjDDQHAdDLvRLJvK7U94pdK1ync/xk+kpq+zVR1MiA5NQw++uawQ+eQzsHgZQeCF9+w7XgLjHL+o4Yh4e/jhbMZ21GL7Vau+TTL+VnF3oU=,iv:h5BIMITLxsj1Kic0Ta1ITyq3By53GzKcGbO/uFxFS4w=,tag:o1hidKDNx18ZrsZ3kGrGKA==,type:str]
    version: 3.11.0
