apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: automation
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:urPBBEDKOmLsRHIZ49YFISzJ0FSokSCW4OLoqsVaLKA0BEmchAVxyejFGP2DvMFcHgGYXxtBLgg=,iv:RkyzkYrhUDT9xz6YrUbo3ZnVvIXzmijJ0mRkfBijr38=,tag:uowCrLyYj9V1iDkOBw/cow==,type:str]
    HERMES_WEBHOOK_SECRET: ENC[AES256_GCM,data:k9zhJ5zmifS9REe9C6PzNzg0GdG4y5LCzrt/1TqtWiU=,iv:vq+TxHeB1P45wHaeJll5Kxc0Z8LvlrYUb7FnU9GdEXM=,tag:V1f4ZI+Q0Xi/NLQbWTFKQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWJOa3crMU9wdHRJa1o2
            SnJaSDdDYXBmSFJKYXdrMHlCMXVaUHorTEdBClJkUk9tRzZ4L1NmUWlyc2dYcm41
            ZGpKRTgxUURKQ29aN1hkNEdGVUwzbHMKLS0tIEd6Z1ByWFgyNGxMS2VsWDNTaDNy
            L29VaGVIYStPa0ZmS1RaN096YjN2dmsKq/I7+WMFGw6L6I3xAXU7EyolZY8Q+gK5
            aEMHmwZARQI98LanukIARipAb1VoaVvle0SBoyw+yOf1oHu//RIRhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T13:21:58Z"
    mac: ENC[AES256_GCM,data:TMkrDTRNn+798L3/QwRYZncK4JscE0HB+lSTWq/8EG84k3EDmPHD1eZBpgy8QFbAjL50n1Tg+lFCAukuZFpWIf1ptTOuSn7J4DAlOYUGF9Mhr+n2NVCr6Osk6J2fcGjRnBIFhXMqVx1/Nhpuf5wFH2B4XxEJlxIi7ts1UCw4V1s=,iv:/7JOQVg0hBavmj87h4JQ8JmdQprZwGHuYXW6uhsIlq4=,tag:eXNnUD0PK5m9FWZv/38ZnA==,type:str]
    version: 3.13.3
