apiVersion: v1
kind: Secret
metadata:
    name: n8n-sandbox-secrets
    namespace: automation
type: Opaque
stringData:
    N8N_SANDBOX_SERVICE_API_KEY: ENC[AES256_GCM,data:aA9ooarul/q1gXunBuyOqwSiQfwB/yAG/zK+/Aft7nmIZiFI0/NcBYLJCFGroT3A0B3XvgHnNxxYnA8AN3n2wg==,iv:voSGDLgMDqg3ffh5L78bSX/E5v1CtA7JTiA78O58JNM=,tag:YIVU606v25c705puAtXD2Q==,type:str]
    SANDBOX_API_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:CkS2cCgLsKjaEhyniJvmpj9pZlidTJKj5P2/Y1DXihsukJLk4zzCWDU1kxjM/stGesuxfgrvvHutajaJWKy6kQ==,iv:gNNVpRjH0j+Hg/u5maIuMHg7anbjrS8d/bAo4qgE/8w=,tag:Sk4xtaJOOm0a/rk4xPoGHQ==,type:str]
    SANDBOX_API_RUNNER_API_KEY: ENC[AES256_GCM,data:YIVYAdMkMqgSfNECmSWiQofHVNPJFq/H8P3nwrPk/vtiJch0oPnGmxKmb0AZ29Ke1iz+qjfJWLQKkuPigBBUQw==,iv:wh45uY2/0Ep1NtrLhpWMVh/YBpgF5a+MadiqnlunFXM=,tag:f3llf6OB2Hc2SUV+YnMafg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbmVSODZxWWVNeFgrQWtC
            VUlDRWNlVG9pNFRHVDNKSDU5RkpRUE04NEE0CldxR3VzMTUxOXg2OWx4Zmp2bWRV
            SGhBNzJjRUZhL3ZJdVpwUGI1ZmErZzAKLS0tIG9QNkRBdm9jUUpTalFocUtpa0RT
            V0grVkVCaHNMc0FnVHpmMVBlWERTUjQKPy8krj606Q90jQOa8eGMJdt2V1UvoVYh
            GqQSX6uHOupB/wUsXUfb3woj1QuHFy7B1YQsi9nj9eH7oQGCV0KZvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T14:38:57Z"
    mac: ENC[AES256_GCM,data:G6yfynDMkwU5/+h5yL3lGgEZiTfVjBHmMOoeeuimC+a/msCRZ9E5H/EBygFZRtxkGTsTIZXYdvaHqkBqVF/KseUAGQTuoYkYOB0TwNTiakDLaxWCkBdrlJNREPvfDnuRino56oBtTsMlmLV1pOQsaik7cbjBq/KhI1RyiRlwH1U=,iv:4wLCq2FoXJwlzzFzFbR9ICCjHV1Px5rlWJ277saFk00=,tag:BhSJ9y+pdefja8hptdYYKg==,type:str]
    version: 3.13.3
