apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: automation
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:urPBBEDKOmLsRHIZ49YFISzJ0FSokSCW4OLoqsVaLKA0BEmchAVxyejFGP2DvMFcHgGYXxtBLgg=,iv:RkyzkYrhUDT9xz6YrUbo3ZnVvIXzmijJ0mRkfBijr38=,tag:uowCrLyYj9V1iDkOBw/cow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWJOa3crMU9wdHRJa1o2
            SnJaSDdDYXBmSFJKYXdrMHlCMXVaUHorTEdBClJkUk9tRzZ4L1NmUWlyc2dYcm41
            ZGpKRTgxUURKQ29aN1hkNEdGVUwzbHMKLS0tIEd6Z1ByWFgyNGxMS2VsWDNTaDNy
            L29VaGVIYStPa0ZmS1RaN096YjN2dmsKq/I7+WMFGw6L6I3xAXU7EyolZY8Q+gK5
            aEMHmwZARQI98LanukIARipAb1VoaVvle0SBoyw+yOf1oHu//RIRhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-22T01:25:28Z"
    mac: ENC[AES256_GCM,data:WYgRlfFCHbXnM35I+Hlg7HKXGs4GuJrbVwXDMVlrOok7A1fDmwkTXo/fy3B8r6Sl2gnqgpkwSfwbO3SvYkmIcOk+a7M3MmH2kwVoWFSa/6x+3XpLTQXlJ5gG8NVWq5Kj7AWR+3KbHsCwtKHS7n3lGrZZughQE84uuHYD34OMLnU=,iv:/AKJ1gC0+n0OQ065L3bjBAZb176kXTWzX4CPlyk1LBw=,tag:6s5dbvZPbO93oit1ZtItcg==,type:str]
    version: 3.11.0
