apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-token
  namespace: renovate
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-runtime
  target:
    name: renovate-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: ot4pia6t2shfg2tm3uxkq2mswm/TOKEN
    - secretKey: RENOVATE_AUTODISCOVER
      remoteRef:
        key: ot4pia6t2shfg2tm3uxkq2mswm/AUTODISCOVER
    - secretKey: RENOVATE_HOST_RULES
      remoteRef:
        key: ot4pia6t2shfg2tm3uxkq2mswm/HOST_RULES
    - secretKey: RENOVATE_PLATFORM
      remoteRef:
        key: ot4pia6t2shfg2tm3uxkq2mswm/PLATFORM
    - secretKey: RENOVATE_GIT_AUTHOR
      remoteRef:
        key: ot4pia6t2shfg2tm3uxkq2mswm/GIT_AUTHOR
    - secretKey: RENOVATE_ENDPOINT
      remoteRef:
        key: ot4pia6t2shfg2tm3uxkq2mswm/ENDPOINT
