apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:olUQm3kin5IXEL9lR8bNf0Mou7ok4bhHYPUUeIAd4u1uQQp1QVtYSf+zrW39kCJ08IJmBuVXXqVdTf7OzRJ5kSCDzdJLXZK7j0ZdRT1qJqb9NMzYucv11dTWm4TY,iv:XUVDKt7PXJYDI5cT38ThOK615QNayFYpLqFHk6k70WY=,tag:fX+DRsBZO31VUkbXI0anDg==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:F+nfkkI=,iv:SgzdjEqayS3S/jlhJxVzYe56ybb56CkAnp/WjhYt8yA=,tag:ImlmUyQvn3FenPzpj/uO1A==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:f0nJqaVi,iv:i0mzhb9dZsRJN1Cc8lex7TyjqxEu+ErOjko9sISRC+U=,tag:5ycZiRAO8gFq+Os/hh2vFA==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:Q+Ux1lnykgoXiZWQ/jZ7MyhlxbiCfA==,iv:2Ru05WTbNiyr6RCFof5il9LhMm/Jz2gHZw68xB2p67E=,tag:aieKodVT+Y6Ew7KZC+6e3w==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:aiPqfI6bXWkl7bjazFAaNSU39UohzoruVQS7HgnvpwSgpZs=,iv:tf/8ab2L4OP3yKDiP0aBKDYfXsmwCDleyXyj0RaxtFU=,tag:gBcHnGkU+aPQBlXhgDnzZQ==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:L4QeaRUVxisoYjEwX+5SCgyarO3kdSi+whku7vevnce9gqAO5JMuwDLS1dN0Wjj2B1g+HBTofTLY9lVONj4IPOKwElqn0l9XEU4Y0moe2ve9bP1EV5n18otCFcct7rT9kM1ehjPwwMP2ZJ+sxucA1liJnEu0m5MWYS8UueUg0bjh6D0oHaoSh0p16LJ+YvesbIwmpX1B5QKcrartnH6T1fkA/DSgUtlfLyFDkiCQcVjvuvhLMevY3N0mIar4XOFEM9kFoSCSWnDoRI6RFpq9hvJHS1prIpks6WAXo/HhaFdUZsA5GbtA/b1asuvHH5fn69parx1aI/EDylrgX8nq8s0N6TpmpRNnhERo+ZtZyS4OvhdGeO+p5vGB7NCkX3OZePOYRUROboRJCmtLr7z7wEcjw7e/FGQwfg7tf6Rlfv5yC7l27/TBAXX8I1NBsaDZdwGF1WA2o0iCDFyPIujpQ1UIamJyaImVjFgc9EGfRCtPNAwC,iv:8hzvcHGwIOAcUu9oHEFILSgs2pgMdaSif1+ebhJ0BNg=,tag:E+GhsTAtqwnRlrG6TQ5o+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVlYwdy9NN2hXTUlQVWMr
            WFQvMVY4TWNxYXArVFpyRlY2eUFleHpuTmw4CkwzSnovaGxnNzBFc2o1b2d4YzRp
            Ty9WNFhQaVRvQlNsNzVjS1dZcWdNZFEKLS0tIFE2U3JKZ25NUWkxcjNURmhNblV1
            Rmp2OE9IVExKaXZqdlFhMEFVV1hYVnMKRjZEWNQLzoELD+e+xg6Y1dcEDDMRhnaj
            IDSh/3qSkh0aHg3E2SbUKELt2feJXLPMGP969OrmykOOv3a77Nwesw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T00:06:09Z"
    mac: ENC[AES256_GCM,data:ttYTKnKpuYj9226XM5BoN8FHPeMfKx/kWGY3aS7tjV/LhDwqyObU7l27vw7ndaL1wqXWe04GlhigtiHcVkP9tZ7QJYqLQzZmqze3a7OfkLydYbiXDC3xr8rJ3KqewBX2iYkKUoXYCH0wvSFE/Ly8YBU7aaLneHNgNL3O9bkLl0k=,iv:XBlOnUllIBK4xFHo6fk73kDYS6XK5+mQKY2MemkVox0=,tag:bY55GOWDwgl34FPhOTxilw==,type:str]
    version: 3.13.3
