apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:olUQm3kin5IXEL9lR8bNf0Mou7ok4bhHYPUUeIAd4u1uQQp1QVtYSf+zrW39kCJ08IJmBuVXXqVdTf7OzRJ5kSCDzdJLXZK7j0ZdRT1qJqb9NMzYucv11dTWm4TY,iv:XUVDKt7PXJYDI5cT38ThOK615QNayFYpLqFHk6k70WY=,tag:fX+DRsBZO31VUkbXI0anDg==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:F+nfkkI=,iv:SgzdjEqayS3S/jlhJxVzYe56ybb56CkAnp/WjhYt8yA=,tag:ImlmUyQvn3FenPzpj/uO1A==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:f0nJqaVi,iv:i0mzhb9dZsRJN1Cc8lex7TyjqxEu+ErOjko9sISRC+U=,tag:5ycZiRAO8gFq+Os/hh2vFA==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:Q+Ux1lnykgoXiZWQ/jZ7MyhlxbiCfA==,iv:2Ru05WTbNiyr6RCFof5il9LhMm/Jz2gHZw68xB2p67E=,tag:aieKodVT+Y6Ew7KZC+6e3w==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:aiPqfI6bXWkl7bjazFAaNSU39UohzoruVQS7HgnvpwSgpZs=,iv:tf/8ab2L4OP3yKDiP0aBKDYfXsmwCDleyXyj0RaxtFU=,tag:gBcHnGkU+aPQBlXhgDnzZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVlYwdy9NN2hXTUlQVWMr
            WFQvMVY4TWNxYXArVFpyRlY2eUFleHpuTmw4CkwzSnovaGxnNzBFc2o1b2d4YzRp
            Ty9WNFhQaVRvQlNsNzVjS1dZcWdNZFEKLS0tIFE2U3JKZ25NUWkxcjNURmhNblV1
            Rmp2OE9IVExKaXZqdlFhMEFVV1hYVnMKRjZEWNQLzoELD+e+xg6Y1dcEDDMRhnaj
            IDSh/3qSkh0aHg3E2SbUKELt2feJXLPMGP969OrmykOOv3a77Nwesw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T22:09:35Z"
    mac: ENC[AES256_GCM,data:Wp6dgoUkVsOIWzf0wEG0h2Z2wgehTBfbt8WKrl9YgCJf48pTR5UatZ2f7E69cW1q0SZxg3rYNf1uQ0R0HU++EjwHVFN4dBjsv74PSsqhI3O4l40l3/Qji9FZ7ZvVi6TRjo/2lnQF4uVNNwQEFHWcn7jDEh8UIgd89c/bs89Zf4A=,iv:teaQh0cTR5O555VpJWJepcIGvtRviGpnkioVj4xrJg4=,tag:/+Q+q9PbrfetVkRzCiMkeg==,type:str]
    version: 3.13.3
