apiVersion: v1
kind: Secret
metadata:
    name: renovate-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:olUQm3kin5IXEL9lR8bNf0Mou7ok4bhHYPUUeIAd4u1uQQp1QVtYSf+zrW39kCJ08IJmBuVXXqVdTf7OzRJ5kSCDzdJLXZK7j0ZdRT1qJqb9NMzYucv11dTWm4TY,iv:XUVDKt7PXJYDI5cT38ThOK615QNayFYpLqFHk6k70WY=,tag:fX+DRsBZO31VUkbXI0anDg==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:F+nfkkI=,iv:SgzdjEqayS3S/jlhJxVzYe56ybb56CkAnp/WjhYt8yA=,tag:ImlmUyQvn3FenPzpj/uO1A==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:f0nJqaVi,iv:i0mzhb9dZsRJN1Cc8lex7TyjqxEu+ErOjko9sISRC+U=,tag:5ycZiRAO8gFq+Os/hh2vFA==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:Q+Ux1lnykgoXiZWQ/jZ7MyhlxbiCfA==,iv:2Ru05WTbNiyr6RCFof5il9LhMm/Jz2gHZw68xB2p67E=,tag:aieKodVT+Y6Ew7KZC+6e3w==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:aiPqfI6bXWkl7bjazFAaNSU39UohzoruVQS7HgnvpwSgpZs=,iv:tf/8ab2L4OP3yKDiP0aBKDYfXsmwCDleyXyj0RaxtFU=,tag:gBcHnGkU+aPQBlXhgDnzZQ==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:EQZ9sQRKbzne5aqxSoCnWoY/VWaCPoyMQD1JV6NyFeP8LRNynksSkwJ6wjc3mCRvfA3JD7viaptNuLsi3EfYNQGkk9CTVGj+Kg2jSmEh8r6AwMLO46gdnnXRZpNEgsUK+BN++cMgJ6opfJgMJFFLulIcOzXGzTsc4+qwKQ1eU5ngTXGyVY19cJcpZHRVM9jrcOtHUg9yBuuLveiZneUIIjqwX1t101bxwzE+/6nwI4BDObD5HPrg,iv:b6JaX1B8H4w2MApx7qJT06WfHR83yBkDILHhalOgAaU=,tag:cGoOTaYGPGlr3e/aZehNOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVlYwdy9NN2hXTUlQVWMr
            WFQvMVY4TWNxYXArVFpyRlY2eUFleHpuTmw4CkwzSnovaGxnNzBFc2o1b2d4YzRp
            Ty9WNFhQaVRvQlNsNzVjS1dZcWdNZFEKLS0tIFE2U3JKZ25NUWkxcjNURmhNblV1
            Rmp2OE9IVExKaXZqdlFhMEFVV1hYVnMKRjZEWNQLzoELD+e+xg6Y1dcEDDMRhnaj
            IDSh/3qSkh0aHg3E2SbUKELt2feJXLPMGP969OrmykOOv3a77Nwesw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T23:34:50Z"
    mac: ENC[AES256_GCM,data:kZnUXeVzsYRRNIRGN1wH4ZbnF1xkW+2UVlidVyAEIwQRUC00+UvNxmLGvPd40ISw7R5oCp5wyOu1Wvg/+fKzsPgzXri9mKtem/WkBBm8w/jd2aISgOW3nefd4jsSJ2JMUH5DpfPgJr9TGPj27cGISVpMLse/mAPLPDozprp0o3A=,iv:VR2imDwjemZ7P1/6otKWPEb6we7LtJ1M2Lyhitz/o7Y=,tag:4u/K8aW7ANxVS6wq2Qih4g==,type:str]
    version: 3.13.3
