apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
    namespace: harbor
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:yaaHzobEiUCKDek3oDRm/zuIqKOtOznESlE5v1SweZo=,iv:QIYLgcQaIuBkRvzL6xXzyWKOLRCu6jqCsTDooZCuyFo=,tag:q2vphlZMbu5i0mJDrPWDKQ==,type:str]
    secretKey: ENC[AES256_GCM,data:Nv4NzJx9nikA1X8uwz/bug==,iv:2GNSuYY+GdiNjZ/iS/Jol8tiLINUVC8Q/hOJBBBBwdI=,tag:/fXJ12Fg3WvkxfmCAY4jQw==,type:str]
    secret: ENC[AES256_GCM,data:z2R9LI4FgZOlZR8z8ktwwQ==,iv:SAymbfSABer4BIqaulwj9UeldfSh172iatsQNNYWn0g=,tag:sQHs8SaCkGh8YLnzdf4mvA==,type:str]
    JOBSERVICE_SECRET: ENC[AES256_GCM,data:Aiv5SGSAt8D4UK5c00CzJw==,iv:TbYDQWVS1jwTi54zF0JAwJMIvEZ+0IcvApUNMRYXb5U=,tag:YF2Cr3Qg95fn/Go2bfx60A==,type:str]
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:utAMsWlY3IGrv3hrqISrrg==,iv:vqE6srzLLrC9KOUylO9zQ4l0i25AgF+JNufK71s1fLc=,tag:qOdxmA3IphhhJezRubNtgQ==,type:str]
    CSRF_KEY: ENC[AES256_GCM,data:0WVfIZz/789Xl9sRAA8FFcmdvLXjcQZEAJ0C5OCGzls=,iv:4cAjmB0GmlFUdhby8xk5lO1wloQjdDBbEXCMnj2LYo0=,tag:BEapmZhgFHGqQYxEtEkQ0w==,type:str]
    REGISTRY_PASSWD: ENC[AES256_GCM,data:DdCn+FngifqPk7TkKisY69q6oLCPQxbd25KhraNN7qc=,iv:V1D+OjxCBhKv9SdlY6VN/MJJwi9rG5VQKwWFKxzMPOg=,tag:MTZmkqx1bKBZLJk4kosySg==,type:str]
    REGISTRY_HTPASSWD: ENC[AES256_GCM,data:zgtyct9KY/ZFR6M1oKLyjcvqicW15fRZdnp05BYIxj042CwacjcTpbOoSY5mMs1EcVJxnCi94934z++mIUX4sikbvHyU4aaSE8eqQtcSKHBI,iv:epbxmSOqT3209My2JkAN68I1KDA/zSGa80PKY72A1mA=,tag:CCiykq4uBtF2J2SzR5ARMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ2NNMHpGc0RlaUJ6R2hj
            RENxM292eXBPNi8rczZhV1lSa2hlcUlIZmhRCm1NZmdsU1ZiYmx2dVFFOEttMEFB
            N3RzL2xtZ0ZRZFRrcytrZFZVZUNRNWcKLS0tIHQxQVNSWStxM25jc0k4WUJCWTN5
            Zm1OV3VCa0FiN2RZUFFTeDZaeHk5ZWMK/b3ZvSIAzuL+orben5ieO834G10hzwf+
            yaLeLRtUhwrpvuDIa5grguqA+8Vj8TWnm0v/0oiL0xziPRaf2CUwKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T22:52:01Z"
    mac: ENC[AES256_GCM,data:rc10LAx1uQaFxy0Vbs5tIIp+1ualC2hC5eP4HemWg2nCKpGdeFkJ5kIoG5ESNtgFLtNh4St1NJkEor1Be4P4M3c+9PtGEmupWz74IUGAMUEyMxVHlwMGXse28Es9cpQfmqVJ/N1UVsAJpzE0H7S/Rt7AvPkQo5JRI4BmEU4De60=,iv:cIUC1HktjYj9K5BmHB3PuvPe3XgbK0mYPzr8t2mj1wg=,tag:eOwjHJdll1Q2g09ENuUWng==,type:str]
    version: 3.13.1
