apiVersion: v1
kind: Secret
metadata:
    name: opnsense-bouncer-key
    namespace: crowdsec
type: Opaque
stringData:
    CROWDSEC_OPNSENSE_BOUNCER_API_KEY: ENC[AES256_GCM,data:E4wtPY6u4x0qbX6UdT9FLLVa3Ke1EPmYfFoCTtABZdmXeEUXjb+Uig3zsw==,iv:K/u9o3CNnjclwkXdfvn7bjiyJ39zpqfnNHWGUxzS0Vo=,tag:SoXJsMctx864xksnoGcC2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTUczWDRnbmUzYmMxcnZG
            OUdQblVhSS9OdnNPbkdVNHdsSFJ0WW9VRkhzCkE1RGtUeFkwcTE3c2Q0U0huenMy
            WkErNTYvcnlOL01DUGEwUllIWER3OXMKLS0tIGE3MkxZK1pFOHRudDZPeEZKSkhv
            UjNYT0tzbFZUNzJrLzBKR2hsTjY3aWsKPwB/OHBQGYKu1q+UplZUMsWDii0DGH1C
            jVWarhburIFhhF2q/4jkbjb//vwQOhYim6gSav6M6wXMSwq89WzpbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T13:05:43Z"
    mac: ENC[AES256_GCM,data:rEtctpVZh/U7TfXCwteiNuSp1Lz3kVQ7uM/BJH70KZvkTrKkQ1P68tAkB8TaQ9CL0OHiATZ0vWY4ZUVOkjSMGCSZBgNSdbwDrfL7NiHqooPZRuuvYN+5wu4saLHal/F7PFzq4Aoq1Ikl/I4mUfd7rlNyb6nqIGHDwyRVuwJDyrg=,iv:mjlmb8RI3fAXpRWJ1IUlsDINMCmdGjzC3OZSXfjnI6g=,tag:PXpOmmkHSbAnYc+y2ctiQw==,type:str]
    version: 3.13.3
