apiVersion: v1
kind: Secret
metadata:
    name: traefik-bouncer-key
    namespace: crowdsec
    annotations:
        replicator.v1.mittwald.de/replicate-to: traefik
type: Opaque
stringData:
    CROWDSEC_TRAEFIK_BOUNCER_API_KEY: ENC[AES256_GCM,data:9mhfRxMAbTaB9kL9LRzOG0dZSrnhbuUVUOwkO64OVEllI+o3TOwRwWl4vg==,iv:TVOD7QlxcaYfpg14wtBxXPUbG47djGS8rg3ntctyXWI=,tag:mGxIIpL4lQ+9x32C48qLpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeUNXaEozOHVWYXJEeWtP
            U2J2OU9OOVBiMDZWcXN5SkpMUXlWcG9NVUg0Ck1KeVVKN0tuU3lPMmp3czZxN0gx
            ODkyZlBpOWlYak1XUGtUNS80ak0wZmMKLS0tIFV5RnBJNHhtdTdPc2VobnlxN29t
            VFNYSmhocG8xVGZmdThiVlNjSjFzV3MKfDbT5xIR82iLJ2gjHBcfG1UMsBogn2AG
            626k4zfgEPmNJr/uhgQNebx6bnUR6Rpt19bccCWYyO3MGiHBPTxgjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T13:05:04Z"
    mac: ENC[AES256_GCM,data:mxd9rRWSkmnavPJD+r01Kdkl1STI7B4XxGnuKqjwRrzI7V4IszDgtW2fV7DSnK9eBZwMDRHLZVsOoLthUdtApFKrRPPEq1tZPtIml2j/0ja15r6V2Il+ZjW8auNKVYzJisFGSmzDsOXJPGIriVpc/4t2LzDt9NPF02/ZTgGOl4c=,iv:QN6Or+wDg3uZDPkPxViRhIuRr2nfqCudYWeuFPJUyTA=,tag:BwUlcDLgstRpM1iUjt8GFw==,type:str]
    version: 3.13.3
