apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-auth-openclaw
  namespace: authentik
spec:
  forwardAuth:
    address: http://ak-outpost-gatekeeper-proxy.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    preserveLocationHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-email
      # This doesn't really work - Will either fix later or remove it.
      - X-Gateway-Password
