apiVersion: v1
kind: Secret
metadata:
    name: airtrail-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:kzscz1+lC/1f05eDB9/l24FVZHr0IoRlXLSPBH1oHTrMqd+DFU/5n4Y9S3KwKXGE3gCm9fDkRRHALZdk/fpjqw==,iv:GIjwA6SlvY0ATe81y2Sq37Syf9lMLmGsiI9Q6YDEneY=,tag:HoK0mOMmttLElD+X0GI0xQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:uy4+ZnCQ5yFVFNagDYvy+xNXS71rk5aZwW2zeZ10TeozU+VAnJLDOZbf40k/j84KhUQWyQNe4RAikZ6QjJCVEwEkJ1KRSg30hRYeV65I4KeBz3gFXAaFdp765YfJ38qK7zapUQ/pSZHSZi8W0hFDPMkNbmcx0P1vHcJwU8n4U7s=,iv:PmxtnW3bVBreaGND6/Rq1+JtV09MLkgXURLPUQktEUY=,tag:loiZBA7rM6tt3At+GDSFYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGhGeEZEaHBGdHY2WFFh
            cHYxRnJjNDlacHdLVlFMb3NJR0ttalZUa3owCmFFbWRQa3dwVTVrS0tEQXVocU81
            Mm91dEJpT3MwRitib2JuY2RjNW4wNjgKLS0tIFc1eDF4OE9BN013L2d2OHRQbTJJ
            eTFNbzFXeWNtbURFcFZGWU1lR2NQenMK+xeoFPySPS5ZbVA5je0M98XIgVMbPX+u
            i1dDfebUOFK0Nfl3WzmnCgKYhA7GzhcotFtBl5wbn55z94d9zj2TVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T00:46:53Z"
    mac: ENC[AES256_GCM,data:znalJUJHaByjiTbH5y0fDSYqitviMedjx/ayEvH38uT/sePeyrmK6N5AQ8mRDJop8SnB8m0AkuzIqzNxfZMJjHOeuJPo9vshP+VL8MWJWsHEgfOdxBFmG0wCUIj70Ox2JulFLWEYi8rKZMUAHBm52UTzlUcNKE7CfJm9O/qALyc=,iv:HPsh1DlXTRKRZJsCYEl08izs7+qeL6SCiGJe8LRrCCw=,tag:ijDvNrFXsJ2r7bmOOatEBQ==,type:str]
    version: 3.13.2
