apiVersion: v1
kind: Secret
metadata:
    name: airtrail-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:p2SHL+qEEC+VKERo2PW7pzqHV33vorN/ADVcakphr5Y=,iv:otHyNZRgT3PD4HyGvQljHxJfQVTqwl/au+z2ivDvQ8A=,tag:gvmE4cfMZ0bA2Sfq4qkeSA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:C4tKeCFWm4pW334jI7jTaMsTcMmPCjPgQLLwGwwmlp+PdIJFXCi8bXAWTpylUSMxFdY+E8Il/QQYQiQIRnFZlg==,iv:HLIZZ7+GCuxwigPtq1suPbRBptQUQAj2pgQ3YBGM5UU=,tag:g3/IRqLPCB0N28FqtnQvtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MnNocW54emFBNUtKcFFP
            YWh5eE9hekhJYU9RM0tlSHUrV2plSzVVdW1zCjdpMmxSa3EzeHZsZkN2QzMzS0tq
            TFNMOXd5MW5kY1BReE55cnhnVTVNZDQKLS0tIDNTZnZFQzBLOEdDd21JUkdTYTlm
            dWZINnMrczZRVEUwYmN0cFkrTG9wYUkKFZo4v9prDXJyqhUXSe+PUXyvKvFJwMTm
            w191A+sGpWfUxgGhjvbPEfIVLUm6kefBBlRMWwy7aADXO/GV25sLIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T23:03:15Z"
    mac: ENC[AES256_GCM,data:GUcXRfWu0kO4/EhdPCLKUZBA/31V41o02AWs80geMz09voGRkgqvoOn/pUMCYpvNC9TyJkd9JKVDfMQcUcDY1R+Y/pPmwgxoTfWfC9fECjgxjfSjUN6W6zAPMYev5Te0oIvGwWjb/30/Kwz+0qBieDWtm8w8HJ4X2p5K0DoRqzE=,iv:EuZ3st+8xKTkBGYqCeNamhVQcSDaF1+uerLkkQ4I6vY=,tag:KdP90WVNsmNsXnfr17huqQ==,type:str]
    version: 3.13.3
