apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:kx9Wfsde30zdads67N4Wavh4F34Gj71TXrE0eynWjk8=,iv:ZcFjbazf41JLiMkdnGk/vnnnBL5DaH/D2Iz+uw/qLnE=,tag:3/JRB2J6kmOLD66Vx8+CXQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:sF2VzSxAqdk+ctoEHBitDK8KPSrEqHnKjtAcH+Ame/mse6nXX/cyymQSz7HYUvV9gXl9o8kYHsnS6HN7qtNUOg==,iv:EEC8OX4OP2G1MhqHwqX3T09bpFWOk98171RszmRHMNw=,tag:JbPedhOas3160zkMSe8XGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeHUyc3I3Yyt4MUV3QU1h
            UlVma1BVc3RXS2tXMmZwRVYwTG1HdTJoVGpFCjhjVDJTSWJ0K3JLcHRDczZkcEtn
            SlJCT0ZkNkxTS2h3djNxNUZNU20yT00KLS0tIGsxeGRiRllZbG1jTENJeW9nOGVq
            M1FaYUF3VWVzdnhiay9qZG9CUkZWUjAKMrc/+PDXj3pBkJF1EQlECBYOdmFPtcBj
            mhGHUE/U93UlZLMl57NdA0CZJPkyETjKwZ0lnYWwA+6K4EpzJ6Xvyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T01:17:49Z"
    mac: ENC[AES256_GCM,data:/AflktCAlx/C/jpvGhsZpvnMXkCW4HODUEfsduBO/angnhcSkW0oVB2I5160F+AmgyJHm1/N/4SKClIgdz36c10hlPXlZqHmXqwbydXDTyFsomPiRmfFZFidmPZkqoXTF/oyloucS0e1ARsJ5xWG+nVm8KbuIArSKD32ds8kMdU=,iv:95RpVAl9xknbLMweovBTpU/+VZxKuuR/eKYydn1e3hE=,tag:CTF2B19rxiStdPnlXO7NUg==,type:str]
    version: 3.11.0
