apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:rz5i4+05lsdN2Rc6gMaVRUb3pqY4cxT9zD3oVNvnWBDoOZKoSsKqyA==,iv:Y7rThiq1WG4No9G2dZou1JAl7Moo1A6FArgocDBhJLA=,tag:2o1ky0MAanjirsYUQU+WRw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:oN1lahNDi2Nu9t2uFjfC+ktjtZSc7xAWG13GGhB8OQH1y8FW1ea0SrwvSfN7j6F4dJUPFkZ2W+AuEJV0yNaHlOv2NDdL3mrULEp/74vuGAkia801HLIze9upEATi2750hiXQHJdPPVepsNeH6VWJ6U7kDcTRgB+xDF0czFoB6c4=,iv:8OsVL4C3SuLU/Gi07cWxjYLrzrzt7QNWwZlMXuYR9us=,tag:wN9JRkXjEwjSNuB+GyFAkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeHUyc3I3Yyt4MUV3QU1h
            UlVma1BVc3RXS2tXMmZwRVYwTG1HdTJoVGpFCjhjVDJTSWJ0K3JLcHRDczZkcEtn
            SlJCT0ZkNkxTS2h3djNxNUZNU20yT00KLS0tIGsxeGRiRllZbG1jTENJeW9nOGVq
            M1FaYUF3VWVzdnhiay9qZG9CUkZWUjAKMrc/+PDXj3pBkJF1EQlECBYOdmFPtcBj
            mhGHUE/U93UlZLMl57NdA0CZJPkyETjKwZ0lnYWwA+6K4EpzJ6Xvyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-25T17:37:29Z"
    mac: ENC[AES256_GCM,data:BvJKK3rOLT183/RVpoMmbl0ONCnBECk6NkS0fLiMDKWokTmBkwOK8OiZfn0aifsmzp6DwekR8a91I1AKiGfvhEbVnmZBLK46MG4KTyC09votER/NqfqwkLBwOM6Hm8Ykt75JJcbIw73ABHo+UamHpnQPqEUc0jwVl54NRGg857U=,iv:bBYVfCbsuePNQYe0NPPPWuMIQfTWD+bqHHZyK9x6aIk=,tag:eiUaodYY5ea5XcNVb2EgrA==,type:str]
    version: 3.11.0
