apiVersion: v1
kind: Secret
metadata:
    name: authentik-env
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:3ZjVUIe9thjucKjTOQf/9WnaCJAohtvWL2GX7JoZCyvYf4MHfMRB5c6mmPqOYZoGqmseNRVtbICNH3anU+zsWeFRq/+sY+7D0PB0tDPfJdzvwjFX/DWmc2PZUrELSa9ccaWxQ+nJ4qZjXQ7NnScN5/ri+WGFHCEjCB9CggScIJg=,iv:sPqWpEjvrGPz9subXmxeuoQH3+4wa0/oR81pG37pmU8=,tag:0XFzylbR8prLC7GyiFeA/g==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:RJRc2T3yExKsAzNsNRZbg/sr1D7cdo7jfs+JTsmFFxfrLjvqN/nkn8nSsfEyFh6s7dHVFeaJysFyej24hdefjA==,iv:npBvszIKzgkzcxSzI0dRlDHAXYKbeIMhkG4kCvwaq4M=,tag:4JSCQMYiM15ga7dxW+8mIg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:cBStW/Mwn7VbdmrSvfD+3kF0RC0k5rDTi10dCHj/KPLDPNNATKaxDrVSYsyDEVhQqYe4IsyXXIMWmiA1C/ZnVQ==,iv:H4TtUvtIPUxB5rpnaAOG93Q81ow4bBRbWYoQ3y0+OHs=,tag:+i/uZM+U0NXq9AEIe8ua4w==,type:str]
    AK_BLUEPRINT_USERNAME: ENC[AES256_GCM,data:EvHKxuKAmj3f,iv:XhDwE9gdHVbdRLq5ed/H3aWGkea7qgz1L8SgHN6rKhM=,tag:0sZnNTMpILppuVwGWl//IA==,type:str]
    AK_BLUEPRINT_NAME: ENC[AES256_GCM,data:XQo0trDVf/jo3CXTxagRCw==,iv:l3NhCHY1+7DIPRowXoff86ox4q8FG4I/yoQXoz9AZzE=,tag:ELvBvgq9TGnhuXfTv5V1fQ==,type:str]
    AK_BLUEPRINT_EMAIL: ENC[AES256_GCM,data:odyDCqGxP0DHftJJ5jizSXa2XInj,iv:kGC3syWx28nWXuKQKFAu8q4ZNypgu7PktGKvCSYRCJY=,tag:sel3L11E+8SG6Vrpc7g37Q==,type:str]
    AK_BLUEPRINT_USER_PASSWORD: ENC[AES256_GCM,data:+tIQsFGizzAaTmoVSR+SrSO+P7/m7VF/brauGaW4qgWdk0ZgyQ==,iv:T+XMjOznUJI6jV6huJuqNxmNbDMipKA4Y5fO9tKMM0s=,tag:DZeazVsT1n9G0MAFhWqjDg==,type:str]
    AK_BLUEPRINT_USER_AVATAR: ENC[AES256_GCM,data:GWaoxmivg38cELK13xBs53YecWkddepJDiXX1B9illIxG8Q8gfGhGP3duqQQAIICQlucOZTxAyav2mjh,iv:5/cn4PWygVBWLJsuThHY8ehxZWlsRdTGj2dlhWJoj+Q=,tag:T2uSwJU+t1YfxoLOedfnIg==,type:str]
    AK_OPENCLAW_USERNAME: ENC[AES256_GCM,data:TaRV7w==,iv:K4ey771hmGSdNaxP+F1g7h4OUNqRI96IXaWXYlSv+I4=,tag:95qlIYQ5NRYNDZxo59eIZw==,type:str]
    AK_OPENCLAW_NAME: ENC[AES256_GCM,data:aDYssDwS6bAZJt+NpKd2yQ==,iv:sr3tDP1ZO/YGMjntgYlrMd6pzPsdjAA/LMBA9CVifpA=,tag:Y73om3sm1uE+ENspzvxV2Q==,type:str]
    AK_OPENCLAW_EMAIL: ENC[AES256_GCM,data:byoziDi1b4jpb5DlkwLxmOK+tmsmFf0HsZkK9FQ=,iv:IA9p8H5hAv5OOhsBCNQ8EySmvpjlY8kTolJJF1Jziag=,tag:Fke0afZ/cNT0v3fr1DJt9A==,type:str]
    AK_OPENCLAW_PASSWORD: ENC[AES256_GCM,data:HelAEUV23fEtHhNscH1c488FD1IsdW5v07jBZh1H8YomoR6m39oRGZdAPw==,iv:Y6CamcAREFmpW9AXQqV2BhjdQOo2x5Vcaho/d/7ISm8=,tag:O9A91377c2nhmnknm9qmCg==,type:str]
    AK_OPENCLAW_AVATAR: ENC[AES256_GCM,data:0ERTwatiISNZrSWtClsP9PyvGxSP9Xwx2eXJ0SzB9lU=,iv:LfOnq+nZJB/6JSA7NBarEk+MqyK+m35LN3xZtyoK9B0=,tag:gDnYShGqWcoEZEO4YczeOQ==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:S58602UjX7pmb8rlAm38/RItjxtHB8qaD38bdnZyqP5sRw==,iv:xfHkm8p9U78tnGtwgG2omqNZhK6+zX0sUgf+cDpceZA=,tag:BBszNg0K0Zg3WoDcoQ36Kg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:jobzLhBtvnMCgbnGIrfBrQS52PhFJNXUNw==,iv:2LKoEvp/qo34FM/UE4xaWcRBxduuvK5xnu4QLstD9+Y=,tag:z7+2lZmA3xXySDb+jkQw6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QzNnc09Ga1NaVW5LM1U4
            Nm02UEJ3ZFE2UG1sR1BXNFRKdGNoZWlFQkJrClllaFBOaktCTGRncUZTNklIRlR5
            TDdkZVlpRWNZMXZjRVdEa1FmYTd6RkUKLS0tIERCUzM5WFhGOFIzNTBxM1YxVzRm
            YmE3UUYvRGhZb2g3RTdSdkF6d1ByZ2cKpA6eCrZHM8AbPxbYhxU7enEh0CJGXdIg
            lICSlQ4/e1Rqn25+UKdGYReUvd1tsjK9hGmBubuB/gG1Nk56sXGejg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T14:44:49Z"
    mac: ENC[AES256_GCM,data:pgbT1ddQmtcAn8ZFBicERmDoIUQIV2a2ETtD127/io9zTUZmqHvpMP10aN8MJBGkf0r8Y4jmTknCGAPhfD5N29EIA+oYE1n7mekDH5hDx5zA1dn5LznFDOL6kWDOb2elNk7TVFOUxOmaf525fTPVttAvilV3ZVKGMOwLlni29Po=,iv:0pspSOoQZ33QBLHNlhBE5MvtgBhnT2fzZj1qYHamX8A=,tag:gPDpSWwY2B64s7XmjyBlGw==,type:str]
    version: 3.13.3
