apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
  labels:
    release: observability-kube-prometheus-stack
spec:
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job.longhorn.io/backup-daily: enabled
      recurring-job.longhorn.io/backup-weekly: enabled
  instances: 2
  monitoring:
    enablePodMonitor: false
  storage:
    size: 2Gi
    storageClass: longhorn-r2

  postgresql:
    parameters:
      wal_level: "logical"
      archive_timeout: "5min"
      archive_mode: "on"

  backup:
    barmanObjectStore:
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-s3
          key: ACCESS_SECRET_KEY
        region:
          name: cnpg-backup-s3
          key: AWS_DEFAULT_REGION
      destinationPath: "s3://cloudnative-pg/authentik"
      endpointURL: "https://s3.${CLUSTER_DOMAIN}"
      serverName: "authentik-pg-v1"
    retentionPolicy: "14d"

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secrets
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-pg-backup
  namespace: authentik
spec:
  schedule: "0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-pg
  method: barmanObjectStore
