apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secrets
    namespace: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:FQciy4hR41zr,iv:Fuwr17ZyMFTKWtenYYIbMG7t0sQe7LejADRdMQriqqc=,tag:Vaw8ftdGiaQg4Sy8ijPwMA==,type:str]
    password: ENC[AES256_GCM,data:QnVkovxKiC2mHlBfdAsipeES4c+NC7cjYtCOU4O/yBinjhFPNcRmVtMsk4r/kssLQw==,iv:PvAtoL4xlra+kKDIT+tyls4rFzxwBKdOTtQskELyr7w=,tag:iQsz6+ESwuuVvVYZAE6h7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Wmp4bENnaU1ITFR6MEQy
            V3hZOUZ0blpMQzBuaUhqeGlxRFArdHlnckYwCkV6dlFNcWpGV0R1MkpsNGxQeWFL
            TzVHaWNmWnplZVBJR2grYTBiQjhxakkKLS0tIHdIbFFoaUlkcU12Z3RoaWJQRkgx
            SEYzRW5YSEhWM1lUWGMxSU1VbWhETlUKCxF4Bfehw3Hnu1/zIwPOBYEwlDYhoQQt
            X/0PYkw1hn96fjzq39IEx0E0GyzVaYG8EHG2kfY7jaFHOAAaa88U2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-23T20:15:54Z"
    mac: ENC[AES256_GCM,data:AbNabnIOX9XqwIIuvQsEwZGCXtVJOUcmsZbCIp90pxd8ALn6g3pWxjB/LXma0g+aiZIzmimbG7ysNzaRYdpIV6wHMMXIyUldYzzVLoXvXw2sJVyYlfrqA1vjFa73ffB2gCS7+mYqkNkFfom1JdgO1KzA1TIOkuW1zq5reCNXWsA=,iv:9Pf7XES5bU0b35zGYkZMCbHEEUho3PYIo5nOqxADeKs=,tag:GhS39Iiy2YpBYZjCN7Nl5Q==,type:str]
    version: 3.11.0
