apiVersion: v1
kind: Secret
metadata:
    name: authentik-env
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:3ZjVUIe9thjucKjTOQf/9WnaCJAohtvWL2GX7JoZCyvYf4MHfMRB5c6mmPqOYZoGqmseNRVtbICNH3anU+zsWeFRq/+sY+7D0PB0tDPfJdzvwjFX/DWmc2PZUrELSa9ccaWxQ+nJ4qZjXQ7NnScN5/ri+WGFHCEjCB9CggScIJg=,iv:sPqWpEjvrGPz9subXmxeuoQH3+4wa0/oR81pG37pmU8=,tag:0XFzylbR8prLC7GyiFeA/g==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:RJRc2T3yExKsAzNsNRZbg/sr1D7cdo7jfs+JTsmFFxfrLjvqN/nkn8nSsfEyFh6s7dHVFeaJysFyej24hdefjA==,iv:npBvszIKzgkzcxSzI0dRlDHAXYKbeIMhkG4kCvwaq4M=,tag:4JSCQMYiM15ga7dxW+8mIg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:cBStW/Mwn7VbdmrSvfD+3kF0RC0k5rDTi10dCHj/KPLDPNNATKaxDrVSYsyDEVhQqYe4IsyXXIMWmiA1C/ZnVQ==,iv:H4TtUvtIPUxB5rpnaAOG93Q81ow4bBRbWYoQ3y0+OHs=,tag:+i/uZM+U0NXq9AEIe8ua4w==,type:str]
    AK_BLUEPRINT_USERNAME: ENC[AES256_GCM,data:EvHKxuKAmj3f,iv:XhDwE9gdHVbdRLq5ed/H3aWGkea7qgz1L8SgHN6rKhM=,tag:0sZnNTMpILppuVwGWl//IA==,type:str]
    AK_BLUEPRINT_NAME: ENC[AES256_GCM,data:XQo0trDVf/jo3CXTxagRCw==,iv:l3NhCHY1+7DIPRowXoff86ox4q8FG4I/yoQXoz9AZzE=,tag:ELvBvgq9TGnhuXfTv5V1fQ==,type:str]
    AK_BLUEPRINT_EMAIL: ENC[AES256_GCM,data:odyDCqGxP0DHftJJ5jizSXa2XInj,iv:kGC3syWx28nWXuKQKFAu8q4ZNypgu7PktGKvCSYRCJY=,tag:sel3L11E+8SG6Vrpc7g37Q==,type:str]
    AK_BLUEPRINT_USER_PASSWORD: ENC[AES256_GCM,data:+tIQsFGizzAaTmoVSR+SrSO+P7/m7VF/brauGaW4qgWdk0ZgyQ==,iv:T+XMjOznUJI6jV6huJuqNxmNbDMipKA4Y5fO9tKMM0s=,tag:DZeazVsT1n9G0MAFhWqjDg==,type:str]
    AK_BLUEPRINT_USER_AVATAR: ENC[AES256_GCM,data:GWaoxmivg38cELK13xBs53YecWkddepJDiXX1B9illIxG8Q8gfGhGP3duqQQAIICQlucOZTxAyav2mjh,iv:5/cn4PWygVBWLJsuThHY8ehxZWlsRdTGj2dlhWJoj+Q=,tag:T2uSwJU+t1YfxoLOedfnIg==,type:str]
    AK_AI_AGENT_USERNAME: ENC[AES256_GCM,data:C7jWAQ==,iv:QVpz9OkY4apKlyk1AZy8+RwcwRbbGixXGeCtq0X5TAw=,tag:0zbH9QqM/F9k/ZIJFwEljg==,type:str]
    AK_AI_AGENT_NAME: ENC[AES256_GCM,data:5ihkE/B/cu5pkeGQQ1JbZA==,iv:cCzlukahuj7BdZn1EzaVXYDDGxtp4n1NBYVf90++wco=,tag:yLqZXkEGl/B/HfpT/QzaoQ==,type:str]
    AK_AI_AGENT_EMAIL: ENC[AES256_GCM,data:eL5CMkt07Ny5DYc9kkYMNKnVcZbhzzrmvH3ULLM=,iv:VPc+Q5ARE0dbagvOpbF8q/G3iOwO2PIxqOJ4W2N6ZF4=,tag:jld+uruucrhJkWM0cvvJ0Q==,type:str]
    AK_AI_AGENT_PASSWORD: ENC[AES256_GCM,data:0v6PbNXp9aYa5XoLIwa5l2mLs0JNq4dpnvpNEgn0r8ACKdpjRJyk93rP+Q==,iv:BNro82jih2XRNhRqkaVLHcRrr512w0QT0SE8Y6biYKg=,tag:8pnQ3lxFUhqpO8ifOOqZ9Q==,type:str]
    AK_AI_AGENT_AVATAR: ENC[AES256_GCM,data:9XnDJyxeQ9W5DbCByNBD1j3DlQUDlJO4hytAzauEtPp5g+TcKO4ZUgCac2Lfd2RBRZpL/wmFJ+JCAMUu,iv:bvquE7JzHOwAdxnf/g7cAPT3yjbeRG+4vN97MhSP3KE=,tag:HW4sPH+zaY5Hn0dyxJoz4g==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:S58602UjX7pmb8rlAm38/RItjxtHB8qaD38bdnZyqP5sRw==,iv:xfHkm8p9U78tnGtwgG2omqNZhK6+zX0sUgf+cDpceZA=,tag:BBszNg0K0Zg3WoDcoQ36Kg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:jobzLhBtvnMCgbnGIrfBrQS52PhFJNXUNw==,iv:2LKoEvp/qo34FM/UE4xaWcRBxduuvK5xnu4QLstD9+Y=,tag:z7+2lZmA3xXySDb+jkQw6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QzNnc09Ga1NaVW5LM1U4
            Nm02UEJ3ZFE2UG1sR1BXNFRKdGNoZWlFQkJrClllaFBOaktCTGRncUZTNklIRlR5
            TDdkZVlpRWNZMXZjRVdEa1FmYTd6RkUKLS0tIERCUzM5WFhGOFIzNTBxM1YxVzRm
            YmE3UUYvRGhZb2g3RTdSdkF6d1ByZ2cKpA6eCrZHM8AbPxbYhxU7enEh0CJGXdIg
            lICSlQ4/e1Rqn25+UKdGYReUvd1tsjK9hGmBubuB/gG1Nk56sXGejg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T11:35:32Z"
    mac: ENC[AES256_GCM,data:ZNcNVKK5cavvjv+caQpqbNYCNy0x5KjZy+dELaSz1z13xdOQDO1xJldsC1PbDXVza7jSxwYejaooqxmfsqr4nAYzdWXmbHlCu2XuJF1LRHzzB87yQ0hpAnPZq0EP0gXsb9HrCHVznyx0yPWiYQW8lYXS3MGXN5YX0UFcngqKE7I=,iv:e0LDmzRCs9L7vDtf+SQgehlsZVVvlq8wgFMzuXV/W14=,tag:nEj1SNxZgn9+AYcTmcRQeA==,type:str]
    version: 3.13.3
