apiVersion: v1
kind: Secret
metadata:
    name: bambuddy-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:qgTqDXNLL8Tjo+QdU3uwqCylAicYubY/M8ekDBx5jMU=,iv:YVFK8la+lVmRHZCMDJpW6Cs+jedJ6kgExZaMfuoqWmc=,tag:CVKeztlKIbz/0TAGKjxDyQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:HIEs70BRUdcSZQu91hvDILLyxAm5N8ciuQ6iBkkZWLBro6b5ir1vQLhU+rOnwq7vA2f/5h+wzZkjGFZsBTZFFg==,iv:JZEHGl+8LhBqQh+3V0UnoqSY6eR0dPRGSihM8ZoPRRw=,tag:X47f7HRJgvGXQPC9W6rShw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZU9yMTFBQ0phcGduTUl3
            NTAydHRiMXdYSlhrVG9NT1VIaEFFRmJQNTI4CkhheC9JdVhJVkNVMnhtWWtsVU1C
            VUsyQVdQVVplL29vS1hoS2hPVmpvYlEKLS0tIFlGRjVFdXZFNmN2RXR5ZkVua095
            bUZvYVhjY0xsMlplbmoxTmJ5b3JZNEUKNPK1/I6+BEHL6oNM1sho+HzQuoJIPKeE
            RN/3Lr5VyKF5uY+ZDsEfoLgt08GgyfemvqlRAymmSEnT26kVZBxkVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T11:00:39Z"
    mac: ENC[AES256_GCM,data:+JJSrWLAOYpJVThAufBJg48I4h6yz3oaCDLAdgXkyky0rrLYuNQb5c/SXToXXEXZuJgwe0XuLN5DLtMPv5kwVUgQTXaZDePmBffqp729+6zrXDR02CFyZfdOplWF0yFlGZkNuLZExgKbcDKR+6HsNEIP6I/kzJev+iTiTSD+8T4=,iv:/Wvz9UDJDbthGNihZ2v0Jwdq5Zgyx4rRfvdzzNbkXpY=,tag:4+5Z8FrZRSB8HToTD1NF9w==,type:str]
    version: 3.13.3
