apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:ywwwfnEQxKFacz4HPXM1VcB/fIl1m/vnd2Y7cyBysuA=,iv:kTDwIG5zlXELcrSdO4WxLnJlz0krBumb11mNdAdZ7iY=,tag:XeIJnLC+IuZMaMjnKykWBA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:f5GVKCJEdyjSotcSbbJn0YvJL+qbNfKhAcm73RbSZ+7ul00dNPcVXMjOq2NaNiWmXkYDEkDflT+mj9aH0p/IVQ==,iv:tAItDGcWO/GotzeOX1RACVKjrZ9X4/mylchkW5iCUyM=,tag:b6tlK6u38hPuIgu3tYlZyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxazEzUk5vMEJyY0p2Tmtl
            eGcvU1VyZ3l2aWpQQk1wSk9sdUJvbkJ2TGx3CkltZXBXMFI1TGFXbHZkZ1krMVRr
            UGg0WFJROHhMNmdTd21ldmlXNkMwOUEKLS0tIDk3UmFWTTN5UDhGUTF1VFhiVDEv
            ZnlEby9GZGo5d3hVa2FTMkd6eElNWUUK7OVr1rnRNt/Rcq04W7hcHp0m7ry1lF47
            cEZC1tHwE00xnRyqZV/WInee5fGz9by1SIHEBN9gn9UoqVBrNsoeCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:43:30Z"
    mac: ENC[AES256_GCM,data:vgshoKUBYvLjXnZ+DgQHlfMZY+JyhuW7m5ojZrBQ2nyCr3/PEgEbcwzikHMLi8XoZPpxJJsDsRxLZ1YLzyl48Vc1BhpvRHMEnIwl3xNjguArRVKA1BH/aI3w/VMtxM/K8TQ5fwtSnx/yqnHimxjTTbCkae5vU4GOe0uYF4MzWEs=,iv:BIBKN3YjDg0Z8ytBvrap7TvIIfBzA6fWe+xiPXoDA6Y=,tag:pvoDfCAwb/qR9IOVeKi3+w==,type:str]
    version: 3.13.3
