apiVersion: v1
kind: Secret
metadata:
    name: continuwuity-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: comms
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Rw5iIfDaQSywfAKvQ9/IEgNxdmZMFXP50YoCjn5FEBs=,iv:XIy5gc3zVg2Zaj8Ug/76ZZgccE3GfrCYm1o3dQQIEGw=,tag:Ki7dKVY6WKoCncfQqGpQnQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:b/O0XX8TpOXvmsgTe/vhXSSCP0NesoEx9OYoV1cObwDyACpSLAzdlfnQRw6fBSn6Yjc3Agudh+No9XsCWKvXqH6fMuIOGS1wT5R22AAGsmilHZTu1s0=,iv:UBc40M0HdF4qBA9CZVK4uBlS/sjnkEgSDTsONZIqGPg=,tag:IwVT9QatKgg6tVV8M/0Ucg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV0JwMmozRFU4eVNtQm4w
            VTMwVVVwZjVOSnMzelZKc0VPaWpydjdRNFQ4CkJ5ZmRtU0lPa0hQWmlVK0NjSzZJ
            WDRsSklIQ3ptbzhFWk1jd05kRGhkT0UKLS0tIHVjRWs3WUFhQkFiRTlheGZiSkJy
            bWJ4SjAwRzdDenNObVc1dk12WmxuSjAK7NG9i91hpzKxX3grvyhQSsbRFoc7ddJq
            xO7ksQahEZEEEE0xdsZYJEMhg+t65a1ed8T9vx6GplqEZfJVE7hc2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T23:59:03Z"
    mac: ENC[AES256_GCM,data:pEwGXl7V7pERjiwhFm8Vc49+jrN5CrzjpUNi4jmijtjkhHzyLWgeNEvVFl7U6X1xoSjbCOoZZfdkPB05B9XAR3wyeZ2UTO8SjpLQ0a7l88K9SutphhmUHsqj74Ul25g43ySfuPD4hOYfnHmf3vY5Rrd4a2CbSKTRBXKPUE+pK+0=,iv:g1HOToxcR3ogx3tZxLYxY4CAFLX15vQx1Vj/2P+JC98=,tag:KEMFkVfS74ViHwAu++O6rQ==,type:str]
    version: 3.13.3
