apiVersion: v1
data:
    CLIENT_ID: ENC[AES256_GCM,data:0fbjnA6s/+ibxEo+j0a9bh5jsvnnaBjYnnUdJHzWC7DhwVOhn/st2wqtE1+OHkdpN4yE3bCtlpSUUzr7kMCJlJeyqW4/xpPQ8O/31NLeC4QRkDs8qqZPwQ==,iv:6Ea7/UzzgTgg7a0lO8sspBIgHUixvcAFRJz9pS76Gi0=,tag:/lmRxNMfLmlvymoDIwhdtQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:CpNRvMzx9az7o08D+fTPZmQx+1nAcP82P1ENpw952BxytKJor6pe2NDIFWg1wM+XWHAJ4qHCXM3Ii2OdI1YUD2HbB8km9kpkf6hfZyi/hsPOlv/svB/Ys3QvOD2jCYjyvnK+x4Q7TMZ9Dx4Wa1ssg3A5DD9LvQPhF5Ll8xFUx7g=,iv:xTgvSVZXTrmcaifc50ElYKJFVEI4U6QXnMkD2wsxQ3Y=,tag:Clkt0ChwsJpBM4/LKjfwLA==,type:str]
kind: Secret
metadata:
    name: dawarich-sso-secret
    namespace: authentik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1b1gvN2t5QS9qc0FCdko3
            NFZxUmU4bVZSenpMNWQwTWJDYUlITXNXLzFFCmdQbFdWN3BBZFk5aHJsOEgzRUZH
            Wm5BQU1VTFR2WkpRQ0kvZmY0WWZtV0EKLS0tIDRMMnh4RERCTm94T2k3UTFUeGY0
            UExHZGFuNjFJYkNpN0VNN0tKdzh3dUUKXEuyNzSYISwdLNsy/42MFEGiZqnSOsQY
            +JPZEpmtqSuOMmU6+y3DBvT2JQQwPvPm2KovwpGQ33E8TCXNR2ZE8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:38:00Z"
    mac: ENC[AES256_GCM,data:ZZlNJWQTD5gUp5n7GsuDQdskPAe34wVVV84fzOS4Tj3CkjwXcDO+d7yeOLQuhntFZXzshourRTbdgz4kYseOV+nzzZ+y0gJqlmOGpLVnkftgBy1WiUZniPUR9F/XRLu5UkiME907gj+7GvNv18ctpAHG/suz8Z2SfjP8JP8g+Rc=,iv:4nrTIuvUp+FQbDYHgACFaa41SFa3R5sRcM9rCe2yOBg=,tag:NF/Qvw27dljr1oKPDxPorw==,type:str]
    version: 3.13.1
