apiVersion: v1
data:
    CLIENT_ID: ENC[AES256_GCM,data:0fbjnA6s/+ibxEo+j0a9bh5jsvnnaBjYnnUdJHzWC7DhwVOhn/st2wqtE1+OHkdpN4yE3bCtlpSUUzr7kMCJlJeyqW4/xpPQ8O/31NLeC4QRkDs8qqZPwQ==,iv:6Ea7/UzzgTgg7a0lO8sspBIgHUixvcAFRJz9pS76Gi0=,tag:/lmRxNMfLmlvymoDIwhdtQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:CpNRvMzx9az7o08D+fTPZmQx+1nAcP82P1ENpw952BxytKJor6pe2NDIFWg1wM+XWHAJ4qHCXM3Ii2OdI1YUD2HbB8km9kpkf6hfZyi/hsPOlv/svB/Ys3QvOD2jCYjyvnK+x4Q7TMZ9Dx4Wa1ssg3A5DD9LvQPhF5Ll8xFUx7g=,iv:xTgvSVZXTrmcaifc50ElYKJFVEI4U6QXnMkD2wsxQ3Y=,tag:Clkt0ChwsJpBM4/LKjfwLA==,type:str]
kind: Secret
metadata:
    name: dawarich-sso-secret
    namespace: authentik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNWNpYkRldGZLeGdMKy9o
            YktZQkN0L2FQY21LTWVUNVRpbm1nazZ5YkdvClQ4NitqWGJ6enBRNGxGWGRyMTRp
            YUY4ZkZRaVMrVlNlTGZtVFpHRkdSNXcKLS0tIHBBMFZBc3NabWFZcnN3SUErVFF0
            UmRmaFZ1V0F6MkpsR3lucDYzU1hwRGMKLGI60YUbt7Kal2QF+C8hrjZKbVtkk054
            UJoYey8Q7mBwV7XcVEuRAHzsF58uaWYNo8FG4pnYm2KRwRivDlTpPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:38:00Z"
    mac: ENC[AES256_GCM,data:ZZlNJWQTD5gUp5n7GsuDQdskPAe34wVVV84fzOS4Tj3CkjwXcDO+d7yeOLQuhntFZXzshourRTbdgz4kYseOV+nzzZ+y0gJqlmOGpLVnkftgBy1WiUZniPUR9F/XRLu5UkiME907gj+7GvNv18ctpAHG/suz8Z2SfjP8JP8g+Rc=,iv:4nrTIuvUp+FQbDYHgACFaa41SFa3R5sRcM9rCe2yOBg=,tag:NF/Qvw27dljr1oKPDxPorw==,type:str]
    version: 3.13.1
