apiVersion: v1
data:
    CLIENT_ID: ENC[AES256_GCM,data:aXHDxcn4K9p8mPOcvjvp7Dh2n752DvCKlpKxcw4MwV3FBJz+shnBRv8YV/hpmw2yQM4arAwmi66NseLn3xCkAXuX7EdmzTCOO0W9kVOY3OVjXhHqt0b5pA==,iv:k+W4qsBznnr92iWzrhalOLnP5E+6HGR/Wh6Ia/NHqY4=,tag:wQSWUw72A6AuXEyQlihlIQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:IWqv4RZ0qwyGX3yjLXtssDGqyFpu5csDzR4dqDAw7NqwxktgZ7TqZ+X0iJZEVDa/qecB4lf0/wDzkEy5XY63tGrx9vXplHAv1CqEIiJXV90T9AlCvhY0OVXZGAiuU4OsGEdbVRe5/IWg0U0jLmDI2nXWJ9UheHgVZeJhichXCrg=,iv:Mp6zOWLEmp+kgKwdO75UXc+gfxJ3spZ5GdPi3u3Emgw=,tag:ZkhAm5mvgYaEPSXLUB+71g==,type:str]
kind: Secret
metadata:
    name: dawarich-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:CmT94zY8BLWC9WD4quJsedWbRyMW/mXT4YkEneSy4t4=,iv:C04qFGw4siktQMbiX8Uar4Vm5JqHKdboBdpeEATXa00=,tag:PqeDfy/qUtH2GzkVDylk0A==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:99MfHPaFxIl97F6FfjnCNTzrNgjKAOKOHFOfKBd1IWlwR2s+mfGSFt7E4HCE2eeYn8A0aR3YRdTOPFUEEhxetA==,iv:UZhVJgm5Sbb6BTYg7g1pNnEEGvsamEEzr2LoqUC7r+U=,tag:Z/pcCRTLOOmIs2b/0sHViA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YTZHNVpJR0RkdEl5SFNU
            bzdZRGxVWmV4em5aMTVFOHBiMzhaWXl2LzJNClRKRStvRzFoRVlJeEZyeTRwbWdL
            Smhmd0NITnErcHlCalBIY29mL3NxKzAKLS0tIDZ0eUJUTE5oa3hoSURacHdSLzN2
            RGRjVko4ejlWMkhXU1FKbzZXankyREkKt8W+/c1mphymy3I5+ouG520tbig+eYjT
            GXgBGDrAxt99qrE6CLn9nNqDClD8kcVTyjZideCFEMBiqA9kSyR4gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T23:03:15Z"
    mac: ENC[AES256_GCM,data:OKFo2Viji+PON7mW3c2WRM1j0fGsMgqG/gs6hBc5B7Gk5KQnKujIaHqXmTfZczWA04SgBJqiApxJYcIvQbaBeiqt6H/ucNYoJ7CYSiucGoDVHSQ0oTi0CVjmMCWE9ikXMsebLHhkO6Z8EaGf2eKVD+S5ajViBgmQXL7OMFRd4Vo=,iv:mYf33hc7rE0xFqi5x1VLPbekjedIiWLGID4qBQLoIOE=,tag:Y7mV6hi9AmuYJhOO5T5/TQ==,type:str]
    version: 3.13.3
