apiVersion: v1
kind: Secret
metadata:
    name: discord-auth-secret
    namespace: authentik
type: Opaque
stringData:
    BASIC_AUTH: ENC[AES256_GCM,data:WbChqcwFIk4FfGiCYOrP/Pvo8sAv1TtD3f6gPMCZztrGZCwiSs8D8hpOfncLCxbSz4ik0ur60gEXWp0CxK/9wdgJC0hwhw==,iv:zz165ghQ7WTchmyz61zITQQcsxJAAJB099hQoNEy3x4=,tag:G7Rb701VdPn5EoiYj9aehQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOU9HMmtaY2NXQzZxLytE
            Z29oMVIxU2Fsb0YzenE3RXhZdG1YSkd5V0JrCkJMSGZCeHljVUFlaENURWtrVnll
            VWFnVWh0cWZ6Tm1QWUp0MHZIUEx2WFEKLS0tIFZuRzFoSHZyVDBTTEVzd05tQmNq
            TVFmdS9FVTFxMms0TlkvSFM3TVRaaUUKRfTT7xggvDQonctBRZPQUGi70Wed9C8T
            VyeTzP/BkVOY5nj5K4V6FwJMyV6s54BKCJ2TCZtwpz3GN+XwjWNbFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-14T22:30:33Z"
    mac: ENC[AES256_GCM,data:V4xG5g6LkvUZbK6a/bt0ra9rOvnMfWhjm2aSlIXdURhzi2HhBV72QA/SMtRbZo6pAscLa5e6Q2shmXZYs8OGux7lFnb4kEYO525MAaiSAhj6lCqSIVp1341qf28WKoJpdGi6cxK9rVckzSFaCIeSi9sq1mBNAdu9gc/G0VW1yxk=,iv:WQvQtvjWPfVhqJm2v1GseCoHkp8Hr4/SUj5gnpaxURA=,tag:ulYAoBSSv/VYXMUGN9DtlQ==,type:str]
    version: 3.11.0
