apiVersion: v1
kind: Secret
metadata:
    name: gitea-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: development
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:/VtWhyFB0qrfc7njMoikumZbEZ0Jm5+SUu2zx1uhGmw=,iv:7jd4jAq1q0tIdj11ROVtrNwocTczaLkzvuhr9n8Gxd8=,tag:BkoMr+XsetNxa24dv3J/uQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:15h/iHVNgVmxWFBNf2WFIHw/AjV/ULdF0QQ+jCX1DujiM3h0e3PBHJs9KiBaIpnpxRJyK/MeiEjMlfGR6Iv85Q==,iv:lRHIS6LXpYBXtKcCqYWDrrQB1J+Vc0M5kQ3mO4JV9bM=,tag:Vd2ZLzhEWioKxFtffTxSfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNW9yTkNzRVVCckdwcFVV
            UkFXckUvOEI2Q1gzUlhER2lPVFI5UTN2ZWlNCktTVHJWWjczbEhWeld0Z2NIUERH
            M0VHUm9ZRUQvTGp6YVZ0clVMRXBhdDAKLS0tIEJITytraUZCTXFKaHhhZzRvNmw2
            MVA2Nk5BdGtTdHlkN0VvQXM5RXJJUzQKVvAvbKbAIduio7khVn+uJNgZa7o2LSMA
            mutYpxQKQohTko96mWtNW94jRfdFPnpCnwck+DtX/vC1pQrZzxWzyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T01:09:04Z"
    mac: ENC[AES256_GCM,data:OfEhWaxdaxw7L6KnoAZPBWvcWt3OGm0NDrVwp70ikqtwpp15k4BnllPlcFOXk4uOzenqZWe0YtfPxxJSlAazslzmBxhlhP7jo2VXU0mTey59SOGelu/Ljr3Gbw7ilZUGYSTZ6LN7fRHFLdhsrx0FcMsgY0gGQpKPCyfpPogwj3w=,iv:Cvy63N11BDvgr9vrAyTyHTykQZnfJRQ6f1uzZshKrD0=,tag:sLhLJ1CxRYFvtOeDxbIw+Q==,type:str]
    version: 3.11.0
