apiVersion: v1
kind: Secret
metadata:
    name: gitea-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: development
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:DInxuGGQeya9fAiBFt4ZkszAgbzA0vmLcIYM/W0DECIUMWCr3MVw7g==,iv:oTWRmJYx5VZhWB/4fXGWi0NHpNzMNAi+Jc/GP2/P2B8=,tag:aYREJ60y9KNkGQhZU9WJEA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:XIXp79Q0kAAAyHIUaBJWJG3wQR7fhobtCwLvz7xiu4kSsIru3kr14ul/Jqadu9+BRAx7N4gN/yxI2XULgIAPTra+ltvUv2MpjBMtKpdlzbmx7V0ZmsZuDjcIpY8EEZ2TRcnkGCCqctrLjf3J1IFmtI2nJmqX0sz8B0Z2FwNM520=,iv:rhj36PfDsyuUWMOmcJGqBYEE7ymWsDzx5HyK3pSNCoY=,tag:MKHMpzi4qILE01xsBsT+yQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNW9yTkNzRVVCckdwcFVV
            UkFXckUvOEI2Q1gzUlhER2lPVFI5UTN2ZWlNCktTVHJWWjczbEhWeld0Z2NIUERH
            M0VHUm9ZRUQvTGp6YVZ0clVMRXBhdDAKLS0tIEJITytraUZCTXFKaHhhZzRvNmw2
            MVA2Nk5BdGtTdHlkN0VvQXM5RXJJUzQKVvAvbKbAIduio7khVn+uJNgZa7o2LSMA
            mutYpxQKQohTko96mWtNW94jRfdFPnpCnwck+DtX/vC1pQrZzxWzyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-05T00:51:18Z"
    mac: ENC[AES256_GCM,data:KmxaiFu70bLRUSEdZvAEq/mWQPxj5PTwkXA68FhRfEZAX9TalQ17MX881qPezXJXfK2almuNLIVSOnXHB384GDBBdx1cT4cB0ZdgZwso7MtKpF8zCHKMtXnaM2enJ7UoURIFlmdz+ikqFDXM/g6k/rG8M6RXoqYk74hH7Bat0uY=,iv:ceLTjCH6eba7EM+nrGM21uInRADUlAEMeqgBHuiEHFY=,tag:tFvavlacfXLXcDSu5Hty5g==,type:str]
    version: 3.11.0
