apiVersion: v1
kind: Secret
metadata:
    name: grafana-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: observability
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Hg9mYpxGSSTK/wdiUBTEvokU/Iv/LnTPh4c7lZbwlGYfWptNE1klfg==,iv:zjRuvWtDnVVXOBsL/TcQrnD2arImQDwYgt4x1Pgk6E0=,tag:JjPo8c3jCWZIZsiCXKHkLQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:j5sLEM/+E3ukU2kAgrkkNKHFNK2lzDEXXB5TePGG2YMYTVEqJ/tflFKLgsVI8BrA5sy/jnkQNsJU571iLGHkzF2LqSO9HeP2VMB4zHAKHbQ5khmLNwHVLgD+4D9GZIdgFKJGxHmUASb8R/DlOHjTVomFgp9l0fwOwRRZsQ4aoA4=,iv:caiTsqHdv8pcGKY1Da5o1A6qLkiWwIF/4jp2MgLUCW0=,tag:W7peIq69eAGp5mO9VQlniw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleXlLOEg5dEY0YloyaTBo
            ektiaDBseE5xV3ZOSVExV1crSVkvUmQ2NDJnCitqYWVtb1pkU2NjTSsrZWhPa0E0
            ZW55dVlRM2p2cnRPNVFNNGpjTHYzUFkKLS0tIHQ1dG9yUHBidHB1OUd4ckZoWjFC
            NzF3VXROdWk4ZXZoUWRIWjV1NFdURkUKwPS4A1RZ7iEO+CBExz46Tahpmr4wPN7y
            fZ1prcHbnJZju6d5jgdw9Olukz5EeC9t1v6vysiSmHbzCJ7+J6bjHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-23T20:16:20Z"
    mac: ENC[AES256_GCM,data:p4LOtRGHYN2ErJlzr9yF11GNo8o0l1vQeyU7Hpfv3xAH7hCXViHPrA8uABuDsvjXbGBKdBzjSjMJt26IGevs6lHfqXpqY6SVWZtbPrFCMvVUuWVZsTCZaRYHyjVAe2Df7zuQ5w1Q+qzH9zxZi3cDj9/9u6s8zIL4BxYD+Vj5uAM=,iv:97o1VPg1wUsI8tidxNUVujJm2yDiqfRcBSFgWEg4rIQ=,tag:V0uVHI8Q+/HVL+qvq8Ymjg==,type:str]
    version: 3.11.0
