apiVersion: v1
kind: Secret
metadata:
    name: grafana-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: observability
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:nWzB/6IVySC377ZShD/tPK2Tzdnu9rh6mmLMJdsXW7I=,iv:fic1Pv3OXVkI9r0nRYK69yE4qghbi2vZBZN3sUHTMQw=,tag:Qd2B0JttCfBpOTGPZ4YFIA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:PwecUPiym+zFJMt05Mckr57z/pOlHnAdKFKs+M+fFkYQjfZ3cwBG1er2FtjKaRqQfgjHhtaHpQMl5v6riaZLPA==,iv:0y1Rci3GWbLA0kAHwq0lDB1sN/68r5spOirqb0nB270=,tag:TBH3tl1Ua1j2v0EN2IeJGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleXlLOEg5dEY0YloyaTBo
            ektiaDBseE5xV3ZOSVExV1crSVkvUmQ2NDJnCitqYWVtb1pkU2NjTSsrZWhPa0E0
            ZW55dVlRM2p2cnRPNVFNNGpjTHYzUFkKLS0tIHQ1dG9yUHBidHB1OUd4ckZoWjFC
            NzF3VXROdWk4ZXZoUWRIWjV1NFdURkUKwPS4A1RZ7iEO+CBExz46Tahpmr4wPN7y
            fZ1prcHbnJZju6d5jgdw9Olukz5EeC9t1v6vysiSmHbzCJ7+J6bjHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T00:03:56Z"
    mac: ENC[AES256_GCM,data:VGtJ4KctLBYjU1Pp/CR2GgtXw+W87PBosn+j8mLLu9n8+nZ+dQwfBO3SvqFkGJDSOgPMD5FPL+yMb8nHU1TPRwoqvshvvZrYfU77s+ep69shZlfkbvJwo2gSt+WqXEA3b87n/rHN9vfYoBP6IjkAtysb012TbOCZaTiyXVxMcX8=,iv:cEWy3ZtI3TaSSfX/epAEyVui1q3DspBApU8dNp6eGsU=,tag:1rQtHe14TvjV56nsMVgQmQ==,type:str]
    version: 3.11.0
