apiVersion: v1
kind: Secret
metadata:
    name: harbor-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: harbor
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:d1pZvyeX,iv:Pw95C+n1IyaIXDPBwqa6ytSZ/WpOaCQF/IlycMH5ci0=,tag:mb9JT5kT0SooH/t0dnm7Iw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:dek7ZWmgat/aKUqeKblCWRhs2AAbV64Yt4ByDPdBvNt2+3FI1RGMvBup95sKMQ9VLsce3hNj9J5VLTh86Tnwk60gCW3T7xqQJ1oJXWjykKWOinmxZq/DlTD8vMeyDfyk,iv:0tpMETdEV8a5NNmk4zQSgckPyVHHudtvMotbjylBbyY=,tag:kxpmbUQbFHOrPKAWWJSfZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY2NJN0VXVXREL1JGaDhj
            S3VqYlhJSUhVNEg1UkpFWERmTjZUTGpOQURzCmVCYzgrNUdsT3hSYkF4MGIxMmtR
            M3ZTYUdDRWNIbkkrSm9VMnJhTWVmZW8KLS0tIHVqcVBDWExHdzhFSzRGb1RnUjZW
            ZkxrNjhZTUxxYy9VVi9WN1JhbEYrUkEKfeTT3jkgsYkONCcg1Oi+qm4cQBwiXGij
            eht+HVqNxjsulv5ppKZ+AmERyZCzE9YU3d56Jw1jMwozQE4wzujwZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T22:40:00Z"
    mac: ENC[AES256_GCM,data:GmUARUB9CXqJeTxTWJOOYRCREF/v5AJo1uB3iVVXFExOBOiHPtt62GyjsfEXUiREktId6V4jLpqfEdLGzFM0GeM7cDJ7vWO/+5rB943GwLSLVaSblP3qoqWYiyIL5rMFeq71Jn2GcH5AFOu7g7baX8cA3qFzFcTScElmdw+f3dY=,iv:qb+ZksTuuV6cIi4TYSYCSSsyKS1jyZXaG+PsG/BmbxA=,tag:pRqebPXpkv7PLisG3TwDJA==,type:str]
    version: 3.13.1
