apiVersion: v1
kind: Secret
metadata:
    name: harbor-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: harbor
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:fOH5TaYqi27MGQ1YEYRIi7OfOGvpudi4l8sNtDp9DIA=,iv:Zvyyfe19CdK0xAfVDmawciRF1QU8d/ydeSRFlHGaCTA=,tag:3PALLMHRfvs4T1rXCws/Dg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:X9G9hPFPINW7cTw2mc6A20GaM84bVHBVWv7FI+vvKUyq5f+kR5f0zbpteszWqRimUjgItB/S6fr/CEi20D7yww==,iv:0yMRmEB4u5Xlj72TBnC0y4LVegSVSxhyqe5ESBB17PI=,tag:BocILGkTiIwhQUDCikv1Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUnI2Nk9DTGhMalhYa1ZR
            NTkrSXZsYU82QjA5ZmJrR0x1MFBVUlNDMWg4CjZ6WU0wNHNsWWpuekVTTkRucVJH
            SE1lTFE5aFM4SHg1b2wwNmt3THR1TFEKLS0tIGdiMVVZQW4vTit2QTBqU09kdFBT
            L3NiSXNxOXBtR0NTcC9KQ3dTL2ZnQUEKJByt21wtINdEFbBVK8PofvPG6+ts2FIW
            SrxTxZ83/Xk8qBblinNIon7/HLsobcEHjBqFuoJG7yvGhvh0qgMoQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T00:02:40Z"
    mac: ENC[AES256_GCM,data:Z5k9jH1BKjD22NnnQljEww8xM9IXlTQoQN6tBicZVNafEnXpBNDg1PQys5CXC7y9GZCK2OBqHFcnY21gHP6wYOoagoChuvdY2xj9rXliuJrMSPAx4ssMjloR1wnI9j4h3pzvKWEIJSRcSAEuXV+kzoBEK/GqhCSfwokNeOovtMc=,iv:ug7m2FYRGzR8PA/VdXEjxfGRumz8Y3g37gxPjKf6o9g=,tag:gKJ4wWHy0F8PiulW3GE7Ig==,type:str]
    version: 3.13.1
