apiVersion: v1
kind: Secret
metadata:
    name: harbor-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: harbor
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:d1pZvyeX,iv:Pw95C+n1IyaIXDPBwqa6ytSZ/WpOaCQF/IlycMH5ci0=,tag:mb9JT5kT0SooH/t0dnm7Iw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:dek7ZWmgat/aKUqeKblCWRhs2AAbV64Yt4ByDPdBvNt2+3FI1RGMvBup95sKMQ9VLsce3hNj9J5VLTh86Tnwk60gCW3T7xqQJ1oJXWjykKWOinmxZq/DlTD8vMeyDfyk,iv:0tpMETdEV8a5NNmk4zQSgckPyVHHudtvMotbjylBbyY=,tag:kxpmbUQbFHOrPKAWWJSfZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUnI2Nk9DTGhMalhYa1ZR
            NTkrSXZsYU82QjA5ZmJrR0x1MFBVUlNDMWg4CjZ6WU0wNHNsWWpuekVTTkRucVJH
            SE1lTFE5aFM4SHg1b2wwNmt3THR1TFEKLS0tIGdiMVVZQW4vTit2QTBqU09kdFBT
            L3NiSXNxOXBtR0NTcC9KQ3dTL2ZnQUEKJByt21wtINdEFbBVK8PofvPG6+ts2FIW
            SrxTxZ83/Xk8qBblinNIon7/HLsobcEHjBqFuoJG7yvGhvh0qgMoQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T22:40:00Z"
    mac: ENC[AES256_GCM,data:GmUARUB9CXqJeTxTWJOOYRCREF/v5AJo1uB3iVVXFExOBOiHPtt62GyjsfEXUiREktId6V4jLpqfEdLGzFM0GeM7cDJ7vWO/+5rB943GwLSLVaSblP3qoqWYiyIL5rMFeq71Jn2GcH5AFOu7g7baX8cA3qFzFcTScElmdw+f3dY=,iv:qb+ZksTuuV6cIi4TYSYCSSsyKS1jyZXaG+PsG/BmbxA=,tag:pRqebPXpkv7PLisG3TwDJA==,type:str]
    version: 3.13.1
