apiVersion: v1
kind: Secret
metadata:
    name: hermes-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Wx8+VmPicyiC/C4huqYixtqaIqPIE3vOARMgZFiMRlZTWbISHPVf,iv:LcCmsT/FWd+kPW3XvvsFI96W7dfT/1HlKUK9RcPlc3U=,tag:T5ZPsgueMyznHkF/LkcYtw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:/ydpWIf7Z4Bk6AxVO7hwPDXyKpoT7SsUAfFyZGMgFDNpbu48QiLASMRFWWAw9rt7t6vA7sLyTOzbdO5dsORVNQ==,iv:enuAv9+FNTWFGRn2PBCijI6o0RatpqsNiRAhDftSB7g=,tag:w3I+aQgYTGuP3dyds8rWMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaam5ldEE3SGMvSE5RNEtS
            OFA0UVlYWkl5Z1NpT201c2xSMVB1ZTdxeFd3CmhMWnEraWd0dk5GWHJhR3JucVhY
            MnI0MnBrN3JFSExIUk1mOVpBbTVrVDgKLS0tIDMxZ0hWWGVaN1liZVhnOHR6dlIw
            bmQ4OEgxU3ZqbUozN3M4VkRNTnVnNDQKf8j/pdgGNW25akjy8UPBcPSLdVQuo/XO
            Gy6iXObeH5TcfpoGFCgb12bm9dIm8b0RjsXB3hTfbqyvKmt8Dkgy2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T20:26:01Z"
    mac: ENC[AES256_GCM,data:PijBcaGN5d0vc6EHtxG/ZTReXJfs37jZjtk5LR3UquyP1oObXbfqHM8Wc2gYts3z0uDVPyMDGq/hoz2VHs7EVeUmKBAtiZBsuDCaJ+3RRa6AGZHe6G5JYfyii3bsEkB4TwuqeZDafSmQYTEDqJNYAPeH2BbFVgJS3c7l2Cbhuio=,iv:7meaC3PKseIvUyXi1bh6/MfF5pyJ2qXykgkMNGNYsfw=,tag:wT4VCB09mbLFScQ0I5meVg==,type:str]
    version: 3.13.3
