apiVersion: v1
kind: Secret
metadata:
    name: homepage-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:a1DAH+MYkfcNj2c7icEY2OaT67RASKxn4uepV7W+m5X15Yr1FLW+/yct4Eb4hJ4M,iv:Ol7C5fu10j/ZHqeDlRZfCW3fbkfNismYgU/cGbnKUro=,tag:2wiS48hekaZsLyEQetknsg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:b0xYrxIBuSy2C8/oWPIQ9AQnADUfiBYwV1W3O1aN8rZa1vlGLzDJeDsknH992FvJc+zkDX/+MQlqhCxUUlEtHg==,iv:NWpALWdUJbPEFGM0hLmZnTKJYUOWB+K35Rp81EYlgeU=,tag:8qTgGPdaOzl31o/lzRMNaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRDY3THhSUWVvKzhyNmRH
            MzB2NVNscXhlQmJUSkFHWjhBdXdiWnU1UUdzClRWNU5DbzU2Q3lURm9Wd04zcVE5
            dVJVM2tCajI3QnJDdW1pY0pENVpBZzgKLS0tIHBzYi82eFIzN2xWaFZtWUQwd2Nw
            MlFTWnZRN0hyV2FJcGhBRS9seXNyV3MKHG68/V+1f6NZ2zuF1Ol0aLLxCm4ainPe
            feFNl/NJAnCeRp/JMUZ0UpPa1CE2MRXupmcnQVacZBhHSPh3qQVyOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T13:43:39Z"
    mac: ENC[AES256_GCM,data:Kbas2WJSGQ9GcAQ87B1yoRn6rfjYYl2zBQzwqT2e0Dez0vHRqezr7KJFOIR9Dk31r/mw4+eWZySjqAyRTIl2ZdPkdd8dnmRp+QpBJCpmqPsoyJTNTs9hs3XhnRwaPwDgTrPRhaYESM9ij1bZzaZB/0VkOQSGXlEqAau6M6E9bfU=,iv:/P6oe05xPWA9tUbioe9SWhrJiNPGY874NdyopgrQ6zw=,tag:SV7Kn/QhSmcVO0jrr1PNKQ==,type:str]
    version: 3.13.3
