apiVersion: v1
kind: Secret
metadata:
    name: homepage-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:fYud9X+ezuwV6s3ALRH05tAQrnLcoWfph5RlASaHRemAZrEnSUz05B4cBJXggXZg,iv:H0En6JtvgYQlENgKhGYoJWnR6PoskBfqINKni3KVbpA=,tag:/DfRLpTZu5Ou3lxHc65jew==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:g1V/sCYi4SyZDY9//D659niKjtPvBK2lM0VY6sgBp6yeQUzNABbsvNLJJniLNhWFShsl8+bThIWke3NqzUP3tQ==,iv:w3s7aRFC05419NbQ1hP9SrzqvoUkNO7oiKjygMjfvt4=,tag:EfDSCiaUNA3TxcA85WpJFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQlBmZHI4cUdZcmpWWnpH
            bGU2S1k4VFNkK3VxK1FtdVI5TlZOV1ZJekNrCkhEV3RMQmlkUGhycjB2c2RzckhN
            WHo1dWxseGRrWEcvRStXVU1OQTArYjgKLS0tIGtyTHhRYXFOTjVESFNBUVk4L1hU
            Qm5MM0U1bk41T1U3bm9CdmxHV1VYdVEKh5Zx6DyjFPsT+mcrM7Y6vn3s8DTsCVas
            FygOwTLcZdfLVF3D5BiV67q1r4ElBcdy+imRrIzVWD6+RfjxluhaYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T13:31:37Z"
    mac: ENC[AES256_GCM,data:Vl2V81ZI4lD2lOlhbaltxAN9zGUyFICqU07TL0aftj1pbtWCqJIiNu7OZNggK+2FNI+gL2/OxPHWceQYMn6HEbQOL8+oLwabSMF61rKYIfukBm1EyMmyNHF8IRMJ7JzIAqCVoyP48/6ijITsbrCmUkfMCKdPx2XuryJ9z5G23uU=,iv:UQfvlA7n4up+HNiGz5nTSZGhZYGGO1tc4cGNSQrsepI=,tag:4B1Ru/VvQDR8RxZFAwmZjQ==,type:str]
    version: 3.13.3
