apiVersion: v1
kind: Secret
metadata:
    name: immich-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: immich
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:RoMMkOPOnxkTPQxLlZA7Y3OB9TNGb1hLfiaSHhsli3sM/AXkQq7C5w==,iv:BXnnx/lW/BzCupwYg1PCWF+5wT8e/gV1zztEa4bJzjE=,tag:R1BiVXRvNQHCYHrw/msd/g==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:dgKXheajZDJrpyhFuMbwB1swtyPr4vH2Y7s5ejgSZEGiLyZYw8VKHP6L4aszUHB+njov9he465vk/hW7jBfiT6pWhlrTjZSXWhfRIlTjTGYDozHmIvMoierVbiCAPteOmPcNFFJMHi2LQOsMwwbSHxe6MkZgmM8ZfB1Vpabh0Rc=,iv:b0ofIkTHVFxEl3GxFUaJQ3Mop9xTFutN8dfDm0XiJZI=,tag:WvctIMEVBEDQsN21qNHNVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRFJQY0U3T2tVRjhsVXd5
            R0JZUUdVTTBGN3dWWXQzZEUzek80ZHdLdVMwCi9sRWxtdXNoNWp2RnBnUkFaK1l0
            Z3JqKzBPcENWVzA5UEdjcVhJaVR2OUEKLS0tIE5OWDdrUG9hVllhcCtob0FrbkxL
            MERKd1d6MlgvMzhhQVdWRnh0emlPZk0K77JxDBLyoUPRj80JPq/tPfpa3a5H7H/g
            pxNiu1OEJtUvN75xBAfckbtOPF9GTY09ixzwd8J+QbnkRAbHO2A/KQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-20T23:52:02Z"
    mac: ENC[AES256_GCM,data:V1j+qfYw+sWHxddjpzS2kMpkiAQyD1M4pis46DatTX25METm55bzJwCwxm9nSsuy6Psab5NjupsxK2nbi/YI/YIc9BCNAQK3vEETx7S/rWFqUJ4eXFF41p2PTaZosZlh4LOKp2tgdILqtwM6qMONScsY9hmSXyBaS6YQSCIQbTc=,iv:LGqHYoAyV33qTbFv4RhHEGmhb3mgSzhVMzap0UYiZEE=,tag:5ToLndES5/++SwoXqWBKaw==,type:str]
    version: 3.12.0
