apiVersion: v1
kind: Secret
metadata:
    name: immich-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: immich
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:rqckZEI5QUMPyATYbFMhN8IsPxy4GRn++VTefL57W9w=,iv:offqjbVyZuDlNeA3DimV35NQvTO/blx934EozA/rd9c=,tag:NvD81k7TaCU6lrqPURbnqw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:luQjEqwgGij0TRhwBxvfD9u0A1PLxEyPj+cegb/rizpf9nZX41y38dYc50Sdmd8nBmr0lzYTvDISNpIJZuBxNA==,iv:zJb0q5VDSdt69NEZI8u7H0/mWvGjM5J82V7lb+xZDu4=,tag:HQtaatE7Sn/66CiyW4B9Wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRFJQY0U3T2tVRjhsVXd5
            R0JZUUdVTTBGN3dWWXQzZEUzek80ZHdLdVMwCi9sRWxtdXNoNWp2RnBnUkFaK1l0
            Z3JqKzBPcENWVzA5UEdjcVhJaVR2OUEKLS0tIE5OWDdrUG9hVllhcCtob0FrbkxL
            MERKd1d6MlgvMzhhQVdWRnh0emlPZk0K77JxDBLyoUPRj80JPq/tPfpa3a5H7H/g
            pxNiu1OEJtUvN75xBAfckbtOPF9GTY09ixzwd8J+QbnkRAbHO2A/KQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T01:17:49Z"
    mac: ENC[AES256_GCM,data:3CGmP8aQfpqc/NqfiNbUIFZ/jjLCGtTmZUuilxSHtfNSYC0Gxq0e0O0UywxpHQEBt012INTGYGipDYTT5qOGFlFhAT8eid4o0PxjuIqBmdQ6YA1zbcVD0j+jeqvX3et7MN0to3AlBU9Vmc8hp6xmIC1Ek+BETmfxMWMeJ49Shzs=,iv:5mB7LrjvSyb/I5aNM0wQ13zbm3jaj2ulQDKgJTq+hJw=,tag:5NTHpYnnTNg3nExsMgxoqg==,type:str]
    version: 3.12.0
