apiVersion: v1
kind: Secret
metadata:
    name: karakeep-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:51OQ2V7Ilxib2X5d/BJUvWy4kAa0IyYnktQGcGAVBSI=,iv:UoYZZ1x2OjMnfbSjYDcRBIZ6BYyUIGZ0MwPMs/c1c2M=,tag:myp34Afm4OZr6/BXWjS5ag==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:tzUajSd+pBSdwyt7vCDm7MlDhVo3yjI0gnz84dUuiXG41mvJ432Hd9VI7r3A7vENxm8Topwj9yR7J+XB934roA==,iv:l8az7r9vuakagdHhrOBtIWvRhI1FLbSgBiBO9GjoC/Q=,tag:AE/74/R4eHYPSNnOgbXLFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ0pNWEJRQ0xjc3R4SUp3
            ajBoOWlQOVRGU01qVU5IblZaWTlSQXI1VjJrCjJwSktPckVHNEM5WXdXbHRvdUdl
            MU12a2dZWkVjRmkvOTNZYktQSExCRjQKLS0tIDFtdC9vbkExRnVFSTR1VG9LREg0
            d0djSmd4NDhZWkN5ekVIQTJGQjBtdHcK/cDE8kDdu8UErnZFAFGr0TKKKUen7mxs
            XWsEp++8BMvEcXheFWqq7KF/FkGCr13GiRETaZjdB+8lqF9TFlHjDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T23:03:15Z"
    mac: ENC[AES256_GCM,data:xq3zewboU9d2Jkj3F+c264FRdtFAJ50ktPSEW2HwKWNvmM9S0YSf6nsqAuc5gQP9R9OpPp5eIGUZ9pvIk8aF0kp8qgypfau4Q6KJL5ba5dva61mJ4W2Xkb5V1mI2Nv+/rDmlD4/pOghotQqG2qaGkNgjHw2Qc4ZdrwRrbYHRH6s=,iv:TtnL60cmSXPu8cuDCXZuNVYmLRaNUsOl1Fe4w9ikv2Y=,tag:jESfkPwum2RiMFIrlvAM/Q==,type:str]
    version: 3.13.3
