apiVersion: v1
kind: Secret
metadata:
    name: karakeep-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Tjb3hY1ynV9WwAbW6/fCEVMqX4yYwETld7ewZCvRxpLa2hrdy0aRQ2Mz9FRqb43C,iv:XApUPVK00zEK4YZdYD37U7UBgaSE/oc+lvPeQSqHa08=,tag:5e8f/o67dWmAPMTrGKMPjw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:jSz8LzEUOB++F66eCwBMJIBBjyVduaWX/EhL5gOv6k6AVaXApMo0XdCBcggtYzPp,iv:tnWWS7n3GYgEaDLywcCnggFqX0AlDQvRwt1wSq2fcAU=,tag:4BTiYmTo4e1mOgomDSdPIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybHVubytpT3IrVWkyMEVu
            OXVEcGdCRmc0Qk1ZWVduMTdwMWtDYllmQ2dzCjNFdWQzUkUyTEh2SCtNeU1iUTh1
            Y1ZxRVFMOXc3Q0szZkZpWGpqZ0RIVUUKLS0tIDdFeVJlT25iNWd1ZVlWbzd6T2x6
            SCs0dndadzFBVXdpRm9SYU1YT0FVWE0KNubdKYfjohkKLb6TOQ+REsoXLTXpMtSL
            NJ3wZsSozy/g6/XM1hr8gMPkx0tGL5YmN2+/nrF+jjVjpWZN9c439w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:40:29Z"
    mac: ENC[AES256_GCM,data:3NBleJZ8SdpGSCmwTxK81Mc9r5xXRPuAxCPDgl+itOBOvO4EIyQWoDuG3tDG+HBT+aRjrN5qaRbk4GzQ5kTapT2+DzXrdb9PoCR1vpiplqEQWMmr7GtaVrzIeeVqdyiHNU8zcm5rVyk1zjtsM8YdROLCHKGeYu9nxUuIXK2fUXQ=,iv:AERtYzYcffLcW7Fm0k9CiFdhUvknQns0izMXLbCsx5s=,tag:43r8DpvVpKH74xzYPdRdXA==,type:str]
    version: 3.13.2
