apiVersion: v1
kind: Secret
metadata:
    name: komga-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:NBteeOo5AYNYrSy8tleMMYQFQgnpt4pGXEzD6v23QbJqTTBM3q+uwg==,iv:DXQ0N/y3EjRcVFslYdc/GwRsvprfymcH2ktjUvF+dkE=,tag:WwdZc+Uf3xmpy1TbSTnaag==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:pke8c48gDDWOJ6lBkd8a8Y/0CFDIeWEeXFuFSNQlMdMllyvj3wA8KtUuhielSzJPFrTyJpjrwgCAD3vr3PXOi+u0GqgQNwjfgMfUFyeeC8LUK+A1k6Q+W/CHMS7D5ZXxQK6wQ18Mb416X2i/nLNlFO8jNZIQrCeoSaFFj/KQzEQ=,iv:jYrG+ftOiYt5m82km/EXpbZqwh6y0Q6Zw9Avg6lntMo=,tag:Szoj9QfCyFDGeJ/fOwiMtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ29SZkpmUitHOEZEclY1
            NGxpQXU2dW5lZmMzTGp4cXB6YVYxWVNTMlgwCkVvNlI5aisxTHhNODJLYXgrU3Nm
            cUpIbWxHejUrZXBRZ2tRSjB5cE9oSGMKLS0tIDV2YmVON0FGMTAyZVoyOHBjL3Fs
            eEpQcVBlWWVpN25SZk55S2hGL0lGTlUKCbQu22PRNh3CgrcnWpFzDchDvbxQiNxT
            KHLkuAIvMzNhy4TJHVpM3kkQlSnQpdPndqLTxRTaCDawfOgUoDY80Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-25T18:18:50Z"
    mac: ENC[AES256_GCM,data:cmE2Mu1MCrK78ctGDuF3+YlpbipA8FasETH4M/QBbE+fINroKRMCKzfHBhD6YvR3qfLVBUi4E/5gqYZwRw/wfKleAhpIDvgiadgtNZgYLwIW6wYlI/CnjL1SvatBCRi9v6kRRdEkm5MZsbq71gbAx3GZCQPVc+8HPS9x46NEIwQ=,iv:biAXYRJmkfcUmv9p0rczwBITMS0RIWH+O5Is1/zuVrs=,tag:9F1Tx6mZPBTC8GRibuLPZw==,type:str]
    version: 3.11.0
