apiVersion: v1
kind: Secret
metadata:
    name: komga-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:w5y9kwht3pY91dj2Ily546c/8F0A0wp9THoADgWWzo0=,iv:ox2H94MSXo+VEJw08eHj+IerOYvtoMaW2zthqpHgptk=,tag:nxOzFj5ZMkzDPeLkRHZ6WA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:vAD4hIU/dZU9XKHy8O3vOvx6WU6fpGA3hUry+s89dUwn+g+nz1vbhYxEujtaXkN6Gr3rg8PzJYrOcZHMUzYSZQ==,iv:071BVNwTVvWDjpp/oMeJsbIGmiZKXvx+H9UiGHz54JQ=,tag:vhClt0FYhA7FBwSS/9onxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ29SZkpmUitHOEZEclY1
            NGxpQXU2dW5lZmMzTGp4cXB6YVYxWVNTMlgwCkVvNlI5aisxTHhNODJLYXgrU3Nm
            cUpIbWxHejUrZXBRZ2tRSjB5cE9oSGMKLS0tIDV2YmVON0FGMTAyZVoyOHBjL3Fs
            eEpQcVBlWWVpN25SZk55S2hGL0lGTlUKCbQu22PRNh3CgrcnWpFzDchDvbxQiNxT
            KHLkuAIvMzNhy4TJHVpM3kkQlSnQpdPndqLTxRTaCDawfOgUoDY80Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T00:04:08Z"
    mac: ENC[AES256_GCM,data:Kv7g5ufMQvEvgVncPylc2eMLndDlaFHM/ftrhKSY6gZkyr3N1TPQGw97n4r/XzkUbCX5e8yfLzT3Zhsn60eT1BIL2yP2bjjB5DWzr/SCWPDVmCfncRw1UYiwVSH/FRVkk5ztmepaIA/l5pU6VZ3ZJ0qrm57K6xnB7zZ2Xyp5Jvg=,iv:OtQS1B7siHF9Zsn32daFwLbfyZ14nRjECGXSgEjzFlE=,tag:r1pL+r4YWbCG1IbDHPSHoA==,type:str]
    version: 3.11.0
