apiVersion: v1
kind: Secret
metadata:
    name: kopia-auth-secret
    namespace: authentik
type: Opaque
stringData:
    BASIC_AUTH: ENC[AES256_GCM,data:+rags96cX+ETUVEusxbOYKBIgveY1uF0Y3fXMsbeMY0Sgoi5TaYaKopVvU26+8pNSouJ4iHnxz6irZbfF5V1OKzS7potGpKxpY0TMvchgqr7F2A5sgE=,iv:6ZxQ/zi0ZqnURcukTcXcvcQHcqa+km0IszBiCFJA6ns=,tag:rQflVFphzIJSwAuibSLZSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOFBlWFBKNTdXRWdSSFFx
            OTlWZndUVm9KT2lXbDVySkU0WWxmb1lwU1FNCmVjRHpLdW9HdkJycmFzL3p0MjZo
            Wm14M1FvTDVPOVp1VnhGN2hVTC9jbEEKLS0tIEdDMW1uTG1QY2xhU0Y2Q2hiOHRM
            SkNSYmJCSWVUbEo3UEloVjlxYkZmMFUK0eFV6s/9fb538kmqymVlcb9fbHL1gC9D
            mmrPTmJki+3XIuicfcp56ika9skQsNQG+ckO9M0qeVM6+aWLbr5hDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-03-02T00:27:15Z"
    mac: ENC[AES256_GCM,data:/LLZ/qAuF5blxc/xpyRwUBgWXpmv2kdeBWfU61AZ0gvcQ4xmRH6ZoHnMegjqSkKt9HG9mlQTxFr9yYqVfhyJgP4qBnjaSV8WHoyEvWlHidwoqzlR8vZ4zAuycHRPa3T0nHjJxZ+GZhhvSB4DiurxAw4CUMv4OIFHOF/yQSwyt/o=,iv:gmneDDQ93Kw156yTwCPBqZoN/Vt/UTVd34ay9Y8wvRY=,tag:5SrSlOaKnW8ES3X7mu/4dw==,type:str]
    version: 3.12.1
