apiVersion: v1
kind: Secret
metadata:
    name: ldap-search-secret
    namespace: authentik
type: Opaque
stringData:
    AK_LDAP_SEARCH_PASSWORD: ENC[AES256_GCM,data:XwXtv36fefJCqsxY/hdj885Qgo16T8PSWt2wtrveaPofEiQOlvkr1KJ3Kep5bDOcnQhThaKwI4PCJItZ2NKbwQ==,iv:da7HIbv+KXw0vlxo7D+RliPYSkZfOGCowPihu2xBwUE=,tag:o7uKEAcwCLIBQ8roLnJ13g==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY3JNM1I2Nkl2OEdFbnN6
            SjI4UnlaRktNSXVkM1NFdDVCYzhWNkx1SkU0ClhSNTE3OU5XQjFhSzhVbTZwRUFZ
            RmVJZk1zQ1lqd2JOQ1I2bDNld1V4QWsKLS0tIExLUjMvUTVHOVBSdlZ5ZzVrVDN5
            Z2E5MkNWVDlWVWtKT2I2VnlOWXpMZlUK2LYc0uT0yoBR3qjN+ecrJzLH8gcRfaSV
            vBd1pIC0VQcBbMQGBuT5kJP9s2xr6XtgWIXGK4FjdbT+lugGV9lSPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T00:00:55Z"
    mac: ENC[AES256_GCM,data:d1sb3bHp31tWVFmPbwXFPb9/ZFJmHHp7KPAxvD/jU6kYeyENisQX14zV9K+Ohp06ckF2IWga3w7LD/7TDizR9ouIHHE8FXXbPCQfM1uB1sEW2BIRRTSDj99/uGQsIS2ANnaYJ2S1JbZY+as50n+ZddIGIgnDq6LQhKLwjpX9Brg=,iv:jZU7eQQf4CxLyJ+V5QDjjWG9VPIl8rkz8iHXBmmvC88=,tag:ukb3aZm4zJ/ZPcwNVe0ZJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
