apiVersion: v1
kind: Secret
metadata:
    name: ldap-search-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    AK_LDAP_SEARCH_PASSWORD: ENC[AES256_GCM,data:F3WMujs/lMkH92D9kgHdp4RfaEXWC2DKz0LC7H/2bROPDiNTXZXNgbkScYobsK+M,iv:yVFBshxzdxLy+ShtaVaHDjFYS0dD8nTU0xkpqg3SAWw=,tag:kYR4isbqdunmK9wpE3X4PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MThTZ1hUYng5MVROckpT
            ZjlyWWlZOVFlZHppM09WcENIQU5YQW82emlNCnBYWW9lZFEyOWhlK0xLUjF6VG41
            UDcwMDVJT0o0Rm5wa3I4ZEVqbGpkekkKLS0tIEVldTgxNmlzQjRGNEhka2o0OUdP
            bW9KYVJEeGo2UHk1MDJBdHhqYTZFS1EKiGbVow5yaF4E2jUoS4koWaWqQYp7/xMQ
            4C0HZZjjwec3PtN9QTD26cw7BenG0YABRcX8Q4ECtvpO1X+zWTGYhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T00:04:08Z"
    mac: ENC[AES256_GCM,data:XO87MefBSHJtogJGGBo9R2H3p547XOR+JaGyMtMOa0nsiZvevFiryrMIUZFvqH8fXTYobpf3BCwCaChnzdNZORTMfOHWdqggZFyI9u+EjI045ZhrBnuEmcneAHu4JbZXX4E1WLfzj1KmvVCgwqYz3ITbWL/NiEJYbzBCJjVkDxA=,iv:NWFmF2Ms332OgR8iyzDginzH1hA/U/d2xAmMTfdvmc8=,tag:q9QAuURFPYgc/AwPAbvwpw==,type:str]
    version: 3.13.2
