apiVersion: v1
kind: Secret
metadata:
    name: ldap-search-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    AK_LDAP_SEARCH_PASSWORD: ENC[AES256_GCM,data:+/UaDX4GU3RfFmCD1y64ChgW7iSf47b07HPB2urxrSIck9+oxYpC7BINddab7meey7p+5tmG59mtx5+gzXTlCw==,iv:77iw/XjY4vzna0kAlLy0ug2sf2QuSpaZ8DA66AQpGOg=,tag:sMY6Lnc2p6QK2aWHH1gCgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MThTZ1hUYng5MVROckpT
            ZjlyWWlZOVFlZHppM09WcENIQU5YQW82emlNCnBYWW9lZFEyOWhlK0xLUjF6VG41
            UDcwMDVJT0o0Rm5wa3I4ZEVqbGpkekkKLS0tIEVldTgxNmlzQjRGNEhka2o0OUdP
            bW9KYVJEeGo2UHk1MDJBdHhqYTZFS1EKiGbVow5yaF4E2jUoS4koWaWqQYp7/xMQ
            4C0HZZjjwec3PtN9QTD26cw7BenG0YABRcX8Q4ECtvpO1X+zWTGYhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:56:05Z"
    mac: ENC[AES256_GCM,data:DJRH8oaj6JbFnsdhaQHbL0y8rhg5UaAHhPCWPeBhUWP+kfIensxO7PEArca5m+89aWuUf2YwDyLsvAVUX0FiBjc47RZv68N9ghLTNiicoNEZj/+H2Eo2okFaIuVGTu6fqt0T6FbuYhqkykORTTCP5uY29aWPHjKE50RP4UdjU5w=,iv:hP1bIfHAeDuUfgRJPIJAOUNZXLaiQ28VCr6V338csEU=,tag:niakkPQ5OcDooQsq33t6SA==,type:str]
    version: 3.13.2
