apiVersion: v1
kind: Secret
metadata:
    name: librechat-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: ai
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:OuItqDTPdnKtvexgS7OeukJKXx4ecNbg2v1M6PKygzo=,iv:hT77rJtz7DXdR71AsgaSij/A2bOcLEzz7P68Dm5HOZw=,tag:VHkwCU4NgKxdmh6nkzt2oQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:o/WxNmhJsnNL6jK4G2HrsrdeixlnPKjEaIE2iTkxfoypnu+YsfeZvnyogc46jzMS0zy/WwUIupZCChQ5FQcUHg==,iv:ZcdQFhmGp5IWxheXlJJLM5+mRCl0ZBcPrL0jTpAOfMg=,tag:aAya2PL6zkmJn5Heg9p1kQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRUM0RlV3SEQ4MStYRkdN
            V3J1VmtaaTZhZXRXLzRXK2tnTzk5WWZXeDBvCnpNUVdDOEoyNHlPenZrNllwMWx3
            eDA1aUhLZFhKZnU3eTBiZy9vWS9EdXMKLS0tIGFlY0poVFlzd1pqUWc0MS9DckFt
            a0NPV2EvZXovaTN5ajMrNHZLMVRwTTgK7h7bqjvjKlN4eAIJdDZqEZUTF5EsL3fa
            plWJu+qhAQ87hcwON2gAdHKD+t4/KUvPux/rJVmDq7jxEyx18iaGqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T00:02:40Z"
    mac: ENC[AES256_GCM,data:bY2cYHrwKpe3XtRP+GhxSBlWyugxP1w17MDs5BYI/UtRD32Y1NpbLOBRDvnOsaDCiOck2FnSj9hugYX/OtVHbGnc4f2wPkjXylIUKH4+gUdCYJ6YGZQA/JXwqWsJ//s3/b6wi7IRzLXGlofTwSW3+fD93aO7rOYU5INHrXpjfpc=,iv:vj36GoKY05qoKiNWHBqfxfCqGprpSFtLqjNRJZ2A1Xc=,tag:G0YMXUsFja44J8a0ho/qSQ==,type:str]
    version: 3.13.1
