apiVersion: v1
kind: Secret
metadata:
    name: librechat-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: ai
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:zi1yoLW8Cj4cOuzMQ+Uc012qXLnYRAv5l7cC7Nipfr3uHhL3o+EbEdd9d0dBlN/a,iv:krvZq/2mX9dByM5H1Kk3Lwmt8TIF4EjR7hXwfkWj5wk=,tag:SjZJYJAJ/rfwTwydAeQjYw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:8E3DiOVN4sfaIFKdoO3IT4rhshX2hnUG5rZFKZxSOo0VYGHyIHhKaMGBapN69qR3iTuaq9pWV8YYcQ/Mk7X2+RmKIDhhVOv+S/OVjjKSS7XZuWILhoApViFHcOGPBqGIQw==,iv:sw4xVvNsi4x/hrTyXQBly743f675lWYCom12nRz8mts=,tag:gqy2Vz3IO4ro0xfWq52o2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRlc2Z1B1Vm5zMTlWT082
            bE5yZVowNmJ2T3NpdGE2L2VzbmFjbElrc0ZBCkZTSmhGK2RUZUprK3B5aW9aWmND
            enJITzJQQlRlRjhEYU4yaDR4bDBWWlkKLS0tIE00aEE1VTF0enJYMjg5aHpvSmJj
            dHM4YXlMYkUyUTN3aDBYakIwK0tqT1kKWtbnHWV+COPbysVCmqDK283yY+0LPiNw
            NHKFH7dMfALTIEnP5h7GWRS9nPFxXTA5pUEe7TFjZZgTcn/tZPMuJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T01:48:19Z"
    mac: ENC[AES256_GCM,data:AEY0K41uncazRk5R+CpxW06zA3VxfFw8fpyr+AgxWODtHHPmGX22xznNShl2N8ZHjJqfhxTy2db+LKucN0exWkrNhsekomodRiZMvRd/Qv+xx7/BCcP658SMPaQCej9XYJQ5bgb3D9oPn9dKPuImqqno7v1pfvh1vP0CeBLJRA0=,iv:pbom5hxdrREBCNSVAxm0utBcn5jb3qy7UIBKemoAvBc=,tag:pVcwHtGKNjERqffb0WiA3Q==,type:str]
    version: 3.13.1
