apiVersion: v1
kind: Secret
metadata:
    name: litellm-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: ai
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:evP7zO5tHsCk6B2H2V+CG7eb2PLDh356TgmSvM/tMAwAVVjvaqJqgzp4agwVF6RF,iv:aETt4bDvzLiLrZljGftapCsalZaASH7LFjTdPSPauX4=,tag:zbaFq9tTwxFxjA0bXq0j6Q==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:EzLIBcWEJPF4d2ZlmGGV1qnwN0lLT7HlBIZbxI14DbOkfXHmQm14/S8j1Gios5YDreEsc/EeSiRjTYuKd7iDFlcFjSShUdrTAPB3kXtG+Kbjk+XBilohnGvfzSAo6PJb,iv:Iv06OcSrpl3veQ1I/Yzm3SMKygnEQFn7eNGgUnoYcx4=,tag:WLj+YTdg2jcm+NaCEvEfcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMUdYR3lvZVI4c3ptQk13
            dU9qaVY1c1NiWDhUR0hMWU8vRXlHSmwrZnp3CnJVbmNCdlo3TUtQMGh5ZnRFMU44
            WS9TV2NMVEwyVkQvazNIVnBHU2RHSVEKLS0tIDB5QkdzdUtZNmNmbW5XdUU1RDJ3
            UThXT3RLb3RMNkFjVytWYjkxOEtwRzQKlA/sHN1mahg9vjHf3yaEc7oCWldylgbN
            9YtQPeHVE7wQa1d0ASWTXCw5vg+oFvXIys03mZvcasl1Lse+o6U1Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T22:31:20Z"
    mac: ENC[AES256_GCM,data:MwP30Rwybqbq1g5y4KfZsnFVcfr1kn7dIYgcLoTD5ebK7sSOE4Y1twpkkyVDjn3i14bp6d5oEA+8fTgFkczEp0wX1Pw2Ja2dfFC9NfxVeXMEmtHFORiquzT8iHR1nu0y0O0IDN3QZIY2d8Cc6M1K6FZLzKaAzRcesm35vDvwrDg=,iv:tdEeZVAoKt7WKI1JQjuz6Jq+wq0trqtheiOhA8XLpps=,tag:FGdOEYL6GKHtmI3KQsHz4g==,type:str]
    version: 3.13.1
