apiVersion: v1
kind: Secret
metadata:
    name: litellm-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: ai
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:IBQiWQJ5thsJX/+EbhGa3dAfc19z1qTS8nmYZCWN2O8=,iv:igCzVIvFmB3WjQdlOi7Qo9X0IQiodFf7kPgFLO63HHk=,tag:hqG28LDR2/dD2hUYP2Uq+Q==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:bogdsfgKoiiw95gF2P3tgsolaX2/KP/QvTjfCN8BOUmGPKf/7XtmIT3DzV5Z5r+tYSamRoLzXbds/TKVezIn+w==,iv:suAGmdssKoKI2qI1Et1yCVAqxIysyhSxa2d9ebpzaxY=,tag:c/ntMbf38CpyG3Lc0QsYcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENVlKaTBWR1Q5MFBGL2dt
            RmovSGI0cks5ZUlEamZxVG4ycVM3RG8vSkhnCkJHNHVQQ1cxMUQ2eDBhWFN5Rmxj
            V0pxdXRpMUFieVdXU1BBUUkrRXYxKzgKLS0tIFJuMTlTTU45MzJCWkNhdEkyUnI5
            RzRySWZzSjJTQ1ROZUZXejBPZ0d5Y3MKq7ABjMt9LCdvrqZ4B14cZ2dNYHaltZIV
            4UdHDS8y81N1f2RbNAOwsoiy7qV97NLfjIfa+RkKGKyOO171tdHRPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T00:02:40Z"
    mac: ENC[AES256_GCM,data:0m/pcRQVSq0Q7SRXvHTCHjK3rJRpN4ddGl/60Cr7oY5NSehit+4vXyTM17yfjWXqN394RADK580ohDtS51er75pxoXUGpWAkFxnLSYnxn8HFNZxsE5SzRvA+U4z/qWt/ywYQNHnp96nFzFANiNVdrMMk0czN5KrbOuNd8EvJM6o=,iv:ME3tpVIKXkF+JMKHpQRxReZpTvE6uOTSeMF2+ggw2Gc=,tag:OHgX/WhqkkTNXkbBQB0HVQ==,type:str]
    version: 3.13.1
