apiVersion: v1
kind: Secret
metadata:
    name: litellm-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: ai
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:evP7zO5tHsCk6B2H2V+CG7eb2PLDh356TgmSvM/tMAwAVVjvaqJqgzp4agwVF6RF,iv:aETt4bDvzLiLrZljGftapCsalZaASH7LFjTdPSPauX4=,tag:zbaFq9tTwxFxjA0bXq0j6Q==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:EzLIBcWEJPF4d2ZlmGGV1qnwN0lLT7HlBIZbxI14DbOkfXHmQm14/S8j1Gios5YDreEsc/EeSiRjTYuKd7iDFlcFjSShUdrTAPB3kXtG+Kbjk+XBilohnGvfzSAo6PJb,iv:Iv06OcSrpl3veQ1I/Yzm3SMKygnEQFn7eNGgUnoYcx4=,tag:WLj+YTdg2jcm+NaCEvEfcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENVlKaTBWR1Q5MFBGL2dt
            RmovSGI0cks5ZUlEamZxVG4ycVM3RG8vSkhnCkJHNHVQQ1cxMUQ2eDBhWFN5Rmxj
            V0pxdXRpMUFieVdXU1BBUUkrRXYxKzgKLS0tIFJuMTlTTU45MzJCWkNhdEkyUnI5
            RzRySWZzSjJTQ1ROZUZXejBPZ0d5Y3MKq7ABjMt9LCdvrqZ4B14cZ2dNYHaltZIV
            4UdHDS8y81N1f2RbNAOwsoiy7qV97NLfjIfa+RkKGKyOO171tdHRPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T22:31:20Z"
    mac: ENC[AES256_GCM,data:MwP30Rwybqbq1g5y4KfZsnFVcfr1kn7dIYgcLoTD5ebK7sSOE4Y1twpkkyVDjn3i14bp6d5oEA+8fTgFkczEp0wX1Pw2Ja2dfFC9NfxVeXMEmtHFORiquzT8iHR1nu0y0O0IDN3QZIY2d8Cc6M1K6FZLzKaAzRcesm35vDvwrDg=,iv:tdEeZVAoKt7WKI1JQjuz6Jq+wq0trqtheiOhA8XLpps=,tag:FGdOEYL6GKHtmI3KQsHz4g==,type:str]
    version: 3.13.1
