apiVersion: v1
kind: Secret
metadata:
    name: llama-auth-secret
    namespace: authentik
type: Opaque
stringData:
    BASIC_AUTH: ENC[AES256_GCM,data:jvoKDPfC/FErVf9v6CSgZCAAJ+8dkSzWfSvn4zwGls3qij7Mx2gxzX6vt2yH5sBSLURCzra7CNOZViLqJ5k96pjwKknIbt2wwssUym1qvoxaC5lR6JJ9g9jZTNM53Q==,iv:NWTM0cUER8FYlY2+H+ID2qZsbD0P5lfBaf0H0RCdJ/0=,tag:FUDNV+hL0Vmww3xxxfnmDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNlBHTDdIODFocDh3TFdS
            RjZiS3lXNGJiaFpubVdhN2lWN0xIZ1U0RG13CmZUQjZiSnNCWS9iZXBWM1Vhc2h2
            d0hVMmN6cVJ2MTRaNm90cEw2RFV5VFkKLS0tIEZlWlRNS1o0SnJMZEIzVVh0L01o
            aTFhUHZRWldteURqbVVBVS93VGNqZE0Khg7nKUTqLzFSXckE0NKiRcv0FFCSIQi8
            8kzgs9AuY1a/4bpMOr80rBFJZJ5Ds5l9AmxugMMCcMlZWIVBGwKN7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T11:59:27Z"
    mac: ENC[AES256_GCM,data:s37JmIL8O+AZq3uty60HElWW3cx/aIBSr2YSSAlCJTbCTRCNMCwy/sMMiIxAI68j4km2Mo+/29c0I2PYvB7oeGgrtS6PzlMdLSlVSFzArnGkoh6IMGyouLZtBaAq5KDlwHPPRscq1vUZaAG2q3x5fdUPlwvhafyZ41g5fmtKvr4=,iv:xSEvAY4hqrCGCfBBRIv9sTI7cYuTaf/aM8ugInLG0uU=,tag:MC8xnHgK9M3/1uRkeU4gaw==,type:str]
    version: 3.13.1
