apiVersion: v1
kind: Secret
metadata:
    name: llama-auth-secret
    namespace: authentik
type: Opaque
stringData:
    BASIC_AUTH: ENC[AES256_GCM,data:jvoKDPfC/FErVf9v6CSgZCAAJ+8dkSzWfSvn4zwGls3qij7Mx2gxzX6vt2yH5sBSLURCzra7CNOZViLqJ5k96pjwKknIbt2wwssUym1qvoxaC5lR6JJ9g9jZTNM53Q==,iv:NWTM0cUER8FYlY2+H+ID2qZsbD0P5lfBaf0H0RCdJ/0=,tag:FUDNV+hL0Vmww3xxxfnmDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzlvOWR4M0ExTXZtSndm
            bHAvb2plTWVpWkJ1UG9OSnRuc2NDSElzb0VFCnFPd3JRYUE0aEo4ZnFKVmM0OHAv
            RzZQRWhBUmxrMHk1ZGlzamNZdnBsRjgKLS0tIHVOazA4NXN2eTAzcC9RV2hlK1hK
            WlpMSE93TFV1L1QyVDN5dlFjU3djZ3MK2ShRO5NBNStkZKHrYVExTjB20ZQMEl7E
            R96CRVrbcecJmUQnRrAkEgJd7ZQCK+oNaCetiKbkhoH4DP+LXxs/RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T11:59:27Z"
    mac: ENC[AES256_GCM,data:s37JmIL8O+AZq3uty60HElWW3cx/aIBSr2YSSAlCJTbCTRCNMCwy/sMMiIxAI68j4km2Mo+/29c0I2PYvB7oeGgrtS6PzlMdLSlVSFzArnGkoh6IMGyouLZtBaAq5KDlwHPPRscq1vUZaAG2q3x5fdUPlwvhafyZ41g5fmtKvr4=,iv:xSEvAY4hqrCGCfBBRIv9sTI7cYuTaf/aM8ugInLG0uU=,tag:MC8xnHgK9M3/1uRkeU4gaw==,type:str]
    version: 3.13.1
