apiVersion: v1
kind: Secret
metadata:
    name: mailflow-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:0j76a+dxJ/cBhpfV7AIaBQkS9HKLqysUcml0TSmYPag=,iv:4ylvHqWFcbJzXhPSbl/QUnCLsUjP0RjisPrnjfN0asw=,tag:kAfoUeOPJcbVsuOfHS2xfQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:NLmto9tj0VFH6y2UrR+9+q9aN7tKk5hTolas5S8+zDiYhSbhVmqDyzDd9QWnJbEKlhaIXii0J3+9UmJYB6EA/Q==,iv:MEuiXBGlgc5hucIBoK9/HUuJFKAOhatmPvZLmhqWQNY=,tag:gr2p3cC9bGoROWBwMUjkxQ==,type:str]
sops:
    age:
        - recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dWNOa0VRdm1yM1Nhc0Vw
            eU93c1VBMUVyRzFHVDNtYnFNZllMekRBQjNFCkNUNkVLcGJpRytIUFZPTWlFNUJY
            RUVsQWgvejZNVld6Nm14NUtYckhZQm8KLS0tIFRRd1dJZzVCRDVzdzB3dlljeW9q
            c3RZRG8zM1hvK0szWmduNTM3SUZTamcKuNuW/Nja2yEU3H22E36xi/c8athnK4w3
            jFwZDlPXbEsBfusaF+2rkuYy7MSax3pFam2/+8/VdAdpHYr26IDQTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T22:23:05Z"
    mac: ENC[AES256_GCM,data:SGHwaPPc7wHb1GP08rQ5shm+FQE0D92jM0shqWsMZ+JGbVGKu6nzt0lIxasb8Qjb/yb+X6wv5vRk6sbUjq8kMTfHSu8cI8mGXCcTlllxYoaSzdci8fPSJH7trnraSHpzzXZCXTwWQs9Ec7kPrhIMC7OKQX2GCS94205cU1sEUrg=,iv:RCbLhhJ4ekvoT1784CoYR0w85IZZCAlLvcsSYCtN0Ug=,tag:CQZ6KsDXcb9Ir3czVTJK3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
