apiVersion: v1
kind: Secret
metadata:
    name: mailflow-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: comms
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:0j76a+dxJ/cBhpfV7AIaBQkS9HKLqysUcml0TSmYPag=,iv:4ylvHqWFcbJzXhPSbl/QUnCLsUjP0RjisPrnjfN0asw=,tag:kAfoUeOPJcbVsuOfHS2xfQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:NLmto9tj0VFH6y2UrR+9+q9aN7tKk5hTolas5S8+zDiYhSbhVmqDyzDd9QWnJbEKlhaIXii0J3+9UmJYB6EA/Q==,iv:MEuiXBGlgc5hucIBoK9/HUuJFKAOhatmPvZLmhqWQNY=,tag:gr2p3cC9bGoROWBwMUjkxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dWNOa0VRdm1yM1Nhc0Vw
            eU93c1VBMUVyRzFHVDNtYnFNZllMekRBQjNFCkNUNkVLcGJpRytIUFZPTWlFNUJY
            RUVsQWgvejZNVld6Nm14NUtYckhZQm8KLS0tIFRRd1dJZzVCRDVzdzB3dlljeW9q
            c3RZRG8zM1hvK0szWmduNTM3SUZTamcKuNuW/Nja2yEU3H22E36xi/c8athnK4w3
            jFwZDlPXbEsBfusaF+2rkuYy7MSax3pFam2/+8/VdAdpHYr26IDQTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T02:16:31Z"
    mac: ENC[AES256_GCM,data:xJjFHYk3+RcS9S+b+BfkvF21KH84YUiQwkGg2szPLPnk8hn4SsdziN3mf+c+QnYQ0+q6wzIYj4i+fhEBBih3CrfK6n8SCcGMxA9bqXUXCOml045fpqlMh/dQ2CrRmRIooW6ocu2XIZbSZtp+76JUKOfkyAZ/C1JxBp4Hc6TRJRc=,iv:1QeQZUBuqMoLbGhcOY0uPEE+s0N4ERwgitXcylV4bDk=,tag:2FVdVvnpy9FK4/eDmGONIQ==,type:str]
    version: 3.10.2
