apiVersion: v1
kind: Secret
metadata:
    name: netbird-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Gi7vRD637jmJnVvhjViJNEV3d2tptCfyypPSbtu+OCU=,iv:+eHGtLfS3+FWyG3bp6yWICArHPtTRDCzZSHdkuc3HA8=,tag:s1fnu8VBtbunZtljjsCWCA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:oMFru+vl1x4tXXTeRd5pcBP0BUjl+QHGLA7spQ5S8sUceGtVQXfuif2DxWJfIOPCyEBWr3FcB0ZmFq6jmb7TPg==,iv:XwzjbjNJGBtqGGkefUgmumPDtjo3FWXI6xLg3YxiM0g=,tag:lTZRJfuULBWZJwNzWUWu/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeitWek5YUmlGN3BrYity
            a1MxaFo1aHJlT2N0UTExNURVaHZRVVJadm1vCi9YbE1OOE9VaUhQVlJMLzVPRWxC
            NUZEdEZMSGZSanU3cXNzWVc5NzZMZW8KLS0tIEdJZUQ0eGZkdDk4d2NoaHNoUitj
            R3h5NG9ZUWs1MHphOE1BODlGZVZKTFUKg/kJbOGapiXAz45VMHFmNtP/eBJLxa8E
            qJlYAhbVX1uoiKrtUgRBiDTEh+OeKzc2ni4oIpjDUn0foCJLG3Hc3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T14:56:38Z"
    mac: ENC[AES256_GCM,data:VMX+R06EImgiV6hxoPtE5PAwHPf+fl/iyS8XMip8Z2WAIxH7Lfy21oMlK+tOOTBTZMIS4H5hFKETZT9eGdfr5TkdjfnEmgkPXB/AIJ+6Xj54MEoAaueIIwNc6+N33w7We4wjJjdNt6357YahbLYoGOyflACBleIpfzVSML41psg=,iv:UxjgTBrRcUR8+lqbSfv3agcnktDHbudTUMi2d796Iq0=,tag:3JIlyKgLYVs/5uST1bA/AQ==,type:str]
    version: 3.13.2
