apiVersion: v1
kind: Secret
metadata:
    name: netbird-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Gi7vRD637jmJnVvhjViJNEV3d2tptCfyypPSbtu+OCU=,iv:+eHGtLfS3+FWyG3bp6yWICArHPtTRDCzZSHdkuc3HA8=,tag:s1fnu8VBtbunZtljjsCWCA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:oMFru+vl1x4tXXTeRd5pcBP0BUjl+QHGLA7spQ5S8sUceGtVQXfuif2DxWJfIOPCyEBWr3FcB0ZmFq6jmb7TPg==,iv:XwzjbjNJGBtqGGkefUgmumPDtjo3FWXI6xLg3YxiM0g=,tag:lTZRJfuULBWZJwNzWUWu/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERE5reU5JS1ptZkk2c1F4
            bTZVVzNKQVlFYmZRMFJyMUFsRmVXMHZDSG5VClIyWDRmV3VqcTlxNEV1dzA1T3dX
            Zk5HTFRXOWZBdDU0SXVqSUtOVWZCMU0KLS0tIHZ4UlJaWDFMMjFrYnBsMk5aamw3
            L0FNeGVtNVVlRDh3cnZub0Q1ekpwNnMKxWiZHxpXkshkhbUHuvGdXAZp0b+h34oi
            DhOa1oPhRGAHAWyMk8voTLgRCfMAgKGwKpVlBbvFSMt2IFrFtOwkjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T14:56:38Z"
    mac: ENC[AES256_GCM,data:VMX+R06EImgiV6hxoPtE5PAwHPf+fl/iyS8XMip8Z2WAIxH7Lfy21oMlK+tOOTBTZMIS4H5hFKETZT9eGdfr5TkdjfnEmgkPXB/AIJ+6Xj54MEoAaueIIwNc6+N33w7We4wjJjdNt6357YahbLYoGOyflACBleIpfzVSML41psg=,iv:UxjgTBrRcUR8+lqbSfv3agcnktDHbudTUMi2d796Iq0=,tag:3JIlyKgLYVs/5uST1bA/AQ==,type:str]
    version: 3.13.2
