apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: nextcloud
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:FaEHhyw/XOqbI9m2ONPNPv2+wkbrAf+dy4KWimxguHf91NaYytxjrQ==,iv:dvTix3xbQyDdfUAmTvBZuwPHxGxfEwXJ46HJjEMquzk=,tag:4jtRKgQHqDAVDye+Racpuw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:cCfgoeKlJqZpjYklEF0r49X0+lpTorUzlxRSD3etzsQI3QDbZd3NAv4Annv143qo09LN+o6/tVNLM6KN6VU67SOvDITfAyB0vpBeorTAX+FqLDMHircSQfEJ5dPj5NTE/se/EE1WIgMGui5rssC2QG3lRPHxxKPK/uwE3jdzLT8=,iv:pZk5VVeX+A64vR3p5myHNOJV5G8htDHoxD/3nY/LLfg=,tag:wxWyct+F+Z1GnjDl+U59Xg==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b1ByazRidTZ0ekJqRkox
            eGd4N2JEbjllTThHL3NNU1lMRUVFQzhla1JZCjl5QjFSRDkvSGdGTjJYU1RpYWZu
            VXBDN1Nza1hjZEIxMU1SUS9Ray9Cb2cKLS0tIEExMzNPMlNtMFpsb0xvbjdGcEdL
            dVJXOThra2k1bUZvdkR5WmFiNjAvOUEKhdypcoTl1taygJbVzNh/GiLjZhX5TbR6
            W8w/QAC4VLNkJtHaVNMRxzJZNbBCqVnSqKrqaLvb3c4uTdQMt8nP9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T01:47:45Z"
    mac: ENC[AES256_GCM,data:wmMtXvzzRY9Tra27oz2ERpdI+jRPn77b39CRpTgvC2XsTG5MVh19omd8mQzUCMia6A/qjOr3O07hokmoOrGUwSHLS5sZUNcSQdEFWWsksXRZdZGi+HxHoIwEbRvPumN3fSuLExKDdBeZiMpyN8KtxdLhwG99Jv8zfbg4J8zZ9kc=,iv:9qcw+dHyOR41hjgSC4Rx7Ic2UCGrkYAAMucrESabGxU=,tag:7uo/lEm5B/L5JSu7hY/IEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
