apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: nextcloud
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:/GVSrGwZTafI8hl/DzwLRDmvgAfDiivFXCvHWLWjDg0=,iv:zvQdZsqGilw/MFG4iEHXkJvg4wg67SWA1B77pELFLrY=,tag:7xfh5OryCoUh4Ap5MR1E1Q==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:qKOm0VaMxd4/riwnFzy77y6l31EazmIxpnPmpsOQkfIO0X7+azjd0+n94WDWVVBIpCvTVX9GXqeRKHR7E0zV/A==,iv:wgxKQ/mkXaF9HpDVor9MXFXT9WQc/TQ7mGJY/atEg10=,tag:FBQ9+e58yR2ODKYVThitng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaCsrM093aHA3VmNYb0d3
            ajZ6Z2EvcDBJODVRSk5OajBPOHBQaE1MbWk0CkV6UkVNQXRWcXk3QytFaUNqWHd4
            dkJDSStPeVpCVmYzSnUrSEM1c1NGbkEKLS0tIEgxNXF4T3pnMjhBa1JxTHNQb3hW
            ZzRmVklua3hnU1ZGTngxTGtXYU9PQ28KVnpx1WwI1GlMnyz5hnPY++wDvDGC4o79
            9ksP8NyPowRiT3qNO/CPAUZrujSez8NTP2L6w6Md9wpkQ2Ux0BLArg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T01:09:04Z"
    mac: ENC[AES256_GCM,data:uxCKBYsgoAnPoq297zLusn9V2NEjpM6gj2neD/kgKRkS8ODR68HKXzRLT0Vex0og4hBIqRpyb0ngIxg5soj3uc7FAjCJoQcvrVpwDELLtxFtvV6323IBCwocDkT7+FR+QuKYqKU6w6kc8+/XWa+zBukFX7KXOLJANqm5CPO8KaI=,iv:8iXOSwkUMbbOpmlwkPaCVq+SQy78+j3P0sbVwUvbuRo=,tag:3JYlIR9z2gOWUXODMF8txg==,type:str]
    version: 3.12.1
