apiVersion: v1
kind: Secret
metadata:
    name: omniroute-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:+sGw7Cg7SPEtWwQMOsrXa5evX0hGLvzp2ME=,iv:wCvRzi9a1EKnGLjlRx32kTwl/yoq2FozTIgV36uvUUY=,tag:CXFBIbqXByvspR8DxCTbGA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:QTfUc8RPQp9L7TS2Yeuv+pYjeicQFa7VjYuogd7dmrxs9nyhTUiCk+tfTQ/IqSAwcuffBClSNCwOnpTJbd1Njw==,iv:tRpS9VuHfK8oQwjmrpSgsNYAGkd0c5qT1mtFdK8m2II=,tag:l08ndURF60rY2fg8T3/4ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1RDcVJhRnEzYWdLWkRF
            T0grOXA4ODUvV0tWN05ST2VxRGs0K1RZREhnCi9uUFpUS3RGdUltbi9tM25tNU9q
            Mmh4bUtTb1NlNkdleFZwUWxxeXNlU1EKLS0tIGEwRms1VjlHN1JrSGZ4WCtSbCtS
            TUZkYVZUUFJQOW5URERTTG9NZ3dIVEUKYCn6ndQ6TD5/OWAdKNOD6QzYKzZi8jb9
            JIzOjAh5qRpG7W+YtOjCpokQZltFvLJsjfJVNZDyJMO/l1cmq7Zcpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:19:40Z"
    mac: ENC[AES256_GCM,data:A4b+VU7J4yQD6Fm5DsU42qSx3iKAF0EZo9hTUZSZPv3W2w01leA5hZ+JvVa6Bd/Cl5arpn9Ai9iSap4Wb7UvRvT3YuHsUz35da+Ce8hZUpNXDo/jpaHs1RZBsc7YuYSA9KjFHi3/iSDdkB4XYzSNez4RsRtjhwaqDKFuDzdkCnw=,iv:qbn31DpWmdXbE97IkfJGoFvZtdn1cVqVgiZQeRWTny8=,tag:pOaZYg7sr94lK34rqtxT7w==,type:str]
    version: 3.13.3
