apiVersion: v1
kind: Secret
metadata:
    name: openclaw-gateway-secret
    namespace: authentik
type: Opaque
stringData:
    OPENCLAW_GATEWAY_PASSWORD: ENC[AES256_GCM,data:8GbUx1oZPaqFOjBcSsPLiyJ7TFA/d66wJSO73XdpC+5RBzGyNZlzGdknMIIWQrHT,iv:tApuAW+8q5ASRkzFE3BRPhfWvFfjaL+oe06rGtqZbco=,tag:SaajeKg5QfmZ+aj0vM3+Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOHluN3hiOTRYWjlHNXRq
            SU5rM0ppRTc5c29qc2k1ajNrcGlhRjRkaldzClFHcGY3Q1BJTVlUdk5HL1JpTlgr
            bVVna1F3TWgzZlhWeC9RODZ5R3ZDcEUKLS0tIDdZVk5Vb2RxUzdWRU5WT0dhYm1w
            QWZSMW92SUJMNmhOWXg3cEJ1NEh0dlEKxc8G2lCRxwsa7g9PBRTrsAqwOUwxMNRV
            HsUYLnIB2yBM1MDnUMfSx/iUAbTkCQppy3hzujxVAU4c3TXKWP8eZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-21T17:12:29Z"
    mac: ENC[AES256_GCM,data:i/c2/xRzp/wP20egLiOS5Om5tqGwuXE8CUhVupkBFc/I6J5dbYgdyOEi/9+pTxkfoVPtJTDfBPZt9Ttke6qFTywfGHodjyWf3ibFfm6JBtBHeeQxkioq+oWRNDKoM0Lz4cpOQ0YTdco4gazFA1vCnEpZHYnvDo8BYPHjuxZeT0k=,iv:Nvipaj4aRdFCFsfxtJVM/q1pa+tqbfjroLocFUGmlUQ=,tag:Kaht27BR7qrjxzp8L0KbHA==,type:str]
    version: 3.12.2
