apiVersion: v1
kind: Secret
metadata:
    name: openclaw-gateway-secret
    namespace: authentik
type: Opaque
stringData:
    OPENCLAW_GATEWAY_PASSWORD: ENC[AES256_GCM,data:8GbUx1oZPaqFOjBcSsPLiyJ7TFA/d66wJSO73XdpC+5RBzGyNZlzGdknMIIWQrHT,iv:tApuAW+8q5ASRkzFE3BRPhfWvFfjaL+oe06rGtqZbco=,tag:SaajeKg5QfmZ+aj0vM3+Lw==,type:str]
sops:
    age:
        - recipient: age189vx0wdx4q2hjdzqm3j5yxjjupfun5y3a7ajj40t3cl6lttmz9wsv36vck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbmhQRUU0eE93S2V5aEJG
            THZSTnVNcG5UOWFnQ1Rwb3ZQbFRuWW04V1FvCm4rSW1mVGtaRSs3TlJYU2luZFpB
            WVdJejFVQ3pNa1dMWFU4M0M2eTM2NGcKLS0tIFlLMmNyTmd3R1lGMFhSSEJ6UHND
            OVZqVjlBTi9wUEV6bW15Q2M5czlONzAKpdiyRkQsDZkFPGmPZPVh2GbBJ95rQVdh
            NRrNDJw2+SHU1WN925+rb/GzCcT4Ohim2VvC488pBnG7HyOJF+Rujw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:12:29Z"
    mac: ENC[AES256_GCM,data:i/c2/xRzp/wP20egLiOS5Om5tqGwuXE8CUhVupkBFc/I6J5dbYgdyOEi/9+pTxkfoVPtJTDfBPZt9Ttke6qFTywfGHodjyWf3ibFfm6JBtBHeeQxkioq+oWRNDKoM0Lz4cpOQ0YTdco4gazFA1vCnEpZHYnvDo8BYPHjuxZeT0k=,iv:Nvipaj4aRdFCFsfxtJVM/q1pa+tqbfjroLocFUGmlUQ=,tag:Kaht27BR7qrjxzp8L0KbHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
