apiVersion: v1
kind: Secret
metadata:
    name: open-webui-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: ai
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:76DieWGWcAtVw4tbfeYeF7ky4MXVM5P/+1ElQ7NGWziF75OfzXfisg==,iv:GOvpEwkWa+IIrB6aUD9OmLa5InZoOTeopRE56xSDZQs=,tag:ztmsIC7Jjcl150ugiL/S1A==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:htDTdlwlkMQfYPJK1rhukcyFbODMCM+kVE2GyM6P6xVWMPW333hzZx4b1DtgbUvRcPG3cX38yA5LwewQZsn74w==,iv:hz15voiTPXvcldB+etiT3ld60Tj+894DV8IFU+ER8gM=,tag:llvtO01FjRjQBkkJ6sfx1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTkxoQUFwQTFhSlVEb1Nk
            WVA3NkRWSEJSZGIyUW4wd0NpRFZTR3hLOWtnCkpRM0hPUUhPN05iQlJkWGlYYlk2
            VFdKSXFrZVkxSFlRWCtMbmc3ci9tTUEKLS0tIEh3WDZkYzVlazZ0Qmw1REhhYlVn
            UGpSdURPUlpndTVVNFgxYk9SbklmQkkKgOKh2yqpU6ikYTJkzhN2J5oDE9cMbiW1
            ubLlRFWU9WdDuDbTQalU5o2Qz/W8NoDGmkz6H1s+Wg9ok8esRAyrFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T21:50:56Z"
    mac: ENC[AES256_GCM,data:TnP2j/qhe6O0aIINZFYwhPFIsjf5kSUaIbgP9fK5xInqzLxOL8LpXEz47h47ajq3h3QM48NmSn7S6L1TaNYP23wzHl1lqb4niGSKYVaC/lX8DTZLsLzvvAN0ESoLNz/pIe9yfsZHbYK/2dG6JyH7OrMBmG8924x7oWSTqKatgjM=,iv:dFoYnFbQCYCH6o8bDRzR/SSYzM4sJJB+cABfwZtezPM=,tag:4L/9RnsAHT7G6dxFv6gf2w==,type:str]
    version: 3.13.3
