apiVersion: v1
kind: Secret
metadata:
    name: paperless-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: paperless
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:NGCXiYyJJZ8sgwG+C9mKPM2nbiVOrO+k6sI+bcFEWtM=,iv:YCkY8kHZlwDIm4BYZzc3Dnp4T0akO2reMXxr0m4bK14=,tag:YbwiK7CzAw4HlHcZByglYA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:MtHAazsfkjtUSpfOx2QgD3GbpJKrbfvmkiep10kan++Ma09Ir3P0cgvmL/ueBDpk/U+ivQCjgULwcjWMRLVtSA==,iv:Oyivcs5nNIkDWfXw2Q8bba5oJ9XmfFWQ06uuQCbNKqg=,tag:M+fXcZclrNULB9t+iHr4dg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:SpMhJDSk/SBrHq9zdfK1kgLhMzwKdXGTVcNaD0RyILWVcjZ8EpAlaQwF488EzVdeoLw3sqyHSWn9RkVeqovou5K3knuE2c753fkP8L2IH8WKZ8wawGYy2QWjeHoVcmtvgcjMsM+mrLCXeudR95iixEB6V7pmgFaxwsEBJHaf8iVdTWt6hBr7LD5GEhQRZ9oor87fqbhaEvKfKw54LgxUCpJ2JT2vWPvj+hfCHLLY4P2fJBVPMaIrCc275Z9lE2seltwoHAqLVZzg9TKcYMhmWNmcJv5iQWgruO0jWHnxOKmLQVn8fFoIpKYLdU0Fdb7Gcgakgpj9AFYa+DeKSCfH57wsxTpB3D+PKpdfydEqCwJ6xqtoyUcBss1d/BS43REPKT5ozd0S6NuIem4saVA6VLyBmpeTQOX/s1itBo2Nn2YRNeAwS9JU5FaS1rSiVEAfDYXeXCTy3vmTTldOM3sVfxpO3q8mndAWUOpmeGx3BPiIFACWNJ0Fd40hQ8wCjW47QjIHMAd2u8gcIhZVetnkkndvrHPhKA==,iv:suIOIVhNRfqptEqp0akzQsVyJBUzcJSTiMexRRh5gdw=,tag:jJOoIgnYMa8TxqQezplm6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncTZINUFGM0w0SGVkVXdZ
            K0pvQUtaSG96QVltcXZuOGRSRVBsS1hEVlFjCjV3emtqcDNuMFBzd2RhTkFTYlFL
            d3JSZGZic21vdnhTNitUUWJuc2hZUjAKLS0tIE9vNTJkK3k0RjRLY3ZicnB0N0Qz
            SldkY3JQSkhVWkpXZTlNK1A1RmFUSEkKcxztYcvrX7iiHH7MmgOyQwxsn0jh+d5H
            eWWeaK+O0iRX6h0yEmjxeVnVx/p83Jhol5K0IYDyOaqtvMBw0gqlVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T23:03:15Z"
    mac: ENC[AES256_GCM,data:gY8w8FSSa3AdVmu2uRLQhXrA722g9/dzIOty9BMPBalMsnf9sFbQLa8YhgAL3bLyikIXsmXFRIpgvl9BlWpZehNT/x17lvoqMX/jLioH704cH0AheAnprY11tEx4fajqfas29h7KBgyZ6aD4trhnMp2X/QwGbMNS2WFQrD/zR8E=,iv:vtvtKAyKpAlH5wktfiNxOxI1b1IZJlyWeGOOUKqy/QQ=,tag:xzhb4l7mV/iqOJPp9Lkzqw==,type:str]
    version: 3.13.3
