apiVersion: v1
kind: Secret
metadata:
    name: paperless-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: paperless
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:GBMUGuW891fhOYp7HEO8sgYPP7Xmv6XbGFwyBzRpPQg=,iv:UpLzjdia4Q6zWIQkb21jRU2gjBILevACVLQ7BEJFZLk=,tag:6d1VPjDnnyFG5AgnO849mQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:a7eP7MH7Xkf8pH5zK25sDa33oNYatLQNWigb+A15vJPUeOBKvjqG/pK/uo+ZeAueUxCgz2l6NLdD2BRDnvKJPe5+fKTtgXCUMH8esqMBVQwJAORcBRPGB1riyxyKuekCpSF/YkFDwf4ZlKY2hnD8eZ5LGtzkjjGWhnYztcT6TIMHZs1LKKbcZGEmniXQ9wZlYQUdxEc2b6G0cjDe8HA4mmVYgjiwuzkiSEJq4sMm6OT/t7iecqMe7sHGS7BqCKHOqZIkN+ygp3SG/mLXLnzyLOwCbq6kV81iLxO9Bs7VuSwNyio99pyfMxUswWjSqQ+X+NJ0q576Pl+fCoswI6q6azZ2jVT5ueoILASlHNBwK1HWFaOb1xy7x+zwHyGxPXVPI6ARVvfaDCDW6biwM+ezlEPFDDbWXC2EGqKCx4GrlS+0S6vJHSpDsmHYCXoomaC5Gu3mdir2KWtBuYAqLn7+etAJwjE=,iv:o/SR7UObtOXPIifxLBOUEVb6llbcAOleA2saevrUQKM=,tag:HIcalq7EaSaz8/ppbqmC3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcXR0NlFneUp1R3QydkVv
            ZmE3eXBZc01vNEMyem1EUW1RUUh1aEVwZEVZCkROcDlWRVY0SHNZMFhTZWlrWEhJ
            RzFVaSt1a2NicEIvdThuVzJncmUwbkkKLS0tIGErUTkyaEo2dW4xTDNIVTZSRlBk
            QXF5Z1pmLytzTy9WQW8zd2hzYld6TkEKEjoEA+CzK/9hk2uubFDfiV/yeQUjS1R3
            82ROIJgFXilezp2/Xqq4CIEzOE6mnlRDFlF1app9aDrPpWMDu8PUrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T10:42:39Z"
    mac: ENC[AES256_GCM,data:4Ls/c5D7POJaDPXAIyJ+Sw5ZCESV0t4AqPVocv01vfYQ8YyFdmrj0f6xE7lq94XSTyYB/WMydQojqJluyv/kDZ1dPb7ZIBM20+cO/qzCU9dPB/fF3sL84XaOCEb3Wz/ioCLbU8xAuvaBk713MKVEF0Ahjh/lpusx7AX6dOyAzWU=,iv:k2iQuyTozTlXN5/iPsMxqM8+CdyyOUI+6RohTb6jZUY=,tag:+NUjqmR4VbX+lLzzjDCQWw==,type:str]
    version: 3.13.3
