apiVersion: v1
kind: Secret
metadata:
    name: proxmox-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:UUe0OnAOQSCIAzkf4X0OCZuovcpDZD1V6PxJc6AyiL93X0oFYmGBqm0krznq,iv:w7h+TmDvI8HNu/7d4jwkVNv02YNl3HY6WX6DxnxEm2c=,tag:jkdcJmRpRNm0c7JkVG68DQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:zkca7NSKNFEx9GGOmcrFzBVopsZT/nZxQP+UqGJM17pVTQrQmqTHDtzFn2Vc/oao,iv:zzz2Up8vCeZHYd2xjPe/1swD5gOa0lxxbmHeXcmsWzU=,tag:Gc9z9dosvL4LR82MP4cdOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb3pDVmJySE53ZHdTTnRm
            ajAzdmZpZnZSVlN3WnNkMXRGeWlhSEV6WkY4CjVDSGdHeHlnVUc3WmZxbldSSmZG
            VlJzN24xV1hxbHVhTklBSHNGS2dBUVkKLS0tIGg5OXlPTmc1VDNLRngyK3Flalhs
            Z0h5TElxc0ZKQ1dPSHVabW93a0FYZ00KvKJ26WWvQ9I6Bynb5XvNqfcoV/dQ8Eyb
            DbN+iMcyNqxd283uAc8pMQZk1v7qmJdvV2B5mFMz3niKC8PB5zgSmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T12:47:09Z"
    mac: ENC[AES256_GCM,data:LJ5C956wnfwErdKgQJAxmytTmLMHp4rociYiMUSzLhvGRXmGGn5Qx48YGpR5cCTxay6Icl2E2V++sCXudHoCCulltcN7EEtQKI7Acax+wpoKE2mZ8LSjIzOkjmF9vcFMZWqJGuLNofIah/hx/axXLjoi7vO6fDcCyYG/4RSAguo=,iv:NR0BJPjV2FaQG05ur1XH5qoPu/v3H4wlXHL8Zh1Lu6s=,tag:U7vMJrrfZJXp6jOvYWrDFQ==,type:str]
    version: 3.13.3
