apiVersion: v1
kind: Secret
metadata:
    name: proxmox-backup-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:nEzuP6Ljyk8LkXTadYutzkN3z6hK80XmlT5TlpULBNxF3rqrOPTUkmBUc354JOTJYQgvwVdan5e1HoeOkY0NnA==,iv:vfDqbI4dxvG2A9gneWN09jk0Xm6iNLn95QkapQ3F1mA=,tag:KyVieHT3gjlMBdAF04ei7g==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:uc1P9jWS9KqZK/c6RKN/BXmczoqYZv/D9so3JKWmko0WwR1xdGUpc3wOWavke4OOC8bM2+Xh+NtrmJ5ysbj8Kp1Mv0djHkEKnYpfPbiQ4jZq+8C5DoJOXDcM9GWufmzH,iv:gg1WuEICKdNPjxeE182RSPQj7jiU/z7iZFStY4GqTjg=,tag:E+IErelpbqN8uK9mxljcig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd05aL3hzOG5Hc1czTzQ5
            eEtxdlVnMktRcnBtYi92TlU2Mk9LZzdZZURJCnZNdlZadnlaZ3RNamlVZ3hvMGtC
            YzhsL0dycnNFU1J0aEJ2TmkxRkVoMWMKLS0tIDBXZ21wYnFxZzhWY1R2UXRuMno4
            MmVvaStaRFpLNjFaV2JqSmR3bWl0T0UKfYWpSxGtg3K3mK+739hY86vbpsXMtvyf
            fHLwz3dHHNhEp0jU1jZ8Jcu+vvEr4AcqhIrA/H6ZH1tYryRGGMt7oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T21:08:22Z"
    mac: ENC[AES256_GCM,data:BbXr4oHpVXnzd4/hjW10Ld/Hhg+zvInPPymiwsqxZy8gRFjkBbQD9ZniSBAzEeH+juWpYoxHO4QdLPIVxGJYBaUajBjGZbLDOea/ZWmFI5H1iRhoyLSLG1/uEfcLyHbvs5Xx3mR/kYmXRoSxJS7PNPaKD3rvl4j/2i1ir+sStK0=,iv:IByldVI+l/qc1DIuYD0MHXIkjHtfpQEVsmOaFi+oW6w=,tag:+kwYs83Ye8vmxNdEACXDPA==,type:str]
    version: 3.13.3
