apiVersion: v1
kind: Secret
metadata:
    name: scrob-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:ZM84evIlK9sYZbqh1NQNXrLLw/00A3EHnUxt24ZZLvE=,iv:wdU2dtreodSNCJbU1D/gkksKm2azmUkygEpehzwclc4=,tag:PDF3NEZ50YXhl7psv2v/yg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:+HYVWTeNSOofai8rxsnFrpryAgfG0DpewOah1QmYVgkNtGX1Og5Lb1xLyl3/DWFwsl+VQ8qijN8MFGzRgCXBwA==,iv:YQdBtX/MSV+bnF9PcxKPjuVnf7p3ndYkgum7hmh6ri8=,tag:vCg15SJMBZ4HnYZzl+Yvkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS015OWwyOVRZQ3Uvb2pU
            dHNlTDZnaWNWQ0ZuOTJtL1VVYU5uZDdDd0RjClhnZFl4UkRpTElkMThjVFRKQm4z
            MWphbit5bkl1d3I0M2x0R1NsVlNZQ1UKLS0tIGFLME4xcnJ4V0lIbHBlM1VSc210
            UXoyZysvSVRubEJkUE9wMW9CQ3VkUjQK05EVFhDJiSvNk38NR1Omz7aZdJkK6UI5
            EDU1eS1aV2s9S+InYeugJBozHG6nQtgSMGr8uQVguY1fjbgGHcKLHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T15:51:47Z"
    mac: ENC[AES256_GCM,data:i/2xdSV3my9iD5VP9fGnptIyvIx8jimFVg0isyPdNA7Vo7Wr0nCoQI/qZCxEmM8RL6w3tjoMbIwgyyFH/J5Xj+c6oexNjZRDOBhSR6u+ggBPOkRzGk+UWoaucNacCYYF+A121zpJjfQso8YrwW2HHKA6MoBT5XsxLEouW5Rzr0w=,iv:BcCa4ukC6L44lQGWyXMFaGkFj8TzEYBZRzdaFfMFTws=,tag:bGNSFWFY54KqdtqYJ8rCtg==,type:str]
    version: 3.13.3
