apiVersion: v1
kind: Secret
metadata:
    name: sure-sso-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: utils
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:4ObmVS1CBr9OfXa5bTA1Y7ACobJm,iv:Nul4U9H3Z8Wq+uTtYKCRo5oAXp5bf5FM5ttaxH3OA+s=,tag:M9A2p3VKcGtMRkQwS+5m/w==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:SEmt8g8csMiWDgbBkRbHV1mC8+umCp+knFFnYdZlK6vxfTnMX+Z5LwTewiEemJXI6mcgf4gWeF6ocE0MRhBvYg==,iv:q04oVb0nmj7o0F+eXU30UqwWbN6vfEa9XgRkEhkwbBM=,tag:hHSBbcbY9vbKNBoQOzDubw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTUJWYnRjOS8wbEtMQUhD
            WkJDWUxVajZrQ3NBNnhWaXhBSHl4bXNqcjAwCmZWS0JxL1kvYytRR2hXSjRUb3V2
            d0VzaW90bWovc3hEK3lCSUhqZlZPeFUKLS0tIE9lWnk1SGhYeHFGY2pidUdvRTZW
            WWRuSmE2eUpJK2QzVlVRZVNCQU9DUjgKD0DNQPiNcKCN7KE2/WaiRt8UpGDH4dTl
            y0YQx067PjmFSg/CzjhE4PkWEMSgQgbEEPgqQLcehpItduMgA4Pm4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T11:13:43Z"
    mac: ENC[AES256_GCM,data:ykPTJEN+add1gvqxd/UhDLoiiK9V/Eh04ZdX0V3TdvI3aOS0GwndWNBfZP880vW6uKc/YWxmU/gDVuQ0HvSwnS2FB6FUQxOEyC6BAan3MYogTPeNAZxMJN/3FteeLOUeyr1SOD+ohaoC81YacvArROSAimlZaGZezQ1Zvuy/0rY=,iv:+qEOWDgcdZ0pMC8pQrCJLr3ZyX6spC47quxb+tht8SQ=,tag:7ot/7AofELsKC2QdYcnahQ==,type:str]
    version: 3.13.3
