apiVersion: v1
kind: Secret
metadata:
    name: tautulli-basic-auth-secret
    namespace: authentik
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:Cj1PCdb+ZzhI,iv:CSQkk0vBlmYPEVS8oAXXhuFNcrva9AoIeCtfEuhRHNo=,tag:kOx+Za4vS9Leond+rebuSw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:S5i778eZ6hWHfNMdFInQ84Ibxk4IF0x7SW4TAy312mUuoibpNNnM+4AG8HtK,iv:odCmE1hlhizSSgqlS91h7M0HxU5AAC47PJ9NEQsKKLs=,tag:Bjwn7tb71xtGkuBZXXOGTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUkd2TmtvdHBheVFWaDAv
            aUUzTlJVVnUwVmEwMjZqQjQ1R0FYUGhRWW5vCmhaekRremo4dXdkNjF2WUx3OUk5
            UlZ6QWpQbk9xMEdNdnloN3hDVGU3djgKLS0tIGN1STdhL1RkSklsakVoTGprd2hH
            cExIeTVjbnUrVVo3YUordkY3YkxwRnMKWqS24QA3zCHcLk8Map7CsuSwzJ3mN2pG
            oBOAg25ld5zTbRrek0L1Vqj9W8jK3FGCpmm96ed0rEgAoAFUCIaBPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T21:41:21Z"
    mac: ENC[AES256_GCM,data:hxYiGEKAvd36JBp5/oGyphs6u/qoC7JiPKMhr2Osu4NqJlagbXMRuOUQIl+N3VHghMYNsMR9+Qx4mqdKn3qqur7GHSmKHOf0KVDHZK8lQzGJ6KO4TlKtdx/kqe5GbTt7VEUCnb3AMwPIajSVYChU71QNOR+cDyWbaLznJEnvdnc=,iv:98WBFVjyoJlOYrlrUXZ9vpCclJ/cdGQmT7/lhjWMUo8=,tag:DAidKexOqZSxtCo8RDpTDQ==,type:str]
    version: 3.13.3
