apiVersion: v1
kind: Secret
metadata:
    name: tautulli-basic-auth-pbk-secret
    namespace: authentik
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:+lRXvdMCYMPL,iv:AlcgUYIufNCPQ0MQCTS0vEzfobqR4pH1jzJZQ+ZKKRU=,tag:32gJe68xMyQT4j463GDJkQ==,type:str]
    PBK: ENC[AES256_GCM,data:S2pvDyNHafpI3aLHGAUVU3OtEZKSRIqhI1fc8Mrbum+ddOA2YNYR1xpIDgRBd14InYAtsAqWsQATzeij5Tk9Sj4UbpluWBMenPW6EcPD,iv:ZvNn4VEcGDbPJhsJH8gREWwTqPa2CPw7oknLFechnF4=,tag:6TvcrPeg3ZUM8Vghv24F8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdVFZZTUvUGhKaDAwWi83
            M2U0WE1SemRjUHdVa2dPS2VzTko3aWZsaGtvCmxVZUwzQkhzMCs1eTlYWHVWRTE5
            V2l1RFYyVitYVS9lalVpZUo3ZUFYQ3cKLS0tIG53SDYwM0RXQkZ2Ujl4S28wbzFw
            bkhyUVdCb3Qxd0kxQm9FVXBPSUd1a1EKu6fmouE97JTW7pYpUpjDbfiQCHBgbo68
            Fq+XZ57sKo4J+OjahbWrwNh85JyPCqnxnp4nL8hU1zDFIvnCQmsnRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T09:16:35Z"
    mac: ENC[AES256_GCM,data:ZB6jO4uaH7OwlrPvb2oofZf4Bzg3JsZMaFSZFCR1GMhNC2RsOcqVQUDwQQZ4YmceuONnYEHmAnho4ovWaJsXFvkdWt35scqFW/vPAuuP2DDBM7E3XS4sVSXDA61mCju+H55zw1ZPZOpYXV5gat9K5IbdQKzMWf1pCVVyE1uL4xk=,iv:/f3P0Bkruyz6gVC+PK7hz7Sk/miWp2IQ5O36ynkNbY8=,tag:aEkmgGEL5LxIPVzm1klyFg==,type:str]
    version: 3.13.3
