apiVersion: v1
kind: Secret
metadata:
    name: unraid-sso-secret
    namespace: authentik
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:HFr54mnctqMiAXeViHxMa43w7QOYvMieSI7wzHGp8lbWs11y3whFfUflKA==,iv:GSTfNbkZS0ei8QFALpRfppiXhAo5dQCMwSDLXB5SzEU=,tag:pMwZ3gzWTeqFpVcMqnfShg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:7zrtAvG+1u6r+wbrIMQxTZDGe+4dvGzszAC6t5YpWovXXbOBgjD20DI2aHRUwHXBM80ti/A67k6fpD004kmx1Q==,iv:xjPV6f6X+RFhJ/EMJY3AwUJdscJk4YvBxdClfnh1xo0=,tag:fX1lwrCgFGHKVgcOxWRccg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXNnZHFlanN1RytGazZ0
            c29XSjY0bFp5cE52bVNGQmJFKzlDbEkwYVVzCkVvd2RCMXhxem5scmJIRlVJQ1A0
            U25JT0NWeHdyUHBaK2VPYUVNZU9TTGcKLS0tIENjQmZ0UUl6aGZjU2drcWxLTjlt
            T2g0K0FRODJEWCt3MWhKNUc1TXM4NzAKTA5OWeTuE7B/A6307C0TnGrkOT2gnJkF
            me5VDO9x226Xh9eRM76z+1S805HrEAHzRdp1g41dVnDp57Y7lt31Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T14:51:17Z"
    mac: ENC[AES256_GCM,data:NQUKE13N/ANLW9NM1nGSPchX0XSmQihoAbE4PA3YIza2y92WxA31vM10qUbAQi+V3L7ds80J6sD0k922afT4BVTEWTRPMV+zsQqUW9N/WxpamCBFdoXjS/vOmT3T2JdcG2DUh3LJZtE0LYqKWo8n6NNU7F0kNAYXYmnewJ1SxDY=,iv:AhSHGJg2oYThJrTgbIQQlWFOculV+9LOdvTel7ka3to=,tag:p8iYNmZWkG5EFUP61JDALA==,type:str]
    version: 3.13.3
