apiVersion: v1
kind: Secret
metadata:
    name: apprise-secrets
    namespace: notifications
type: Opaque
stringData:
    personal.cfg: ENC[AES256_GCM,data:RS6MmPVls8GT+rIjdVEvmef3OoW8oBFiKBgB/jNOtvc/W95aAkU04RzQJ2Dw4TUCd6Gioe269Dr4KyDILsXPeFQWlrHp7LkYsrekm0iu,iv:zt8NPwEKdPActLSBgP08CGiWlXb4e365ARn6xjPZxBc=,tag:8qgDOXh3Kfg5pVQtGSJpqQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:sh/QxI2KEsU7CiYrQllvDVKRUojZsWCCXp6O8H952H4hqSg2vxVmE8504a6wTfhIVs7D5abws/j15PN3YCQ7iw==,iv:oEY9V6KQjpE9LnOMIMWIdGj0b8iN4NsOBk4hBWSXl7U=,tag:69xVA480LJHY2rLVsXgfNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbExTNlcrZVVWSDFTYkxu
            bTBISFdMOWpEUHlid2lvS0dnMzF6emc5M3lnCnNuZ29VTmN6Ym1Va0JzVklOTUtp
            ZzZZbVZ0bEY0M25IK2J2RzdrZFY1c2MKLS0tIFdQMnMzcjRJUzlmZ2JveFZzMEdx
            QVNFV0FQeFVQM2VHb09RY1Nra2JwakEKEiwZf9ZV0fHHZPn/I7WUty4QbceqKq5R
            FZtafUXfBM8By2hwy8kHBGsNkEwVccost161xinjsN78dyXN0Q6npw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T13:54:19Z"
    mac: ENC[AES256_GCM,data:sUFlaX8VNMgsJGa9oE47fkrIlfHJ+n2q98UebVsZji6Jv56VwPakC+mRQDziarPh/tDLnbE3Ztq16Iz+5xCxnFlF5nXUt8/pkrW6fMA313x2wRirbTv6DpxajCVca1WvmcOKj1SRu3TuhHPww28jxb5lhLb8zTFALCjtdRYr0Wk=,iv:YMz6jFJ35KS+JlXMUqxx1k54FeBc91ZRmXjxcoqVIyc=,tag:rMi3Ni30380/irjj5zDUCg==,type:str]
    version: 3.13.3
