apiVersion: v1
kind: Secret
metadata:
    name: apprise-secrets
    namespace: notifications
type: Opaque
stringData:
    apprise.cfg: ENC[AES256_GCM,data:tfPFi3pU/HdKCE9xqY8l0u0Rc5eCAHMqgHmsFV+d4AzbEsYiXJdIp8OoHVAjlWDwUGyIRcOQyUEjCwaMoH3ePpm+lcS8J5GaNoppEw==,iv:ufTG3BF/6iTmlWAjpdjSKtGmY40cXckoLJl6kUMJ++I=,tag:zKiCA92lZLTDgTdyzBFM3w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:sh/QxI2KEsU7CiYrQllvDVKRUojZsWCCXp6O8H952H4hqSg2vxVmE8504a6wTfhIVs7D5abws/j15PN3YCQ7iw==,iv:oEY9V6KQjpE9LnOMIMWIdGj0b8iN4NsOBk4hBWSXl7U=,tag:69xVA480LJHY2rLVsXgfNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbExTNlcrZVVWSDFTYkxu
            bTBISFdMOWpEUHlid2lvS0dnMzF6emc5M3lnCnNuZ29VTmN6Ym1Va0JzVklOTUtp
            ZzZZbVZ0bEY0M25IK2J2RzdrZFY1c2MKLS0tIFdQMnMzcjRJUzlmZ2JveFZzMEdx
            QVNFV0FQeFVQM2VHb09RY1Nra2JwakEKEiwZf9ZV0fHHZPn/I7WUty4QbceqKq5R
            FZtafUXfBM8By2hwy8kHBGsNkEwVccost161xinjsN78dyXN0Q6npw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejjf4e7dnkc0tmwmyuyr9k5cl8sz9g0rpj4gnywk26x56jut6ygqph0x4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T00:10:02Z"
    mac: ENC[AES256_GCM,data:i6feK16CWXkxNC0zHwGQWm8mbkyneZTzbaKcoGC2pDQ7lyYIkM9JXpoUyV87e0esd65etLErQjEO3z7gCV7zL+lrWU7VQmQaiGhxCrtO3NlaEmvdVGDBwDysZLM4Obp6k+3VwbWzzIDka6ThMIc940TeDwIBXaNtRoTQFsnuLQ4=,iv:oZt2LMoZKNN8SXz96PeexR2uT+KJPB9xdb5EmBcU/os=,tag:Hh2rUoVyWKUokqpUItsCfg==,type:str]
    version: 3.13.3
