---
# THIS FILE IS DYNAMICALLY GENERATED BY TERRAFORM.
# DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN.
#
# This file defines the OpenClaw VM and assigns it to the openclaw_vms group.

all:
  children:
    openclaw_vms:
      hosts:
        ${name}:
          ansible_host: ${ip}
          ansible_user: "${ansible_user}"
          ansible_port: 22
          node_os: "${node_os}"
